// mynclex/lib/bank/actions/save-question.ts
//
// Server action for the new authoring tree. Branches on question_type
// and dispatches to the matching parser (lib/bank/parsers/<type>.ts)
// to build content + correct JSONB. Covers every live question type:
// MCQ, TF, SATA, SELECT_N, MATRIX, MATRIX_MR, BOWTIE, CLOZE, HIGHLIGHT,
// DRAG_CLOZE, DRAG_ORDER. (The old DRAG_DROP type was split into
// DRAG_CLOZE + DRAG_ORDER and retired 2026-07-02.)
//
// Surface-aware: reads the `surface` hidden input on the form and
// branches between admin (nclex_bank_items, NCLEX_<TYPE>_NNNNN) and
// tutor (nclex_tutor_questions, NCLEX_TUT_<TYPE>_NNNNN, with
// tutor_id = auth.uid()).
//
// Returns a structured SaveResult instead of redirecting — the modal
// host (sandbox client / bank-list client) closes and re-renders the
// list via revalidatePath. Old `app/(app)/admin/bank/actions.ts` uses
// redirect() because it lives inside a focus-mode page; the new path
// is modal-based, so it owns its own UX flow.

'use server';

import { revalidatePath } from 'next/cache';
import { requireBankCurator, type ServerSupabaseClient } from '@/lib/access';
import {
  CLIENT_NEEDS_CATEGORIES,
  DIFFICULTY_LEVELS,
  ITEM_ID_PREFIX,
  TUTOR_ITEM_ID_PREFIX,
  type QuestionType,
} from '@/lib/bank/classifications';
import { seedIrtForLabel } from '@/lib/bank/difficulty';
import type {
  BankItemContent,
  BankItemCorrect,
} from '@/lib/bank/types';
import { parseMcq } from '@/lib/bank/parsers/mcq';
import { parseTf } from '@/lib/bank/parsers/tf';
import { parseSata } from '@/lib/bank/parsers/sata';
import { parseSelectN } from '@/lib/bank/parsers/select-n';
import { parseMatrix } from '@/lib/bank/parsers/matrix';
import { parseMatrixMr } from '@/lib/bank/parsers/matrix-mr';
import {
  parseBowtie,
  type BowtieWingInput,
} from '@/lib/bank/parsers/bowtie';
import {
  parseCloze,
  type ClozeBlankInput,
} from '@/lib/bank/parsers/cloze';
import { parseRichDoc, serializeRichDoc } from '@/lib/authoring/rich-doc';
import {
  normalizeClozeStem,
  clozeStemScanText,
  renumberClozeStem,
} from '@/lib/bank/editors/cloze-stem-doc';
import {
  normalizeHighlightStem,
  highlightStemScanText,
} from '@/lib/bank/editors/highlight-stem-doc';
import {
  normalizeDragClozeStem,
  dragClozeStemScanText,
} from '@/lib/bank/editors/drag-cloze-stem-doc';
import { computeMarksFromKey } from '@/lib/scoring';
import {
  parseHighlight,
  type HighlightChunkInput,
} from '@/lib/bank/parsers/highlight';
import {
  parseDragCloze,
  type DragClozeSlotInput,
  type DragClozeTokenInput,
} from '@/lib/bank/parsers/drag-cloze';
import {
  parseDragOrder,
  type DragOrderSlotInput,
  type DragOrderTokenInput,
} from '@/lib/bank/parsers/drag-order';

const VALID_CATEGORIES = new Set<string>(CLIENT_NEEDS_CATEGORIES);
const VALID_DIFFICULTIES = new Set<string>(DIFFICULTY_LEVELS);

type Surface = 'admin' | 'tutor';

export type SaveResult =
  | { ok: true; item_id: string; created: boolean }
  | { ok: false; error: string };

// ─────────────────────────────────────────────────────────────
// Surface plumbing.
// ─────────────────────────────────────────────────────────────

function surfaceConfig(surface: Surface) {
  if (surface === 'tutor') {
    return {
      table: 'nclex_tutor_questions' as const,
      prefix: TUTOR_ITEM_ID_PREFIX,
      revalidate: '/tutor/bank/all',
    };
  }
  return {
    table: 'nclex_bank_items' as const,
    prefix: ITEM_ID_PREFIX,
    revalidate: '/admin/bank/all',
  };
}

function readSurface(formData: FormData): Surface {
  const raw = String(formData.get('surface') ?? '');
  return raw === 'tutor' ? 'tutor' : 'admin';
}

// ─────────────────────────────────────────────────────────────
// Auto-numbering — same scheme as the legacy action so the IDs
// generated by both surfaces stay aligned during the transition.
//
// We can't trust a single lexical-max row: the table also holds
// manually-named ids (e.g. NCLEX_TF_T24, NCLEX_TF_TESTCASE02_Q6) whose
// suffix sorts ABOVE the zero-padded numbers ('T' > '0'). Taking the
// lexical max + parseInt yields NaN for those, the old code then fell
// back to 1, and `NCLEX_TF_00001` collided on the pkey. Instead, scan
// every id for this prefix and take the true max over only the suffixes
// that are a pure run of digits — the auto-numbering scheme's own ids.
// Manually-named ids sit outside the scheme and are ignored here.
// ─────────────────────────────────────────────────────────────

async function nextItemId(
  supabase: ServerSupabaseClient,
  surface: Surface,
  type: QuestionType,
): Promise<string> {
  const cfg = surfaceConfig(surface);
  const prefix = cfg.prefix[type];

  // Tutor surface: RLS scopes a tutor to their OWN rows
  // (nclex_tutor_questions_tutor_own = tutor_id = auth.uid()), so a
  // client-side max+1 only counts the caller's questions and collides with
  // other tutors' ids on the pkey. Defer to a SECURITY DEFINER RPC that scans
  // the whole table. The admin/bank surface keeps the direct scan below —
  // curators can read every bank item, so its count is already whole-table.
  if (surface === 'tutor') {
    const { data, error } = await supabase.rpc('nclex_next_tutor_item_id', {
      p_prefix: prefix,
    });
    if (error) throw error;
    if (typeof data !== 'string' || data.length === 0) {
      throw new Error('nclex_next_tutor_item_id returned no id');
    }
    return data;
  }

  const { data, error } = await supabase
    .from(cfg.table)
    .select('item_id')
    .like('item_id', `${prefix}%`);

  if (error) throw error;

  let max = 0;
  for (const r of data ?? []) {
    const suffix = (r.item_id as string).slice(prefix.length);
    if (/^\d+$/.test(suffix)) {
      const n = parseInt(suffix, 10);
      if (n > max) max = n;
    }
  }

  return `${prefix}${String(max + 1).padStart(5, '0')}`;
}

// ─────────────────────────────────────────────────────────────
// Form parsing — branches per supported question type. Adds one
// case per slice (3-10) until every editor is wired in.
// ─────────────────────────────────────────────────────────────

const SUPPORTED_TYPES = new Set<QuestionType>([
  'MCQ',
  'TF',
  'SATA',
  'SELECT_N',
  'MATRIX',
  'MATRIX_MR',
  'BOWTIE',
  'CLOZE',
  'HIGHLIGHT',
  'DRAG_CLOZE',
  'DRAG_ORDER',
]);

interface ParsedQuestion {
  question_type: QuestionType;
  instruction: string | null;
  stem: string;
  rationale: string | null;
  rationale_img: string | null;
  content: BankItemContent;
  correct: BankItemCorrect;
  client_needs_category: string;
  client_needs_subcategory: string | null;
  nursing_subject: string | null;
  body_system: string | null;
  topic: string | null;
  subtopic: string | null;
  difficulty: string | null;
  bloom_level: string | null;
  tags: string[];
  is_published: boolean;
  is_free_sample: boolean;
  is_builder_visible: boolean;
  marks: number;
  shuffle_options: boolean;
  question_ref: string | null;
  batch_id: string | null;
}

function parseQuestionFormData(formData: FormData): ParsedQuestion | { error: string } {
  const question_type = String(formData.get('question_type') ?? '') as QuestionType;
  if (!SUPPORTED_TYPES.has(question_type)) {
    return {
      error: `Unsupported question type "${question_type}" — current support: ${[...SUPPORTED_TYPES].join(', ')}.`,
    };
  }

  const stem = String(formData.get('stem') ?? '').trim();
  if (!stem) return { error: 'Stem is required.' };

  const instructionRaw = String(formData.get('instruction') ?? '').trim();
  const instruction = instructionRaw || null;

  const client_needs_category = String(formData.get('client_needs_category') ?? '').trim();
  if (!VALID_CATEGORIES.has(client_needs_category)) {
    return { error: 'Client Needs category is required.' };
  }

  const optionIds = formData.getAll('option_id').map(String);
  const optionTexts = formData.getAll('option_text').map(String);
  const optionFeedbacks = formData.getAll('option_feedback').map(String);
  const correctIds = formData
    .getAll('correct_id')
    .map((v) => String(v).trim())
    .filter(Boolean);

  // Per-type content/correct construction. Each branch returns the
  // matching parser's { content, correct } pair (or an error).
  // MATRIX uses a different form-data contract (rows × columns +
  // dynamic per-row correct radios) so it builds its own input
  // payload instead of consuming the option arrays.
  const parsed = (() => {
    switch (question_type) {
      case 'TF':
        return parseTf(optionIds, optionTexts, optionFeedbacks, correctIds);
      case 'SATA':
        return parseSata(optionIds, optionTexts, optionFeedbacks, correctIds);
      case 'SELECT_N': {
        const selectCount = parseInt(String(formData.get('select_count') ?? ''), 10);
        return parseSelectN(
          optionIds,
          optionTexts,
          optionFeedbacks,
          correctIds,
          selectCount,
        );
      }
      case 'MATRIX': {
        const rowIds = formData.getAll('matrix_row_id').map(String);
        const rowTexts = formData.getAll('matrix_row_text').map(String);
        const rowFeedbacks = formData.getAll('matrix_row_feedback').map(String);
        const colIds = formData.getAll('matrix_col_id').map(String);
        const colTexts = formData.getAll('matrix_col_text').map(String);
        const correctByRow: Record<string, string> = {};
        for (const rid of rowIds) {
          const picked = String(formData.get(`matrix_correct_${rid}`) ?? '').trim();
          if (picked) correctByRow[rid] = picked;
        }
        return parseMatrix({
          row_label: String(formData.get('matrix_row_label') ?? ''),
          rowIds,
          rowTexts,
          rowFeedbacks,
          colIds,
          colTexts,
          correctByRow,
        });
      }
      case 'MATRIX_MR': {
        // Same rows × columns contract as MATRIX, but each row's correct
        // picks ride as REPEATED checkbox values (matrixmr_correct_<rowId>),
        // so read them with getAll → columnId[].
        const rowIds = formData.getAll('matrixmr_row_id').map(String);
        const rowTexts = formData.getAll('matrixmr_row_text').map(String);
        const rowFeedbacks = formData.getAll('matrixmr_row_feedback').map(String);
        const colIds = formData.getAll('matrixmr_col_id').map(String);
        const colTexts = formData.getAll('matrixmr_col_text').map(String);
        const correctByRow: Record<string, string[]> = {};
        for (const rid of rowIds) {
          const picked = formData
            .getAll(`matrixmr_correct_${rid}`)
            .map((v) => String(v).trim())
            .filter(Boolean);
          if (picked.length > 0) correctByRow[rid] = picked;
        }
        return parseMatrixMr({
          row_label: String(formData.get('matrixmr_row_label') ?? ''),
          rowIds,
          rowTexts,
          rowFeedbacks,
          colIds,
          colTexts,
          correctByRow,
        });
      }
      case 'BOWTIE': {
        const readWing = (
          wing: 'left' | 'centre' | 'right',
        ): BowtieWingInput => ({
          label: String(formData.get(`bowtie_${wing}_label`) ?? ''),
          tokenIds:       formData.getAll(`bowtie_${wing}_token_id`).map(String),
          tokenTexts:     formData.getAll(`bowtie_${wing}_token_text`).map(String),
          tokenFeedbacks: formData.getAll(`bowtie_${wing}_token_feedback`).map(String),
          // Centre uses a single radio value; left/right post repeated checkbox values.
          correctIds:
            wing === 'centre'
              ? [String(formData.get('bowtie_centre_correct') ?? '')]
              : formData.getAll(`bowtie_${wing}_correct`).map(String),
        });
        return parseBowtie({
          left:   readWing('left'),
          centre: readWing('centre'),
          right:  readWing('right'),
        });
      }
      case 'CLOZE': {
        // Read the parallel arrays of blank cards (every card the
        // editor holds, including orphans). For each one, read its
        // per-blank choice arrays via dynamic field names keyed on
        // the blank ID. Filter out orphans (in_stem !== 'true')
        // before handing to the parser.
        const blankIds = formData.getAll('cloze_blank_id').map(String);
        const inStemFlags = formData.getAll('cloze_blank_in_stem').map(String);
        const blanks: ClozeBlankInput[] = [];
        for (let i = 0; i < blankIds.length; i++) {
          const bid = blankIds[i];
          if (inStemFlags[i] !== 'true') continue;
          const choiceIds  = formData.getAll(`cloze_choice_id_${bid}`).map(String);
          const choiceTexts = formData.getAll(`cloze_choice_text_${bid}`).map(String);
          const choiceFbs   = formData.getAll(`cloze_choice_feedback_${bid}`).map(String);
          const choices = choiceIds.map((cid, j) => ({
            id: cid,
            text: choiceTexts[j] ?? '',
            feedback: choiceFbs[j] ?? '',
          }));
          blanks.push({
            id: bid,
            choices,
            correct_id: String(formData.get(`cloze_correct_${bid}`) ?? ''),
          });
        }
        // The stem is a rich doc (JSON) with the {N} markers as plain text
        // inside it (Slice 6d, Option B). Normalise it (strip any marks
        // clinging to a marker + isolate each one), scan its flattened text
        // for the markers, run the existing parser for ordering / validation /
        // content, then renumber the DOC to match — and store the doc JSON,
        // not the parser's flattened scan string.
        const stemDoc = normalizeClozeStem(parseRichDoc(stem));
        const result = parseCloze({ stem: clozeStemScanText(stemDoc), blanks });
        if (!result.ok) return result;
        const renumberedDoc = renumberClozeStem(stemDoc, result.order);
        return { ...result, stem: serializeRichDoc(renumberedDoc) };
      }
      case 'HIGHLIGHT': {
        // Five parallel arrays per chunk card. Orphans (in_passage !==
        // 'true') get passed through to the parser, which filters them.
        const chunkIds        = formData.getAll('hl_chunk_id').map(String);
        const chunkTexts      = formData.getAll('hl_chunk_text').map(String);
        const chunkDecisions  = formData.getAll('hl_chunk_decision').map(String);
        const chunkFeedbacks  = formData.getAll('hl_chunk_feedback').map(String);
        const chunkInPassages = formData.getAll('hl_chunk_in_passage').map(String);
        const hlChunks: HighlightChunkInput[] = chunkIds.map((id, i) => ({
          id,
          text: chunkTexts[i] ?? '',
          decision:
            chunkDecisions[i] === 'correct'
              ? 'correct'
              : chunkDecisions[i] === 'wrong'
                ? 'wrong'
                : 'undecided',
          feedback: chunkFeedbacks[i] ?? '',
          in_passage: chunkInPassages[i] === 'true',
        }));
        // The stem is a rich doc (JSON) with the [[chunk]] markers as plain
        // text inside it (Slice 6e, Option B). Normalise it (strip any marks
        // clinging to a bracket + isolate each one — this enforces "chunk text
        // stays plain"), scan its flattened text for the parser, then store the
        // doc JSON, not the parser's flattened scan string. No renumber —
        // Highlight chunk IDs are positional, the prose carries no numbers.
        const hlStemDoc = normalizeHighlightStem(parseRichDoc(stem));
        const hlResult = parseHighlight({
          stem: highlightStemScanText(hlStemDoc),
          chunks: hlChunks,
        });
        if (!hlResult.ok) return hlResult;
        return { ...hlResult, stem: serializeRichDoc(hlStemDoc) };
      }
      case 'DRAG_CLOZE': {
        // Like DRAG_DROP SENTENCE, but a standalone type — no subtype. The
        // stem carries [N] markers as plain text; slots derive from them.
        const slotIds        = formData.getAll('dcz_slot_id').map(String);
        const slotTargets    = formData.getAll('dcz_slot_target_text').map(String);
        const slotAssigned   = formData.getAll('dcz_slot_assigned_token_id').map(String);
        const tokenIds       = formData.getAll('dcz_token_id').map(String);
        const tokenTexts     = formData.getAll('dcz_token_text').map(String);
        const tokenFeedbacks = formData.getAll('dcz_token_feedback').map(String);
        const dczSlots: DragClozeSlotInput[] = slotIds.map((id, i) => ({
          id,
          target_text: slotTargets[i] ?? '',
          assigned_token_id: slotAssigned[i] ?? '',
        }));
        const dczTokens: DragClozeTokenInput[] = tokenIds.map((id, i) => ({
          id,
          text: tokenTexts[i] ?? '',
          feedback: tokenFeedbacks[i] ?? '',
        }));
        // Stem is a rich doc with [N] markers as plain text (Option B). Normalise
        // (strip marks off markers + isolate), scan its flattened text for the
        // parser, then store the doc JSON. No renumber — markers are byte-preserved.
        const dczStemDoc = normalizeDragClozeStem(parseRichDoc(stem));
        const dczResult = parseDragCloze({
          stem: dragClozeStemScanText(dczStemDoc),
          slots: dczSlots,
          tokens: dczTokens,
        });
        if (!dczResult.ok) return dczResult;
        return { ...dczResult, stem: serializeRichDoc(dczStemDoc) };
      }
      case 'DRAG_ORDER': {
        // Ranked-response sibling of DRAG_DROP's ORDERED mode — no subtype, no
        // stem markers. Slots are a curator-ordered list; the stem is a plain
        // rich prompt stored as-is.
        const slotIds        = formData.getAll('do_slot_id').map(String);
        const slotTargets    = formData.getAll('do_slot_target_text').map(String);
        const slotAssigned   = formData.getAll('do_slot_assigned_token_id').map(String);
        const tokenIds       = formData.getAll('do_token_id').map(String);
        const tokenTexts     = formData.getAll('do_token_text').map(String);
        const tokenFeedbacks = formData.getAll('do_token_feedback').map(String);
        const doSlots: DragOrderSlotInput[] = slotIds.map((id, i) => ({
          id,
          target_text: slotTargets[i] ?? '',
          assigned_token_id: slotAssigned[i] ?? '',
        }));
        const doTokens: DragOrderTokenInput[] = tokenIds.map((id, i) => ({
          id,
          text: tokenTexts[i] ?? '',
          feedback: tokenFeedbacks[i] ?? '',
        }));
        const doResult = parseDragOrder({ slots: doSlots, tokens: doTokens });
        if (!doResult.ok) return doResult;
        // No markers to normalise — store the rich stem prompt as-is.
        return { ...doResult, stem: serializeRichDoc(parseRichDoc(stem)) };
      }
      default:
        return parseMcq(optionIds, optionTexts, optionFeedbacks, correctIds);
    }
  })();
  if (!parsed.ok) return { error: parsed.error };

  const subcategory = String(formData.get('client_needs_subcategory') ?? '').trim();
  const difficultyRaw = String(formData.get('difficulty') ?? '').trim();
  const difficulty =
    difficultyRaw && VALID_DIFFICULTIES.has(difficultyRaw) ? difficultyRaw : null;

  const tagsRaw = String(formData.get('tags') ?? '');
  const tags = tagsRaw.split(',').map((t) => t.trim()).filter(Boolean);

  // Marks are system-managed — derived from the answer key by the editor at
  // save time, not curator-typed. See bank-marks-and-scoring.html §5.
  const marks = computeMarksFromKey(question_type, parsed.correct);

  // CLOZE rewrites the stem on save (gap-closing renumber). Other
  // parsers don't touch it, so we fall back to the curator-typed stem.
  const finalStem = 'stem' in parsed ? parsed.stem : stem;

  return {
    question_type,
    instruction,
    stem: finalStem,
    rationale: String(formData.get('rationale') ?? '').trim() || null,
    rationale_img: String(formData.get('rationale_img') ?? '').trim() || null,
    content: parsed.content,
    correct: parsed.correct,
    client_needs_category,
    client_needs_subcategory: subcategory || null,
    nursing_subject: String(formData.get('nursing_subject') ?? '').trim() || null,
    body_system: String(formData.get('body_system') ?? '').trim() || null,
    topic: String(formData.get('topic') ?? '').trim() || null,
    subtopic: String(formData.get('subtopic') ?? '').trim() || null,
    difficulty,
    bloom_level: String(formData.get('bloom_level') ?? '').trim() || null,
    tags,
    is_published: formData.get('is_published') === 'on',
    is_free_sample: formData.get('is_free_sample') === 'on',
    // Default true: when the checkbox is rendered, the form posts 'on'
    // when ticked and nothing when unticked. We treat "absent" as
    // "default true" only in standalone mode (which is the only mode
    // slice 2 ships).
    is_builder_visible: formData.get('is_builder_visible') !== null,
    marks,
    shuffle_options: formData.get('shuffle_options') === 'on',
    question_ref: String(formData.get('question_ref') ?? '').trim() || null,
    batch_id: String(formData.get('batch_id') ?? '').trim() || null,
  };
}

// ─────────────────────────────────────────────────────────────
// Save action — create OR update based on presence of item_id in
// the form. Returns SaveResult for the modal host to consume.
// ─────────────────────────────────────────────────────────────

export async function saveQuestionAction(formData: FormData): Promise<SaveResult> {
  const surface = readSurface(formData);
  const { supabase, user } = await requireBankCurator(surface);

  const parsed = parseQuestionFormData(formData);
  if ('error' in parsed) return { ok: false, error: parsed.error };

  const cfg = surfaceConfig(surface);
  const existingItemId = String(formData.get('item_id') ?? '').trim();

  // ── UPDATE ─────────────────────────────────────────────────
  if (existingItemId) {
    const { data: existing, error: fetchErr } = await supabase
      .from(cfg.table)
      .select('question_type, difficulty')
      .eq('item_id', existingItemId)
      .maybeSingle();

    if (fetchErr || !existing) {
      return { ok: false, error: 'Question not found.' };
    }
    if (existing.question_type !== parsed.question_type) {
      return { ok: false, error: 'Question type cannot be changed after creation.' };
    }

    // §5.2 — re-seed the numeric difficulty ONLY when the curator actually
    // changed the label. Last writer wins: a curator changing the label
    // reclaims the number as curator-owned (source → CURATOR_LABEL). An
    // unrelated edit (fixing a typo) must NOT wipe a number the
    // recalibration job may have taken over — so we leave difficulty_irt /
    // difficulty_source untouched when the label is unchanged.
    const difficultyChanged = existing.difficulty !== parsed.difficulty;
    const difficultyPatch = difficultyChanged
      ? {
          difficulty_irt: seedIrtForLabel(parsed.difficulty),
          difficulty_source: 'CURATOR_LABEL',
        }
      : {};

    const { error } = await supabase
      .from(cfg.table)
      .update({
        ...parsed,
        ...difficultyPatch,
        updated_at: new Date().toISOString(),
      })
      .eq('item_id', existingItemId);

    if (error) return { ok: false, error: `Update failed: ${error.message}` };

    revalidatePath(cfg.revalidate);
    return { ok: true, item_id: existingItemId, created: false };
  }

  // ── CREATE ─────────────────────────────────────────────────
  const item_id = await nextItemId(supabase, surface, parsed.question_type);

  // Case-context: when invoked from the case-study wrapper's "+ Add
  // question" flow, formData carries parent_case_id + case_position
  // (1-6) + case_cjmm_step. We set parent_case_id directly on the
  // new question row, then write the nclex_case_study_items join
  // row right after the question insert succeeds. (Schema's
  // cjmm_step is NOT NULL on the join, so a valid value is required.)
  const parentCaseId = String(formData.get('parent_case_id') ?? '').trim();

  // Trend-context (slice 13d, decision 10): when invoked from the
  // trend wrapper's "+ Add question" flow, formData carries trend_id.
  // Simpler than the CS path — no join table; the link is one column
  // on the question row. UPDATE branch above doesn't touch trend_id,
  // so the column survives untouched on subsequent saves.
  const trendId = String(formData.get('trend_id') ?? '').trim();

  // Note-context (slice 11.15): when invoked from a library note's
  // embedded-questions "Create new question" flow, formData carries
  // parent_note_id. Same one-column linkage as trend_id — BUT unlike
  // case/trend children this is an *origin label only*: the question
  // stays builder-visible + reusable (no is_builder_visible override
  // here), it's just tagged with the note it was born in. The caller
  // (the embed authoring UI) pre-checks Publish so it's immediately
  // embeddable. The UPDATE branch never touches the column, so it
  // survives later edits.
  const parentNoteId = String(formData.get('parent_note_id') ?? '').trim();

  // §5.2 — seed the numeric difficulty from the curator's label on create.
  // difficulty_source defaults to 'CURATOR_LABEL' at the column level.
  const row: Record<string, unknown> = {
    item_id,
    ...parsed,
    difficulty_irt: seedIrtForLabel(parsed.difficulty),
  };
  if (surface === 'tutor') {
    row.tutor_id = user.id;
  }
  if (parentCaseId) {
    row.parent_case_id = parentCaseId;
  }
  if (trendId) {
    row.trend_id = trendId;
  }
  if (parentNoteId) {
    row.parent_note_id = parentNoteId;
  }

  const { error } = await supabase.from(cfg.table).insert(row);
  if (error) return { ok: false, error: `Insert failed: ${error.message}` };

  if (parentCaseId) {
    const positionRaw = String(formData.get('case_position') ?? '').trim();
    const position = parseInt(positionRaw, 10);
    if (!Number.isFinite(position) || position < 1 || position > 6) {
      return { ok: false, error: 'Invalid case_position for case-attached question.' };
    }
    const cjmmStep = String(formData.get('case_cjmm_step') ?? '').trim() || 'Recognise cues';

    const itemsTable =
      surface === 'tutor' ? 'nclex_tutor_case_study_items' : 'nclex_case_study_items';
    const joinId = `${parentCaseId}_ITEM_${position}`;

    const { error: joinErr } = await supabase.from(itemsTable).insert({
      id:        joinId,
      case_id:   parentCaseId,
      item_id,
      position,
      cjmm_step: cjmmStep,
    });
    if (joinErr) {
      // Question is now orphaned (parent_case_id pointing at a case
      // but no join row). Curator's case page won't show it; they
      // can detach via the bank list. Surfacing the underlying error
      // gives the curator a chance to retry without manual cleanup.
      return { ok: false, error: `Question created but link failed: ${joinErr.message}` };
    }

    const wrapperBaseUrl =
      surface === 'tutor' ? '/tutor/bank/cases' : '/admin/bank/cases';
    revalidatePath(`${wrapperBaseUrl}/${parentCaseId}`);
  }

  if (trendId) {
    const wrapperBaseUrl =
      surface === 'tutor' ? '/tutor/bank/trends' : '/admin/bank/trends';
    revalidatePath(`${wrapperBaseUrl}/${trendId}`);
  }

  if (parentNoteId) {
    // The note editor re-reads its embed reference cards on revalidate.
    revalidatePath(`/tutor/library/note/${parentNoteId}`);
  }

  revalidatePath(cfg.revalidate);
  return { ok: true, item_id, created: true };
}
