-- MyNclex bank gap-fill, 2026-07-28
-- Gap 06: paediatric medication and procedures
-- 50 items, item_id block 522001-522050, batch_id gapfill-20260728
-- Type mix: 25 MCQ, 11 SATA, 4 SELECT_N, 4 MATRIX, 2 MATRIX_MR, 2 CLOZE, 1 TF, 1 DRAG_ORDER

INSERT INTO nclex_bank_items (
  item_id, question_type, stem, rationale, content, correct,
  client_needs_category, client_needs_subcategory, nursing_subject, body_system,
  topic, subtopic, difficulty, difficulty_source, bloom_level, tags,
  marks, is_published, is_builder_visible, is_free_sample, cat_pool, batch_id
) VALUES
('NCLEX_MCQ_522001', 'MCQ',
 'A 4-year-old weighing 33 lb is prescribed amoxicillin 40 mg/kg/day, to be given in three equally divided doses. How many milligrams should the nurse give for each dose?',
 'Paediatric doses are calculated on body weight in kilograms, so the nurse first converts 33 lb to kilograms by dividing by 2.2, which gives 15 kg. The total daily dose is 15 kg multiplied by 40 mg, or 600 mg in 24 hours, and dividing that total by three gives 200 mg per dose. Working in pounds, or giving the whole daily total as a single dose, is one of the commonest sources of paediatric overdose.',
 '{"options":[{"id":"A","text":"150 mg"},{"id":"B","text":"200 mg"},{"id":"C","text":"300 mg"},{"id":"D","text":"600 mg"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. 150 mg results from using a total of 30 mg/kg/day rather than the prescribed 40 mg/kg/day.","B":"Correct. 33 lb is 15 kg, 15 kg multiplied by 40 mg is 600 mg per day, and 600 mg divided into three doses is 200 mg.","C":"Incorrect. 300 mg divides the daily total into two doses rather than the three that were prescribed.","D":"Incorrect. 600 mg is the total for 24 hours, not a single dose."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pharmacology', 'Not applicable', 'Weight-based dosing', 'Milligram per kilogram calculation',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_522002', 'MCQ',
 'A child is prescribed 400 mg of an oral antibiotic. The suspension supplied on the ward is labelled 250 mg in 5 mL. How many millilitres should the nurse draw up?',
 'The volume is found by dividing the dose wanted by the dose held and multiplying by the volume it is held in: 400 divided by 250, multiplied by 5 mL, equals 8 mL. The nurse measures this in an oral syringe rather than a household spoon, because domestic spoons vary from about 2 mL to 7 mL and are a recognised cause of paediatric dosing error.',
 '{"options":[{"id":"A","text":"5 mL"},{"id":"B","text":"8 mL"},{"id":"C","text":"10 mL"},{"id":"D","text":"12.5 mL"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. 5 mL delivers only 250 mg, which is less than prescribed.","B":"Correct. 400 divided by 250, multiplied by 5 mL, gives 8 mL.","C":"Incorrect. 10 mL delivers 500 mg, which is an overdose.","D":"Incorrect. 12.5 mL delivers 625 mg and reverses the calculation."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pharmacology', 'Not applicable', 'Oral suspension dosing', 'Volume calculation',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_522003', 'MCQ',
 'A child weighs 24 kg. The paediatric formulary states that the safe dose of the prescribed medication is 10 to 15 mg/kg per dose. What is the maximum single dose the nurse may safely administer?',
 'A safe range is checked at both ends before any paediatric dose is given. The lower limit here is 24 kg multiplied by 10 mg, or 240 mg, and the upper limit is 24 kg multiplied by 15 mg, or 360 mg. Any prescribed dose above 360 mg falls outside the safe range and must be clarified with the prescriber rather than adjusted by the nurse.',
 '{"options":[{"id":"A","text":"240 mg"},{"id":"B","text":"300 mg"},{"id":"C","text":"360 mg"},{"id":"D","text":"480 mg"}]}'::jsonb,
 '{"answer":"C","feedback":{"A":"Incorrect. 240 mg is the lowest dose in the safe range, not the maximum.","B":"Incorrect. 300 mg sits inside the range but is not its upper limit.","C":"Correct. 24 kg multiplied by 15 mg/kg gives a maximum single dose of 360 mg.","D":"Incorrect. 480 mg uses 20 mg/kg, which is above the stated range."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Pediatrics', 'Not applicable', 'Safe dose range', 'Upper limit check',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_522004', 'MCQ',
 'A 12 kg toddler is prescribed gentamicin 100 mg intravenously as a single dose. The paediatric formulary gives a maximum of 7.5 mg/kg per dose. Which action should the nurse take?',
 'The maximum safe dose for this child is 12 kg multiplied by 7.5 mg, or 90 mg, so the prescribed 100 mg is outside the safe range. A nurse may not alter a prescribed dose independently, and a second checker does not make an unsafe prescription safe. The correct action is to withhold the dose and contact the prescriber so the prescription can be rewritten.',
 '{"options":[{"id":"A","text":"Administer the 100 mg as prescribed, since it is close to the calculated limit"},{"id":"B","text":"Administer 90 mg and document the reduced dose"},{"id":"C","text":"Withhold the dose and contact the prescriber to clarify"},{"id":"D","text":"Ask a second nurse to check the prescription and then administer it"}]}'::jsonb,
 '{"answer":"C","feedback":{"A":"Incorrect. A dose above the published maximum is unsafe however small the excess appears.","B":"Incorrect. Altering a prescribed dose is prescribing, which is outside the scope of the nurse.","C":"Correct. The dose exceeds the safe range, so it is withheld and the prescriber is contacted for a new prescription.","D":"Incorrect. A second check confirms the arithmetic but does not make an unsafe prescription safe to give."}}'::jsonb,
 'Safe and Effective Care Environment', 'Management of Care',
 'Pediatrics', 'Not applicable', 'Safe dose range', 'Action on an unsafe prescription',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_522005', 'MCQ',
 'A child is prescribed an intravenous antibiotic diluted in 50 mL of sodium chloride 0.9 percent, to be infused over 30 minutes by volumetric pump. At what rate in millilitres per hour should the nurse set the pump?',
 'A volumetric pump is programmed in millilitres per hour, so the nurse converts the prescribed time into an hourly rate. Fifty millilitres given over half an hour is the same as 100 mL in one hour. Setting the pump to 50 mL per hour would double the infusion time and delay the antibiotic, which matters when doses are timed to maintain a therapeutic level.',
 '{"options":[{"id":"A","text":"25 mL/hour"},{"id":"B","text":"50 mL/hour"},{"id":"C","text":"100 mL/hour"},{"id":"D","text":"150 mL/hour"}]}'::jsonb,
 '{"answer":"C","feedback":{"A":"Incorrect. 25 mL/hour would take two hours to deliver the 50 mL.","B":"Incorrect. 50 mL/hour delivers the volume over a full hour, twice the prescribed time.","C":"Correct. 50 mL over 30 minutes is equivalent to 100 mL in one hour.","D":"Incorrect. 150 mL/hour would deliver the dose in 20 minutes, faster than prescribed."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pediatrics', 'Not applicable', 'Intravenous medication in children', 'Infusion rate calculation',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_CLZ_522006', 'CLOZE',
 'A child weighs 55 lb. The nurse records the weight in kilograms as {1} and calculates a single paracetamol dose at 15 mg/kg, which is {2}.',
 'Pounds are converted to kilograms by dividing by 2.2, so 55 lb is 25 kg. The paracetamol dose is then 25 kg multiplied by 15 mg, which is 375 mg. Multiplying by 2.2 instead of dividing gives 121 kg and a grossly unsafe dose, which is why paediatric weights are recorded in kilograms only and never in two units on the same chart.',
 '{"blanks":[{"id":"b1","choices":[{"id":"c1","text":"22 kg"},{"id":"c2","text":"25 kg"},{"id":"c3","text":"27.5 kg"},{"id":"c4","text":"121 kg"}]},{"id":"b2","choices":[{"id":"c1","text":"250 mg"},{"id":"c2","text":"330 mg"},{"id":"c3","text":"375 mg"},{"id":"c4","text":"412 mg"}]}]}'::jsonb,
 '{"answers":{"b1":"c2","b2":"c3"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pharmacology', 'Not applicable', 'Weight conversion', 'Pounds to kilograms',
 'Hard', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_522007', 'SATA',
 'The nurse is preparing a weight-based intravenous medication for a hospitalised child. Which actions should the nurse take before administering the dose? Select all that apply.',
 'Paediatric doses leave almost no margin for error, so every link in the chain is verified: a current measured weight in kilograms, an independent repeat of the arithmetic by a second registered nurse, a comparison against the published safe range, and correct identification of the child. Reported or historical weights and convenience rounding both introduce error that the small body mass of a child cannot absorb.',
 '{"options":[{"id":"A","text":"Confirm the weight in kilograms measured during this admission"},{"id":"B","text":"Check the calculated dose against the safe range in the paediatric formulary"},{"id":"C","text":"Ask a second registered nurse to repeat the calculation independently"},{"id":"D","text":"Use the weight the parent recalls from the last clinic visit"},{"id":"E","text":"Identify the child using two identifiers, with the parent present"},{"id":"F","text":"Round the dose up to the nearest whole millilitre so it is easier to measure"}]}'::jsonb,
 '{"answers":["A","B","C","E"],"feedback":{"A":"Correct. A weight measured during this admission is the only reliable basis for a weight-based dose in a growing child.","B":"Correct. Checking against the formulary safe range catches a prescribing error before the dose reaches the child.","C":"Correct. An independent double check by a second registered nurse detects arithmetic errors that a shared calculation would repeat.","D":"Incorrect. A recalled or historical weight may be months out of date and is not an acceptable basis for dosing.","E":"Correct. Two identifiers confirm that the calculated dose is given to the child it was calculated for.","F":"Incorrect. Rounding for convenience can change a paediatric dose by a clinically significant percentage."}}'::jsonb,
 'Safe and Effective Care Environment', 'Safety and Infection Control',
 'Pediatrics', 'Not applicable', 'Paediatric medication safety', 'Pre-administration checks',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_522008', 'MCQ',
 'A 4-month-old infant is to receive an intramuscular injection. What is the maximum volume the nurse should give into a single intramuscular site?',
 'Muscle mass limits the volume a site can absorb without pain or tissue damage. In an infant the vastus lateralis will take about 0.5 mL, rising to roughly 1 mL in a toddler and 1 to 2 mL in an older child or adolescent. A volume larger than the muscle can hold is divided between two sites rather than forced into one, because a distended muscle causes pain, poor absorption and sterile abscess.',
 '{"options":[{"id":"A","text":"0.5 mL"},{"id":"B","text":"1 mL"},{"id":"C","text":"1.5 mL"},{"id":"D","text":"2 mL"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. About 0.5 mL is the maximum a single intramuscular site will take in an infant of this age.","B":"Incorrect. 1 mL is the approximate limit for a toddler, not for a 4-month-old.","C":"Incorrect. 1.5 mL exceeds the capacity of infant muscle and would need to be divided between sites.","D":"Incorrect. 2 mL is an adolescent or adult volume and would cause pain and tissue damage in an infant."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pediatrics', 'Musculoskeletal', 'Intramuscular injection in children', 'Maximum volume by age',
 'Easy', 'CURATOR_LABEL', 'Remember', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MAT_522009', 'MATRIX',
 'For each client below, select the intramuscular site the nurse should use.',
 'Site selection follows muscle development rather than age alone. The vastus lateralis is the site of choice in infants because it is the largest developed muscle and has no major vessels or nerves close by. The deltoid holds only small volumes and is used once a child is well into school age or adolescence, while the ventrogluteal site takes larger volumes in a child who has been walking for at least a year.',
 '{"rows":[{"id":"r1","text":"A 3-month-old infant receiving a 0.5 mL vaccine"},{"id":"r2","text":"A 16-year-old receiving a 1 mL vaccine"},{"id":"r3","text":"A 5-year-old needing 1.5 mL of an intramuscular antibiotic"},{"id":"r4","text":"A 9-month-old infant who is not yet walking"}],"columns":[{"id":"c1","text":"Vastus lateralis"},{"id":"c2","text":"Deltoid"},{"id":"c3","text":"Ventrogluteal"}],"row_label":"Client"}'::jsonb,
 '{"cells":{"r1":"c1","r2":"c2","r3":"c3","r4":"c1"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pediatrics', 'Musculoskeletal', 'Intramuscular injection in children', 'Site selection by age',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_522010', 'MCQ',
 'The nurse is selecting equipment for an intramuscular injection into the vastus lateralis of a 12-month-old infant. Which needle should the nurse choose?',
 'The needle must be long enough to deposit the medication inside the muscle rather than in subcutaneous fat, where absorption is unpredictable and sterile abscess is more likely. A 25 mm needle reaches the vastus lateralis at this age, and a bore of 22 to 25 gauge suits the viscosity of most intramuscular preparations. A 38 mm needle risks striking the femur in a small thigh, while very short fine needles deliver the dose subcutaneously.',
 '{"options":[{"id":"A","text":"13 mm, 27 gauge"},{"id":"B","text":"16 mm, 25 gauge"},{"id":"C","text":"25 mm, 23 gauge"},{"id":"D","text":"38 mm, 21 gauge"}]}'::jsonb,
 '{"answer":"C","feedback":{"A":"Incorrect. A 13 mm 27 gauge needle is a subcutaneous or intradermal size and will not reach muscle.","B":"Incorrect. 16 mm is too short to deposit the dose reliably into the vastus lateralis of a 12-month-old.","C":"Correct. A 25 mm needle of 22 to 25 gauge reaches the muscle without risking bone contact.","D":"Incorrect. A 38 mm needle is an adult length and risks striking the femur."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pediatrics', 'Musculoskeletal', 'Intramuscular injection in children', 'Needle selection',
 'Hard', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728');

INSERT INTO nclex_bank_items (
  item_id, question_type, stem, rationale, content, correct,
  client_needs_category, client_needs_subcategory, nursing_subject, body_system,
  topic, subtopic, difficulty, difficulty_source, bloom_level, tags,
  marks, is_published, is_builder_visible, is_free_sample, cat_pool, batch_id
) VALUES
('NCLEX_TF_522011', 'TF',
 'The nurse plans to use the dorsogluteal site for an intramuscular injection in a 2-year-old. This is correct practice.',
 'The dorsogluteal site lies close to the sciatic nerve and the superior gluteal artery, and the gluteal muscle does not develop adequately until a child has been walking for at least a year, often longer. Because of the risk of permanent nerve injury the dorsogluteal site is no longer recommended for children at all. The vastus lateralis or the ventrogluteal site is used instead.',
 '{"options":[{"id":"A","text":"True"},{"id":"B","text":"False"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. The gluteal muscle of a 2-year-old is underdeveloped and the site carries a genuine risk of sciatic nerve injury.","B":"Correct. The dorsogluteal site is avoided in children; the vastus lateralis or ventrogluteal site should be used."}}'::jsonb,
 'Safe and Effective Care Environment', 'Safety and Infection Control',
 'Pediatrics', 'Musculoskeletal', 'Intramuscular injection in children', 'Sites to avoid',
 'Very easy', 'CURATOR_LABEL', 'Understand', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_522012', 'MCQ',
 'The nurse is giving an oral liquid medication to a 5-month-old infant. Which technique should the nurse use?',
 'An infant of this age still has an extrusion reflex and cannot drink from a cup. Directing small amounts down the side of the tongue with an oral syringe uses the natural swallow, keeps the liquid away from the taste buds in the centre of the tongue, and lets the nurse pause if the infant gags. Pinching the nose forces swallowing and risks aspiration, and adding a dose to a full bottle means the dose is lost if the feed is not finished.',
 '{"options":[{"id":"A","text":"Add the dose to a full bottle of formula and offer it at the next feed"},{"id":"B","text":"Use an oral syringe to place small amounts along the side of the tongue, allowing the infant to swallow between each"},{"id":"C","text":"Pinch the nostrils closed briefly so the infant swallows the whole dose quickly"},{"id":"D","text":"Pour the dose into a medicine cup and hold it to the lips of the infant"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. If the infant does not finish the bottle, part of the dose is lost and the amount given is unknown.","B":"Correct. Small amounts placed along the side of the tongue use the natural swallow and reduce gagging and aspiration risk.","C":"Incorrect. Occluding the nose forces swallowing and is both frightening and a direct aspiration risk.","D":"Incorrect. A 5-month-old cannot control liquid from a cup and most of the dose would be lost."}}'::jsonb,
 'Physiological Integrity', 'Basic Care and Comfort',
 'Pediatrics', 'Gastrointestinal', 'Oral medication in infants', 'Administration technique',
 'Very easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_522013', 'MCQ',
 'A student nurse tells a 4-year-old that the tablets in the medicine pot are sweets, so that the child will take them. What is the BEST response by the nurse?',
 'Describing medication as sweets or a treat teaches a preschool child that tablets are safe to eat, and preschoolers are the age group most often poisoned by medicines found at home. The nurse addresses this with the student at the time and gives the reason, so the practice changes rather than simply stopping in front of a senior. Substituting the word vitamins carries exactly the same risk.',
 '{"options":[{"id":"A","text":"Agree with the approach, because the child took the dose without distress"},{"id":"B","text":"Explain to the student that medicines must never be described as sweets, because the child may later take them unsupervised"},{"id":"C","text":"Suggest that the student use the word vitamins instead"},{"id":"D","text":"Report the student to the ward manager without discussing it"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. A calm administration does not offset teaching a preschooler that tablets are safe to eat.","B":"Correct. Naming the risk and the reason corrects the practice and protects the child at home.","C":"Incorrect. Calling medication vitamins is the same deception and carries the same poisoning risk.","D":"Incorrect. Escalating without explaining leaves the student unaware of why the practice is unsafe."}}'::jsonb,
 'Safe and Effective Care Environment', 'Safety and Infection Control',
 'Pediatrics', 'Not applicable', 'Medication language with children', 'Accidental poisoning risk',
 'Very easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_522014', 'MCQ',
 'A 2-year-old refuses a bitter oral antibiotic. After asking the parent for permission to mix it with food, which vehicle should the nurse choose?',
 'When mixing is permitted, only a small amount of a non-essential food is used, so that the whole dose is taken even if the child eats little, and so that a staple food does not become associated with an unpleasant taste. A full bottle of milk or formula risks an incomplete dose and can put the child off feeding altogether. The nurse also checks compatibility, since dairy binds some antibiotics, and asks permission first because families may object on cultural or dietary grounds.',
 '{"options":[{"id":"A","text":"A full 240 mL bottle of milk"},{"id":"B","text":"One teaspoon of apple puree given immediately before the rest of the meal"},{"id":"C","text":"The infant formula the toddler takes at bedtime"},{"id":"D","text":"A cup of warm herbal tea prepared by the family"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. A large volume risks an incomplete dose and can make the child refuse milk in future.","B":"Correct. A small amount of a non-essential food carries the whole dose and protects staple foods from a bitter association.","C":"Incorrect. Mixing into a bedtime feed risks both an incomplete dose and refusal of the feed itself.","D":"Incorrect. The contents and compatibility of a home-prepared tea are unknown, and the volume is too large."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pediatrics', 'Gastrointestinal', 'Oral medication in toddlers', 'Mixing with food',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_522015', 'SATA',
 'A 3-year-old is refusing a prescribed oral medication on the paediatric ward. Which approaches should the nurse use? Select all that apply.',
 'Preschoolers are working on autonomy and initiative, so refusal is developmentally normal rather than defiance. Offering controlled choices, letting the child take part in the task, giving a very short concrete explanation, and praising cooperation all restore a sense of control and make the next dose easier. Deception secures one dose at the cost of trust, and force risks injury and aspiration as well as long-term fear of medical care.',
 '{"options":[{"id":"A","text":"Offer a limited choice, such as which cup to hold or where to sit"},{"id":"B","text":"Tell the child that the medicine is a sweet treat"},{"id":"C","text":"Allow the child to push the plunger of the oral syringe while the nurse guides it"},{"id":"D","text":"Explain in one short sentence that the medicine will help the sore throat"},{"id":"E","text":"Hold the child down firmly and give the dose quickly"},{"id":"F","text":"Withhold the dose and record that the child refused"}]}'::jsonb,
 '{"answers":["A","C","D","F"],"feedback":{"A":"Correct. A limited choice returns control to a child whose developmental task is autonomy, without negotiating whether the dose is given.","B":"Incorrect. Calling medicine a treat teaches a preschooler that tablets and syrups are safe to take unsupervised.","C":"Correct. Taking part in the task converts a procedure done to the child into one done with the child.","D":"Correct. A single short concrete sentence is what a 3-year-old can process; long explanations increase anxiety.","E":"Incorrect. Force risks aspiration and injury and destroys cooperation for every subsequent dose.","F":"Correct. If refusal persists the dose is withheld, documented and reported so an alternative route or formulation can be considered, rather than forced."}}'::jsonb,
 'Psychosocial Integrity', 'Psychosocial Integrity',
 'Pediatrics', 'Not applicable', 'Medication refusal in preschoolers', 'Developmental approaches',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SELN_522016', 'SELECT_N',
 'A child cannot swallow tablets whole and the parent asks whether they can be crushed. Which 3 preparations is crushing CONTRAINDICATED for?',
 'Crushing destroys a formulation designed to control where or how fast a drug is released. An enteric coating protects the drug from stomach acid, or the stomach from the drug; a modified-release matrix holds a whole day of drug that would then be delivered at once; and a sublingual tablet is designed to absorb under the tongue and bypass the liver. Plain, dispersible and scored tablets have no such mechanism and may be crushed or dispersed when no liquid form exists.',
 '{"options":[{"id":"A","text":"An enteric-coated tablet"},{"id":"B","text":"A plain paracetamol tablet"},{"id":"C","text":"A modified-release tablet"},{"id":"D","text":"A soluble dispersible tablet"},{"id":"E","text":"A sublingual tablet"},{"id":"F","text":"A scored plain antibiotic tablet"}],"select_count":3}'::jsonb,
 '{"answers":["A","C","E"],"feedback":{"A":"Correct. Crushing removes the coating that protects the drug from acid or the stomach from the drug.","B":"Incorrect. A plain paracetamol tablet has no release-controlling feature and may be crushed.","C":"Correct. Crushing a modified-release tablet delivers a whole day of drug at once, risking toxicity.","D":"Incorrect. A dispersible tablet is designed to be broken up in water.","E":"Correct. Crushing and swallowing a sublingual tablet sends it through first-pass metabolism and destroys its effect.","F":"Incorrect. A scored plain tablet is intended to be divided and may also be crushed if needed."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pharmacology', 'Not applicable', 'Altering medication formulations', 'Preparations that must not be crushed',
 'Very hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_522017', 'MCQ',
 'A 20 kg child requires maintenance intravenous fluids. Using the standard formula of 100 mL/kg for the first 10 kg and 50 mL/kg for the next 10 kg, how much fluid should the child receive in 24 hours?',
 'Maintenance fluid replaces normal ongoing losses and is calculated in bands, because the requirement per kilogram falls as a child grows. The first 10 kg attracts 100 mL/kg, or 1000 mL, and the second 10 kg attracts 50 mL/kg, or 500 mL, giving 1500 mL in 24 hours, roughly 62 mL per hour. Applying 100 mL/kg to the whole weight would give 2000 mL and risks circulatory overload.',
 '{"options":[{"id":"A","text":"1000 mL"},{"id":"B","text":"1250 mL"},{"id":"C","text":"1500 mL"},{"id":"D","text":"2000 mL"}]}'::jsonb,
 '{"answer":"C","feedback":{"A":"Incorrect. 1000 mL covers only the first 10 kg and omits the second band.","B":"Incorrect. 1250 mL uses 25 mL/kg for the second band rather than 50 mL/kg.","C":"Correct. 1000 mL for the first 10 kg plus 500 mL for the next 10 kg gives 1500 mL in 24 hours.","D":"Incorrect. 2000 mL applies 100 mL/kg to the whole weight and exceeds the maintenance requirement."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pediatrics', 'Multisystem', 'Paediatric maintenance fluids', 'Daily volume calculation',
 'Hard', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MAT_522018', 'MATRIX',
 'An 11-month-old infant is receiving intravenous maintenance fluids. For each finding, select whether it is expected or indicates fluid overload.',
 'A small child has a limited circulating volume, so a modest excess of intravenous fluid produces circulatory overload quickly. Sudden weight gain is the earliest and most reliable sign, because roughly 1 kg of acute gain represents 1 litre of retained fluid, and it appears before crackles or visible oedema. Periorbital oedema is often noticed first in an infant, because the loose tissue around the eyes swells before the ankles do in a child who spends much of the day lying down.',
 '{"rows":[{"id":"r1","text":"Urine output of 2 mL/kg/hour"},{"id":"r2","text":"Weight gain of 400 g over 12 hours"},{"id":"r3","text":"Fine crackles at both lung bases"},{"id":"r4","text":"Moist mucous membranes"},{"id":"r5","text":"Periorbital oedema on waking"},{"id":"r6","text":"Capillary refill of 2 seconds"}],"columns":[{"id":"c1","text":"Expected"},{"id":"c2","text":"Indicates fluid overload"}],"row_label":"Finding"}'::jsonb,
 '{"cells":{"r1":"c1","r2":"c2","r3":"c2","r4":"c1","r5":"c2","r6":"c1"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Pediatrics', 'Multisystem', 'Intravenous fluid therapy in children', 'Recognising fluid overload',
 'Medium', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_522019', 'MCQ',
 'A student nurse asks why intravenous fluids for children are given through a volumetric pump with a burette rather than a standard gravity giving set. Which explanation is correct?',
 'A burette is filled with only one or two hours of fluid at a time, so even if the pump fails or the roller clamp is opened fully, the child can receive only the small volume in the chamber. It is a physical safeguard rather than a calculation aid, and it matters because a volume that would be trivial for an adult can overload a 10 kg child within minutes. The rate is still calculated and the pump is still programmed.',
 '{"options":[{"id":"A","text":"The burette warms the fluid before it reaches the child"},{"id":"B","text":"The burette limits the volume that can be infused at any one time, so a pump or clamp failure cannot deliver a large volume"},{"id":"C","text":"The burette removes the need to calculate an infusion rate"},{"id":"D","text":"The burette allows medication to be given without dilution"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. A burette does not warm fluid; a dedicated fluid warmer is used when warming is needed.","B":"Correct. Only the small volume in the chamber can run through, which caps the harm from any single failure.","C":"Incorrect. The rate is still calculated and programmed into the pump.","D":"Incorrect. A burette is used to dilute medication into a measured volume, not to avoid dilution."}}'::jsonb,
 'Safe and Effective Care Environment', 'Safety and Infection Control',
 'Pediatrics', 'Multisystem', 'Paediatric infusion equipment', 'Burette rationale',
 'Very easy', 'CURATOR_LABEL', 'Understand', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_522020', 'SATA',
 'A 20-month-old with acute diarrhoea is being managed at home with oral rehydration solution. Which instructions should the nurse give the parent? Select all that apply.',
 'Small volumes given very frequently are absorbed even when a child is vomiting, whereas a large drink triggers further vomiting. Feeding is continued because early refeeding shortens the illness and prevents weight loss, and breast milk is never stopped. Fruit juice and soft drinks contain too much sugar and too little sodium, drawing water into the gut and worsening the diarrhoea, and the sachet must be made up with exactly the stated volume of clean water or the solution becomes dangerously concentrated.',
 '{"options":[{"id":"A","text":"Give 5 mL of the solution by oral syringe or spoon every one to two minutes"},{"id":"B","text":"Replace the oral rehydration solution with apple juice if the child dislikes the taste"},{"id":"C","text":"Continue breastfeeding or the usual milk feeds alongside the solution"},{"id":"D","text":"Withhold all food until the diarrhoea has stopped completely"},{"id":"E","text":"Return to the clinic if the child passes no urine for eight hours"},{"id":"F","text":"Prepare the solution with the exact volume of clean water stated on the sachet"}]}'::jsonb,
 '{"answers":["A","C","E","F"],"feedback":{"A":"Correct. Very small volumes given continuously are absorbed and do not distend the stomach enough to provoke vomiting.","B":"Incorrect. Fruit juice is high in sugar and low in sodium, which draws water into the gut and worsens the diarrhoea.","C":"Correct. Milk feeds and especially breast milk are continued, because early feeding shortens the illness.","D":"Incorrect. Prolonged starvation delays gut recovery and causes weight loss in a small child.","E":"Correct. Anuria for eight hours indicates significant dehydration and needs prompt review.","F":"Correct. Too little water makes the solution hypertonic, which can cause hypernatraemia."}}'::jsonb,
 'Physiological Integrity', 'Basic Care and Comfort',
 'Pediatrics', 'Gastrointestinal', 'Oral rehydration in children', 'Parent teaching',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728');

INSERT INTO nclex_bank_items (
  item_id, question_type, stem, rationale, content, correct,
  client_needs_category, client_needs_subcategory, nursing_subject, body_system,
  topic, subtopic, difficulty, difficulty_source, bloom_level, tags,
  marks, is_published, is_builder_visible, is_free_sample, cat_pool, batch_id
) VALUES
('NCLEX_MCQ_522021', 'MCQ',
 'A 9-month-old admitted with dehydration has received oral rehydration solution and intravenous fluids for 12 hours. Which finding is the BEST indicator that rehydration has been effective?',
 'Acute change in body weight is the most sensitive measure of fluid balance in a small child, because almost all of a short-term weight change is water. A rise from 7.2 kg to 7.6 kg represents about 400 mL of fluid replaced. A level fontanelle and settled behaviour support the picture but are subjective and appear later, and tolerating the solution tells the nurse that the route is working, not that the deficit has been corrected.',
 '{"options":[{"id":"A","text":"The infant is taking the oral rehydration solution without vomiting"},{"id":"B","text":"The body weight has risen from 7.2 kg to 7.6 kg"},{"id":"C","text":"The anterior fontanelle feels level rather than sunken"},{"id":"D","text":"The parent reports that the infant seems more settled"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. Tolerating the fluid shows the route is usable but says nothing about how much deficit has been replaced.","B":"Correct. A 400 g gain over 12 hours represents about 400 mL of fluid replaced and is the most objective measure available.","C":"Incorrect. A level fontanelle is supportive but is a subjective assessment that changes late and varies between examiners.","D":"Incorrect. Improved behaviour is reassuring but is influenced by rest, comfort and parental presence."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Pediatrics', 'Genitourinary', 'Dehydration in children', 'Evaluating rehydration',
 'Hard', 'CURATOR_LABEL', 'Evaluate', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_522022', 'MCQ',
 'A 10-month-old receiving intravenous fluids develops fine crackles at both lung bases, periorbital oedema, and a respiratory rate that has risen from 32 to 56 breaths per minute. Which action should the nurse take FIRST?',
 'When an intervention is causing harm, stopping the cause comes before assessing or reporting it, because every further millilitre worsens the overload. Reducing the infusion to a keep-vein-open rate takes seconds, protects the venous access for treatment that may be needed, and removes the ongoing insult. Sitting the infant upright, giving oxygen, weighing and contacting the prescriber all follow immediately afterwards, but none of them helps while fluid continues to run in at the same rate.',
 '{"options":[{"id":"A","text":"Reduce the infusion to a keep-vein-open rate"},{"id":"B","text":"Weigh the infant"},{"id":"C","text":"Contact the prescriber to review the fluid prescription"},{"id":"D","text":"Sit the infant upright and administer oxygen"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Stopping the ongoing cause is the first step; the line is kept patent for treatment that may follow.","B":"Incorrect. The weight confirms the diagnosis but does nothing to halt fluid still entering the circulation.","C":"Incorrect. The prescriber must be contacted, but not before the infusion causing the harm has been reduced.","D":"Incorrect. Positioning and oxygen improve the symptoms while the cause continues unchecked."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Pediatrics', 'Cardiovascular', 'Fluid overload in children', 'First action',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_522023', 'SATA',
 'The nurse is reviewing children attending an immunisation clinic. Which situations are true contraindications to giving the scheduled vaccine today? Select all that apply.',
 'The list of true contraindications is short: anaphylaxis to a previous dose or to a vaccine component, live vaccines in significant immunosuppression, and encephalopathy shortly after a pertussis-containing vaccine. Minor illness with or without low-grade fever, current antibiotics and breastfeeding are all false contraindications. Treating false contraindications as reasons to defer is a leading cause of children falling behind schedule and remaining unprotected.',
 '{"options":[{"id":"A","text":"Anaphylaxis after a previous dose of the same vaccine"},{"id":"B","text":"A runny nose and a temperature of 37.6 °C"},{"id":"C","text":"A live vaccine prescribed for a child receiving high-dose immunosuppressive therapy"},{"id":"D","text":"A current course of oral antibiotics for otitis media"},{"id":"E","text":"Encephalopathy within 7 days of a previous pertussis-containing vaccine"},{"id":"F","text":"A mother who is breastfeeding"}]}'::jsonb,
 '{"answers":["A","C","E"],"feedback":{"A":"Correct. Anaphylaxis to a previous dose is an absolute contraindication to further doses of that vaccine.","B":"Incorrect. Minor illness with low-grade fever is a false contraindication and the vaccine is given.","C":"Correct. A live vaccine can cause disseminated infection in a significantly immunosuppressed child.","D":"Incorrect. Antibiotics do not interfere with the immune response to vaccines.","E":"Correct. Encephalopathy within 7 days of a pertussis-containing vaccine contraindicates further pertussis-containing doses.","F":"Incorrect. Breastfeeding is not a contraindication for either the mother or the infant."}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance',
 'Pediatrics', 'Immune', 'Immunisation', 'True and false contraindications',
 'Hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_522024', 'MCQ',
 'At a well-child visit a parent tells the nurse that the family has decided against the measles vaccine because of material they have read online. Which response by the nurse is most appropriate?',
 'Vaccine hesitancy is rarely changed by contradiction, and dismissing a concern usually hardens it. Asking what the parent has actually read identifies the specific worry, respects the role of the parent as decision maker, and lets the nurse give information that answers that worry rather than a general reassurance. The refusal is documented, immunisation is offered again at the next visit, and the relationship is preserved so that the conversation can continue.',
 '{"options":[{"id":"A","text":"Explain that the vaccine is required and the visit cannot continue without it"},{"id":"B","text":"Ask what specific concerns the parent has read about, and listen before responding"},{"id":"C","text":"Tell the parent that online information is unreliable and should be ignored"},{"id":"D","text":"Document the refusal and end the discussion"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. Coercion is neither accurate nor effective and usually ends the conversation permanently.","B":"Correct. Eliciting the specific concern allows a targeted response and keeps the parent engaged.","C":"Incorrect. Dismissing the source without addressing the concern tends to entrench the decision.","D":"Incorrect. Documentation is necessary but closing the conversation forfeits the chance to inform the decision."}}'::jsonb,
 'Psychosocial Integrity', 'Psychosocial Integrity',
 'Pediatrics', 'Immune', 'Immunisation', 'Parental refusal',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SELN_522025', 'SELECT_N',
 'A 4-month-old is to receive two separate intramuscular vaccines at the same visit. Which 3 actions should the nurse take?',
 'Two vaccines may be given at the same visit and neither reduces the response to the other, so there is no reason to split the visit and risk a missed appointment. They are given in separate sites, at least 2.5 cm apart if the same thigh is used, so that any local reaction can be attributed to the correct vaccine. Vaccines are never combined in one syringe unless supplied that way, and the name, batch number and site of each are recorded so that reactions can be traced.',
 '{"options":[{"id":"A","text":"Give both vaccines into the vastus lateralis muscles"},{"id":"B","text":"Separate the two injection sites by at least 2.5 cm if the same thigh is used"},{"id":"C","text":"Draw both vaccines into one syringe to reduce the number of injections"},{"id":"D","text":"Document the vaccine name, batch number and site for each injection"},{"id":"E","text":"Massage each site vigorously after the injection"},{"id":"F","text":"Delay the second vaccine by 24 hours to see whether the first is tolerated"}],"select_count":3}'::jsonb,
 '{"answers":["A","B","D"],"feedback":{"A":"Correct. The vastus lateralis is the site of choice for intramuscular vaccines in an infant.","B":"Correct. A gap of at least 2.5 cm allows local reactions to be attributed to the right vaccine.","C":"Incorrect. Vaccines are never mixed in one syringe unless the manufacturer supplies them combined.","D":"Correct. Recording name, batch and site for each injection is required for traceability if a reaction occurs.","E":"Incorrect. Vigorous massage increases local reaction and is not recommended after vaccination.","F":"Incorrect. Splitting the visit delays protection and increases the chance of a missed appointment, with no safety benefit."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pediatrics', 'Immune', 'Immunisation administration', 'Multiple vaccines at one visit',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_CLZ_522026', 'CLOZE',
 'When two live vaccines are not given on the same day, the nurse must separate them by at least {1}. When two intramuscular vaccines are given in the same thigh, the injection sites must be at least {2} apart.',
 'Two live vaccines given a few days apart can blunt the immune response to the second, so if they are not given on the same day they are separated by at least four weeks. Inactivated vaccines carry no such rule and may be given at any interval. The spacing between injection sites in the same limb exists so that a local reaction can be attributed to the correct vaccine.',
 '{"blanks":[{"id":"b1","choices":[{"id":"c1","text":"48 hours"},{"id":"c2","text":"7 days"},{"id":"c3","text":"4 weeks"},{"id":"c4","text":"6 months"}]},{"id":"b2","choices":[{"id":"c1","text":"0.5 cm"},{"id":"c2","text":"2.5 cm"},{"id":"c3","text":"10 cm"},{"id":"c4","text":"15 cm"}]}]}'::jsonb,
 '{"answers":{"b1":"c3","b2":"c2"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pediatrics', 'Immune', 'Immunisation', 'Spacing rules',
 'Very hard', 'CURATOR_LABEL', 'Remember', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_522027', 'MCQ',
 'A 3-year-old has received only the first dose of a three-dose vaccine series, given 18 months ago. What should the nurse do?',
 'An interrupted vaccine schedule is resumed, never restarted, however long the gap has been, because immunological memory from the earlier dose persists. Restarting subjects the child to unnecessary injections and delays full protection further. Serological testing is not required to decide catch-up doses in routine practice, and no routine childhood series is abandoned because of age at this point.',
 '{"options":[{"id":"A","text":"Restart the series from the first dose"},{"id":"B","text":"Give the second dose today and schedule the third at the correct interval"},{"id":"C","text":"Refer the child for antibody testing before giving any further doses"},{"id":"D","text":"Advise the family that the child is now too old to complete the series"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. A lapsed schedule is resumed, not restarted; the earlier dose still counts.","B":"Correct. The series continues from where it stopped, with the remaining doses at the recommended intervals.","C":"Incorrect. Routine catch-up does not require antibody testing before further doses.","D":"Incorrect. Catch-up immunisation is offered well beyond this age."}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance',
 'Pediatrics', 'Immune', 'Immunisation', 'Catch-up schedule',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SELN_522028', 'SELECT_N',
 'A 2-year-old is being observed after surgery. Which 3 findings should the nurse recognise as early signs of deterioration requiring urgent escalation?',
 'A child compensates for circulatory failure by raising the heart rate and respiratory rate and by shunting blood away from the skin, and can maintain a normal blood pressure until compensation abruptly fails. Tachycardia, tachypnoea and poor peripheral perfusion are therefore the early warning signs, and a normal blood pressure is reassuring only in the sense that decompensation has not yet happened. Waiting for hypotension in a child means waiting for arrest.',
 '{"options":[{"id":"A","text":"A heart rate that has risen from 110 to 168 beats per minute"},{"id":"B","text":"A respiratory rate that has risen from 26 to 48 breaths per minute"},{"id":"C","text":"A blood pressure of 92/56 mmHg"},{"id":"D","text":"Cool, mottled peripheries with a capillary refill of 4 seconds"},{"id":"E","text":"Crying vigorously when the wound dressing is touched"},{"id":"F","text":"A temperature of 37.4 °C"}],"select_count":3}'::jsonb,
 '{"answers":["A","B","D"],"feedback":{"A":"Correct. A rising heart rate is the earliest and most consistent compensatory response in a deteriorating child.","B":"Correct. Tachypnoea reflects both respiratory compromise and the effort to correct a metabolic acidosis.","C":"Incorrect. This blood pressure is within normal limits for a 2-year-old; hypotension is a very late sign.","D":"Correct. Mottling and prolonged capillary refill show that blood is being shunted away from the skin.","E":"Incorrect. A vigorous cry to a painful stimulus indicates a responsive child with an intact airway.","F":"Incorrect. 37.4 °C is within normal limits and does not require escalation on its own."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Pediatrics', 'Multisystem', 'Paediatric deterioration', 'Compensation and early recognition',
 'Hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SELN_522029', 'SELECT_N',
 'A 3-year-old of unknown weight is brought to the emergency department in cardiac arrest. Which 3 actions should the nurse take to establish drug doses and equipment sizes?',
 'A length-based paediatric resuscitation tape estimates weight from measured height and gives the corresponding drug doses, tracheal tube sizes and defibrillation energies on the same colour band, which removes arithmetic from the moment when errors are most likely. Halving adult doses has no pharmacological basis in children, recalled weights from relatives are frequently wrong, and no child in arrest is left untreated while a scale is found. Doses are still checked by a second person aloud.',
 '{"options":[{"id":"A","text":"Measure the child with a length-based paediatric resuscitation tape"},{"id":"B","text":"Use the colour band on the tape to select the tracheal tube size and defibrillation energy"},{"id":"C","text":"Have a second practitioner check each drug dose aloud before it is given"},{"id":"D","text":"Use adult doses and halve each one"},{"id":"E","text":"Ask the accompanying relative to estimate the weight in pounds"},{"id":"F","text":"Delay drug administration until the child can be weighed on a bed scale"}],"select_count":3}'::jsonb,
 '{"answers":["A","B","C"],"feedback":{"A":"Correct. The tape converts measured length into an estimated weight without any calculation.","B":"Correct. Equipment sizes and energy settings are read from the same colour band as the drug doses.","C":"Correct. A spoken second check catches decimal-point errors, which are the classic paediatric emergency mistake.","D":"Incorrect. Paediatric doses are not fractions of adult doses and this method has no pharmacological basis.","E":"Incorrect. Recalled weights are often inaccurate, and converting from pounds adds a further error step.","F":"Incorrect. Resuscitation drugs are never delayed while a child is weighed."}}'::jsonb,
 'Safe and Effective Care Environment', 'Management of Care',
 'Pediatrics', 'Multisystem', 'Paediatric resuscitation', 'Weight estimation and equipment sizing',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_522030', 'MCQ',
 'A 15 kg child develops anaphylaxis. Adrenaline (epinephrine) 1 mg/mL is prescribed at 0.01 mg/kg intramuscularly. Which dose should the nurse give, and where?',
 'The dose is 15 kg multiplied by 0.01 mg, which is 0.15 mg, equal to 0.15 mL of the 1 mg/mL strength. The anterolateral thigh is used because the vastus lateralis is large and well perfused, giving faster absorption than the deltoid when the circulation is failing. A misplaced decimal point in either direction is the classic error with this drug, so the calculation is double checked even in an emergency.',
 '{"options":[{"id":"A","text":"0.015 mg into the deltoid"},{"id":"B","text":"0.15 mg into the anterolateral thigh"},{"id":"C","text":"0.5 mg into the anterolateral thigh"},{"id":"D","text":"1.5 mg into the ventrogluteal site"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. 0.015 mg is a tenfold underdose and the deltoid absorbs more slowly in shock.","B":"Correct. 15 kg multiplied by 0.01 mg is 0.15 mg, given into the well-perfused vastus lateralis.","C":"Incorrect. 0.5 mg is the standard adult dose and more than three times what this child needs.","D":"Incorrect. 1.5 mg is a tenfold overdose and the ventrogluteal site is not used for emergency adrenaline."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pharmacology', 'Immune', 'Anaphylaxis in children', 'Adrenaline dose and site',
 'Hard', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728');

INSERT INTO nclex_bank_items (
  item_id, question_type, stem, rationale, content, correct,
  client_needs_category, client_needs_subcategory, nursing_subject, body_system,
  topic, subtopic, difficulty, difficulty_source, bloom_level, tags,
  marks, is_published, is_builder_visible, is_free_sample, cat_pool, batch_id
) VALUES
('NCLEX_MCQ_522031', 'MCQ',
 'A parent telephones to say that a 6-year-old with chickenpox has been given aspirin for fever. Which action should the nurse take?',
 'Aspirin taken during a viral illness such as chickenpox or influenza is associated with Reye syndrome, an acute encephalopathy with fatty infiltration of the liver that can be fatal. The association is with exposure at all rather than with the size of the dose, so reducing it is no safer. Persistent vomiting followed by irritability, confusion or drowsiness is the presenting pattern and must be reported at once; paracetamol is the appropriate antipyretic in children.',
 '{"options":[{"id":"A","text":"Reassure the parent that aspirin is a suitable antipyretic for children"},{"id":"B","text":"Advise the parent to stop the aspirin, explain the link with Reye syndrome, and report any vomiting or unusual drowsiness"},{"id":"C","text":"Advise the parent to halve the aspirin dose"},{"id":"D","text":"Advise the parent to give the aspirin with food to prevent gastric upset"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. Aspirin is avoided as an antipyretic in children because of the association with Reye syndrome.","B":"Correct. The drug is stopped, the reason is explained, and the parent is given the specific signs that require urgent review.","C":"Incorrect. The risk relates to exposure rather than dose size, so a smaller dose is not safer.","D":"Incorrect. Food protects the stomach but does nothing about the encephalopathy risk."}}'::jsonb,
 'Safe and Effective Care Environment', 'Safety and Infection Control',
 'Pediatrics', 'Neurological', 'Aspirin in children', 'Reye syndrome',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_522032', 'MCQ',
 'A 2-year-old has had vomiting and diarrhoea for two days, has passed urine only once in 12 hours, and has a temperature of 38.9 °C. Ibuprofen is prescribed. Which action should the nurse take?',
 'Ibuprofen is a non-steroidal anti-inflammatory drug and reduces renal blood flow by inhibiting prostaglandins. In a dehydrated child whose kidneys already depend on prostaglandin-mediated vasodilation to maintain perfusion, this can precipitate acute kidney injury. Paracetamol does not share this effect and is the safer antipyretic until the child is rehydrated; giving the drug with food or in a smaller dose does not remove the renal risk.',
 '{"options":[{"id":"A","text":"Give the ibuprofen as prescribed, since the fever is high"},{"id":"B","text":"Withhold the ibuprofen, report the reduced urine output, and give paracetamol if an antipyretic is needed"},{"id":"C","text":"Give the ibuprofen with milk to protect the stomach"},{"id":"D","text":"Give half the prescribed ibuprofen dose"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. The height of the fever does not change the renal risk of a non-steroidal drug in a dehydrated child.","B":"Correct. The drug is withheld, the poor urine output is escalated, and paracetamol provides antipyresis without the renal effect.","C":"Incorrect. Milk addresses gastric irritation, not the reduction in renal perfusion.","D":"Incorrect. Halving the dose still inhibits prostaglandins and is also an unauthorised change to the prescription."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pharmacology', 'Genitourinary', 'Ibuprofen in children', 'Withholding in dehydration',
 'Very hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_522033', 'SATA',
 'A parent describes how paracetamol is given at home to a 3-year-old. Which statements indicate a need for further teaching? Select all that apply.',
 'Paracetamol overdose in children is usually cumulative rather than a single large ingestion. Combination cold and flu remedies very often contain paracetamol, so giving one alongside a paracetamol dose silently doubles the intake. Shortening the interval between doses, and dosing by apparent size rather than by weight or the age band on the label, are the two other common routes to exceeding the maximum daily amount.',
 '{"options":[{"id":"A","text":"I also give a cold and flu syrup that helps the blocked nose"},{"id":"B","text":"I measure the dose with the syringe that came in the box"},{"id":"C","text":"I give a dose every four hours, up to four doses in 24 hours"},{"id":"D","text":"If the fever does not come down I give an extra dose after two hours"},{"id":"E","text":"I keep the bottle in a high cupboard with the child-resistant cap on"},{"id":"F","text":"I use the dose for a 5-year-old because he is big for his age"}]}'::jsonb,
 '{"answers":["A","D","F"],"feedback":{"A":"Correct, this needs teaching. Most cold and flu remedies contain paracetamol, so the total daily intake can double without the parent realising.","B":"Incorrect, this is safe practice. The supplied syringe measures the dose accurately, unlike a household spoon.","C":"Incorrect, this is safe practice. Four-hourly dosing to a maximum of four doses in 24 hours is within the recommended limit.","D":"Correct, this needs teaching. Shortening the interval to two hours risks exceeding the maximum daily dose.","E":"Incorrect, this is safe practice. Out-of-reach storage with a child-resistant cap reduces the risk of accidental ingestion.","F":"Correct, this needs teaching. Dosing by apparent size rather than actual weight or age band leads to overdose."}}'::jsonb,
 'Safe and Effective Care Environment', 'Safety and Infection Control',
 'Pediatrics', 'Gastrointestinal', 'Paracetamol safety in children', 'Combination products and maximum dose',
 'Hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_522034', 'SATA',
 'The nurse is teaching the parent of an 18-month-old about managing fever at home. Which instructions should the nurse include? Select all that apply.',
 'Fever is a normal immune response, so the aim of treatment is comfort rather than a particular number on the thermometer. Frequent small drinks and light clothing help, and an antipyretic is given when the child is distressed rather than by the clock. Cold sponging causes shivering, which raises the core temperature, and waking a comfortable sleeping child to medicate has no benefit. Parents are always given the specific signs that mean urgent review is needed.',
 '{"options":[{"id":"A","text":"Offer fluids frequently in small amounts"},{"id":"B","text":"Sponge the child with cold water to bring the temperature down quickly"},{"id":"C","text":"Dress the child in a single light layer"},{"id":"D","text":"Give an antipyretic if the child is distressed by the fever"},{"id":"E","text":"Wake the child overnight to give antipyretics regardless of comfort"},{"id":"F","text":"Seek review if the child becomes floppy, develops a non-blanching rash, or refuses to drink"}]}'::jsonb,
 '{"answers":["A","C","D","F"],"feedback":{"A":"Correct. Insensible losses rise with fever, and small frequent drinks are better tolerated than large ones.","B":"Incorrect. Cold sponging causes shivering and peripheral vasoconstriction, which raise the core temperature.","C":"Correct. A single light layer allows heat loss without causing shivering.","D":"Correct. Antipyretics are given for the comfort of the child rather than to normalise a number.","E":"Incorrect. Waking a settled child to medicate disturbs rest without benefit.","F":"Correct. Floppiness, a non-blanching rash and refusal to drink are red flags that need urgent assessment."}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance',
 'Pediatrics', 'Multisystem', 'Fever management in children', 'Parent teaching',
 'Very easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_522035', 'MCQ',
 'On day three of a ten-day course of oral antibiotics, a parent tells the nurse that the child is now well and the remaining doses will be kept for the next illness. Which response by the nurse is most appropriate?',
 'Symptoms improve well before the organism is eradicated, so stopping early allows the least susceptible bacteria to survive and multiply, which causes relapse and drives resistance. A reconstituted suspension also has a short shelf life and would no longer be effective, and an antibiotic saved from one illness may be entirely wrong for the next. The nurse gives the reason rather than simply instructing, so the family can act on it.',
 '{"options":[{"id":"A","text":"Agree, provided the medicine is stored in the refrigerator"},{"id":"B","text":"Explain that the full course is needed to clear the infection and that leftover antibiotics must never be kept for future use"},{"id":"C","text":"Suggest giving the remaining doses once daily instead of three times daily"},{"id":"D","text":"Advise the parent to stop now and return for a repeat prescription if symptoms recur"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. Refrigeration does not make an interrupted course or a saved antibiotic safe or effective.","B":"Correct. Completing the course clears the organism, and leftover antibiotics are discarded rather than stored.","C":"Incorrect. Spreading out the doses drops the drug level below the therapeutic range and promotes resistance.","D":"Incorrect. This accepts the interrupted course and makes relapse with a less susceptible organism likely."}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance',
 'Pediatrics', 'Immune', 'Antibiotics in children', 'Completing the course',
 'Very easy', 'CURATOR_LABEL', 'Understand', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MAT_522036', 'MATRIX',
 'A parent is being discharged with a reconstituted oral antibiotic suspension for a 4-year-old. For each statement, select whether it shows correct understanding or a need for further teaching.',
 'A reconstituted suspension is a mixture rather than a solution, so the drug settles and the bottle must be shaken before every dose, otherwise the early doses are weak and the last ones are concentrated. Most reconstituted antibiotics are refrigerated and discarded 14 days after mixing, and the remainder is never kept for a future illness. Household spoons vary from about 2 mL to 7 mL, so the supplied syringe or measuring cup is used.',
 '{"rows":[{"id":"r1","text":"I will shake the bottle well before every dose"},{"id":"r2","text":"I will keep the bottle in the refrigerator"},{"id":"r3","text":"I will keep whatever is left for the next time he is unwell"},{"id":"r4","text":"I will measure the dose with a kitchen teaspoon"},{"id":"r5","text":"I will throw away what is left 14 days after it was mixed"},{"id":"r6","text":"I will stop the medicine once the fever settles"}],"columns":[{"id":"c1","text":"Correct understanding"},{"id":"c2","text":"Needs further teaching"}],"row_label":"Statement"}'::jsonb,
 '{"cells":{"r1":"c1","r2":"c1","r3":"c2","r4":"c2","r5":"c1","r6":"c2"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pediatrics', 'Immune', 'Antibiotic suspensions', 'Reconstitution and storage',
 'Medium', 'CURATOR_LABEL', 'Evaluate', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_522037', 'MCQ',
 'On the second day of oral amoxicillin, a 5-year-old develops a widespread raised itchy rash. There is no facial swelling and no respiratory difficulty. Which action should the nurse take FIRST?',
 'An urticarial rash appearing during a penicillin course may be the first stage of a hypersensitivity reaction, and a further dose can convert it into anaphylaxis. Withholding the next dose removes the exposure immediately, and informing the prescriber allows the antibiotic to be changed and the allergy to be recorded so that it follows the child through future care. Symptomatic treatment may well follow, but not while the causative drug continues.',
 '{"options":[{"id":"A","text":"Withhold the next dose and inform the prescriber"},{"id":"B","text":"Apply an emollient and continue the antibiotic"},{"id":"C","text":"Give the prescribed antihistamine and continue the antibiotic"},{"id":"D","text":"Document the rash and reassess in 24 hours"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Removing the exposure comes first, and the prescriber can then change the antibiotic and record the allergy.","B":"Incorrect. An emollient soothes the skin while the drug that may be causing the reaction continues.","C":"Incorrect. An antihistamine may be given, but continuing the penicillin risks progression to anaphylaxis.","D":"Incorrect. Waiting 24 hours means at least two further doses of a drug the child may be allergic to."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pediatrics', 'Immune', 'Antibiotic hypersensitivity', 'First action on a drug rash',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_522038', 'MCQ',
 'A child has been taking oral prednisolone for eight weeks for nephrotic syndrome. The parent asks whether the medicine can simply be stopped now that the child looks well. Which explanation should the nurse give?',
 'Exogenous corticosteroid suppresses the hypothalamic-pituitary-adrenal axis, so after a few weeks the adrenal glands no longer produce cortisol at normal rates. Stopping abruptly leaves the child unable to mount a cortisol response, producing acute adrenal insufficiency with vomiting, hypotension and hypoglycaemia. A planned taper allows the axis to recover, and during intercurrent illness the dose is increased rather than stopped.',
 '{"options":[{"id":"A","text":"The medicine may be stopped at any time once the swelling has gone"},{"id":"B","text":"The dose must be reduced gradually as prescribed, because the adrenal glands have stopped producing cortisol normally"},{"id":"C","text":"The medicine should be stopped only if the child develops an infection"},{"id":"D","text":"The medicine may be stopped and restarted according to how the child looks each week"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. Abrupt withdrawal after weeks of therapy can precipitate acute adrenal insufficiency.","B":"Correct. A planned taper gives the suppressed adrenal axis time to resume cortisol production.","C":"Incorrect. During infection the corticosteroid dose is usually increased, never stopped.","D":"Incorrect. Starting and stopping repeatedly destabilises both the disease and the adrenal axis."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pharmacology', 'Endocrine', 'Corticosteroids in children', 'Never stopping abruptly',
 'Medium', 'CURATOR_LABEL', 'Understand', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_522039', 'SATA',
 'A 7-year-old is starting long-term oral corticosteroid therapy. Which points should the nurse include when teaching the family? Select all that apply.',
 'Long-term corticosteroids slow linear growth, so height as well as weight is plotted at every visit and is often the first measure to change. They also suppress immunity, so exposure to chickenpox or measles needs prompt assessment and the usual signs of infection may be blunted. Morning dosing with food mirrors the natural cortisol peak and protects the stomach. Corticosteroids cause sodium retention rather than loss, so extra salt is not needed.',
 '{"options":[{"id":"A","text":"Height and weight will be measured at every clinic visit"},{"id":"B","text":"Report contact with chickenpox or measles promptly"},{"id":"C","text":"The dose may be stopped for a few days if the child feels unwell"},{"id":"D","text":"Give the dose with food, in the morning"},{"id":"E","text":"Signs of infection may be masked, so report any unexplained fever"},{"id":"F","text":"Add salt generously to meals to replace losses"}]}'::jsonb,
 '{"answers":["A","B","D","E"],"feedback":{"A":"Correct. Growth suppression is a specific paediatric effect, so height is monitored alongside weight.","B":"Correct. An immunosuppressed child exposed to varicella or measles may need post-exposure prophylaxis.","C":"Incorrect. During illness the dose is increased, not stopped, to cover the extra cortisol demand.","D":"Correct. Morning dosing follows the natural cortisol peak, and food reduces gastric irritation.","E":"Correct. Corticosteroids blunt the inflammatory response, so infection can present with few signs.","F":"Incorrect. Corticosteroids cause sodium and water retention, so added salt would worsen oedema and blood pressure."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pediatrics', 'Endocrine', 'Corticosteroids in children', 'Long-term therapy teaching',
 'Very hard', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_522040', 'MCQ',
 'The parent of a 9-year-old with type 1 diabetes telephones to say the child has influenza, is vomiting and has eaten nothing since morning, and asks whether the insulin should be omitted. Which response should the nurse give?',
 'Illness raises counter-regulatory hormones, so the insulin requirement usually rises even when a child is not eating. Omitting insulin is the commonest precipitant of diabetic ketoacidosis during an intercurrent illness. Sick-day rules therefore continue the insulin, add frequent blood glucose and ketone monitoring, and replace missed meals with small frequent sugary drinks, with hospital review arranged if ketones rise or vomiting persists.',
 '{"options":[{"id":"A","text":"Omit the insulin until the child is eating normally again"},{"id":"B","text":"Continue the insulin, check blood glucose and ketones every two to four hours, and give small frequent sugary fluids"},{"id":"C","text":"Give half the usual insulin dose and recheck in the morning"},{"id":"D","text":"Bring the child to hospital before giving any further insulin"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. Omitting insulin during illness is the leading cause of diabetic ketoacidosis in children.","B":"Correct. Insulin continues, monitoring intensifies, and carbohydrate is replaced in fluid form.","C":"Incorrect. Halving the dose without glucose and ketone data risks ketosis, as requirements usually rise in illness.","D":"Incorrect. Insulin is not delayed pending transfer; review is arranged if ketones rise or vomiting continues."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pediatrics', 'Endocrine', 'Insulin in children', 'Sick-day rules',
 'Hard', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728');

INSERT INTO nclex_bank_items (
  item_id, question_type, stem, rationale, content, correct,
  client_needs_category, client_needs_subcategory, nursing_subject, body_system,
  topic, subtopic, difficulty, difficulty_source, bloom_level, tags,
  marks, is_published, is_builder_visible, is_free_sample, cat_pool, batch_id
) VALUES
('NCLEX_SATA_522041', 'SATA',
 'A 15-year-old with type 1 diabetes has joined the school football team. Which advice should the nurse give? Select all that apply.',
 'Exercise increases insulin sensitivity and muscle glucose uptake, so the risk during and after sport is hypoglycaemia rather than hyperglycaemia, and extra rapid-acting insulin beforehand would make that worse. Because muscle continues to replenish glycogen for hours afterwards, delayed and overnight hypoglycaemia is common after a hard match. Exercise is actively encouraged, with planning rather than avoidance.',
 '{"options":[{"id":"A","text":"Check the blood glucose before the match, during prolonged play and afterwards"},{"id":"B","text":"Carry a fast-acting carbohydrate on the pitch and tell the coach where it is"},{"id":"C","text":"Take an extra dose of rapid-acting insulin before kick-off"},{"id":"D","text":"Take extra carbohydrate before exercise if the blood glucose is at the lower end of target"},{"id":"E","text":"Be aware that hypoglycaemia can occur several hours after the match, including overnight"},{"id":"F","text":"Avoid sport on days when insulin is due"}]}'::jsonb,
 '{"answers":["A","B","D","E"],"feedback":{"A":"Correct. Monitoring around exercise shows how this particular adolescent responds and guides adjustment.","B":"Correct. Fast-acting carbohydrate must be immediately available, and someone present needs to know where it is.","C":"Incorrect. Exercise already increases insulin sensitivity, so extra insulin would provoke hypoglycaemia.","D":"Correct. Additional carbohydrate before exercise offsets the increased glucose uptake by working muscle.","E":"Correct. Muscle glycogen replenishment continues for hours, causing delayed and overnight hypoglycaemia.","F":"Incorrect. Insulin is given every day, and avoiding exercise removes a major benefit to glycaemic control and health."}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance',
 'Pediatrics', 'Endocrine', 'Diabetes in adolescents', 'Exercise and hypoglycaemia',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MMR_522042', 'MATRIX_MR',
 'For each diabetes self-care task, select every age at which a child can usually carry out the task independently. Each task has at least one correct answer.',
 'Responsibility is handed over in step with cognitive development rather than with how long the child has had diabetes. A young school-age child can report how they feel and take part in the routine but cannot judge a dose. By about ten years a child can perform the mechanical tasks and act on a low reading, while abstract calculation from a carbohydrate ratio and unsupervised injection belong to adolescence. Adults stay involved throughout, because handing over too early is a common cause of missed doses and poor control.',
 '{"rows":[{"id":"r1","text":"Telling an adult about symptoms of hypoglycaemia"},{"id":"r2","text":"Performing a finger-prick blood glucose test"},{"id":"r3","text":"Recognising hypoglycaemia and treating it with a fast-acting carbohydrate"},{"id":"r4","text":"Drawing up and injecting the correct insulin dose without supervision"},{"id":"r5","text":"Calculating an insulin dose from a carbohydrate ratio"}],"columns":[{"id":"c1","text":"6 years"},{"id":"c2","text":"10 years"},{"id":"c3","text":"15 years"}],"row_label":"Task"}'::jsonb,
 '{"cells":{"r1":["c1","c2","c3"],"r2":["c2","c3"],"r3":["c2","c3"],"r4":["c3"],"r5":["c3"]},"feedback":{}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance',
 'Pediatrics', 'Endocrine', 'Diabetes self-management by age', 'Developmental readiness',
 'Very hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_DO_522043', 'DRAG_ORDER',
 'Place the nursing actions for a lumbar puncture on a 4-month-old infant in the order they should be carried out. One option should not be used.',
 'Consent and explanation come first, because nothing is done to a child without them. Topical anaesthetic needs time to take effect, so it is applied before the infant is positioned rather than afterwards. Positioning opens the intervertebral spaces, and in an infant the knee-to-chest curl must be held without flexing the neck, because neck flexion obstructs the small airway. Continuous observation of breathing and oxygen saturation during the procedure is the specific paediatric nursing responsibility, and pressure with a dressing afterwards reduces leakage from the puncture site.',
 '{"slots":[{"id":"s1","target_text":"1st"},{"id":"s2","target_text":"2nd"},{"id":"s3","target_text":"3rd"},{"id":"s4","target_text":"4th"},{"id":"s5","target_text":"5th"}],"tokens":[{"id":"t1","text":"Monitor respiratory effort and oxygen saturation throughout the procedure"},{"id":"t2","text":"Confirm that written consent has been obtained and the procedure explained to the parents"},{"id":"t3","text":"Apply pressure and a dressing to the puncture site and observe for leakage"},{"id":"t4","text":"Apply the prescribed topical anaesthetic to the site and allow it time to work"},{"id":"t5","text":"Secure the infant with wrist and ankle straps for the duration of the procedure"},{"id":"t6","text":"Position the infant on the side in a knee-to-chest curl, avoiding neck flexion"}]}'::jsonb,
 '{"slots":{"s1":"t2","s2":"t4","s3":"t6","s4":"t1","s5":"t3"}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Pediatrics', 'Neurological', 'Lumbar puncture in infants', 'Nursing sequence and positioning',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_522044', 'SATA',
 'A 4-year-old requires venepuncture for a blood sample. Which comfort measures should the nurse use? Select all that apply.',
 'Preschoolers cope best with a short honest explanation given close to the event, because a long warning only extends the anxiety. Topical anaesthetic, a parent-held comfort position rather than lying flat and held down, and an active distraction such as blowing bubbles all reduce measured distress and make later procedures easier. Promising that it will not hurt destroys trust, and the bed should remain a safe place, so painful procedures are carried out in a treatment room.',
 '{"options":[{"id":"A","text":"Apply a topical anaesthetic and allow the recommended time for it to work"},{"id":"B","text":"Explain what will happen in simple words, shortly before the procedure"},{"id":"C","text":"Invite the parent to hold the child in a comfort position on the lap"},{"id":"D","text":"Tell the child that the procedure will not hurt at all"},{"id":"E","text":"Offer bubbles for the child to blow during the procedure"},{"id":"F","text":"Carry out the procedure in the bed of the child so the surroundings are familiar"}]}'::jsonb,
 '{"answers":["A","B","C","E"],"feedback":{"A":"Correct. Topical anaesthetic reduces the pain of the needle and is one of the few measures with strong evidence behind it.","B":"Correct. A short explanation close to the event matches the attention span of a preschooler and limits anticipatory fear.","C":"Correct. An upright comfort hold on the lap of a parent is less distressing and safer than lying the child flat and restraining them.","D":"Incorrect. A false promise destroys trust and makes every subsequent procedure harder.","E":"Correct. Blowing bubbles is an active distraction that also slows and deepens breathing.","F":"Incorrect. Painful procedures are done in a treatment room so the bed remains a safe space."}}'::jsonb,
 'Physiological Integrity', 'Basic Care and Comfort',
 'Pediatrics', 'Not applicable', 'Procedural comfort in children', 'Distraction and positioning',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_522045', 'SATA',
 'The nurse is passing a nasogastric tube in a 6-year-old for feeding. Which actions are correct? Select all that apply.',
 'The nose to ear to midway between xiphisternum and umbilicus measurement estimates the distance to the stomach more accurately in children than the older nose to ear to xiphisternum method. Placement is confirmed by testing aspirate with pH indicator paper, because the air insufflation test cannot distinguish stomach from lung and has caused deaths. Recording the external length lets any nurse detect later migration, and persistent coughing or a colour change means the tube may be in the airway and is withdrawn at once.',
 '{"options":[{"id":"A","text":"Measure from the tip of the nose to the earlobe, then to a point midway between the xiphisternum and the umbilicus"},{"id":"B","text":"Confirm placement by testing the aspirate with pH indicator paper, expecting a pH of 5.5 or below"},{"id":"C","text":"Confirm placement by injecting air and listening over the stomach"},{"id":"D","text":"Document the external length of the tube at the nostril"},{"id":"E","text":"Flush the tube with water before obtaining the first aspirate"},{"id":"F","text":"Withdraw the tube if the child coughs persistently or becomes cyanosed during insertion"}]}'::jsonb,
 '{"answers":["A","B","D","F"],"feedback":{"A":"Correct. This measurement is more accurate in children than the older method ending at the xiphisternum.","B":"Correct. An aspirate pH of 5.5 or below is the recommended first-line confirmation of gastric placement.","C":"Incorrect. The air insufflation test cannot distinguish stomach from lung and is no longer accepted.","D":"Correct. Recording the external length allows any nurse to detect later migration of the tube.","E":"Incorrect. Nothing is instilled until placement has been confirmed, since a misplaced tube may be in the lung.","F":"Correct. Persistent coughing or cyanosis suggests airway placement and the tube is withdrawn immediately."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Pediatrics', 'Gastrointestinal', 'Nasogastric tube in children', 'Measurement and placement checks',
 'Hard', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_522046', 'MCQ',
 'A urine specimen for culture is needed from a 10-month-old who is not toilet trained. Which method should the nurse use?',
 'A specimen for culture must not be contaminated by skin flora or nappy material, so the perineum is cleaned first and the urine is collected directly into a sterile container. A clean catch is preferred, and where that is impractical a sterile adhesive bag applied to cleaned skin, or catheterisation when a definitive result is needed, is used. Nappy, cotton wool and bath water samples all produce unusable culture results and lead to unnecessary antibiotics.',
 '{"options":[{"id":"A","text":"Squeeze urine from a wet nappy into a sterile container"},{"id":"B","text":"Clean the perineum, then obtain a clean-catch sample into a sterile pot, using a sterile adhesive collection bag or catheterisation if a clean catch is not possible"},{"id":"C","text":"Place cotton wool balls in the nappy and wring them out into the container"},{"id":"D","text":"Collect the specimen from the bath water after the routine bath"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. Nappy material contaminates the specimen and absorbs the components being tested.","B":"Correct. Cleaning the skin and collecting directly into a sterile container gives a culture result that can be acted on.","C":"Incorrect. Cotton wool introduces contaminants and cannot provide a specimen suitable for culture.","D":"Incorrect. Bath water is not sterile and the sample would be uninterpretable."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Pediatrics', 'Genitourinary', 'Urine specimen collection in children', 'Non-toilet-trained child',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_522047', 'SATA',
 'A 3-year-old keeps pulling at an intravenous cannula. Which actions should the nurse take before considering any form of restraint? Select all that apply.',
 'Restraint is a last resort and is never applied routinely or in advance. The least restrictive measures come first: checking whether the device is still needed, protecting and hiding the site, occupying the hands, and using the parent as the source of comfort and distraction. Where holding is unavoidable, a therapeutic hold with the parent, for the shortest possible time and with an explanation, is used rather than mechanical restraint, and it is documented.',
 '{"options":[{"id":"A","text":"Cover the cannula site with a light bandage or a purpose-made protective sleeve"},{"id":"B","text":"Involve the parent in holding, distracting and comforting the child"},{"id":"C","text":"Offer an activity that occupies the hands, such as a sticker book"},{"id":"D","text":"Apply wrist restraints at the start of every shift as a precaution"},{"id":"E","text":"Check whether the cannula is still required and can be removed"},{"id":"F","text":"Administer a sedative so the child sleeps through the infusion"}]}'::jsonb,
 '{"answers":["A","B","C","E"],"feedback":{"A":"Correct. Covering the site removes the visual cue and makes the cannula harder to grasp.","B":"Correct. A parent providing comfort and distraction is the most effective and least restrictive measure available.","C":"Correct. An activity that occupies the hands redirects the behaviour rather than suppressing it.","D":"Incorrect. Routine or precautionary restraint is never acceptable; restraint is a last resort, time limited and documented.","E":"Correct. If the cannula is no longer needed, removing it resolves the problem entirely.","F":"Incorrect. Sedation for the convenience of staff is a form of chemical restraint and is not appropriate here."}}'::jsonb,
 'Safe and Effective Care Environment', 'Safety and Infection Control',
 'Pediatrics', 'Not applicable', 'Restraint in children', 'Least restrictive alternatives',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MAT_522048', 'MATRIX',
 'For each client, select the pain assessment tool the nurse should use.',
 'A pain tool must match what the child is actually able to do. FLACC scores observed behaviour, so it is used for infants and for any child who cannot self-report, whatever the chronological age. The Wong-Baker faces scale needs only the ability to point at a picture and suits roughly three to seven years. A numeric scale requires the abstract idea that a number can stand for intensity, which is reliable from about eight years. Self-report is always preferred where the child can give it.',
 '{"rows":[{"id":"r1","text":"A 7-month-old infant on the first day after abdominal surgery"},{"id":"r2","text":"A 4-year-old after tonsillectomy who can point but cannot count reliably"},{"id":"r3","text":"A 14-year-old admitted with a sickle cell pain crisis"},{"id":"r4","text":"A 5-year-old with severe learning disability who has no verbal communication"},{"id":"r5","text":"A 10-year-old with a fractured femur who understands numbers well"}],"columns":[{"id":"c1","text":"FLACC scale"},{"id":"c2","text":"Wong-Baker FACES scale"},{"id":"c3","text":"0 to 10 numeric rating scale"}],"row_label":"Client"}'::jsonb,
 '{"cells":{"r1":"c1","r2":"c2","r3":"c3","r4":"c1","r5":"c3"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Basic Care and Comfort',
 'Pediatrics', 'Neurological', 'Paediatric pain assessment', 'Matching the tool to the child',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MMR_522049', 'MATRIX_MR',
 'For each task on the paediatric ward, select every person who may safely carry it out. Each task has at least one correct answer.',
 'Delegation turns on whether the task requires nursing judgement. Measuring, recording and comforting are routine, stable and predictable, so they may be delegated to assistive personnel and fall within the ordinary care a parent gives. Assessing a dose against a safe range is judgement and can never be delegated, and medication administration during a hospital admission remains with the registered nurse. A parent may safely give an established medicine at home once teaching has been given, return-demonstrated and documented, which is a different situation from delegating within the ward team.',
 '{"rows":[{"id":"r1","text":"Weighing a stable 4-year-old and recording the weight"},{"id":"r2","text":"Administering an oral antibiotic suspension during the hospital admission"},{"id":"r3","text":"Deciding whether a prescribed dose falls within the safe range"},{"id":"r4","text":"Giving the established subcutaneous insulin dose to the child at home"},{"id":"r5","text":"Holding the child in a comfort position during venepuncture"},{"id":"r6","text":"Emptying a urine collection bag and recording the volume"}],"columns":[{"id":"c1","text":"Registered nurse"},{"id":"c2","text":"Assistive personnel"},{"id":"c3","text":"Parent, after documented teaching"}],"row_label":"Task"}'::jsonb,
 '{"cells":{"r1":["c1","c2","c3"],"r2":["c1"],"r3":["c1"],"r4":["c1","c3"],"r5":["c1","c2","c3"],"r6":["c1","c2","c3"]},"feedback":{}}'::jsonb,
 'Safe and Effective Care Environment', 'Management of Care',
 'Pediatrics', 'Not applicable', 'Delegation in paediatric care', 'Registered nurse, assistive personnel and parent',
 'Very hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_522050', 'MCQ',
 'A 2-year-old was discharged home with a gastrostomy tube for overnight feeds. The parent was taught the procedure, demonstrated it correctly twice, and this was documented. The parent now telephones to say the feed will not run. Which response by the nurse is most appropriate?',
 'Once teaching has been given, return-demonstrated and documented, the parent is a competent carer for that specific task and is supported rather than replaced. The nurse works through the simple causes first, because kinking, the position of the child and flush technique account for most blockages. Forcing a feed can rupture the tube or displace it, and simply omitting a feed in a small child who depends on tube feeding risks dehydration and hypoglycaemia, so review is arranged if the problem persists.',
 '{"options":[{"id":"A","text":"Explain that only a nurse may troubleshoot the tube and arrange an emergency department attendance"},{"id":"B","text":"Talk the parent through checking for kinks and the position of the child, confirm the flush technique that was taught, and arrange review if the feed still will not run"},{"id":"C","text":"Advise the parent to push the feed through with a syringe using firm pressure"},{"id":"D","text":"Advise the parent to omit the feed and wait for the next community visit"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. The parent has documented competence in this task and should be supported to troubleshoot it, with review kept in reserve.","B":"Correct. The simple and common causes are checked first, with escalation if they do not resolve the problem.","C":"Incorrect. Firm pressure can rupture the tube or dislodge it from the stoma.","D":"Incorrect. A tube-dependent 2-year-old who misses a feed is at risk of dehydration and hypoglycaemia."}}'::jsonb,
 'Safe and Effective Care Environment', 'Management of Care',
 'Pediatrics', 'Gastrointestinal', 'Home care after discharge', 'Parent competence and support',
 'Very hard', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728');
