-- MyNclex gap-fill batch 10 — psychotropic medication (Pharmacology / Mental Health)
-- Batch: gapfill-20260728   Item block: 541001-541040 (40 items)
-- Focus: NMS vs EPS discrimination, antipsychotics (FGA / SGA / clozapine / depot),
--        lithium, MAOIs and tyramine, SSRIs and SNRIs, serotonin syndrome, TCAs,
--        benzodiazepines, valproate and carbamazepine, stimulants, dependence
--        pharmacotherapy, covert administration and refusal.

INSERT INTO nclex_bank_items (
  item_id, question_type, stem, rationale, content, correct,
  client_needs_category, client_needs_subcategory, nursing_subject, body_system,
  topic, subtopic, difficulty, difficulty_source, bloom_level, tags,
  instruction, marks, is_published, is_builder_visible, is_free_sample, cat_pool, batch_id
) VALUES
('NCLEX_MCQ_541001', 'MCQ',
 'A 24-year-old client on an acute mental health ward has received haloperidol for four days. The nurse finds the client with generalised muscle rigidity, a temperature of 39.4 °C, heavy diaphoresis, and a blood pressure that has swung between 92/50 and 164/96 mmHg over the past hour. Which action should the nurse take FIRST?',
 'Neuroleptic malignant syndrome is a rare but life-threatening reaction to dopamine-blocking medicines, marked by rigidity, hyperthermia, autonomic instability and altered consciousness. Every further dose drives the reaction onward, so the one action that changes the trajectory is stopping the causative medicine and summoning medical help. Cooling, intravenous fluids and agents such as dantrolene or bromocriptine follow, but they do not replace withdrawal of the drug.',
 '{"options":[{"id":"A","text":"Withhold the next dose of haloperidol and notify the prescriber immediately"},{"id":"B","text":"Administer the prescribed as-needed intramuscular benztropine"},{"id":"C","text":"Encourage oral fluids and position a cooling fan at the bedside"},{"id":"D","text":"Document the findings and reassess the client in one hour"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Stopping the dopamine blocker and escalating urgently is the first and most decisive step in suspected neuroleptic malignant syndrome.","B":"Incorrect. Anticholinergics relieve extrapyramidal spasm but do nothing for neuroleptic malignant syndrome, and giving one here delays definitive action.","C":"Incorrect. Cooling and fluids are supportive measures that belong after the causative medicine has been withheld and help summoned.","D":"Incorrect. Fever with rigidity and autonomic instability is an emergency; an hour of observation risks rhabdomyolysis, renal failure and death."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Neuroleptic malignant syndrome', 'First action', 'Hard', 'CURATOR_LABEL', 'Analyze', '{}',
 NULL, 1, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_MCQ_541002', 'MCQ',
 'Two clients on a rehabilitation unit are receiving antipsychotic medicines. Both report muscle stiffness and tremor, and both appear distressed and unable to settle. Which assessment BEST distinguishes neuroleptic malignant syndrome from extrapyramidal side effects?',
 'Rigidity, tremor and distress belong to both pictures, so they cannot separate them. Fever and autonomic instability are what make neuroleptic malignant syndrome an emergency rather than an unpleasant side effect, and temperature is the quickest and most reliable bedside discriminator. Any client on an antipsychotic who becomes rigid should have a temperature taken before the finding is dismissed as extrapyramidal.',
 '{"options":[{"id":"A","text":"Measuring the temperature"},{"id":"B","text":"Asking each client to rate the stiffness on a scale of 0 to 10"},{"id":"C","text":"Observing the hands for a tremor at rest"},{"id":"D","text":"Checking pupil size and reaction to light"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Hyperthermia, alongside autonomic instability, marks neuroleptic malignant syndrome; extrapyramidal side effects do not cause fever.","B":"Incorrect. Severity of stiffness is subjective and marked rigidity occurs in both conditions.","C":"Incorrect. Resting tremor occurs in pseudoparkinsonism and in neuroleptic malignant syndrome, so it does not separate them.","D":"Incorrect. Pupil findings are not part of the diagnostic picture for either condition."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Neuroleptic malignant syndrome', 'Discriminating assessment', 'Medium', 'CURATOR_LABEL', 'Analyze', '{}',
 NULL, 1, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_MAT_541003', 'MATRIX',
 'A nurse reviews findings in clients receiving antipsychotic medicines. Indicate whether each finding points to neuroleptic malignant syndrome or to an extrapyramidal side effect.',
 'The two groups share rigidity and abnormal movement, so the separators are systemic: fever, wide autonomic swings, altered consciousness and a markedly raised creatine kinase from muscle breakdown all belong to neuroleptic malignant syndrome. Movement disturbances that respond to an anticholinergic, or that appear as restlessness or involuntary oral movements without systemic upset, are extrapyramidal. Sorting findings this way is what allows the nurse to choose between giving a routine anticholinergic and calling an emergency.',
 '{"rows":[{"id":"r1","text":"Temperature 39.2 °C with profuse sweating"},{"id":"r2","text":"Neck spasm that eases within 20 minutes of intramuscular benztropine"},{"id":"r3","text":"Lead-pipe rigidity with fluctuating consciousness"},{"id":"r4","text":"Creatine kinase markedly raised with dark urine"},{"id":"r5","text":"Constant pacing and inability to remain seated"},{"id":"r6","text":"Rhythmic tongue and lip movements present for months"},{"id":"r7","text":"Blood pressure swinging widely with tachycardia"}],"columns":[{"id":"c1","text":"Neuroleptic malignant syndrome"},{"id":"c2","text":"Extrapyramidal side effect"}],"row_label":"Finding"}'::jsonb,
 '{"cells":{"r1":"c1","r2":"c2","r3":"c1","r4":"c1","r5":"c2","r6":"c2","r7":"c1"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Neuroleptic malignant syndrome', 'Distinguishing from extrapyramidal effects', 'Very hard', 'CURATOR_LABEL', 'Analyze', '{}',
 'Select one column for each row.', 7, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_MCQ_541004', 'MCQ',
 'Two hours after a first intramuscular dose of haloperidol in the emergency department, a 19-year-old client has a rigidly twisted neck and both eyes are rolled upward and fixed. The airway is patent and the temperature is 36.8 °C. Which action should the nurse take FIRST?',
 'This is acute dystonia: sustained, painful muscle spasm appearing within hours to days of the first doses, typically in the neck, jaw, tongue or eyes. It is frightening and can threaten the airway if the larynx is involved, but it reverses within minutes with an intramuscular anticholinergic such as benztropine, or with diphenhydramine. The normal temperature argues against neuroleptic malignant syndrome.',
 '{"options":[{"id":"A","text":"Administer the prescribed intramuscular benztropine"},{"id":"B","text":"Reassure the client that the movement will settle over the coming week"},{"id":"C","text":"Withhold every future antipsychotic dose permanently"},{"id":"D","text":"Request an urgent psychiatric review for catatonia"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. An intramuscular anticholinergic reverses acute dystonia quickly and relieves a distressing, potentially airway-threatening spasm.","B":"Incorrect. Acute dystonia is treatable now, and waiting leaves the client in pain and at risk if the spasm involves the larynx.","C":"Incorrect. Future therapy is a prescriber decision; dystonia is usually managed with an anticholinergic or a change of dose or agent.","D":"Incorrect. Catatonia does not present as an abrupt fixed upward gaze and torticollis two hours after a first antipsychotic dose."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Extrapyramidal side effects', 'Acute dystonia management', 'Medium', 'CURATOR_LABEL', 'Apply', '{}',
 NULL, 1, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_MCQ_541005', 'MCQ',
 'At a depot clinic review, a client who has taken an antipsychotic for six years shows repetitive lip smacking, tongue protrusion and chewing movements. The movements stop during sleep and the client is unaware of them. Which statement about this finding is correct?',
 'Tardive dyskinesia develops after months to years of dopamine blockade and produces involuntary orofacial, and sometimes limb or trunk, movements that disappear during sleep. It is the extrapyramidal effect that may persist even after the medicine is stopped, so early detection through regular screening, such as the Abnormal Involuntary Movement Scale, matters. Raising the dose can mask the movements briefly while worsening the underlying problem.',
 '{"options":[{"id":"A","text":"It is tardive dyskinesia and may be permanent even if the medicine is stopped"},{"id":"B","text":"It is acute dystonia and will resolve within minutes of an anticholinergic"},{"id":"C","text":"It is akathisia and will settle once the dose is increased"},{"id":"D","text":"It is a sign of relapse and the depot dose should be doubled"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Tardive dyskinesia appears late, is screened for with a tool such as the Abnormal Involuntary Movement Scale, and may be irreversible.","B":"Incorrect. Acute dystonia is a sudden sustained spasm in the first days of treatment, not painless movements after six years.","C":"Incorrect. Akathisia is a subjective inner restlessness with a need to move the whole body, and raising the dose worsens it.","D":"Incorrect. Involuntary oral movements are a medication effect, not psychotic relapse, and a dose increase would compound the harm."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Extrapyramidal side effects', 'Tardive dyskinesia', 'Easy', 'CURATOR_LABEL', 'Understand', '{}',
 NULL, 1, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_MAT_541006', 'MATRIX',
 'A nurse teaches student nurses about the movement effects of antipsychotic medicines. Match each description with the extrapyramidal effect it describes.',
 'The four extrapyramidal effects are separated by their timing and their character. Acute dystonia is a sustained spasm within hours to days; akathisia is subjective restlessness over days to weeks; pseudoparkinsonism brings rigidity, slowed movement and resting tremor after several weeks; tardive dyskinesia brings involuntary orofacial movements after months to years and may not reverse. Naming the effect correctly determines whether the nurse gives an anticholinergic, seeks a dose review, or arranges movement screening.',
 '{"rows":[{"id":"r1","text":"Sustained painful spasm of the neck or jaw within hours of the first dose"},{"id":"r2","text":"Inner restlessness with constant pacing, often mistaken for worsening anxiety"},{"id":"r3","text":"Shuffling gait, mask-like face and cogwheel rigidity after several weeks"},{"id":"r4","text":"Involuntary lip smacking and tongue rolling after years of therapy, possibly irreversible"},{"id":"r5","text":"Pill-rolling tremor of the hands at rest with slowed movement"},{"id":"r6","text":"The client says the legs simply will not keep still, and rocks while seated"}],"columns":[{"id":"c1","text":"Acute dystonia"},{"id":"c2","text":"Akathisia"},{"id":"c3","text":"Pseudoparkinsonism"},{"id":"c4","text":"Tardive dyskinesia"}],"row_label":"Description"}'::jsonb,
 '{"cells":{"r1":"c1","r2":"c2","r3":"c3","r4":"c4","r5":"c3","r6":"c2"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Extrapyramidal side effects', 'Recognition by type', 'Very hard', 'CURATOR_LABEL', 'Understand', '{}',
 'Select one column for each row.', 6, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_SATA_541007', 'SATA',
 'A community nurse is teaching a client who has just started chlorpromazine. Which instructions should the nurse include? Select all that apply.',
 'First-generation antipsychotics carry a predictable cluster of effects: anticholinergic dryness, sedation, orthostatic hypotension, photosensitivity and, rarely, agranulocytosis. Teaching aims to keep the client safe and comfortable enough to continue treatment, since most people stop medicines because of side effects rather than lack of benefit. The instruction to report a sore throat or fever is the one that can save a life.',
 '{"options":[{"id":"A","text":"Use sunscreen and wear protective clothing when outdoors"},{"id":"B","text":"Report a sore throat, fever or mouth ulcers straight away"},{"id":"C","text":"Rise slowly, sitting on the edge of the bed before standing"},{"id":"D","text":"Stop the medicine as soon as the voices settle"},{"id":"E","text":"Sip water or use sugar-free gum to relieve a dry mouth"},{"id":"F","text":"Take a double dose the next day if a dose is missed"}]}'::jsonb,
 '{"answers":["A","B","C","E"],"feedback":{"A":"Correct. Chlorpromazine causes marked photosensitivity, and severe sunburn can follow brief exposure.","B":"Correct. These are the warning signs of agranulocytosis and need a same-day full blood count.","C":"Correct. Orthostatic hypotension is common early in treatment and causes falls.","D":"Incorrect. Stopping once symptoms settle is the commonest route back to relapse and readmission.","E":"Correct. Dry mouth is an anticholinergic effect managed with simple comfort measures.","F":"Incorrect. Doubling a dose increases sedation and hypotension; the client should resume the usual schedule and seek advice."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pharmacology', 'Psychiatric/Mental Health',
 'First-generation antipsychotics', 'Client teaching', 'Very easy', 'CURATOR_LABEL', 'Apply', '{}',
 'Select all that apply.', 4, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_MCQ_541008', 'MCQ',
 'A client who has taken chlorpromazine for three weeks telephones the clinic reporting a sore throat, a temperature of 38.6 °C and mouth ulcers that began yesterday. Which action should the nurse take?',
 'Agranulocytosis is an uncommon but serious reaction to first-generation antipsychotics, and neither the client nor the nurse can tell by symptoms alone whether an infection is trivial or a sign that the neutrophils have collapsed. Only a full blood count answers that question, so any client on these medicines who reports fever, sore throat or ulceration is assessed the same day. Symptomatic treatment with review in a week risks overwhelming sepsis.',
 '{"options":[{"id":"A","text":"Advise the client to attend the same day for a full blood count"},{"id":"B","text":"Advise paracetamol and salt-water gargles, with review in one week"},{"id":"C","text":"Explain that a sore throat is an expected effect that settles with time"},{"id":"D","text":"Advise the client to take an extra dose to cover the period of illness"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Fever with sore throat on an antipsychotic is treated as possible agranulocytosis until the neutrophil count says otherwise.","B":"Incorrect. Symptomatic care without a blood count leaves a possible agranulocytosis undetected for a week.","C":"Incorrect. Sore throat is not an expected effect and is the classic presenting symptom of a collapsed neutrophil count.","D":"Incorrect. An extra dose adds risk and does nothing about a possible blood dyscrasia."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Pharmacology', 'Psychiatric/Mental Health',
 'First-generation antipsychotics', 'Agranulocytosis', 'Easy', 'CURATOR_LABEL', 'Apply', '{}',
 NULL, 1, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_MCQ_541009', 'MCQ',
 'A client stabilised on clozapine has a routine absolute neutrophil count of 1.2 x 10^9/L, down from 3.4 x 10^9/L the previous week. The client feels well and asks for the evening dose. Which action is the PRIORITY?',
 'Clozapine is the one antipsychotic dispensed against a mandatory white cell and absolute neutrophil count schedule, because it can cause severe neutropenia at any stage of treatment. A falling count in a client who feels well is exactly what the monitoring exists to catch, and the dose is held while the prescriber and the monitoring service decide. Feeling well is no reassurance, because infection only appears after the neutrophils have already gone.',
 '{"options":[{"id":"A","text":"Withhold the clozapine dose and notify the prescriber"},{"id":"B","text":"Give the dose and arrange a repeat count in one month"},{"id":"C","text":"Give the dose with food to reduce gastric upset"},{"id":"D","text":"Place the client in protective isolation before contacting anyone"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. A neutrophil count in this range means the dose is held and the prescriber and monitoring service informed before any further supply.","B":"Incorrect. Continuing the medicine and delaying the recheck by a month defeats the purpose of mandatory monitoring.","C":"Incorrect. Administration technique is irrelevant when the safety criterion for giving the medicine has not been met.","D":"Incorrect. Isolation may follow a medical decision, but it does not address the immediate need to stop the causative medicine and escalate."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Clozapine', 'Neutrophil monitoring', 'Hard', 'CURATOR_LABEL', 'Analyze', '{}',
 NULL, 1, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_SATA_541010', 'SATA',
 'A nurse is preparing a client for discharge on clozapine, started after two other antipsychotics failed. Which points should the nurse include in the teaching? Select all that apply.',
 'Clozapine is reserved for treatment-resistant illness and is tied to a registration and blood-monitoring system, so supply is released only when the white cell and absolute neutrophil counts are acceptable. Beyond the blood picture, the effects clients most need to recognise are infection, constipation that can progress to bowel obstruction, seizures at higher doses and heavy night-time salivation. Clozapine is also never simply restarted after a break, because the dose must be retitrated.',
 '{"options":[{"id":"A","text":"Blood tests follow a set schedule and the medicine is supplied only when the count is acceptable"},{"id":"B","text":"Report any fever, sore throat or flu-like illness immediately"},{"id":"C","text":"Report constipation, because untreated it can progress to bowel obstruction"},{"id":"D","text":"Night-time drooling is a recognised effect and should be reported if troublesome rather than managed by stopping the medicine"},{"id":"E","text":"Doses may be skipped for several days and then restarted at the same dose whenever convenient"},{"id":"F","text":"Blood tests are no longer needed once the medicine has been taken for six months"}]}'::jsonb,
 '{"answers":["A","B","C","D"],"feedback":{"A":"Correct. Dispensing is linked to the monitoring result, which is what makes the safety system work.","B":"Correct. These are the signs of agranulocytosis and need an urgent count.","C":"Correct. Clozapine slows the gut markedly, and severe constipation has caused fatal obstruction.","D":"Correct. Hypersalivation is common and manageable, and is not a reason for the client to stop abruptly.","E":"Incorrect. After a break of more than about two days the dose must be retitrated by the prescriber.","F":"Incorrect. Monitoring continues for the whole duration of treatment, although the interval lengthens."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Clozapine', 'Discharge teaching', 'Easy', 'CURATOR_LABEL', 'Apply', '{}',
 'Select all that apply.', 4, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728');

INSERT INTO nclex_bank_items (
  item_id, question_type, stem, rationale, content, correct,
  client_needs_category, client_needs_subcategory, nursing_subject, body_system,
  topic, subtopic, difficulty, difficulty_source, bloom_level, tags,
  instruction, marks, is_published, is_builder_visible, is_free_sample, cat_pool, batch_id
) VALUES
('NCLEX_MCQ_541011', 'MCQ',
 'A newly qualified nurse is transcribing a prescription that reads clozapine 0.5 mg at night for a client admitted with panic attacks and no psychotic illness. Which action should the nurse take?',
 'Clozapine and clonazepam are a classic look-alike, sound-alike pair, and the details here do not fit clozapine at all: it is not started at 0.5 mg, it is not used for panic attacks, and it requires registration with a monitoring service and a baseline neutrophil count. Clonazepam, a benzodiazepine, fits both the dose and the indication. When any element of a prescription contradicts what the nurse knows about the medicine, the safe action is to clarify with the prescriber before transcribing or giving it.',
 '{"options":[{"id":"A","text":"Contact the prescriber to clarify whether clonazepam was intended"},{"id":"B","text":"Transcribe and administer the dose as written, since the prescriber signed it"},{"id":"C","text":"Administer half the written dose and observe the response"},{"id":"D","text":"Omit the dose and document the omission without informing anyone"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Clarifying a look-alike, sound-alike medicine before it reaches the client is the action that prevents the error.","B":"Incorrect. A signature does not make a prescription safe, and the nurse who administers it shares responsibility for the error.","C":"Incorrect. Altering a dose independently is prescribing, and it does not resolve the underlying ambiguity.","D":"Incorrect. Silent omission leaves the wrong prescription in place for the next nurse and the client untreated."}}'::jsonb,
 'Safe and Effective Care Environment', 'Safety and Infection Control',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Clozapine', 'Look-alike sound-alike medicines', 'Medium', 'CURATOR_LABEL', 'Analyze', '{}',
 NULL, 1, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_SELN_541012', 'SELECT_N',
 'A client with schizophrenia is starting olanzapine. Which 3 parameters should the nurse plan to record at baseline and monitor at regular intervals?',
 'Second-generation antipsychotics rarely cause the movement problems of the older agents, but they carry a metabolic burden instead: weight gain, raised fasting glucose, insulin resistance and dyslipidaemia, which together make up the metabolic syndrome. Because these changes are silent until complications appear, they are tracked by measurement rather than by symptoms. Baseline values matter, since only a comparison shows whether the medicine or the illness is responsible.',
 '{"options":[{"id":"A","text":"Body weight and waist circumference"},{"id":"B","text":"Fasting blood glucose"},{"id":"C","text":"Fasting lipid profile"},{"id":"D","text":"Serum amylase"},{"id":"E","text":"Visual acuity"},{"id":"F","text":"Serum calcium"}],"select_count":3}'::jsonb,
 '{"answers":["A","B","C"],"feedback":{"A":"Correct. Weight gain is the earliest and most visible marker of the metabolic effect.","B":"Correct. Second-generation antipsychotics raise fasting glucose and can precipitate type 2 diabetes.","C":"Correct. Triglycerides and cholesterol rise with these medicines and are monitored routinely.","D":"Incorrect. Amylase relates to pancreatic inflammation and is not part of routine antipsychotic monitoring.","E":"Incorrect. Visual acuity is not affected in a way that warrants scheduled monitoring with olanzapine.","F":"Incorrect. Calcium is unrelated to the metabolic effects of antipsychotics."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Second-generation antipsychotics', 'Metabolic monitoring', 'Very easy', 'CURATOR_LABEL', 'Understand', '{}',
 'Select 3.', 3, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_MCQ_541013', 'MCQ',
 'A client is to receive a first dose of ziprasidone. Which finding should the nurse report to the prescriber before the medicine is given?',
 'Ziprasidone prolongs the QT interval more than most antipsychotics, and a prolonged QT can degenerate into torsades de pointes. The risk is amplified by low potassium and low magnesium, by other QT-prolonging medicines and by pre-existing cardiac disease, so electrolytes are corrected and a baseline electrocardiogram considered before treatment starts. Recognising the interaction between an electrolyte result and a cardiac drug effect is the point of this decision.',
 '{"options":[{"id":"A","text":"Serum potassium 2.9 mEq/L"},{"id":"B","text":"Weight gain of 1 kg over three months"},{"id":"C","text":"A report of dry mouth in the mornings"},{"id":"D","text":"Blood pressure 128/76 mmHg"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Hypokalaemia compounds QT prolongation and must be corrected before a QT-prolonging antipsychotic is started.","B":"Incorrect. One kilogram over three months is modest and does not delay the first dose.","C":"Incorrect. Dry mouth is uncomfortable but carries no cardiac risk.","D":"Incorrect. This blood pressure is within normal limits."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Second-generation antipsychotics', 'QT prolongation', 'Hard', 'CURATOR_LABEL', 'Analyze', '{}',
 NULL, 1, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_MCQ_541014', 'MCQ',
 'A client who has been admitted three times in two years after stopping oral antipsychotics asks the nurse why the team is now suggesting a monthly injection. Which response by the nurse is BEST?',
 'Long-acting depot injections deliver medicine slowly from a muscle store over weeks, so a single forgotten day cannot empty the system as a missed tablet can. Their main role is in relapse driven by inconsistent adherence, and they also make lapses visible, because a missed appointment is noticed by the team. They are not more effective molecule for molecule, and they carry the same side effects as the oral form.',
 '{"options":[{"id":"A","text":"The injection releases the medicine slowly across the month, so a single missed day cannot trigger a sudden relapse"},{"id":"B","text":"The injection works better than any tablet for every client"},{"id":"C","text":"The injection has no side effects, unlike tablets"},{"id":"D","text":"Once the injection is started, clinic attendance is no longer necessary"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Steady release is exactly why depot injections suit clients whose relapses follow missed oral doses.","B":"Incorrect. The active medicine is the same; the advantage is in delivery, not superior potency.","C":"Incorrect. Depot preparations carry the same side effects, plus injection-site reactions.","D":"Incorrect. Depot therapy increases contact with the service, because each dose is given at a review."}}'::jsonb,
 'Psychosocial Integrity', 'Psychosocial Integrity',
 'Mental Health', 'Psychiatric/Mental Health',
 'Long-acting depot antipsychotics', 'Adherence', 'Medium', 'CURATOR_LABEL', 'Understand', '{}',
 NULL, 1, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_MCQ_541015', 'MCQ',
 'A client on lithium for bipolar disorder attends the outpatient clinic after two days of vomiting. The client has a coarse hand tremor and an unsteady, wide-based walk. The lithium level drawn this morning is 1.8 mEq/L. Which action should the nurse take FIRST?',
 'Lithium has a narrow therapeutic index, with a usual maintenance range of about 0.6 to 1.2 mEq/L. Coarse tremor, ataxia, vomiting and confusion above that range signal toxicity, which worsens with every further dose because the kidney is already struggling to clear the drug. Withholding the medicine and contacting the prescriber comes before rehydration decisions, repeat levels or dietary advice.',
 '{"options":[{"id":"A","text":"Withhold the next lithium dose and contact the prescriber"},{"id":"B","text":"Advise a low-salt diet until the level falls"},{"id":"C","text":"Give the next dose with a large glass of water"},{"id":"D","text":"Arrange a repeat level in one week"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. With a level of 1.8 mEq/L and clear toxic signs, the dose is held and the prescriber informed immediately.","B":"Incorrect. Restricting salt makes the kidney retain lithium, driving the level higher.","C":"Incorrect. Water with the dose does not offset toxicity, and giving lithium at this level is unsafe.","D":"Incorrect. A week of continued dosing at a toxic level risks seizures, renal injury and death."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Lithium', 'Toxicity recognition', 'Hard', 'CURATOR_LABEL', 'Analyze', '{}',
 NULL, 1, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_SATA_541016', 'SATA',
 'A nurse is teaching a client who has just been started on lithium. Which instructions should the nurse include? Select all that apply.',
 'Lithium is handled by the kidney in the same way as sodium, so anything that lowers body sodium or fluid volume makes the kidney reabsorb more lithium and pushes the level up. Steady fluid intake, steady salt intake and prompt reporting of vomiting, diarrhoea or heavy sweating are therefore the core of safe self-management, alongside scheduled blood levels. Nonsteroidal anti-inflammatory medicines also raise the level and should not be bought over the counter without advice.',
 '{"options":[{"id":"A","text":"Drink about 2 to 3 litres of fluid a day unless told otherwise"},{"id":"B","text":"Keep salt intake steady rather than starting a low-salt or high-salt diet"},{"id":"C","text":"Report vomiting, diarrhoea or heavy sweating, because these raise the lithium level"},{"id":"D","text":"Use ibuprofen freely for headaches and muscle pain"},{"id":"E","text":"Attend for blood levels on the dates given, even when feeling well"},{"id":"F","text":"Stop the medicine once the mood has been stable for a month"}]}'::jsonb,
 '{"answers":["A","B","C","E"],"feedback":{"A":"Correct. Steady hydration keeps the lithium level stable and protects the kidney.","B":"Correct. A sudden drop in dietary sodium raises the lithium level; a sudden rise lowers it.","C":"Correct. Fluid and sodium losses concentrate lithium and are the commonest trigger for toxicity.","D":"Incorrect. Nonsteroidal anti-inflammatory medicines reduce lithium excretion and can precipitate toxicity.","E":"Correct. Levels are monitored because toxicity can develop before the client feels unwell.","F":"Incorrect. Lithium is a maintenance treatment, and stopping it abruptly carries a high risk of relapse."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Lithium', 'Initiation teaching', 'Easy', 'CURATOR_LABEL', 'Apply', '{}',
 'Select all that apply.', 4, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_MCQ_541017', 'MCQ',
 'A client whose bipolar disorder has been stable on lithium for four years is seen in the general practice clinic with newly diagnosed hypertension. Which new prescription should the nurse question with the prescriber?',
 'Thiazide diuretics increase sodium loss at the kidney, and the tubule responds by reabsorbing more lithium alongside sodium, so lithium levels can climb into the toxic range within days. Angiotensin converting enzyme inhibitors and nonsteroidal anti-inflammatory medicines act in a similar direction. Calcium channel blockers and simple analgesia such as paracetamol are far less likely to disturb the level, which is why the thiazide is the prescription to challenge.',
 '{"options":[{"id":"A","text":"Hydrochlorothiazide"},{"id":"B","text":"Amlodipine"},{"id":"C","text":"Paracetamol"},{"id":"D","text":"Ferrous sulfate"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. A thiazide diuretic increases lithium reabsorption and is a well-recognised cause of lithium toxicity.","B":"Incorrect. Amlodipine does not meaningfully alter renal lithium handling.","C":"Incorrect. Paracetamol is the safer analgesic choice for a client on lithium.","D":"Incorrect. Iron supplementation has no clinically important effect on lithium levels."}}'::jsonb,
 'Safe and Effective Care Environment', 'Management of Care',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Lithium', 'Interacting prescriptions', 'Hard', 'CURATOR_LABEL', 'Analyze', '{}',
 NULL, 1, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_CLZ_541018', 'CLOZE',
 'A client who takes lithium spends the day loading goods outdoors in hot weather, sweats heavily and drinks very little. The nurse understands that this loss of sodium and fluid will cause the lithium level to {1}, so the nurse should {2}.',
 'Sweat carries away both water and sodium. The kidney responds to a fall in sodium and volume by reabsorbing more sodium in the proximal tubule, and lithium is reabsorbed along the same pathway, so the serum lithium level rises. Heat, hard physical work, fever, vomiting and diarrhoea therefore all belong in the same teaching point, and the response is to replace fluid and salt and check the level rather than to restrict either.',
 '{"blanks":[{"id":"b1","choices":[{"id":"c1","text":"rise"},{"id":"c2","text":"fall"},{"id":"c3","text":"stay unchanged"}]},{"id":"b2","choices":[{"id":"c1","text":"encourage fluid and normal salt intake and arrange an urgent lithium level"},{"id":"c2","text":"restrict fluids and continue the usual dose"},{"id":"c3","text":"advise a low-salt diet for the rest of the week"}]}]}'::jsonb,
 '{"answers":{"b1":"c1","b2":"c1"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Lithium', 'Sodium and fluid balance', 'Very hard', 'CURATOR_LABEL', 'Analyze', '{}',
 'Complete the sentence by choosing from each drop-down.', 2, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_TF_541019', 'TF',
 'A serum lithium level for routine monitoring should be drawn approximately 12 hours after the last dose.',
 'Lithium levels are interpreted against a 12-hour post-dose trough, which is why the sample is usually taken in the morning before the next dose in a client on a twice-daily regimen. A sample taken too soon after a dose reflects the absorption peak and reads falsely high, which can lead to an unnecessary dose reduction. Documenting the time of the last dose alongside the sample is part of the nursing responsibility.',
 '{"options":[{"id":"A","text":"True"},{"id":"B","text":"False"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. The therapeutic range is defined against a sample drawn about 12 hours after the previous dose.","B":"Incorrect. Timing is not arbitrary; a level drawn near the absorption peak overstates the true steady-state concentration."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Lithium', 'Timing of serum levels', 'Very easy', 'CURATOR_LABEL', 'Remember', '{}',
 NULL, 1, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_SATA_541020', 'SATA',
 'A client is starting phenelzine. Which foods and drinks should the nurse teach the client to avoid? Select all that apply.',
 'Monoamine oxidase normally breaks down tyramine in the gut wall and liver. When the enzyme is inhibited, tyramine from food is absorbed intact and displaces stored noradrenaline, producing a surge in blood pressure that can cause a hypertensive crisis. Tyramine accumulates whenever protein is aged, fermented, cured, smoked or over-ripe, so the rule the client can carry is simple: fresh is safe, aged and fermented are not.',
 '{"options":[{"id":"A","text":"Aged cheddar and blue cheese"},{"id":"B","text":"Cured and smoked meats such as salami"},{"id":"C","text":"Draught beer"},{"id":"D","text":"Soy sauce and fermented soya bean products"},{"id":"E","text":"Freshly cooked chicken"},{"id":"F","text":"Broad beans"},{"id":"G","text":"Pasteurised milk"}]}'::jsonb,
 '{"answers":["A","B","C","D","F"],"feedback":{"A":"Correct. Ageing raises the tyramine content of cheese sharply.","B":"Correct. Curing and smoking allow tyramine to accumulate in meat.","C":"Correct. Draught and unpasteurised beers continue to ferment and are high in tyramine.","D":"Correct. Fermented soya products are a major tyramine source.","E":"Incorrect. Freshly cooked meat is safe; it is ageing and curing that create the problem.","F":"Correct. Broad beans contain dopa compounds that add to the pressor effect.","G":"Incorrect. Pasteurised milk and fresh dairy contain little tyramine and are permitted."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Monoamine oxidase inhibitors', 'Tyramine-containing foods', 'Medium', 'CURATOR_LABEL', 'Apply', '{}',
 'Select all that apply.', 5, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728');

INSERT INTO nclex_bank_items (
  item_id, question_type, stem, rationale, content, correct,
  client_needs_category, client_needs_subcategory, nursing_subject, body_system,
  topic, subtopic, difficulty, difficulty_source, bloom_level, tags,
  instruction, marks, is_published, is_builder_visible, is_free_sample, cat_pool, batch_id
) VALUES
('NCLEX_MCQ_541021', 'MCQ',
 'Two hours after eating at a restaurant, a client who takes phenelzine develops a severe pounding headache at the back of the head, neck stiffness, palpitations and a blood pressure of 210/118 mmHg. Which action should the nurse take FIRST?',
 'This is a hypertensive crisis caused by tyramine reaching the circulation while monoamine oxidase is inhibited. It carries a real risk of intracranial haemorrhage, so the medicine is withheld and urgent medical help summoned for blood pressure lowering with a rapid-acting agent. Supportive measures such as sitting the client upright with the head elevated help, but lying flat with the legs raised would increase cerebral pressure and is the opposite of what is needed.',
 '{"options":[{"id":"A","text":"Withhold the next dose of phenelzine and summon urgent medical help"},{"id":"B","text":"Give the client a warm drink and recheck the blood pressure in 30 minutes"},{"id":"C","text":"Lay the client flat and elevate the legs"},{"id":"D","text":"Administer the prescribed as-needed lorazepam and reassess"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. A hypertensive crisis on a monoamine oxidase inhibitor is an emergency needing the medicine stopped and rapid medical treatment.","B":"Incorrect. Waiting 30 minutes at this pressure risks stroke and cardiac complications.","C":"Incorrect. Lying flat with the legs raised increases venous return and cerebral pressure, worsening the crisis.","D":"Incorrect. Sedation does not lower a tyramine-driven pressor surge and delays definitive treatment."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Monoamine oxidase inhibitors', 'Hypertensive crisis', 'Very hard', 'CURATOR_LABEL', 'Analyze', '{}',
 NULL, 1, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_MCQ_541022', 'MCQ',
 'A client has been taking fluoxetine for depression, and the prescriber now plans to switch treatment to phenelzine. The client asks the nurse when the new medicine will start. Which response by the nurse is correct?',
 'Combining a serotonin reuptake inhibitor with a monoamine oxidase inhibitor can produce fatal serotonin syndrome, so a washout is required between them. Fluoxetine is the exception among the group because its active metabolite has a very long half-life, and about five weeks must pass after the last dose before a monoamine oxidase inhibitor is started. Switching in the other direction, from a monoamine oxidase inhibitor to another antidepressant, needs about 14 days to allow new enzyme to be produced.',
 '{"options":[{"id":"A","text":"About five weeks must pass after the last fluoxetine dose before phenelzine is started"},{"id":"B","text":"The two can overlap for a few days if the doses are low"},{"id":"C","text":"Fluoxetine can be stopped tonight and phenelzine started tomorrow morning"},{"id":"D","text":"A washout of 24 hours is sufficient"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. The long half-life of fluoxetine and its active metabolite requires a washout of about five weeks.","B":"Incorrect. Deliberate overlap of these two classes is the classic recipe for serotonin syndrome.","C":"Incorrect. Overnight clearance is impossible; active drug persists for weeks.","D":"Incorrect. Twenty-four hours would leave substantial serotonergic activity when the monoamine oxidase inhibitor begins."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Monoamine oxidase inhibitors', 'Washout when switching antidepressants', 'Hard', 'CURATOR_LABEL', 'Understand', '{}',
 NULL, 1, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_SELN_541023', 'SELECT_N',
 'A client taking tranylcypromine asks the nurse about remedies that can be bought without a prescription. Which 3 should the nurse tell the client to avoid?',
 'Monoamine oxidase inhibitors interact with two groups of medicines: sympathomimetics such as decongestants, which drive the same pressor surge as tyramine, and serotonergic agents such as dextromethorphan and St John''s wort, which can precipitate serotonin syndrome. Many of these sit on open shelves in pharmacies and markets, so the teaching has to name them specifically. Simple analgesics, antacids and lubricating eye drops are not affected.',
 '{"options":[{"id":"A","text":"Pseudoephedrine nasal decongestant"},{"id":"B","text":"Dextromethorphan cough syrup"},{"id":"C","text":"St John''s wort herbal capsules"},{"id":"D","text":"Plain paracetamol tablets"},{"id":"E","text":"Calcium carbonate antacid"},{"id":"F","text":"Lubricating eye drops"}],"select_count":3}'::jsonb,
 '{"answers":["A","B","C"],"feedback":{"A":"Correct. Sympathomimetic decongestants can trigger a hypertensive crisis in a client on a monoamine oxidase inhibitor.","B":"Correct. Dextromethorphan is serotonergic and has caused serotonin syndrome with these medicines.","C":"Correct. St John''s wort is a serotonergic herbal preparation and is contraindicated.","D":"Incorrect. Paracetamol is the recommended simple analgesic for these clients.","E":"Incorrect. Antacids do not interact with monoamine oxidase inhibitors.","F":"Incorrect. Lubricating drops act locally and are safe."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Monoamine oxidase inhibitors', 'Interacting medicines', 'Medium', 'CURATOR_LABEL', 'Apply', '{}',
 'Select 3.', 3, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_MCQ_541024', 'MCQ',
 'Five days after starting sertraline, a client tells the community nurse, "This tablet is useless. I feel no different at all, so I may as well stop." Which response by the nurse is BEST?',
 'Antidepressants change receptor sensitivity over time, so mood usually lifts only after two to four weeks, and up to six to eight weeks for the full effect. Sleep, appetite and energy often improve before mood does, which gives the nurse something concrete to point to. Naming the timeline and reviewing early gains keeps the client engaged through the period when discontinuation is most likely.',
 '{"options":[{"id":"A","text":"Antidepressants usually take two to four weeks to lift mood; let us look at what has changed in sleep and appetite so far"},{"id":"B","text":"It sounds as though this medicine is wrong for you; I will ask for a different one"},{"id":"C","text":"You must take it for six months before you can judge whether it works"},{"id":"D","text":"Most people feel better within 48 hours, so the dose is probably too low"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. It gives the accurate timeline and looks for the early, concrete changes that usually precede a lift in mood.","B":"Incorrect. Abandoning an adequate trial after five days denies the client a treatment that has not yet had time to work.","C":"Incorrect. Six months is the length of continuation therapy, not the time before any benefit appears.","D":"Incorrect. A 48-hour expectation is inaccurate and sets the client up for disappointment."}}'::jsonb,
 'Psychosocial Integrity', 'Psychosocial Integrity',
 'Mental Health', 'Psychiatric/Mental Health',
 'Selective serotonin reuptake inhibitors', 'Delayed therapeutic effect', 'Very easy', 'CURATOR_LABEL', 'Apply', '{}',
 NULL, 1, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_MCQ_541025', 'MCQ',
 'A 16-year-old client with moderate depression is started on fluoxetine and is reviewed weekly in the adolescent clinic. Which nursing action is the PRIORITY during the first weeks of treatment?',
 'Suicide risk rises for adolescents and young adults in the weeks after an antidepressant is started or the dose is changed, partly because energy and initiative return before hopelessness lifts. Structured, direct questioning about suicidal thoughts and plans at every contact is what turns that known risk into a manageable one, and the family is asked to report any new agitation or talk of self-harm. Physical monitoring matters but does not carry the same immediate consequence.',
 '{"options":[{"id":"A","text":"Assess directly for new or worsening suicidal thoughts at every contact"},{"id":"B","text":"Weigh the client each week"},{"id":"C","text":"Check liver function tests weekly"},{"id":"D","text":"Advise the client to avoid caffeinated drinks"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. The initiation and dose-change window carries a recognised increase in suicidal thinking in this age group, so it is assessed at every contact.","B":"Incorrect. Weight change is worth tracking but is not the priority safety issue in the first weeks.","C":"Incorrect. Weekly liver testing is not routine with fluoxetine.","D":"Incorrect. Limiting caffeine may help sleep but has no bearing on the main risk."}}'::jsonb,
 'Psychosocial Integrity', 'Psychosocial Integrity',
 'Mental Health', 'Psychiatric/Mental Health',
 'Selective serotonin reuptake inhibitors', 'Suicide risk on initiation', 'Medium', 'CURATOR_LABEL', 'Analyze', '{}',
 NULL, 1, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_MCQ_541026', 'MCQ',
 'During a review appointment a client taking paroxetine says quietly that the medicine has taken away all sexual interest, and that he has therefore not taken it for the past week and has told no one. Which response by the nurse is BEST?',
 'Sexual side effects are among the commonest reasons clients stop antidepressants, and they are frequently unreported because they are embarrassing to raise. The nurse who receives the disclosure without judgement, explains that abrupt cessation can cause discontinuation symptoms, and arranges a prompt prescriber review keeps both the relationship and the treatment intact. Options exist, including dose adjustment, timing changes or switching agent, but they require the conversation to happen first.',
 '{"options":[{"id":"A","text":"Acknowledge the concern, explain that stopping suddenly can cause withdrawal symptoms, and arrange a prompt review to discuss the options"},{"id":"B","text":"Explain that this effect is minor compared with depression and that the tablets must be continued"},{"id":"C","text":"Advise the client to halve the dose until the next appointment"},{"id":"D","text":"Reassure the client that antidepressants do not cause sexual difficulties"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. It validates the concern, warns about abrupt cessation, and moves the problem to someone who can change the prescription.","B":"Incorrect. Dismissing the effect is the response most likely to end the therapeutic relationship and the treatment.","C":"Incorrect. Adjusting a dose is outside the nursing remit and does not address the disclosure.","D":"Incorrect. This is factually wrong; sexual side effects are common with this class."}}'::jsonb,
 'Psychosocial Integrity', 'Psychosocial Integrity',
 'Mental Health', 'Psychiatric/Mental Health',
 'Selective serotonin reuptake inhibitors', 'Side effects and adherence', 'Medium', 'CURATOR_LABEL', 'Evaluate', '{}',
 NULL, 1, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_CLZ_541027', 'CLOZE',
 'A nurse teaches a client starting an SSRI that the full antidepressant effect usually appears after {1} of regular dosing, and that stopping the medicine abruptly can cause {2}.',
 'The delay before benefit and the risk on sudden withdrawal are the two facts clients most need before the first tablet, because both are common reasons for treatment failure. Receptor adaptation takes weeks, so the client who expects an overnight change stops too early. At the other end, an abrupt stop after regular use produces a discontinuation syndrome of dizziness, flu-like aching, irritability and electric-shock sensations, which is avoided by tapering under supervision.',
 '{"blanks":[{"id":"b1","choices":[{"id":"c1","text":"two to four weeks"},{"id":"c2","text":"two to three days"},{"id":"c3","text":"six months"}]},{"id":"b2","choices":[{"id":"c1","text":"discontinuation symptoms such as dizziness, flu-like aching and electric-shock sensations"},{"id":"c2","text":"an immediate hypertensive crisis"},{"id":"c3","text":"permanent liver damage"}]}]}'::jsonb,
 '{"answers":{"b1":"c1","b2":"c1"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Selective serotonin reuptake inhibitors', 'Onset and discontinuation syndrome', 'Very easy', 'CURATOR_LABEL', 'Remember', '{}',
 'Complete the sentence by choosing from each drop-down.', 2, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_SATA_541028', 'SATA',
 'A client has taken sertraline daily for a year. Which additions to the regimen would increase the risk of serotonin syndrome? Select all that apply.',
 'Serotonin syndrome arises from too much serotonergic activity, so the risk comes from stacking agents that raise serotonin by different routes. Herbal preparations, migraine triptans, some analgesics and even an antibiotic with monoamine oxidase inhibiting activity all belong on the list, and clients rarely think of them as psychiatric medicines. Asking specifically about herbal and over-the-counter products at every medicines review is therefore part of safe practice.',
 '{"options":[{"id":"A","text":"St John''s wort bought at a market stall"},{"id":"B","text":"Sumatriptan for migraine"},{"id":"C","text":"Tramadol for back pain"},{"id":"D","text":"Linezolid for a resistant infection"},{"id":"E","text":"Calcium carbonate for indigestion"},{"id":"F","text":"Topical hydrocortisone cream for eczema"}]}'::jsonb,
 '{"answers":["A","B","C","D"],"feedback":{"A":"Correct. St John''s wort has serotonergic activity and is a documented precipitant.","B":"Correct. Triptans act on serotonin receptors and add to the serotonergic load.","C":"Correct. Tramadol inhibits serotonin reuptake in addition to its opioid action.","D":"Correct. Linezolid is a weak monoamine oxidase inhibitor and has caused serotonin syndrome with SSRIs.","E":"Incorrect. Antacids have no serotonergic activity.","F":"Incorrect. A topical corticosteroid does not affect serotonin transmission."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Serotonin syndrome', 'Precipitating agents', 'Medium', 'CURATOR_LABEL', 'Understand', '{}',
 'Select all that apply.', 4, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_MCQ_541029', 'MCQ',
 'Six hours after a first dose of tramadol prescribed for back pain, a client who takes venlafaxine becomes agitated and drenched in sweat, with brisk reflexes, sustained ankle clonus, tremor and a temperature of 38.5 °C. Which action should the nurse take FIRST?',
 'The combination of a serotonin and noradrenaline reuptake inhibitor with tramadol is a well-recognised trigger for serotonin syndrome, which develops within hours rather than days and is characterised by neuromuscular excitability: hyperreflexia, clonus, tremor and agitation. Removing every serotonergic agent is the first step, alongside urgent medical review for supportive care, cooling and possibly cyproheptadine. Giving the next scheduled dose would deepen a reaction that can progress to seizures and rhabdomyolysis.',
 '{"options":[{"id":"A","text":"Withhold both serotonergic medicines and escalate urgently to the medical team"},{"id":"B","text":"Give the next venlafaxine dose on time to keep the blood level steady"},{"id":"C","text":"Administer the prescribed as-needed benztropine"},{"id":"D","text":"Offer oral fluids and reassess the client in two hours"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Stopping every serotonergic agent and getting urgent medical help is the first step in serotonin syndrome.","B":"Incorrect. Continuing the serotonergic medicine drives the reaction further.","C":"Incorrect. Benztropine treats extrapyramidal spasm and has no role in serotonin syndrome.","D":"Incorrect. Fever with clonus and agitation is a medical emergency, not something to observe for two hours."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Serotonin syndrome', 'Recognition and first action', 'Hard', 'CURATOR_LABEL', 'Analyze', '{}',
 NULL, 1, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_MMR_541030', 'MATRIX_MR',
 'A nurse compares serotonin syndrome with neuroleptic malignant syndrome for a teaching session. Indicate which condition each feature belongs to. Some features apply to both.',
 'Both syndromes produce hyperthermia and autonomic instability and both are managed first by removing the causative medicine, which is why they are so easily confused. The separators are the timing and the neuromuscular picture: serotonin syndrome comes on within hours of a serotonergic agent and produces hyperreflexia, clonus and agitation, whereas neuroleptic malignant syndrome builds over one to three days after a dopamine blocker and produces lead-pipe rigidity with bradykinesia. Clonus versus rigidity is the most useful bedside distinction.',
 '{"rows":[{"id":"r1","text":"Onset within hours of adding a serotonergic medicine"},{"id":"r2","text":"Onset over one to three days after starting or increasing a dopamine blocker"},{"id":"r3","text":"Lead-pipe rigidity with slowed movement"},{"id":"r4","text":"Hyperreflexia with sustained ankle clonus"},{"id":"r5","text":"Hyperthermia with autonomic instability"},{"id":"r6","text":"First management step is withdrawal of the causative medicine"}],"columns":[{"id":"c1","text":"Serotonin syndrome"},{"id":"c2","text":"Neuroleptic malignant syndrome"}],"row_label":"Feature"}'::jsonb,
 '{"cells":{"r1":["c1"],"r2":["c2"],"r3":["c2"],"r4":["c1"],"r5":["c1","c2"],"r6":["c1","c2"]},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Serotonin syndrome', 'Comparison with neuroleptic malignant syndrome', 'Very hard', 'CURATOR_LABEL', 'Analyze', '{}',
 'Select all that apply for each row.', 8, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728');

INSERT INTO nclex_bank_items (
  item_id, question_type, stem, rationale, content, correct,
  client_needs_category, client_needs_subcategory, nursing_subject, body_system,
  topic, subtopic, difficulty, difficulty_source, bloom_level, tags,
  instruction, marks, is_published, is_builder_visible, is_free_sample, cat_pool, batch_id
) VALUES
('NCLEX_MCQ_541031', 'MCQ',
 'A community nurse visits a client who lives alone, has depression with active thoughts of suicide, and has just been prescribed amitriptyline. A three-month supply has been dispensed. Which action is the PRIORITY?',
 'Tricyclic antidepressants are cardiotoxic in overdose, producing a widened QRS complex, arrhythmias, seizures and coma, and the gap between a therapeutic dose and a lethal one is small. For a client with active suicidal thoughts, a bulk supply at home is a stored means of death, so limiting the quantity dispensed is a recognised safety intervention. Restricting access to means is discussed openly with the client and prescriber rather than arranged behind the back of the client.',
 '{"options":[{"id":"A","text":"Discuss the overdose risk with the prescriber and arrange for only small quantities to be dispensed at a time"},{"id":"B","text":"Teach the client to take the dose in the morning to reduce daytime drowsiness"},{"id":"C","text":"Advise the client to avoid grapefruit juice while taking the medicine"},{"id":"D","text":"Ask a neighbour to keep the tablets and hand them out daily"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. A tricyclic is lethal in relatively small overdose, so limiting the quantity held at home directly reduces the risk.","B":"Incorrect. Tricyclics are usually taken at night for sedation, and timing does not address the lethal risk.","C":"Incorrect. This is not a clinically important interaction for amitriptyline and is not the priority here.","D":"Incorrect. Handing medicines and confidential information to a neighbour is neither lawful nor a substitute for a proper supply arrangement."}}'::jsonb,
 'Safe and Effective Care Environment', 'Safety and Infection Control',
 'Mental Health', 'Psychiatric/Mental Health',
 'Tricyclic antidepressants', 'Overdose risk and means restriction', 'Hard', 'CURATOR_LABEL', 'Analyze', '{}',
 NULL, 1, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_SATA_541032', 'SATA',
 'A 70-year-old client is starting amitriptyline for neuropathic pain and low mood. Which measures should the nurse include in the plan of care? Select all that apply.',
 'The anticholinergic burden of a tricyclic falls hardest on older adults: dry mouth, blurred vision, constipation, urinary retention, confusion and orthostatic hypotension all become more likely. Most of these are managed with simple comfort and safety measures that let the client tolerate an effective dose. Blurred vision and sedation also make driving unsafe in the first days, and a man with prostatic enlargement needs specific questioning about passing urine.',
 '{"options":[{"id":"A","text":"Offer sugar-free sweets and frequent mouth care for dry mouth"},{"id":"B","text":"Increase dietary fibre and fluids to prevent constipation"},{"id":"C","text":"Teach the client to change position slowly to reduce dizziness"},{"id":"D","text":"Ask each day about difficulty starting or passing urine"},{"id":"E","text":"Treat blurred vision as a sign that the dose is too low"},{"id":"F","text":"Encourage the client to drive as usual during the first week"}]}'::jsonb,
 '{"answers":["A","B","C","D"],"feedback":{"A":"Correct. Dry mouth is the most common anticholinergic complaint and responds to simple mouth care.","B":"Correct. Constipation is predictable and is prevented more easily than treated.","C":"Correct. Orthostatic hypotension is a major fall risk in an older adult.","D":"Correct. Urinary retention is a recognised anticholinergic effect, especially with prostatic enlargement.","E":"Incorrect. Blurred vision is an anticholinergic effect, and raising the dose would worsen it.","F":"Incorrect. Sedation and blurred vision make driving unsafe until the response is known."}}'::jsonb,
 'Physiological Integrity', 'Basic Care and Comfort',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Tricyclic antidepressants', 'Anticholinergic effects', 'Easy', 'CURATOR_LABEL', 'Apply', '{}',
 'Select all that apply.', 4, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_MCQ_541033', 'MCQ',
 'A client with severe generalised anxiety is prescribed sertraline daily together with a two-week course of lorazepam. The client asks the nurse why two different medicines are needed. Which explanation by the nurse is correct?',
 'Antidepressants are the maintenance treatment for anxiety disorders but take two to four weeks to work, and they can briefly increase agitation as they start. A short benzodiazepine course covers that gap, giving relief while the slower agent builds its effect, and is then tapered off. Keeping the benzodiazepine short is deliberate, because tolerance and dependence develop within weeks of regular use.',
 '{"options":[{"id":"A","text":"The lorazepam relieves symptoms during the weeks before the sertraline reaches full effect, and is then tapered off"},{"id":"B","text":"The lorazepam makes the sertraline absorb more quickly"},{"id":"C","text":"Both medicines are antidepressants and work in the same way"},{"id":"D","text":"The lorazepam will be continued indefinitely alongside the sertraline"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. The benzodiazepine bridges the delay before the antidepressant works, then stops before dependence develops.","B":"Incorrect. There is no effect on absorption; the two act by entirely different mechanisms.","C":"Incorrect. Lorazepam is a benzodiazepine acting at GABA receptors, not an antidepressant.","D":"Incorrect. Indefinite benzodiazepine use is what the short course is designed to avoid."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Benzodiazepines', 'Short-term use with an antidepressant', 'Medium', 'CURATOR_LABEL', 'Understand', '{}',
 NULL, 1, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_SATA_541034', 'SATA',
 'A nurse is teaching a client and family about benzodiazepine therapy that has been prescribed for four weeks. Which statements should the nurse include? Select all that apply.',
 'Benzodiazepines work quickly, which is why they are prescribed and why they are difficult to stop. Tolerance and physical dependence build within weeks, and abrupt withdrawal after regular use can cause rebound anxiety, tremor, sweating and seizures, so the dose is tapered. Added to alcohol or opioids they depress respiration, and in older adults they cause falls and confusion out of proportion to the dose.',
 '{"options":[{"id":"A","text":"The medicine is prescribed short term because tolerance and dependence develop with continued use"},{"id":"B","text":"Stopping suddenly after regular use can cause rebound anxiety, tremor and seizures"},{"id":"C","text":"Alcohol should be avoided because it increases sedation and respiratory depression"},{"id":"D","text":"Older adults are at greater risk of falls and confusion on these medicines"},{"id":"E","text":"The dose may be doubled on particularly stressful days"},{"id":"F","text":"A supply of flumazenil should be kept at home in case the client feels too drowsy"}]}'::jsonb,
 '{"answers":["A","B","C","D"],"feedback":{"A":"Correct. Short courses are used precisely because tolerance and dependence develop quickly.","B":"Correct. Withdrawal after regular use can be severe, so the dose is tapered under supervision.","C":"Correct. Combined central nervous system depression is a major cause of respiratory arrest.","D":"Correct. Sensitivity is increased in older adults, and falls and delirium follow.","E":"Incorrect. Self-adjusting the dose accelerates tolerance and dependence.","F":"Incorrect. Flumazenil is an emergency reversal agent given by clinicians, and it can precipitate seizures; it is not a home remedy for drowsiness."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Benzodiazepines', 'Dependence and withdrawal teaching', 'Easy', 'CURATOR_LABEL', 'Apply', '{}',
 'Select all that apply.', 4, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_MMR_541035', 'MATRIX_MR',
 'A nurse reviews monitoring for two clients with bipolar disorder, one taking valproate and one taking carbamazepine. Indicate which medicine each monitoring point applies to. Some apply to both.',
 'Both anticonvulsant mood stabilisers can suppress the bone marrow and injure the liver, so a full blood count and liver function tests belong to both. The differences are specific: valproate raises ammonia, causing lethargy and confusion, and commonly causes weight gain and hair thinning, while carbamazepine causes hyponatraemia through a syndrome of inappropriate antidiuretic hormone and carries the risk of severe skin reactions such as Stevens-Johnson syndrome. Knowing which effect belongs to which agent decides what the nurse asks about at each review.',
 '{"rows":[{"id":"r1","text":"Serum ammonia if new confusion or lethargy appears"},{"id":"r2","text":"Serum sodium for hyponatraemia"},{"id":"r3","text":"Full blood count for marrow suppression"},{"id":"r4","text":"Liver function tests"},{"id":"r5","text":"Urgent review of a spreading rash with mouth and eye involvement"},{"id":"r6","text":"Weight gain and thinning hair"}],"columns":[{"id":"c1","text":"Valproate"},{"id":"c2","text":"Carbamazepine"}],"row_label":"Monitoring point"}'::jsonb,
 '{"cells":{"r1":["c1"],"r2":["c2"],"r3":["c1","c2"],"r4":["c1","c2"],"r5":["c2"],"r6":["c1"]},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Mood stabilisers other than lithium', 'Valproate and carbamazepine monitoring', 'Very hard', 'CURATOR_LABEL', 'Analyze', '{}',
 'Select all that apply for each row.', 8, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_SELN_541036', 'SELECT_N',
 'A 9-year-old child is starting methylphenidate for attention deficit hyperactivity disorder. Which 3 parameters should the school nurse monitor at each review?',
 'Stimulants suppress appetite and can slow growth over time, disturb sleep if given too late in the day, and raise heart rate and blood pressure. Monitoring therefore centres on plotting height and weight, asking about eating and sleeping, and recording pulse and blood pressure at each review. A last dose taken in the early afternoon protects sleep, and a drug holiday may be considered if growth falters.',
 '{"options":[{"id":"A","text":"Height and weight plotted on a growth chart"},{"id":"B","text":"Appetite and sleep pattern"},{"id":"C","text":"Pulse and blood pressure"},{"id":"D","text":"Serum potassium"},{"id":"E","text":"Hearing acuity"},{"id":"F","text":"Deep tendon reflexes"}],"select_count":3}'::jsonb,
 '{"answers":["A","B","C"],"feedback":{"A":"Correct. Growth suppression is a recognised effect and is detected only by plotting measurements over time.","B":"Correct. Appetite suppression and insomnia are the commonest reasons families stop the medicine.","C":"Correct. Stimulants raise heart rate and blood pressure, so both are recorded at each review.","D":"Incorrect. Electrolyte monitoring is not routine with stimulant therapy.","E":"Incorrect. Hearing is unaffected by stimulant medicines.","F":"Incorrect. Reflex testing is not part of stimulant monitoring."}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Stimulants for attention deficit hyperactivity disorder', 'Monitoring in children', 'Very easy', 'CURATOR_LABEL', 'Understand', '{}',
 'Select 3.', 3, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_SATA_541037', 'SATA',
 'A client who has agreed to start disulfiram asks the nurse where alcohol might be hidden in everyday products. Which items should the nurse tell the client to check the label of and avoid? Select all that apply.',
 'Disulfiram blocks aldehyde dehydrogenase, so even a small quantity of alcohol produces flushing, throbbing headache, vomiting, palpitations and hypotension within minutes. The reaction can follow sources the client never thinks of as drinks, which is why the teaching lists everyday products rather than simply saying avoid alcohol. Because the enzyme block persists, these precautions continue for up to two weeks after the last tablet.',
 '{"options":[{"id":"A","text":"Mouthwash"},{"id":"B","text":"Aftershave and skin colognes"},{"id":"C","text":"Some liquid cough and cold medicines"},{"id":"D","text":"Vanilla and other flavouring essences used in cooking"},{"id":"E","text":"Plain boiled rice"},{"id":"F","text":"Tap water"}]}'::jsonb,
 '{"answers":["A","B","C","D"],"feedback":{"A":"Correct. Many mouthwashes contain a high percentage of alcohol and can trigger the reaction.","B":"Correct. Alcohol in colognes and aftershaves is absorbed through the skin in sufficient quantity to cause a reaction.","C":"Correct. Liquid preparations are frequently alcohol based, so labels must be read.","D":"Correct. Flavouring essences are alcohol extracts and are easily overlooked.","E":"Incorrect. Plain rice contains no alcohol and needs no restriction.","F":"Incorrect. Water is safe; the risk lies in alcohol-containing preparations."}}'::jsonb,
 'Safe and Effective Care Environment', 'Safety and Infection Control',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Medicines for alcohol dependence', 'Disulfiram teaching', 'Easy', 'CURATOR_LABEL', 'Apply', '{}',
 'Select all that apply.', 4, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_SELN_541038', 'SELECT_N',
 'A client is entering a methadone maintenance programme for opioid dependence. Which 3 statements by the client indicate correct understanding?',
 'Methadone is a long-acting opioid agonist that removes withdrawal and craving without the peaks of illicit use, and buprenorphine, a partial agonist, is used in the same way. Because it is still an opioid, the dangers are unchanged: taking other opioids on top can be fatal, and combining it with alcohol or sedatives depresses respiration. The dose is set by the prescriber, given under supervision at first, and never stopped abruptly.',
 '{"options":[{"id":"A","text":"The dose is taken once daily and is supervised at the start of the programme"},{"id":"B","text":"Using heroin on top of this medicine can still cause a fatal overdose"},{"id":"C","text":"Alcohol and sedatives taken with it increase the risk of stopping breathing"},{"id":"D","text":"The dose can be doubled on a difficult day"},{"id":"E","text":"This medicine cures opioid dependence within two weeks"},{"id":"F","text":"The medicine should be stopped suddenly once cravings have gone"}],"select_count":3}'::jsonb,
 '{"answers":["A","B","C"],"feedback":{"A":"Correct. Supervised daily dosing is standard at the start of maintenance treatment.","B":"Correct. Additional opioids on top of methadone are a leading cause of fatal overdose.","C":"Correct. Combined respiratory depression is the main cause of death in this group.","D":"Incorrect. Self-adjusting the dose of a long-acting opioid risks accumulation and respiratory arrest.","E":"Incorrect. Maintenance treatment stabilises dependence over months or years; it is not a two-week cure.","F":"Incorrect. Abrupt cessation precipitates withdrawal and commonly leads to relapse."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Medicines for opioid dependence', 'Methadone maintenance teaching', 'Medium', 'CURATOR_LABEL', 'Evaluate', '{}',
 'Select 3.', 3, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_MCQ_541039', 'MCQ',
 'A client with schizophrenia who has capacity and is being treated informally refuses the evening antipsychotic dose. A healthcare assistant suggests crushing the tablet into the evening porridge so that the client does not notice. Which action should the nurse take?',
 'An adult with capacity may refuse any treatment, and concealing medicine in food without a lawful framework and a documented best-interests process is a form of assault and a breach of trust. The nursing action is to accept the refusal, explore the reason for it, record what happened and inform the prescriber and team so that alternatives can be considered. Covert administration is only ever used for a client who lacks capacity, after a multidisciplinary and pharmacist-reviewed decision that is documented in the care plan.',
 '{"options":[{"id":"A","text":"Do not conceal the medicine; document the refusal, explore the reason with the client, and inform the prescriber and the team"},{"id":"B","text":"Follow the suggestion, because the client needs the medicine to stay well"},{"id":"C","text":"Give the porridge and tell the client afterwards that it contained the medicine"},{"id":"D","text":"Withhold all future doses and ask for the prescription to be cancelled"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. A refusal by a client with capacity is respected, explored, documented and escalated, not circumvented.","B":"Incorrect. Concealing medicine from a client with capacity is unlawful regardless of the clinical intention.","C":"Incorrect. Telling the client afterwards does not make covert administration lawful and destroys the therapeutic relationship.","D":"Incorrect. One refusal does not end the treatment plan; the prescriber decides after review."}}'::jsonb,
 'Safe and Effective Care Environment', 'Management of Care',
 'Mental Health', 'Psychiatric/Mental Health',
 'Medication refusal and capacity', 'Covert administration', 'Medium', 'CURATOR_LABEL', 'Evaluate', '{}',
 NULL, 1, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728'),

('NCLEX_SATA_541040', 'SATA',
 'Three days after an increase in the risperidone dose, a client paces the corridor continuously, rocks while seated and says the legs will simply not keep still. Which nursing actions are appropriate? Select all that apply.',
 'Akathisia is a subjective inner restlessness driven by the medicine, and it is frequently mistaken for worsening psychosis or anxiety, which leads to the dangerous response of increasing the dose. It is highly distressing and is associated with impulsive self-harm, so the distress is assessed directly rather than treated as agitation. Management is a prescriber decision, usually a dose reduction, a change of agent or the addition of a beta-blocker such as propranolol.',
 '{"options":[{"id":"A","text":"Report the finding to the prescriber, as the dose may need review or a beta-blocker may be added"},{"id":"B","text":"Ask the client whether the restlessness is an inner urge to move rather than worry about a particular problem"},{"id":"C","text":"Document objective observations such as pacing, rocking and inability to remain seated"},{"id":"D","text":"Assess for distress and any thoughts of self-harm linked to the restlessness"},{"id":"E","text":"Reassure the client that increasing the risperidone dose will settle the restlessness"},{"id":"F","text":"Ask for the client to be restrained in a chair to stop the pacing"}]}'::jsonb,
 '{"answers":["A","B","C","D"],"feedback":{"A":"Correct. Akathisia is managed by a change in the prescription, so it must be reported.","B":"Correct. The inner urge to move is what separates akathisia from anxiety or psychotic agitation.","C":"Correct. Objective description over time allows the team to judge whether the change in prescription worked.","D":"Correct. Akathisia is intensely distressing and is linked with impulsive self-harm.","E":"Incorrect. Increasing the dose worsens akathisia; this is the classic misinterpretation.","F":"Incorrect. Restraint for a medication side effect is neither therapeutic nor justifiable."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pharmacology', 'Psychiatric/Mental Health',
 'Extrapyramidal side effects', 'Akathisia management', 'Easy', 'CURATOR_LABEL', 'Apply', '{}',
 'Select all that apply.', 4, TRUE, TRUE, FALSE, FALSE, 'gapfill-20260728');
