-- MyNclex gap-fill batch 02 — Maternity: labour, birth and intrapartum complications
-- Batch: gapfill-20260728
-- Item id block: 511001-511055 (55 items)
-- Subject: Maternity. Body system: Reproductive (mostly), Multisystem (5 items).
-- No item is classified as Physiological Adaptation (blueprint ceiling already exceeded).

INSERT INTO nclex_bank_items (
  item_id, question_type, stem, rationale, content, correct,
  client_needs_category, client_needs_subcategory, nursing_subject, body_system,
  topic, subtopic, difficulty, difficulty_source, bloom_level, tags,
  marks, is_published, is_builder_visible, is_free_sample, cat_pool, batch_id
) VALUES
('NCLEX_MCQ_511001', 'MCQ',
 'A client at 39 weeks gestation telephones the antenatal clinic. Which finding reported by the client indicates TRUE labour?',
 'False labour contractions are irregular, do not build in strength and usually settle with rest, hydration or a change of activity. True labour contractions follow a progressive pattern - longer, stronger and closer together - because they are doing effective work on the cervix. Teaching clients to judge the pattern rather than a single contraction prevents both unnecessary journeys to the unit and dangerously late arrivals.',
 '{"options":[{"id":"A","text":"The contractions stop when she lies down and rests"},{"id":"B","text":"The discomfort is felt only over the lower abdomen and groin"},{"id":"C","text":"The contractions have become steadily stronger, longer and closer together over the past 3 hours"},{"id":"D","text":"The fetus has moved lower in the abdomen and breathing feels easier"}]}'::jsonb,
 '{"answer":"C","feedback":{"A":"Incorrect. Contractions that ease with rest or a position change are typical of false labour.","B":"Incorrect. Discomfort confined to the lower abdomen and groin is characteristic of false labour; true labour pain usually starts in the back and sweeps forwards.","C":"Correct. A pattern that increases in strength, duration and frequency despite rest is the hallmark of true labour.","D":"Incorrect. Lightening occurs days to weeks before labour and does not mean labour has begun."}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance',
 'Maternity', 'Reproductive', 'True and false labour', 'Distinguishing features',
 'Very easy', 'CURATOR_LABEL', 'Understand', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_511002', 'MCQ',
 'Two clients arrive on the labour ward at the same time, both reporting painful contractions. Which finding gives the MOST valid evidence that labour has truly begun?',
 'Contractions, ruptured membranes and a bloody show can all occur without labour being established. Labour is defined by what is happening to the cervix, so progressive dilation and effacement on serial examinations is the only finding that confirms onset. This is why an admission decision rests on repeated cervical assessment rather than on the contraction pattern alone.',
 '{"options":[{"id":"A","text":"Spontaneous rupture of the membranes"},{"id":"B","text":"Progressive cervical dilation and effacement on serial examinations"},{"id":"C","text":"A bloody show passed 2 hours ago"},{"id":"D","text":"Contractions occurring every 5 minutes"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. Membranes can rupture hours or days before labour begins, and many clients labour with intact membranes.","B":"Correct. Documented cervical change over time is the defining criterion for the onset of labour.","C":"Incorrect. A bloody show signals cervical ripening and may precede labour by several days.","D":"Incorrect. Regular contractions can occur in false labour without producing any cervical change."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Maternity', 'Reproductive', 'Onset of labour', 'Most valid sign',
 'Easy', 'CURATOR_LABEL', 'Understand', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_TF_511003', 'TF',
 'A client reports that her contractions become weaker and further apart when she walks around the ward. The nurse records this as evidence of true labour. Is the interpretation correct?',
 'Activity is a simple bedside discriminator. Walking increases uterine blood flow and mechanical pressure on the cervix, so genuine labour contractions usually persist or intensify with ambulation. Contractions that fade with walking, a warm bath or rest are Braxton Hicks contractions, and the client can safely be advised to rest and reassess at home.',
 '{"options":[{"id":"A","text":"True"},{"id":"B","text":"False"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. Weakening with activity points away from true labour, not towards it.","B":"Correct. True labour contractions continue or strengthen with walking, whereas false labour contractions typically ease with activity or rest."}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance',
 'Maternity', 'Reproductive', 'True and false labour', 'Effect of activity',
 'Very easy', 'CURATOR_LABEL', 'Understand', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MAT_511004', 'MATRIX',
 'The nurse is assessing a client who has come to the maternity unit at 38 weeks gestation. Indicate whether each finding is consistent with true labour or false labour.',
 'True labour is a progressive process: contractions become regular and stronger, discomfort starts in the back and radiates forwards, and - most importantly - the cervix changes and the presenting part descends. False labour produces irregular contractions felt mainly in the lower abdomen that respond to comfort measures and leave the cervix unchanged. Sorting findings this way keeps the admission decision evidence-based rather than driven by how much pain the client reports.',
 '{"rows":[{"id":"r1","text":"Contractions are irregular and vary in length"},{"id":"r2","text":"Pain begins in the lower back and radiates around to the abdomen"},{"id":"r3","text":"The cervix remains 1 cm dilated after 4 hours of contractions"},{"id":"r4","text":"Contractions continue and strengthen while the client walks the corridor"},{"id":"r5","text":"Discomfort is relieved by a warm bath and rest"},{"id":"r6","text":"The presenting part descends from station -2 to station 0"}],"columns":[{"id":"c1","text":"True labour"},{"id":"c2","text":"False labour"}],"row_label":"Finding"}'::jsonb,
 '{"cells":{"r1":"c2","r2":"c1","r3":"c2","r4":"c1","r5":"c2","r6":"c1"},"feedback":{}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance',
 'Maternity', 'Reproductive', 'True and false labour', 'Sorting findings',
 'Medium', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_CLZ_511005', 'CLOZE',
 'A vaginal examination is recorded as: 5 cm dilated, 90 percent effaced, station -1. The nurse explains to a student that 90 percent effaced means the cervix is {1}, and that station -1 means the presenting part is {2}.',
 'Dilation, effacement and station describe three different things and are easily confused. Dilation is how open the cervical os is in centimetres; effacement is how thin the cervix has become, expressed as a percentage; station is how far the presenting part has descended relative to the maternal ischial spines. Because the ischial spines are the reference point, a minus figure means the presenting part is still above them and a plus figure means it has passed below them towards the perineum.',
 '{"blanks":[{"id":"b1","choices":[{"id":"c1","text":"almost completely thinned out"},{"id":"c2","text":"almost completely open"},{"id":"c3","text":"90 percent of the way to the perineum"}]},{"id":"b2","choices":[{"id":"c1","text":"1 cm above the ischial spines"},{"id":"c2","text":"1 cm below the ischial spines"},{"id":"c3","text":"1 cm from crowning"}]}]}'::jsonb,
 '{"answers":{"b1":"c1","b2":"c1"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Maternity', 'Reproductive', 'Cervical assessment', 'Effacement and station',
 'Medium', 'CURATOR_LABEL', 'Understand', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_511006', 'MCQ',
 'The nurse documents that the fetal presenting part is at station 0. What does this finding indicate?',
 'Station 0 means the widest diameter of the presenting part has reached the level of the maternal ischial spines, which is the definition of engagement. Engagement is reassuring because it demonstrates that the pelvis can accommodate the presenting part. A negative station means the presenting part is still above the spines and has not engaged; a positive station means it has descended past them towards the perineum.',
 '{"options":[{"id":"A","text":"The presenting part is floating above the pelvic inlet"},{"id":"B","text":"The presenting part is level with the ischial spines and is engaged"},{"id":"C","text":"The presenting part is visible at the perineum"},{"id":"D","text":"The cervix is fully dilated"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. A floating presenting part is recorded as a negative station such as -3.","B":"Correct. Station 0 places the presenting part at the ischial spines, which defines engagement.","C":"Incorrect. Visibility at the perineum corresponds to station +4 or crowning.","D":"Incorrect. Station describes descent, not dilation; the two are assessed and documented separately."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Maternity', 'Reproductive', 'Fetal station', 'Engagement',
 'Very easy', 'CURATOR_LABEL', 'Remember', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_511007', 'MCQ',
 'Four clients arrive on the labour ward within a few minutes of each other. Which client should the nurse assess FIRST?',
 'Triage in labour is governed by how close each client is to giving birth and by whether the fetus is at risk. A multiparous client at 9 cm with the presenting part at station +3 and an urge to bear down is very close to birth and could deliver unattended. The other three are in early or false labour, or have a normal prelabour finding, and can safely wait a short time.',
 '{"options":[{"id":"A","text":"A primigravida 4 cm dilated at station -2, contracting every 5 minutes"},{"id":"B","text":"A gravida 4 who is 9 cm dilated at station +3 and states she needs to push"},{"id":"C","text":"A client at 39 weeks with irregular contractions and a closed cervix"},{"id":"D","text":"A client at 38 weeks reporting that she has passed a mucus plug with pink-tinged discharge"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. This client is in the early active phase with the presenting part still high, so she is not the most urgent.","B":"Correct. A multipara at 9 cm and station +3 with an urge to push may give birth within minutes and must be assessed immediately.","C":"Incorrect. Irregular contractions with no cervical change suggest false labour, which is not urgent.","D":"Incorrect. A bloody show is a normal prelabour finding that needs no immediate intervention."}}'::jsonb,
 'Safe and Effective Care Environment', 'Management of Care',
 'Maternity', 'Reproductive', 'Triage in labour', 'Prioritising clients',
 'Medium', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SELN_511008', 'SELECT_N',
 'During Leopold manoeuvres at 38 weeks the nurse palpates a hard, round, easily movable mass in the fundus and a broad softer mass over the symphysis pubis. The fetal heart is heard most clearly above the umbilicus. Which 3 conclusions or actions are appropriate?',
 'The fetal head is the hard, round, ballottable part, so finding it in the fundus means the fetus is lying bottom-down in a breech presentation. Auscultating the fetal heart above the umbilicus supports this, because the sound is loudest over the fetal back, which sits higher in a breech. Breech presentation matters clinically because vaginal birth is usually avoided at term and because a presenting part that does not fill the pelvic inlet leaves room for the cord to slip through when the membranes rupture.',
 '{"options":[{"id":"A","text":"The fetus is in a breech presentation"},{"id":"B","text":"The nurse should anticipate discussion of caesarean birth or external cephalic version"},{"id":"C","text":"The fetus is in a vertex presentation"},{"id":"D","text":"The client is at increased risk of umbilical cord prolapse when the membranes rupture"},{"id":"E","text":"The nurse should reassure the client that no further assessment is needed"},{"id":"F","text":"The fetal heart should instead be auscultated well below the umbilicus"}],"select_count":3}'::jsonb,
 '{"answers":["A","B","D"],"feedback":{"A":"Correct. A hard, round, movable mass in the fundus is the fetal head, which places the fetus in a breech presentation.","B":"Correct. Term breech presentation is usually managed by planned caesarean birth or an attempted external cephalic version.","C":"Incorrect. In a vertex presentation the hard round head is felt over the symphysis pubis, not in the fundus.","D":"Correct. A breech presenting part does not seal the pelvic inlet, so the cord can prolapse when the membranes rupture.","E":"Incorrect. An unexpected presentation at 38 weeks requires confirmation and a documented plan for birth.","F":"Incorrect. Hearing the fetal heart above the umbilicus is consistent with breech and is not an error to correct."}}'::jsonb,
 'Safe and Effective Care Environment', 'Management of Care',
 'Maternity', 'Reproductive', 'Fetal presentation', 'Breech presentation',
 'Medium', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MAT_511009', 'MATRIX',
 'For each fetal lie and presentation, indicate whether a vaginal birth may reasonably be attempted or whether a caesarean birth should be anticipated.',
 'Mode of birth depends on whether the presenting part can negotiate the pelvis. A well-flexed vertex - anterior or posterior - can rotate and descend, so labour may continue even though a posterior position makes it slower and more painful. A transverse lie presents a shoulder, which cannot deliver vaginally at all, and a chin-posterior face presentation forces the neck into a hyperextension the pelvis cannot accommodate; both require caesarean birth. Term breech presentation in a first labour is also managed by planned caesarean in most settings.',
 '{"rows":[{"id":"r1","text":"Vertex presentation, occiput anterior, station +1"},{"id":"r2","text":"Transverse lie with a shoulder presenting in established labour"},{"id":"r3","text":"Vertex presentation, occiput posterior, progressing slowly"},{"id":"r4","text":"Complete breech presentation at 39 weeks in a primigravida"},{"id":"r5","text":"Face presentation with the chin posterior"},{"id":"r6","text":"Vertex presentation with intact membranes at station 0"}],"columns":[{"id":"c1","text":"Vaginal birth may be attempted"},{"id":"c2","text":"Caesarean birth is anticipated"}],"row_label":"Lie and presentation"}'::jsonb,
 '{"cells":{"r1":"c1","r2":"c2","r3":"c1","r4":"c2","r5":"c2","r6":"c1"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Maternity', 'Reproductive', 'Fetal lie and presentation', 'Implications for mode of birth',
 'Medium', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MAT_511010', 'MATRIX',
 'Match each finding to the phase of the first stage of labour in which it is expected.',
 'The first stage is divided into three phases with distinct contraction patterns. In the latent phase contractions are widely spaced, short and mild while the cervix opens to about 3 cm. In the active phase they come every 3 to 5 minutes, last 45 to 60 seconds and are moderate to strong as the cervix opens from about 4 to 7 cm. In transition, contractions are almost continuous - every 2 to 3 minutes, 60 to 90 seconds, strong - and the client is often irritable, nauseated and shaking as the cervix completes to 10 cm.',
 '{"rows":[{"id":"r1","text":"Contractions every 15 to 20 minutes lasting 30 seconds, mild on palpation"},{"id":"r2","text":"Contractions every 3 to 5 minutes lasting 45 to 60 seconds, moderate to strong"},{"id":"r3","text":"Contractions every 2 to 3 minutes lasting 60 to 90 seconds, strong"},{"id":"r4","text":"Cervix 1 to 3 cm dilated, client sociable and talkative"},{"id":"r5","text":"Cervix 8 to 10 cm dilated, client irritable, nauseated and shaking"},{"id":"r6","text":"Cervix 4 to 7 cm dilated, client focused inward and quieter"}],"columns":[{"id":"c1","text":"Latent phase"},{"id":"c2","text":"Active phase"},{"id":"c3","text":"Transition phase"}],"row_label":"Finding"}'::jsonb,
 '{"cells":{"r1":"c1","r2":"c2","r3":"c3","r4":"c1","r5":"c3","r6":"c2"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Maternity', 'Reproductive', 'First stage of labour', 'Phases and contraction patterns',
 'Medium', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728');

INSERT INTO nclex_bank_items (
  item_id, question_type, stem, rationale, content, correct,
  client_needs_category, client_needs_subcategory, nursing_subject, body_system,
  topic, subtopic, difficulty, difficulty_source, bloom_level, tags,
  marks, is_published, is_builder_visible, is_free_sample, cat_pool, batch_id
) VALUES
('NCLEX_MCQ_511011', 'MCQ',
 'A client is admitted in the latent phase of the first stage of labour: 2 cm dilated, contracting every 15 minutes, talking easily between contractions. Which nursing action is most appropriate at this point?',
 'Nursing priorities change with each phase. The latent phase is the longest and least intense part of labour, and the client is still able to take in information, so this is the window for orientation, teaching and encouraging ambulation, light diet and fluids. Energy conserved and information given now pays off later, when contractions in the active and transition phases make learning impossible.',
 '{"options":[{"id":"A","text":"Encourage ambulation and oral fluids and orientate the client to the unit"},{"id":"B","text":"Coach the client to push with each contraction"},{"id":"C","text":"Confine the client to bed with continuous monitoring"},{"id":"D","text":"Prepare the client immediately for an epidural"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Ambulation, hydration and teaching suit the latent phase, when the client can still absorb information and conserve energy.","B":"Incorrect. Pushing before full dilation causes cervical oedema and trauma.","C":"Incorrect. Routine confinement to bed in early labour slows progress; intermittent monitoring is appropriate for a low-risk client.","D":"Incorrect. Regional analgesia sited in the latent phase can slow labour, and this client is coping well."}}'::jsonb,
 'Physiological Integrity', 'Basic Care and Comfort',
 'Maternity', 'Reproductive', 'First stage of labour', 'Latent phase nursing care',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_511012', 'MCQ',
 'During the transition phase a client shouts at the nurse, states that she cannot go on and asks to be left alone, then immediately asks the nurse not to leave the room. Which nursing action is the PRIORITY?',
 'Irritability, loss of control, nausea, shaking and contradictory demands are expected behaviours in transition, driven by the intensity of contractions and by rapidly changing hormones. The nurse who interprets them as expected rather than as rudeness can stay present and give calm, unhurried reassurance that this phase is short. Withdrawing from the client at this moment removes support exactly when it is most needed.',
 '{"options":[{"id":"A","text":"Remain with the client and offer calm, non-judgemental encouragement between contractions"},{"id":"B","text":"Explain that shouting will tire her and ask her to control herself"},{"id":"C","text":"Leave the room as requested and return in 15 minutes"},{"id":"D","text":"Ask the partner to take over the coaching so the nurse can complete the charting"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Staying present with calm, accepting support meets the psychosocial need of a client in transition, whose behaviour is an expected response to intense labour.","B":"Incorrect. Asking a client in transition to control herself is shaming and ignores the physiological basis of the behaviour.","C":"Incorrect. Leaving abandons a client at the most demanding point of labour, and she has already asked the nurse to stay.","D":"Incorrect. The partner also needs support at this point; charting is not a priority over presence."}}'::jsonb,
 'Psychosocial Integrity', 'Psychosocial Integrity',
 'Maternity', 'Reproductive', 'First stage of labour', 'Transition phase support',
 'Hard', 'CURATOR_LABEL', 'Evaluate', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_511013', 'MCQ',
 'A client has just reached full dilation and has begun to bear down. Which nursing action is the PRIORITY during the second STAGE of labour?',
 'Note that the priority in the second stage is not the same as the priority in the second phase of the first stage. During the second phase, the active phase, the focus is coping and comfort. During the second stage the fetus is being pushed through the pelvis, each contraction plus each maternal pushing effort reduces placental blood flow, so the fetal heart rate is assessed after every contraction to detect the hypoxia that expulsive effort can cause.',
 '{"options":[{"id":"A","text":"Assess the fetal heart rate after every contraction"},{"id":"B","text":"Encourage the client to sleep between contractions"},{"id":"C","text":"Assess cervical dilation every 30 minutes"},{"id":"D","text":"Massage the fundus every 15 minutes"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Pushing further reduces placental perfusion, so fetal heart rate assessment after each contraction is the priority in the second stage.","B":"Incorrect. Rest between contractions is encouraged, but it is a comfort measure rather than the priority.","C":"Incorrect. Dilation is already complete; repeating cervical examinations adds no information and raises infection risk.","D":"Incorrect. Fundal massage belongs after the placenta is delivered, in the fourth stage."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Maternity', 'Reproductive', 'Second stage of labour', 'Nursing priority',
 'Hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_511014', 'SATA',
 'The nurse is with a client immediately after the birth of the baby. Which findings indicate that the placenta has separated and is ready to be delivered? Select all that apply.',
 'The third stage lasts from the birth of the baby to the delivery of the placenta and usually takes 5 to 30 minutes. Separation is recognised by a cluster of signs: a sudden gush of dark blood as the retroplacental clot escapes, lengthening of the visible cord, a uterus that rises and becomes globular and firm, and a returning urge to bear down. Waiting for these signs before applying any cord traction protects the client from a partially separated placenta and from uterine inversion.',
 '{"options":[{"id":"A","text":"A sudden gush of dark blood from the vagina"},{"id":"B","text":"Lengthening of the umbilical cord at the introitus"},{"id":"C","text":"The uterus rises in the abdomen and becomes globular and firm"},{"id":"D","text":"The client reports that all abdominal cramping has stopped"},{"id":"E","text":"The fundus becomes soft and boggy and cannot be located"},{"id":"F","text":"The client feels an urge to bear down again"}]}'::jsonb,
 '{"answers":["A","B","C","F"],"feedback":{"A":"Correct. The gush of dark blood is the retroplacental clot escaping as the placenta shears away.","B":"Correct. Visible lengthening of the cord shows the placenta has descended into the lower segment.","C":"Correct. The uterus rises and becomes globular and firm as it empties of the placenta.","D":"Incorrect. Cramping continues in the third stage because the uterus keeps contracting to expel the placenta.","E":"Incorrect. A boggy fundus that cannot be located suggests atony or uterine inversion, not normal separation.","F":"Correct. The placenta in the lower segment produces a renewed urge to bear down."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Maternity', 'Reproductive', 'Third stage of labour', 'Signs of placental separation',
 'Medium', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_511015', 'SATA',
 'During the first hour after birth the nurse assesses a client every 15 minutes. Which assessments belong in this fourth-stage routine? Select all that apply.',
 'The fourth stage covers the first 1 to 2 hours after delivery of the placenta, when the risk of haemorrhage is highest. Assessment is therefore aimed at detecting bleeding early: fundal tone and position, the amount and colour of lochia, vital signs, bladder distension that can displace the uterus and prevent it contracting, and the perineum for a concealed haematoma. Cervical examination has no place here, as the birth is complete.',
 '{"options":[{"id":"A","text":"Fundal position, tone and height"},{"id":"B","text":"Amount and colour of the lochia"},{"id":"C","text":"Blood pressure and pulse"},{"id":"D","text":"Bladder distension"},{"id":"E","text":"Cervical dilation"},{"id":"F","text":"The perineum for haematoma or excessive swelling"}]}'::jsonb,
 '{"answers":["A","B","C","D","F"],"feedback":{"A":"Correct. A firm, midline fundus at or below the umbilicus shows the uterus is controlling bleeding.","B":"Correct. Lochia that soaks a pad in under an hour or contains large clots signals haemorrhage.","C":"Correct. Rising pulse and falling blood pressure are early signs of concealed blood loss.","D":"Correct. A full bladder pushes the uterus up and to the side and prevents effective contraction.","E":"Incorrect. Cervical dilation is no longer assessed once the birth is complete.","F":"Correct. A tense, discoloured, exquisitely painful perineum indicates a haematoma."}}'::jsonb,
 'Physiological Integrity', 'Basic Care and Comfort',
 'Maternity', 'Reproductive', 'Fourth stage of labour', 'Recovery assessments',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_511016', 'MCQ',
 'The nurse is teaching a student nurse about the stages of labour. The second stage of labour begins at which point?',
 'Labour is divided into four stages by fixed events, not by how the client feels. The first stage runs from the onset of true labour to full dilation, the second from full dilation to the birth of the baby, the third from the birth of the baby to delivery of the placenta, and the fourth covers the first 1 to 2 hours of recovery. Knowing the boundaries matters because the nursing priority changes at each one.',
 '{"options":[{"id":"A","text":"When contractions become regular and painful"},{"id":"B","text":"When the cervix is fully dilated at 10 cm"},{"id":"C","text":"When the baby is born"},{"id":"D","text":"When the placenta is delivered"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. Regular painful contractions mark the beginning of the first stage.","B":"Correct. Full dilation ends the first stage and begins the second.","C":"Incorrect. Birth of the baby ends the second stage and begins the third.","D":"Incorrect. Delivery of the placenta ends the third stage and begins the fourth."}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance',
 'Maternity', 'Reproductive', 'Stages of labour', 'Boundaries of each stage',
 'Very easy', 'CURATOR_LABEL', 'Remember', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_511017', 'MCQ',
 'The external monitor shows contractions beginning at 08:00, 08:04 and 08:08, each lasting 50 seconds. How should the nurse document the frequency?',
 'Frequency and duration are measured from different points, which is where most errors occur. Frequency is timed from the beginning of one contraction to the beginning of the next, so contractions starting at 08:00, 08:04 and 08:08 are every 4 minutes. Duration is timed from the beginning to the end of the same contraction, which is 50 seconds here, and is documented separately.',
 '{"options":[{"id":"A","text":"Every 4 minutes"},{"id":"B","text":"Every 50 seconds"},{"id":"C","text":"Every 3 minutes and 10 seconds"},{"id":"D","text":"Every 8 minutes"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Beginning-to-beginning is 4 minutes, so the frequency is every 4 minutes.","B":"Incorrect. Fifty seconds is the duration of each contraction, not the frequency.","C":"Incorrect. This subtracts the duration from the interval, which is not how frequency is measured.","D":"Incorrect. Eight minutes spans two intervals rather than one."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Maternity', 'Reproductive', 'Contraction assessment', 'Measuring frequency',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_CLZ_511018', 'CLOZE',
 'A contraction begins at 10:02:00 and ends at 10:03:05. At the peak of the contraction the fundus feels to the nurse like the tip of the nose. The nurse documents a duration of {1} and an intensity of {2}.',
 'Duration is measured from the beginning to the end of a single contraction, so 10:02:00 to 10:03:05 is 65 seconds. Intensity cannot be read from an external tocodynamometer, because the height of that tracing reflects how tightly the belt is applied and how much abdominal fat lies beneath it. Intensity is judged by palpating the fundus at the peak, using the classic comparison: as yielding as the chin is mild, as firm as the tip of the nose is moderate, and as hard as the forehead is strong.',
 '{"blanks":[{"id":"b1","choices":[{"id":"c1","text":"65 seconds"},{"id":"c2","text":"3 minutes"},{"id":"c3","text":"35 seconds"}]},{"id":"b2","choices":[{"id":"c1","text":"moderate"},{"id":"c2","text":"mild"},{"id":"c3","text":"strong"}]}]}'::jsonb,
 '{"answers":{"b1":"c1","b2":"c1"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Maternity', 'Reproductive', 'Contraction assessment', 'Duration and intensity by palpation',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_511019', 'MCQ',
 'A client receiving an oxytocin infusion has contractions lasting 100 seconds occurring every 90 seconds, and the fetal heart rate baseline has fallen to 100 beats per minute. Which action should the nurse take FIRST?',
 'When a question asks what to do FIRST, it is asking about sequence. Oxytocin is the cause of the hyperstimulation, and it has a half-life of only a few minutes, so stopping the infusion removes the stimulus immediately and is the first step. Repositioning, intravenous fluid, oxygen and notifying the obstetrician all follow within moments, but they cannot work while the drug is still driving the uterus.',
 '{"options":[{"id":"A","text":"Stop the oxytocin infusion"},{"id":"B","text":"Turn the client to the left lateral position"},{"id":"C","text":"Administer oxygen at 8 to 10 litres per minute by non-rebreather mask"},{"id":"D","text":"Notify the obstetrician"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Removing the drug that is causing the excessive contractions is the first step, and it acts within minutes.","B":"Incorrect. Left lateral positioning is part of the response but comes after the oxytocin is stopped.","C":"Incorrect. Oxygen is given as part of the bundle but does not address the cause.","D":"Incorrect. The obstetrician must be told, but the nurse acts to remove the cause before making the call."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Maternity', 'Reproductive', 'Uterine hyperstimulation', 'First action',
 'Hard', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_511020', 'MCQ',
 'The same client continues to have contractions lasting more than 90 seconds with less than 2 minutes between them. Which problem is the PRIORITY concern for the nurse?',
 'Where the FIRST question asks about sequence, the PRIORITY question asks what matters most. The placenta is perfused only while the uterus is relaxed, so the resting interval between contractions is when the fetus receives its oxygen. Contractions longer than 90 seconds or closer than 2 minutes abolish that interval, and the resulting uteroplacental insufficiency causes fetal hypoxia, which is more immediately threatening than pain, speed of labour or fluid balance.',
 '{"options":[{"id":"A","text":"Maternal exhaustion from an unusually painful labour"},{"id":"B","text":"Impaired uteroplacental perfusion leading to fetal hypoxia"},{"id":"C","text":"Rapid cervical dilation causing a precipitous birth"},{"id":"D","text":"Fluid overload from the intravenous infusion"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. Exhaustion is a genuine consequence but is not immediately life-threatening to the fetus.","B":"Correct. Without an adequate resting interval the placenta cannot be reperfused, so the fetus becomes hypoxic and acidotic.","C":"Incorrect. A precipitous birth is possible but is a lesser concern than fetal oxygenation.","D":"Incorrect. Fluid overload relates to prolonged high-dose oxytocin over hours, not to the contraction pattern itself."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Maternity', 'Reproductive', 'Uterine hyperstimulation', 'Priority concern',
 'Very hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728');

INSERT INTO nclex_bank_items (
  item_id, question_type, stem, rationale, content, correct,
  client_needs_category, client_needs_subcategory, nursing_subject, body_system,
  topic, subtopic, difficulty, difficulty_source, bloom_level, tags,
  marks, is_published, is_builder_visible, is_free_sample, cat_pool, batch_id
) VALUES
('NCLEX_SATA_511021', 'SATA',
 'A client receiving oxytocin develops uterine tetany with late decelerations. Which nursing actions are indicated? Select all that apply.',
 'Management of tetany combines removing the stimulus with restoring uterine blood flow. The oxytocin is stopped, the client is turned onto her side to lift the uterus off the inferior vena cava, a fluid bolus expands circulating volume, and oxygen raises the maternal oxygen content available to cross the placenta. If the uterus still does not relax, a tocolytic such as terbutaline is prescribed to relax the myometrium directly.',
 '{"options":[{"id":"A","text":"Discontinue the oxytocin infusion"},{"id":"B","text":"Reposition the client to the left lateral position"},{"id":"C","text":"Increase the rate of the maintenance intravenous fluid"},{"id":"D","text":"Administer oxygen by non-rebreather mask at 8 to 10 litres per minute"},{"id":"E","text":"Prepare to administer terbutaline as prescribed"},{"id":"F","text":"Increase the oxytocin rate to shorten the labour"}]}'::jsonb,
 '{"answers":["A","B","C","D","E"],"feedback":{"A":"Correct. Stopping the drug removes the stimulus driving the excessive contractions.","B":"Correct. Side-lying relieves compression of the inferior vena cava and improves uterine blood flow.","C":"Correct. A fluid bolus raises circulating volume and therefore placental perfusion.","D":"Correct. Supplemental oxygen increases the amount available to cross to the fetus.","E":"Correct. Terbutaline is a tocolytic that relaxes the myometrium when stopping the infusion is not enough.","F":"Incorrect. Increasing oxytocin would worsen the tetany and deepen the fetal compromise."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Maternity', 'Reproductive', 'Uterine tetany', 'Nursing interventions',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SELN_511022', 'SELECT_N',
 'A nurse is supervising an oxytocin infusion for labour augmentation. Which 3 findings require the infusion to be discontinued immediately?',
 'Oxytocin is titrated against the uterine response, not against a fixed target rate. The infusion must be stopped when contractions last longer than 90 seconds, when they occur more often than every 2 minutes, or when the fetal heart tracing shows recurrent late decelerations or loss of variability. A pattern of contractions every 2 to 3 minutes lasting 45 to 70 seconds with a reassuring tracing is the goal of the infusion, not a reason to stop it.',
 '{"options":[{"id":"A","text":"Contractions lasting 95 seconds"},{"id":"B","text":"Contractions occurring every 90 seconds"},{"id":"C","text":"Recurrent late decelerations with minimal variability"},{"id":"D","text":"Contractions every 3 minutes lasting 60 seconds"},{"id":"E","text":"The client reports that the contractions are becoming more painful"},{"id":"F","text":"A fetal heart rate baseline of 145 beats per minute"}],"select_count":3}'::jsonb,
 '{"answers":["A","B","C"],"feedback":{"A":"Correct. A duration beyond 90 seconds leaves too little time for placental reperfusion.","B":"Correct. Contractions closer together than every 2 minutes abolish the resting interval.","C":"Correct. Recurrent late decelerations with minimal variability indicate uteroplacental insufficiency and fetal compromise.","D":"Incorrect. This is the intended contraction pattern for an augmented labour.","E":"Incorrect. Increasing pain is expected as labour becomes effective and is managed with analgesia and support.","F":"Incorrect. A baseline of 145 beats per minute is within the normal range of 110 to 160."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Maternity', 'Reproductive', 'Oxytocin infusion', 'Criteria for discontinuing',
 'Very hard', 'CURATOR_LABEL', 'Evaluate', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_511023', 'MCQ',
 'Which baseline fetal heart rate is within the expected range for a term fetus during labour?',
 'The normal baseline fetal heart rate at term is 110 to 160 beats per minute, measured over a 10-minute window between contractions and excluding accelerations and decelerations. A sustained rate below 110 is bradycardia and may reflect hypoxia, cord compression or maternal hypotension. A sustained rate above 160 is tachycardia and often reflects maternal fever, infection, dehydration or early fetal hypoxia.',
 '{"options":[{"id":"A","text":"95 beats per minute"},{"id":"B","text":"105 beats per minute"},{"id":"C","text":"140 beats per minute"},{"id":"D","text":"175 beats per minute"}]}'::jsonb,
 '{"answer":"C","feedback":{"A":"Incorrect. Ninety-five beats per minute is bradycardia and requires intervention.","B":"Incorrect. This is just below the lower limit of 110 beats per minute.","C":"Correct. One hundred and forty beats per minute sits comfortably within the 110 to 160 range.","D":"Incorrect. One hundred and seventy-five beats per minute is tachycardia and must be investigated."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Maternity', 'Reproductive', 'Fetal heart rate monitoring', 'Baseline rate',
 'Very easy', 'CURATOR_LABEL', 'Remember', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_511024', 'MCQ',
 'The fetal monitor shows a baseline of 140 beats per minute with fluctuations of 10 to 20 beats per minute around that baseline. How should the nurse interpret this finding?',
 'Variability is the beat-to-beat irregularity produced by the interplay of the fetal sympathetic and parasympathetic nervous systems. Moderate variability, defined as 6 to 25 beats per minute, is the single most reassuring feature of a tracing because it shows the fetal central nervous system is well oxygenated and intact. Absent or minimal variability, by contrast, raises the possibility of hypoxia, sedation or a sleep cycle.',
 '{"options":[{"id":"A","text":"Moderate variability, indicating adequate fetal oxygenation"},{"id":"B","text":"Minimal variability, indicating fetal hypoxia"},{"id":"C","text":"Marked variability, indicating cord compression"},{"id":"D","text":"An unstable baseline requiring immediate birth"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Fluctuations of 6 to 25 beats per minute define moderate variability, the most reassuring sign on a tracing.","B":"Incorrect. Minimal variability means fluctuations of 5 beats per minute or fewer.","C":"Incorrect. Marked variability exceeds 25 beats per minute.","D":"Incorrect. This is a normal, reassuring tracing that requires no intervention."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Maternity', 'Reproductive', 'Fetal heart rate monitoring', 'Variability',
 'Easy', 'CURATOR_LABEL', 'Understand', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_511025', 'SATA',
 'A fetal heart tracing has shown variability of 3 beats per minute for the past 40 minutes. Which possible causes should the nurse consider? Select all that apply.',
 'Minimal variability is not automatically an emergency, but it always requires explanation. Benign causes include a fetal sleep cycle, which usually lasts 20 to 40 minutes, prematurity, and central nervous system depression from opioids or magnesium sulfate given to the mother. The dangerous cause is fetal hypoxia and developing acidosis, so if minimal variability persists beyond a sleep cycle or is accompanied by decelerations, it must be treated as compromise until proved otherwise.',
 '{"options":[{"id":"A","text":"A fetal sleep cycle"},{"id":"B","text":"Recent administration of an opioid analgesic to the mother"},{"id":"C","text":"A magnesium sulfate infusion"},{"id":"D","text":"Fetal hypoxia and developing acidosis"},{"id":"E","text":"Repositioning the client to the left lateral position"},{"id":"F","text":"Prematurity"}]}'::jsonb,
 '{"answers":["A","B","C","D","F"],"feedback":{"A":"Correct. Fetal sleep cycles of 20 to 40 minutes reduce variability and are benign.","B":"Correct. Opioids cross the placenta and depress the fetal central nervous system.","C":"Correct. Magnesium sulfate is a central nervous system depressant for the fetus as well as the mother.","D":"Correct. Hypoxia and acidosis blunt autonomic control and reduce variability.","E":"Incorrect. Left lateral positioning improves uteroplacental perfusion and would tend to improve variability.","F":"Correct. The autonomic nervous system is immature before about 32 weeks, so variability is naturally lower."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Maternity', 'Reproductive', 'Fetal heart rate monitoring', 'Minimal variability',
 'Hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_511026', 'MCQ',
 'The fetal monitor shows decelerations that begin as each contraction begins, reach their lowest point at the peak of the contraction and return to baseline as the contraction ends. Which action should the nurse take?',
 'A deceleration that mirrors the contraction is an early deceleration, caused by vagal stimulation as the fetal head is compressed in the pelvis. It is a benign, physiological response associated with descent and requires no intervention beyond continued observation and documentation. Treating it as an emergency wastes resources and can lead to unnecessary intervention in a normally progressing labour.',
 '{"options":[{"id":"A","text":"Continue to monitor and document the tracing"},{"id":"B","text":"Stop the oxytocin infusion and administer oxygen"},{"id":"C","text":"Perform a vaginal examination to check for a prolapsed cord"},{"id":"D","text":"Prepare the client for an immediate caesarean birth"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Early decelerations mirror the contraction, reflect head compression and need only continued observation.","B":"Incorrect. That response is reserved for late decelerations or other non-reassuring patterns.","C":"Incorrect. A vaginal examination for cord prolapse follows abrupt variable decelerations, not mirrored early ones.","D":"Incorrect. Early decelerations are benign and are not an indication for caesarean birth."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Maternity', 'Reproductive', 'Fetal heart rate decelerations', 'Early decelerations',
 'Very easy', 'CURATOR_LABEL', 'Understand', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_511027', 'MCQ',
 'A client at 40 weeks has repetitive decelerations that begin after the peak of each contraction and do not return to baseline until after the contraction has ended. No oxytocin is running. Which action should the nurse take FIRST?',
 'A deceleration that lags behind the contraction is a late deceleration and signals uteroplacental insufficiency. The first action is the one that can be performed instantly and that most reliably improves uterine blood flow: turning the client onto her side, which lifts the gravid uterus off the inferior vena cava and abdominal aorta. Increasing fluids, giving oxygen and notifying the obstetrician follow immediately afterwards.',
 '{"options":[{"id":"A","text":"Reposition the client onto her left side"},{"id":"B","text":"Increase the rate of the intravenous infusion"},{"id":"C","text":"Apply oxygen by non-rebreather mask"},{"id":"D","text":"Notify the obstetrician"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Repositioning takes seconds, needs no prescription and immediately relieves compression of the great vessels.","B":"Incorrect. A fluid bolus is part of the bundle but takes longer to take effect than repositioning.","C":"Incorrect. Oxygen is given next, but it cannot help if the uterus is still compressing the vena cava.","D":"Incorrect. The obstetrician is notified after the nurse has begun intrauterine resuscitation."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Maternity', 'Reproductive', 'Fetal heart rate decelerations', 'Late decelerations first action',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_511028', 'MCQ',
 'Recurrent late decelerations persist after the client has been repositioned and given a fluid bolus. As the nurse continues to intervene, which goal is the PRIORITY?',
 'Every intervention in this situation is aimed at one physiological target. Late decelerations mean the placenta is not delivering enough oxygen during contractions, so the priority goal is to restore uteroplacental perfusion and fetal oxygenation. Naming the goal, rather than memorising a list of actions, lets the nurse judge any new intervention by asking whether it increases blood flow and oxygen delivery to the placenta.',
 '{"options":[{"id":"A","text":"Restoring uteroplacental perfusion and fetal oxygenation"},{"id":"B","text":"Relieving compression of the umbilical cord"},{"id":"C","text":"Reducing maternal anxiety about the tracing"},{"id":"D","text":"Shortening the second stage of labour"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Late decelerations reflect uteroplacental insufficiency, so restoring placental blood flow and oxygen delivery is the priority goal.","B":"Incorrect. Cord compression produces variable decelerations, not late decelerations.","C":"Incorrect. Explanation and reassurance matter, but they do not address fetal oxygenation.","D":"Incorrect. Expediting birth may become necessary, but it is a consequence of failed resuscitation, not the immediate goal."}}'::jsonb,
 'Safe and Effective Care Environment', 'Management of Care',
 'Maternity', 'Reproductive', 'Fetal heart rate decelerations', 'Late decelerations priority goal',
 'Very hard', 'CURATOR_LABEL', 'Evaluate', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_511029', 'MCQ',
 'The fetal monitor shows abrupt V-shaped decelerations that vary in shape and timing and bear no consistent relationship to the contractions. What do these decelerations indicate, and what should the nurse do?',
 'Variable decelerations are abrupt, vary in appearance and occur at any point relative to contractions because their cause is mechanical rather than rhythmic: the umbilical cord is being compressed. The first response is to change the maternal position, which often shifts the fetus off the cord. If they persist and the membranes have ruptured, amnioinfusion may be prescribed to restore the fluid cushion around the cord.',
 '{"options":[{"id":"A","text":"Head compression; continue routine monitoring"},{"id":"B","text":"Umbilical cord compression; change the maternal position"},{"id":"C","text":"Uteroplacental insufficiency; prepare for an immediate caesarean birth"},{"id":"D","text":"A fetal sleep cycle; stimulate the fetus with a cold cloth on the abdomen"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. Head compression produces early decelerations that mirror the contraction.","B":"Correct. Abrupt variable decelerations reflect cord compression, and repositioning is the first corrective measure.","C":"Incorrect. Uteroplacental insufficiency produces late decelerations, and caesarean birth is not the first response.","D":"Incorrect. A sleep cycle reduces variability; it does not cause abrupt decelerations."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Maternity', 'Reproductive', 'Fetal heart rate decelerations', 'Variable decelerations',
 'Easy', 'CURATOR_LABEL', 'Understand', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MMR_511030', 'MATRIX_MR',
 'For each fetal heart rate pattern, select all of the nursing actions that are indicated. Each pattern has at least one indicated action.',
 'Matching the response to the pattern prevents both under-reaction and over-reaction. Early decelerations and accelerations are reassuring and call only for continued observation and documentation. Variable decelerations are mechanical and call for a position change. Recurrent late decelerations with oxytocin running call for both a position change and stopping the infusion, because the drug is intensifying the very contractions that are limiting placental perfusion.',
 '{"rows":[{"id":"r1","text":"Early decelerations at 7 cm dilation"},{"id":"r2","text":"Recurrent late decelerations with an oxytocin infusion running"},{"id":"r3","text":"Repetitive variable decelerations after the membranes rupture"},{"id":"r4","text":"Accelerations of 15 beats per minute lasting 15 seconds"}],"columns":[{"id":"c1","text":"Continue routine monitoring and document"},{"id":"c2","text":"Reposition the client"},{"id":"c3","text":"Discontinue the oxytocin infusion"}],"row_label":"Fetal heart rate pattern"}'::jsonb,
 '{"cells":{"r1":["c1"],"r2":["c2","c3"],"r3":["c2"],"r4":["c1"]},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Maternity', 'Reproductive', 'Fetal heart rate monitoring', 'Pattern-specific actions',
 'Hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728');

INSERT INTO nclex_bank_items (
  item_id, question_type, stem, rationale, content, correct,
  client_needs_category, client_needs_subcategory, nursing_subject, body_system,
  topic, subtopic, difficulty, difficulty_source, bloom_level, tags,
  marks, is_published, is_builder_visible, is_free_sample, cat_pool, batch_id
) VALUES
('NCLEX_SATA_511031', 'SATA',
 'A client with an oxytocin infusion develops a prolonged fetal heart rate deceleration lasting more than 2 minutes. Which actions make up the intrauterine resuscitation bundle? Select all that apply.',
 'Intrauterine resuscitation is a fixed bundle that the nurse can start without waiting for a prescription. The oxytocin is stopped first because it is the reversible cause, the client is turned onto her side to free the great vessels, a fluid bolus raises circulating volume, oxygen raises maternal arterial oxygen content, and the obstetrician is notified so that a decision about expediting birth can be made. Lying flat is the one manoeuvre that makes the situation worse.',
 '{"options":[{"id":"A","text":"Stop the oxytocin infusion"},{"id":"B","text":"Reposition the client to a left lateral position"},{"id":"C","text":"Give a bolus of intravenous fluid"},{"id":"D","text":"Administer oxygen at 8 to 10 litres per minute by non-rebreather mask"},{"id":"E","text":"Notify the obstetrician"},{"id":"F","text":"Lay the client flat on her back with her legs extended"}]}'::jsonb,
 '{"answers":["A","B","C","D","E"],"feedback":{"A":"Correct. Oxytocin is stopped first because it is the reversible cause of reduced placental perfusion.","B":"Correct. Side-lying relieves aortocaval compression and improves uterine blood flow.","C":"Correct. A fluid bolus expands circulating volume and raises placental perfusion pressure.","D":"Correct. Supplemental oxygen increases the oxygen available to cross the placenta.","E":"Correct. The obstetrician must be informed so a decision about expediting birth can be made.","F":"Incorrect. The supine position compresses the vena cava and worsens the deceleration."}}'::jsonb,
 'Safe and Effective Care Environment', 'Management of Care',
 'Maternity', 'Reproductive', 'Intrauterine resuscitation', 'Bundle of actions',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_511032', 'MCQ',
 'Immediately after the membranes rupture spontaneously, the nurse sees a loop of umbilical cord at the introitus and the fetal heart rate falls to 80 beats per minute. Which action should the nurse take FIRST?',
 'A prolapsed cord kills the fetus by compression between the presenting part and the pelvis, so the very first action must physically relieve that compression. The nurse inserts a gloved hand and holds the presenting part upwards off the cord, and keeps it there while calling for help and until the baby is delivered, usually by caesarean. Positioning, oxygen and preparation for theatre all follow, but none of them lift the presenting part off the cord.',
 '{"options":[{"id":"A","text":"Insert a gloved hand into the vagina and lift the presenting part off the cord"},{"id":"B","text":"Gently push the cord back inside the vagina"},{"id":"C","text":"Place the client in the knee-chest position"},{"id":"D","text":"Telephone the obstetrician and prepare the theatre"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Manually elevating the presenting part is the only action that immediately relieves the compression causing the bradycardia.","B":"Incorrect. Handling or replacing the cord causes vasospasm and worsens fetal hypoxia.","C":"Incorrect. Knee-chest positioning helps and is done immediately afterwards, but manual elevation acts first and most directly.","D":"Incorrect. Help is summoned while the nurse holds the presenting part up, not instead of doing so."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Maternity', 'Reproductive', 'Prolapsed umbilical cord', 'First action',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_511033', 'SATA',
 'A nurse is holding the fetal presenting part off a prolapsed umbilical cord while the team assembles. Which additional actions should the team take? Select all that apply.',
 'Once manual elevation is in place, everything else is aimed at keeping the cord decompressed and perfused until birth. Gravity is recruited with the knee-chest or Trendelenburg position, maternal oxygen maximises what little blood is still reaching the fetus, and an exposed cord is kept warm and moist with sterile saline gauze to prevent drying and vasospasm. The two things never done are replacing the cord and removing the hand before the baby is delivered.',
 '{"options":[{"id":"A","text":"Place the client in the knee-chest or Trendelenburg position"},{"id":"B","text":"Administer oxygen at 8 to 10 litres per minute by face mask"},{"id":"C","text":"Cover any exposed cord with a sterile saline-soaked dressing"},{"id":"D","text":"Attempt to replace the cord inside the uterus"},{"id":"E","text":"Prepare the client for an emergency caesarean birth"},{"id":"F","text":"Withdraw the gloved hand once the client has been repositioned"}]}'::jsonb,
 '{"answers":["A","B","C","E"],"feedback":{"A":"Correct. These positions use gravity to shift the presenting part away from the pelvic inlet.","B":"Correct. Maternal oxygen maximises the oxygen carried in whatever cord flow remains.","C":"Correct. Keeping the cord warm and moist prevents drying and vasospasm.","D":"Incorrect. Replacing the cord causes vasospasm and delays definitive management.","E":"Correct. Immediate caesarean birth is the definitive treatment unless vaginal birth is imminent.","F":"Incorrect. The hand stays in place until the baby is delivered, however uncomfortable that is for the nurse."}}'::jsonb,
 'Safe and Effective Care Environment', 'Management of Care',
 'Maternity', 'Reproductive', 'Prolapsed umbilical cord', 'Ongoing management',
 'Hard', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_511034', 'MCQ',
 'A client in the active phase reports severe unrelenting lower back pain that does not ease between contractions. Vaginal examination confirms an occiput posterior position. Which nursing measure is BEST?',
 'In an occiput posterior position the hard fetal occiput presses against the maternal sacrum, producing continuous back pain that ordinary contraction-focused comfort measures do not touch. Firm counter-pressure applied to the sacrum during contractions opposes that pressure directly, and a hands-and-knees or forward-leaning position swings the fetal back away from the sacrum, often helping the fetus rotate to an anterior position as well.',
 '{"options":[{"id":"A","text":"Apply firm counter-pressure to the sacrum and help the client into a hands-and-knees position"},{"id":"B","text":"Position the client flat on her back with a pillow under her head"},{"id":"C","text":"Encourage the client to hold her breath and push with each contraction"},{"id":"D","text":"Apply a cold pack to the abdomen over the fundus"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Sacral counter-pressure opposes the fetal occiput directly, and the hands-and-knees position relieves pressure and encourages rotation.","B":"Incorrect. Lying supine increases sacral pressure and risks supine hypotension.","C":"Incorrect. Pushing before full dilation causes cervical oedema and does not relieve back pain.","D":"Incorrect. The pain source is the sacrum, and abdominal cold will not reach it."}}'::jsonb,
 'Physiological Integrity', 'Basic Care and Comfort',
 'Maternity', 'Reproductive', 'Occiput posterior position', 'Back labour comfort measures',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_511035', 'MCQ',
 'The fetal head is born but retracts tightly against the perineum and the shoulders do not deliver with the next contraction. Which action should the nurse take FIRST?',
 'Retraction of the head against the perineum is the turtle sign of shoulder dystocia, an obstruction of the anterior shoulder behind the symphysis pubis. The first manoeuvre is McRoberts: sharply flexing the maternal thighs onto the abdomen, which rotates the symphysis pubis upwards and flattens the sacrum, frequently freeing the shoulder on its own. Suprapubic pressure applied by a second person is added if McRoberts alone does not succeed.',
 '{"options":[{"id":"A","text":"Sharply flex the maternal thighs onto the abdomen"},{"id":"B","text":"Apply firm pressure to the uterine fundus"},{"id":"C","text":"Ask the client to push harder with the next contraction"},{"id":"D","text":"Prepare the client for an immediate caesarean birth"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. The McRoberts manoeuvre rotates the symphysis pubis and frees the impacted shoulder in most cases.","B":"Incorrect. Fundal pressure drives the shoulder harder against the symphysis and risks uterine rupture.","C":"Incorrect. Harder pushing against a fixed obstruction increases fetal injury without freeing the shoulder.","D":"Incorrect. The head is already born, so caesarean birth is not the immediate answer."}}'::jsonb,
 'Safe and Effective Care Environment', 'Management of Care',
 'Maternity', 'Reproductive', 'Shoulder dystocia', 'First manoeuvre',
 'Hard', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_511036', 'SATA',
 'During a shoulder dystocia, which actions are CONTRAINDICATED? Select all that apply.',
 'The manoeuvres that help in shoulder dystocia change the shape of the maternal pelvis or move the fetal shoulders; the ones that harm push the fetus harder against the obstruction. Fundal pressure and forceful traction on the fetal head both drive the anterior shoulder further behind the symphysis and are the classic causes of brachial plexus injury and uterine rupture. Continued unsupported maternal pushing has the same effect and wastes the seconds in which repositioning could work.',
 '{"options":[{"id":"A","text":"Applying pressure to the uterine fundus"},{"id":"B","text":"Applying suprapubic pressure"},{"id":"C","text":"Continuing strong maternal pushing without any repositioning"},{"id":"D","text":"Flexing the maternal thighs sharply onto the abdomen"},{"id":"E","text":"Pulling forcefully on the fetal head"},{"id":"F","text":"Calling for additional help immediately"}]}'::jsonb,
 '{"answers":["A","C","E"],"feedback":{"A":"Correct. Fundal pressure wedges the shoulder more firmly behind the symphysis and can rupture the uterus.","B":"Incorrect. Suprapubic pressure is a recommended manoeuvre that pushes the shoulder into an oblique position.","C":"Correct. Pushing against a fixed obstruction increases fetal injury and delays effective manoeuvres.","D":"Incorrect. This is the McRoberts manoeuvre and is the recommended first step.","E":"Correct. Forceful traction on the head is the classic cause of brachial plexus injury.","F":"Incorrect. Shoulder dystocia is an emergency requiring extra hands immediately."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Maternity', 'Reproductive', 'Shoulder dystocia', 'Contraindicated actions',
 'Hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_511037', 'SATA',
 'A client with a scar from a previous caesarean birth is labouring with an oxytocin infusion. Which findings suggest uterine rupture? Select all that apply.',
 'Uterine rupture is heralded by the sudden loss of what was previously working. The client feels a sharp tearing pain, the contraction pattern stops abruptly, the presenting part loses station because the fetus is no longer held in the pelvis, and fetal parts may become palpable through the abdominal wall as the fetus moves into the peritoneal cavity. Bleeding is often largely concealed, so maternal tachycardia and falling blood pressure appear before any obvious external loss.',
 '{"options":[{"id":"A","text":"Sudden sharp tearing abdominal pain at the height of a contraction"},{"id":"B","text":"Abrupt cessation of contractions"},{"id":"C","text":"Loss of fetal station on vaginal examination"},{"id":"D","text":"Maternal tachycardia with falling blood pressure"},{"id":"E","text":"A firm fundus at the level of the umbilicus with moderate lochia"},{"id":"F","text":"Fetal parts palpable through the abdominal wall"}]}'::jsonb,
 '{"answers":["A","B","C","D","F"],"feedback":{"A":"Correct. A sudden tearing pain at the peak of a contraction is the classic presenting symptom.","B":"Correct. Contractions stop because the myometrium can no longer generate coordinated pressure.","C":"Correct. The presenting part rises because the fetus is no longer being held down in the pelvis.","D":"Correct. Bleeding is largely concealed, so shock appears before visible blood loss.","E":"Incorrect. This describes a normally contracted uterus after birth and is unrelated to rupture during labour.","F":"Correct. Easily palpable fetal parts suggest the fetus has moved outside the uterus."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Maternity', 'Reproductive', 'Uterine rupture', 'Recognition',
 'Very hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_511038', 'MCQ',
 'A nurse suspects uterine rupture in a labouring client. Which action is the PRIORITY?',
 'Uterine rupture is a surgical emergency with a very short window: the fetus must be delivered and the uterus repaired before maternal exsanguination or fetal death. The priority therefore bundles calling the emergency team with immediate preparation for laparotomy and aggressive fluid resuscitation through large-bore access. Interventions that would be reasonable in a stable client, such as catheterisation or analgesia, consume time that this client does not have.',
 '{"options":[{"id":"A","text":"Summon the emergency team and prepare the client for immediate surgery while starting fluid resuscitation"},{"id":"B","text":"Insert a urinary catheter to monitor hourly urine output"},{"id":"C","text":"Give an intravenous opioid bolus for the sudden severe pain"},{"id":"D","text":"Reposition the client to the left lateral position and reassess in 10 minutes"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Survival of mother and fetus depends on immediate surgical delivery and repair with simultaneous volume replacement.","B":"Incorrect. A catheter is inserted as part of theatre preparation but is not what saves the client.","C":"Incorrect. Analgesia does not address catastrophic haemorrhage and may mask deterioration.","D":"Incorrect. Repositioning and waiting delays surgery in a rapidly fatal emergency."}}'::jsonb,
 'Safe and Effective Care Environment', 'Management of Care',
 'Maternity', 'Reproductive', 'Uterine rupture', 'Priority action',
 'Very hard', 'CURATOR_LABEL', 'Evaluate', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_511039', 'MCQ',
 'Moments after artificial rupture of the membranes a client becomes acutely breathless, restless and cyanosed, with a blood pressure of 70/40 mmHg and oozing from her intravenous cannula site. Which action should the nurse take FIRST?',
 'Sudden cardiorespiratory collapse with bleeding from puncture sites during or just after labour suggests amniotic fluid embolism, in which amniotic debris entering the maternal circulation triggers cardiopulmonary collapse and disseminated intravascular coagulation. It is not reversible by any single drug, so survival depends on immediately calling the resuscitation team, securing the airway with high-flow oxygen and preparing for full cardiopulmonary support and urgent delivery.',
 '{"options":[{"id":"A","text":"Call the emergency team and start high-flow oxygen while preparing for resuscitation"},{"id":"B","text":"Send blood for an urgent clotting screen"},{"id":"C","text":"Increase the oxytocin infusion to hasten the birth"},{"id":"D","text":"Sit the client upright and reassess her in 5 minutes"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Amniotic fluid embolism causes cardiorespiratory collapse, so summoning help and supporting oxygenation come before everything else.","B":"Incorrect. Clotting studies are needed but must not delay resuscitation.","C":"Incorrect. Increasing oxytocin in a collapsing client is unsafe and does not treat the embolism.","D":"Incorrect. Repositioning and waiting are inadequate for a client in cardiovascular collapse."}}'::jsonb,
 'Safe and Effective Care Environment', 'Management of Care',
 'Maternity', 'Multisystem', 'Amniotic fluid embolism', 'Recognition and first action',
 'Very hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_511040', 'MCQ',
 'Shortly after being laid flat on her back for an examination, a labouring client becomes pale, dizzy and nauseated, and her blood pressure falls. Which action should the nurse take?',
 'In the supine position the heavy pregnant uterus compresses the inferior vena cava, so venous return, cardiac output and blood pressure all fall - supine hypotensive syndrome. Turning the client onto her side, or wedging one hip, lifts the uterus off the vessel and reverses the problem within moments, which is why side-lying is the default position for any unwell pregnant client. The same manoeuvre also improves uterine blood flow to the fetus.',
 '{"options":[{"id":"A","text":"Turn the client onto her left side"},{"id":"B","text":"Raise the head of the bed to 90 degrees"},{"id":"C","text":"Administer an antiemetic as prescribed"},{"id":"D","text":"Ask the client to take slow deep breaths while remaining supine"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Side-lying lifts the uterus off the inferior vena cava and restores venous return and blood pressure.","B":"Incorrect. Sitting upright does not relieve compression of the vena cava by the uterus.","C":"Incorrect. The nausea is a symptom of hypotension and settles once the position is corrected.","D":"Incorrect. Remaining supine allows the compression, and therefore the hypotension, to continue."}}'::jsonb,
 'Physiological Integrity', 'Basic Care and Comfort',
 'Maternity', 'Multisystem', 'Supine hypotensive syndrome', 'Positioning',
 'Very easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728');

INSERT INTO nclex_bank_items (
  item_id, question_type, stem, rationale, content, correct,
  client_needs_category, client_needs_subcategory, nursing_subject, body_system,
  topic, subtopic, difficulty, difficulty_source, bloom_level, tags,
  marks, is_published, is_builder_visible, is_free_sample, cat_pool, batch_id
) VALUES
('NCLEX_MMR_511041', 'MATRIX_MR',
 'A client has been labouring for 20 hours with ruptured membranes. For each finding, select all of the statements that apply. Each finding has at least one.',
 'Chorioamnionitis is infection of the amniotic fluid and membranes, and its risk rises with every hour that the membranes stay open and with every vaginal examination. Maternal fever, foul-smelling fluid, uterine tenderness between contractions and fetal tachycardia are the cardinal features, and each is a reason to inform the provider so that antibiotics can be started and birth expedited. Clear, odourless fluid draining after rupture is simply the expected finding.',
 '{"rows":[{"id":"r1","text":"Maternal temperature of 38.6 degrees C"},{"id":"r2","text":"Foul-smelling amniotic fluid"},{"id":"r3","text":"Clear odourless fluid continuing to drain"},{"id":"r4","text":"Fetal heart rate baseline of 180 beats per minute"},{"id":"r5","text":"Uterine tenderness that persists between contractions"}],"columns":[{"id":"c1","text":"Suggests chorioamnionitis"},{"id":"c2","text":"Requires the nurse to notify the provider"},{"id":"c3","text":"Expected after rupture of membranes"}],"row_label":"Finding"}'::jsonb,
 '{"cells":{"r1":["c1","c2"],"r2":["c1","c2"],"r3":["c3"],"r4":["c1","c2"],"r5":["c1","c2"]},"feedback":{}}'::jsonb,
 'Safe and Effective Care Environment', 'Safety and Infection Control',
 'Maternity', 'Multisystem', 'Chorioamnionitis', 'Recognition in labour',
 'Hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_511042', 'SATA',
 'A client in established labour suddenly reports constant severe abdominal pain that does not ease between contractions. Which findings would support a diagnosis of placental abruption? Select all that apply.',
 'Abruption is separation of a normally sited placenta, and blood collects behind it. The trapped blood irritates the myometrium, producing a rigid board-like uterus that never fully relaxes, and any blood that escapes has been in contact with the decidua so appears dark rather than bright. Because much of the loss can stay concealed, a rising fundal height and a deteriorating fetal heart tracing may be the only external clues, and the fetal picture worsens as placental surface area is lost.',
 '{"options":[{"id":"A","text":"A rigid board-like uterus that does not relax between contractions"},{"id":"B","text":"Dark red vaginal bleeding"},{"id":"C","text":"Painless bright red vaginal bleeding"},{"id":"D","text":"A rising fundal height"},{"id":"E","text":"Late decelerations with loss of variability"},{"id":"F","text":"A soft non-tender uterus with a reassuring tracing"}]}'::jsonb,
 '{"answers":["A","B","D","E"],"feedback":{"A":"Correct. Blood behind the placenta irritates the myometrium and produces a rigid, tender uterus.","B":"Correct. Blood that has been in contact with the decidua before escaping appears dark red.","C":"Incorrect. Painless bright red bleeding is the classic description of placenta praevia, not abruption.","D":"Correct. A rising fundal height reflects blood collecting behind the placenta.","E":"Correct. Loss of placental surface area produces uteroplacental insufficiency and late decelerations.","F":"Incorrect. A soft uterus with a reassuring tracing argues against abruption."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Maternity', 'Reproductive', 'Placental abruption', 'Recognition during labour',
 'Very hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_511043', 'SATA',
 'A client at 37 weeks is admitted with premature rupture of membranes and is not yet contracting. Which nursing actions are indicated? Select all that apply.',
 'Once the membranes are open, the barrier between the vagina and the uterine cavity is gone, so care is organised around detecting and limiting infection. Vaginal examinations are kept to the minimum because each one carries organisms upwards, temperature is checked at least four-hourly, the draining fluid is inspected for a change in colour or odour, and the fetal heart rate is watched for the tachycardia that often precedes maternal fever. Nothing is inserted into the vagina.',
 '{"options":[{"id":"A","text":"Limit vaginal examinations to the minimum necessary"},{"id":"B","text":"Measure the maternal temperature at least every 2 to 4 hours"},{"id":"C","text":"Record the colour, amount and odour of the draining fluid"},{"id":"D","text":"Monitor the fetal heart rate for tachycardia"},{"id":"E","text":"Perform hourly vaginal examinations to track cervical change"},{"id":"F","text":"Insert a vaginal pack to reduce the loss of fluid"}]}'::jsonb,
 '{"answers":["A","B","C","D"],"feedback":{"A":"Correct. Every vaginal examination carries vaginal organisms towards the uterine cavity.","B":"Correct. Regular temperature measurement is the earliest routine screen for chorioamnionitis.","C":"Correct. Cloudy, green or foul-smelling fluid signals infection or meconium.","D":"Correct. Fetal tachycardia frequently appears before the mother becomes febrile.","E":"Incorrect. Hourly examinations markedly increase infection risk and are unnecessary in a client not yet contracting.","F":"Incorrect. Nothing is inserted into the vagina; a pack would trap organisms against the cervix."}}'::jsonb,
 'Safe and Effective Care Environment', 'Safety and Infection Control',
 'Maternity', 'Reproductive', 'Premature rupture of membranes', 'Nursing care',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SELN_511044', 'SELECT_N',
 'A client at 30 weeks gestation telephones the maternity unit. Which 3 reports indicate possible preterm labour and mean the client should be seen?',
 'Preterm labour often announces itself quietly, which is why clients are taught a specific list of warning signs. Regular tightenings, a constant low backache with pelvic pressure, and a sudden increase in watery or bloody vaginal discharge all suggest that the cervix is changing and need assessment. Normal fetal movement, dependent ankle swelling at the end of the day and occasional tightenings that stop with rest are expected findings in the third trimester.',
 '{"options":[{"id":"A","text":"Regular tightenings every 10 minutes for the past 2 hours"},{"id":"B","text":"A constant dull low backache with a feeling of pelvic pressure"},{"id":"C","text":"A sudden increase in watery vaginal discharge"},{"id":"D","text":"Fetal movements felt about 10 times over 2 hours"},{"id":"E","text":"Mild ankle swelling at the end of the day that settles overnight"},{"id":"F","text":"Occasional painless irregular tightenings that stop with rest"}],"select_count":3}'::jsonb,
 '{"answers":["A","B","C"],"feedback":{"A":"Correct. Regular tightenings before 37 weeks may be preterm labour and require assessment.","B":"Correct. Constant low backache with pelvic pressure is a recognised warning sign of preterm labour.","C":"Correct. A sudden increase in watery discharge may be ruptured membranes.","D":"Incorrect. This is reassuring fetal activity.","E":"Incorrect. Dependent oedema that resolves overnight is a normal third-trimester finding.","F":"Incorrect. Irregular tightenings that stop with rest are Braxton Hicks contractions."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Maternity', 'Reproductive', 'Preterm labour', 'Warning signs',
 'Medium', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_511045', 'MCQ',
 'A client in preterm labour at 30 weeks is prescribed betamethasone and asks the nurse what it is for. Which explanation is correct?',
 'Betamethasone is an antenatal corticosteroid given to accelerate fetal lung maturity by stimulating surfactant production, which reduces the risk of respiratory distress syndrome, intraventricular haemorrhage and neonatal death. It works over about 24 to 48 hours, which is why tocolytics are sometimes used alongside it to buy time. It has no tocolytic, antibiotic or analgesic action of its own.',
 '{"options":[{"id":"A","text":"It helps the lungs of the baby to mature before birth"},{"id":"B","text":"It stops the contractions immediately"},{"id":"C","text":"It prevents infection now that the membranes have ruptured"},{"id":"D","text":"It reduces the pain of the contractions"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Betamethasone stimulates fetal surfactant production and reduces respiratory distress syndrome.","B":"Incorrect. Stopping contractions is the role of a tocolytic, not a corticosteroid.","C":"Incorrect. Infection is prevented with antibiotics, not corticosteroids.","D":"Incorrect. Betamethasone has no analgesic effect."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Maternity', 'Reproductive', 'Betamethasone', 'Purpose in preterm labour',
 'Very easy', 'CURATOR_LABEL', 'Understand', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_511046', 'MCQ',
 'A client in preterm labour at 31 weeks says tearfully that she must have done something wrong and that her baby is coming early because of her. Which response by the nurse is most therapeutic?',
 'Self-blame is a common reaction to preterm labour and is rarely relieved by facts alone. Reflecting the feeling back and inviting the client to say more acknowledges the emotion, keeps the conversation open and gives the nurse the information needed to correct any specific misunderstanding. False reassurance, dismissal and probing for a cause all close the conversation down and can deepen the guilt.',
 '{"options":[{"id":"A","text":"You sound as though you are blaming yourself. Tell me more about what you are thinking."},{"id":"B","text":"Do not worry, babies born at 31 weeks nearly always do well."},{"id":"C","text":"There is no point upsetting yourself now, it will not change anything."},{"id":"D","text":"What do you think you did that caused this?"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Reflecting the feeling and inviting elaboration acknowledges the emotion and opens the conversation.","B":"Incorrect. This offers false reassurance and dismisses the feeling rather than exploring it.","C":"Incorrect. Telling a distressed client not to be upset is dismissive and blocks communication.","D":"Incorrect. This question implies that the client did cause the preterm labour and reinforces the guilt."}}'::jsonb,
 'Psychosocial Integrity', 'Psychosocial Integrity',
 'Maternity', 'Reproductive', 'Preterm labour', 'Therapeutic communication',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_511047', 'MCQ',
 'A multiparous client is 9 cm dilated with contractions every 2 minutes and asks for an intravenous opioid. The midwife expects birth within the hour. Which response by the nurse is correct?',
 'Systemic opioids cross the placenta freely, and the newborn clears them far more slowly than the mother does. Given within about an hour of birth, the peak fetal drug level coincides with delivery, so the baby is born sedated with depressed respirations and poor feeding. For that reason opioids are given earlier in labour, and naloxone plus resuscitation equipment is kept available whenever an opioid has been given close to birth.',
 '{"options":[{"id":"A","text":"Systemic opioids are withheld this close to birth because they can depress the respirations of the newborn"},{"id":"B","text":"Systemic opioids are safest when they are given at full dilation"},{"id":"C","text":"The opioid will be given now because pain relief may be requested at any stage"},{"id":"D","text":"Opioids given during labour do not cross the placenta"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. The peak fetal drug level would coincide with birth, producing a sedated newborn with depressed respirations.","B":"Incorrect. Full dilation is the point at which systemic opioids become least safe for the newborn.","C":"Incorrect. Pain relief is offered, but the timing must protect the newborn; other options remain available.","D":"Incorrect. Opioids cross the placenta readily, which is precisely the problem."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Maternity', 'Reproductive', 'Systemic opioid analgesia', 'Timing relative to birth',
 'Easy', 'CURATOR_LABEL', 'Understand', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_511048', 'SATA',
 'A client in the active phase has requested an epidural. Which nursing actions should be completed before the epidural is sited? Select all that apply.',
 'The predictable complication of an epidural is hypotension, caused by sympathetic blockade and consequent vasodilation, so a fluid preload is given to fill the expanded vascular space before the block takes effect. Baseline maternal observations and a fetal heart rate recording provide the comparison against which any post-procedure fall is judged, an empty bladder prevents distension once sensation is lost, and consent plus a recent platelet count must be confirmed before the anaesthetist proceeds.',
 '{"options":[{"id":"A","text":"Give the prescribed intravenous fluid preload"},{"id":"B","text":"Record a baseline blood pressure, pulse and fetal heart rate"},{"id":"C","text":"Ask the client to empty her bladder"},{"id":"D","text":"Confirm that consent has been obtained and that a platelet count is available"},{"id":"E","text":"Lay the client flat on her back for the procedure"},{"id":"F","text":"Withhold all oral fluids for 8 hours beforehand"}]}'::jsonb,
 '{"answers":["A","B","C","D"],"feedback":{"A":"Correct. A fluid preload fills the vascular space that sympathetic blockade is about to dilate.","B":"Correct. Baseline observations give the reference point for detecting hypotension afterwards.","C":"Correct. Sensation of a full bladder is lost after the block, so the bladder is emptied first.","D":"Correct. Consent and a platelet count are required before regional anaesthesia is undertaken.","E":"Incorrect. The client sits or lies on her side for insertion; supine positioning risks aortocaval compression.","F":"Incorrect. Eight hours of fasting is neither required nor safe for a labouring client."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Maternity', 'Reproductive', 'Epidural analgesia', 'Preparation before siting',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_511049', 'MCQ',
 'Ten minutes after an epidural is sited the maternal blood pressure falls from 118/74 to 84/48 mmHg and late decelerations appear on the tracing. Which action should the nurse take FIRST?',
 'Epidural hypotension arises from sympathetic blockade, and the fetus shows it as late decelerations because uterine perfusion depends directly on maternal blood pressure. The first action combines the two measures the nurse can take instantly without a prescription: turning the client onto her side to remove aortocaval compression and opening the intravenous infusion to restore preload. A vasopressor such as ephedrine, oxygen and a call to the anaesthetist follow if the pressure does not recover.',
 '{"options":[{"id":"A","text":"Turn the client onto her left side and increase the rate of the intravenous infusion"},{"id":"B","text":"Administer ephedrine as prescribed"},{"id":"C","text":"Apply oxygen by face mask"},{"id":"D","text":"Notify the anaesthetist"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Repositioning and a fluid bolus can be started immediately and directly reverse the cause of the hypotension.","B":"Incorrect. Ephedrine is given if position and fluid do not restore the blood pressure.","C":"Incorrect. Oxygen supports the fetus but does nothing for maternal blood pressure.","D":"Incorrect. The anaesthetist is informed after the nurse has begun the immediate corrective measures."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Maternity', 'Multisystem', 'Epidural analgesia', 'Hypotension first action',
 'Hard', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MAT_511050', 'MATRIX',
 'A client has had an epidural sited 30 minutes ago. Indicate whether each finding is expected or requires immediate action by the nurse.',
 'Some effects of an epidural are simply the block doing its job: warm numb legs, pressure felt without sharp pain, and a stable blood pressure once the preload has been given. Others signal a complication. A bladder that fills unnoticed can obstruct descent and be injured, a rising temperature may reflect either the block itself or developing chorioamnionitis and must be investigated, and a sensory level rising to the nipple line with breathlessness suggests a high block threatening the respiratory muscles.',
 '{"rows":[{"id":"r1","text":"Blood pressure 108/68 mmHg thirty minutes after siting"},{"id":"r2","text":"The client cannot feel the urge to void and the bladder is palpable above the symphysis"},{"id":"r3","text":"Numbness and warmth of both legs"},{"id":"r4","text":"Maternal temperature has risen to 38.2 degrees C"},{"id":"r5","text":"Loss of sensation up to the nipple line with difficulty breathing"},{"id":"r6","text":"The client reports pressure but no sharp pain with contractions"}],"columns":[{"id":"c1","text":"Expected finding"},{"id":"c2","text":"Requires immediate action"}],"row_label":"Finding"}'::jsonb,
 '{"cells":{"r1":"c1","r2":"c2","r3":"c1","r4":"c2","r5":"c2","r6":"c1"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Maternity', 'Reproductive', 'Epidural analgesia', 'Ongoing monitoring',
 'Medium', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728');

INSERT INTO nclex_bank_items (
  item_id, question_type, stem, rationale, content, correct,
  client_needs_category, client_needs_subcategory, nursing_subject, body_system,
  topic, subtopic, difficulty, difficulty_source, bloom_level, tags,
  marks, is_published, is_builder_visible, is_free_sample, cat_pool, batch_id
) VALUES
('NCLEX_DO_511051', 'DRAG_ORDER',
 'A baby has just been born in a birthing room. Place the immediate care activities in the order in which the nurse should carry them out. One option will not be used.',
 'Immediate newborn care follows the same airway, breathing, circulation logic as any resuscitation, with thermoregulation added because a wet newborn loses heat extremely fast. The airway is cleared first if it is obstructed, the baby is then dried and placed skin to skin under warm towels, the 1-minute Apgar score is assigned, the cord is clamped and cut, and identification bands are applied before the baby leaves the room. A bath is delayed until the temperature is stable and is never part of immediate care.',
 '{"slots":[{"id":"s1","target_text":"1st"},{"id":"s2","target_text":"2nd"},{"id":"s3","target_text":"3rd"},{"id":"s4","target_text":"4th"},{"id":"s5","target_text":"5th"}],"tokens":[{"id":"t1","text":"Dry the newborn and place skin to skin under warm towels"},{"id":"t2","text":"Clear the mouth then the nose if the airway is obstructed"},{"id":"t3","text":"Clamp and cut the umbilical cord"},{"id":"t4","text":"Assign the 1-minute Apgar score"},{"id":"t5","text":"Apply matching identification bands to the newborn and the mother"},{"id":"t6","text":"Give the newborn a full bath at the bedside"}]}'::jsonb,
 '{"slots":{"s1":"t2","s2":"t1","s3":"t4","s4":"t3","s5":"t5"}}'::jsonb,
 'Safe and Effective Care Environment', 'Management of Care',
 'Maternity', 'Reproductive', 'Immediate care at birth', 'Order of activities',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_511052', 'MCQ',
 'Immediately after birth the nurse inspects the cut end of the umbilical cord and counts one artery and one vein. Which action is appropriate?',
 'A normal umbilical cord contains three vessels: two arteries carrying deoxygenated blood from the fetus to the placenta, and one larger vein returning oxygenated blood to the fetus. A two-vessel cord, in which one artery is absent, is associated with congenital renal and cardiac anomalies, so it must be reported and documented and the newborn assessed further. Counting the vessels takes seconds and is part of routine care at every birth.',
 '{"options":[{"id":"A","text":"Report the finding, because a normal cord has two arteries and one vein and a single artery is associated with congenital anomalies"},{"id":"B","text":"Document a normal three-vessel cord"},{"id":"C","text":"Take no action, because two vessels are normal in a term newborn"},{"id":"D","text":"Reclamp the cord closer to the abdominal wall"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. A two-vessel cord is abnormal and is associated with renal and cardiac anomalies that require further assessment.","B":"Incorrect. Only two vessels were counted, so this documentation would be inaccurate.","C":"Incorrect. Three vessels, not two, are normal in a term newborn.","D":"Incorrect. Reclamping does not change the number of vessels and is unnecessary."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Maternity', 'Reproductive', 'Umbilical cord', 'Three-vessel cord',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_511053', 'SATA',
 'The nurse inspects the placenta and membranes after the third stage of labour. Which findings should be reported to the obstetrician? Select all that apply.',
 'Inspecting the placenta is a haemorrhage-prevention measure, not a formality. Retained tissue keeps the uterus from contracting down, so a missing cotyledon or ragged incomplete membranes must be reported before the client is transferred out of the birthing room. A foul odour suggests chorioamnionitis, and an adherent clot with an overlying crater on the maternal surface indicates that an abruption occurred. A lobed dark red maternal surface and a three-vessel cord are the normal findings.',
 '{"options":[{"id":"A","text":"A cotyledon appears to be missing from the maternal surface"},{"id":"B","text":"The membranes are ragged and appear incomplete"},{"id":"C","text":"The cord contains two arteries and one vein"},{"id":"D","text":"The placenta has a foul odour"},{"id":"E","text":"The maternal surface is dark red and divided into lobes"},{"id":"F","text":"An adherent clot with an overlying crater is seen on the maternal surface"}]}'::jsonb,
 '{"answers":["A","B","D","F"],"feedback":{"A":"Correct. A missing cotyledon means placental tissue has been retained, which prevents the uterus contracting and causes haemorrhage.","B":"Correct. Ragged incomplete membranes suggest retained fragments and infection risk.","C":"Incorrect. Two arteries and one vein is the normal three-vessel cord.","D":"Correct. A foul odour suggests intra-amniotic infection and requires investigation.","E":"Incorrect. A dark red lobed maternal surface is the expected appearance.","F":"Correct. An adherent clot with a crater beneath it is evidence of placental abruption."}}'::jsonb,
 'Safe and Effective Care Environment', 'Management of Care',
 'Maternity', 'Reproductive', 'Placental inspection', 'Findings to report',
 'Medium', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SELN_511054', 'SELECT_N',
 'A nurse is working on a busy labour ward. Which 3 intrapartum situations should lead the nurse to anticipate an immediate caesarean birth?',
 'Caesarean birth becomes urgent when the fetus cannot be delivered vaginally at all, or when continuing labour is actively dangerous. Complete placenta praevia obstructs the cervical os and bleeds catastrophically with dilation, a transverse lie presents a shoulder that cannot deliver, and a prolapsed cord at 4 cm means birth is nowhere near and the cord is being compressed. An occiput posterior position, early decelerations and a 45-minute second stage in a first labour are all variations of normal.',
 '{"options":[{"id":"A","text":"Complete placenta praevia with active bleeding"},{"id":"B","text":"Transverse lie in established labour"},{"id":"C","text":"A prolapsed umbilical cord with the cervix 4 cm dilated"},{"id":"D","text":"An occiput posterior position at 6 cm dilation"},{"id":"E","text":"Early decelerations at 8 cm dilation"},{"id":"F","text":"A second stage lasting 45 minutes in a primigravida"}],"select_count":3}'::jsonb,
 '{"answers":["A","B","C"],"feedback":{"A":"Correct. A placenta covering the os obstructs birth and bleeds heavily as the cervix dilates.","B":"Correct. A shoulder presentation cannot be delivered vaginally.","C":"Correct. With the cervix only 4 cm dilated, the cord will be compressed long before vaginal birth is possible.","D":"Incorrect. Occiput posterior labours are slower and more painful but usually deliver vaginally.","E":"Incorrect. Early decelerations reflect head compression and are benign.","F":"Incorrect. A second stage of 45 minutes is well within normal limits for a first labour."}}'::jsonb,
 'Safe and Effective Care Environment', 'Management of Care',
 'Maternity', 'Reproductive', 'Caesarean birth', 'Indications',
 'Hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_511055', 'SATA',
 'A client is admitted to the recovery area immediately after an emergency caesarean birth performed under spinal anaesthesia. Which assessments are priorities during the first hour? Select all that apply.',
 'Recovery after caesarean birth combines postoperative and postnatal priorities. Airway and breathing come first, because a spinal block that rises too high can impair the respiratory muscles, so respiratory rate, oxygen saturation and the level of the sensory block are checked repeatedly. Postnatal haemorrhage risk is unchanged by the surgical route, so fundal tone, lochia and the wound dressing are assessed, along with urine output through the catheter and the return of lower limb sensation and movement before any attempt to mobilise.',
 '{"options":[{"id":"A","text":"Respiratory rate, oxygen saturation and the level of the sensory block"},{"id":"B","text":"Fundal tone and height"},{"id":"C","text":"Amount of lochia and the wound dressing for oozing"},{"id":"D","text":"Return of sensation and movement in both legs"},{"id":"E","text":"Urine output through the indwelling catheter"},{"id":"F","text":"Encouraging the client to walk unaided to the toilet"}]}'::jsonb,
 '{"answers":["A","B","C","D","E"],"feedback":{"A":"Correct. A block that rises too high impairs the respiratory muscles, so ventilation is monitored closely.","B":"Correct. Uterine atony and haemorrhage remain a risk after caesarean as after vaginal birth.","C":"Correct. Lochia and the dressing together reveal both uterine and surgical bleeding.","D":"Correct. Sensation and movement must return before the client can safely mobilise.","E":"Correct. Urine output reflects perfusion and detects bladder injury after abdominal surgery.","F":"Incorrect. The client cannot mobilise safely until the block has worn off and stability is confirmed."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Maternity', 'Multisystem', 'Caesarean birth', 'Immediate postoperative priorities',
 'Very hard', 'CURATOR_LABEL', 'Evaluate', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728');
