-- MyNclex bank gap-fill, 2026-07-28
-- Batch: gapfill-20260728
-- Gap 09 — Pharmacology: therapeutic ranges, toxicity and high-alert medication safety
-- item_id block: 540001-540040 (40 items)
-- Type mix: 19 MCQ, 8 SATA, 3 SELECT_N, 4 MATRIX, 2 MATRIX_MR, 2 CLOZE, 1 DRAG_ORDER, 1 TF

INSERT INTO nclex_bank_items (
  item_id, question_type, stem, rationale, content, correct,
  client_needs_category, client_needs_subcategory, nursing_subject, body_system,
  topic, subtopic, difficulty, difficulty_source, bloom_level, tags,
  marks, is_published, is_builder_visible, is_free_sample, cat_pool, batch_id
) VALUES
('NCLEX_MCQ_540001', 'MCQ',
 'A client who has taken lithium carbonate for two years attends the community mental health clinic reporting three days of vomiting and diarrhoea. The nurse notes a new coarse hand tremor and slurred speech. The serum lithium level is 1.9 mEq/L. Which action should the nurse take?',
 'The therapeutic range for lithium is 0.6 to 1.2 mEq/L; levels above 1.5 mEq/L are concerning and levels above 2.0 mEq/L are frankly toxic. Lithium is handled by the kidney in competition with sodium, so any state that depletes sodium and water — vomiting, diarrhoea, sweating, diuretics, a low-salt diet — drives reabsorption and pushes the level up. A coarse tremor, slurred speech and ataxia are toxic effects rather than side effects, so the drug is withheld and the prescriber informed, not simply monitored.',
 '{"options":[{"id":"A","text":"Administer the next scheduled dose and encourage extra oral fluids"},{"id":"B","text":"Withhold the dose, notify the prescriber and keep the client under observation"},{"id":"C","text":"Reassure the client that a coarse tremor is an expected side effect of lithium"},{"id":"D","text":"Advise the client to restrict sodium intake until the tremor settles"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. Giving a further dose when the level is already 1.9 mEq/L with neurological signs will deepen the toxicity.","B":"Correct. A level above 1.5 mEq/L with coarse tremor and slurred speech is toxicity, which requires the dose to be held and the prescriber informed.","C":"Incorrect. A fine tremor is an expected side effect; a coarse tremor is a warning sign of toxicity.","D":"Incorrect. Restricting sodium increases lithium reabsorption and would raise the level further."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential', 'Pharmacology', 'Psychiatric/Mental Health',
 'Lithium', 'Therapeutic and toxic serum levels', 'Hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_540002', 'MCQ',
 'The nurse is preparing to give digoxin 0.25 mg orally to an older adult on a medical ward. The apical pulse, counted for one full minute, is 52 beats per minute. Which action should the nurse take FIRST?',
 'Digoxin slows conduction through the atrioventricular node, so an apical rate below 60 beats per minute in an adult is the standard hold parameter. The pulse must be apical and counted for a full minute, because digoxin can produce a pulse deficit that a radial count would miss. Holding the dose comes before any other step: once the drug is swallowed the decision cannot be undone, whereas informing the prescriber can follow immediately after.',
 '{"options":[{"id":"A","text":"Give the dose and recount the apical pulse in one hour"},{"id":"B","text":"Withhold the digoxin and notify the prescriber"},{"id":"C","text":"Recheck the apical pulse in 15 minutes before deciding"},{"id":"D","text":"Give the dose, because a slow pulse is an expected effect of digoxin"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. Once the dose is given the bradycardia can only worsen; the reassessment happens after the decision to hold.","B":"Correct. An apical rate below 60 beats per minute is the hold parameter, so the dose is withheld and the prescriber informed.","C":"Incorrect. Delaying the decision does not change the current rate and leaves the client without a plan.","D":"Incorrect. Digoxin does slow the rate, but 52 beats per minute crosses the safety threshold and is not simply accepted."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Pharmacology', 'Cardiovascular',
 'Digoxin', 'Apical pulse and hold parameter', 'Very easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_540003', 'MCQ',
 'A client on a cardiology ward takes digoxin daily and has just been started on furosemide. Which laboratory result should the nurse report before the next digoxin dose is due?',
 'Digoxin competes with potassium for the same binding site on the sodium-potassium pump in cardiac muscle. When serum potassium falls, more digoxin binds and toxicity can develop even though the serum digoxin level still reads within the therapeutic 0.5 to 2 ng/mL range. Loop diuretics such as furosemide waste potassium, which is why the pairing is a recognised high-risk combination and potassium is checked before the dose.',
 '{"options":[{"id":"A","text":"Serum potassium 2.8 mEq/L"},{"id":"B","text":"Serum sodium 138 mEq/L"},{"id":"C","text":"Haemoglobin 12.6 g/dL"},{"id":"D","text":"Serum magnesium 2.0 mEq/L"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Hypokalaemia increases digoxin binding at the cardiac cell membrane and can cause toxicity even at a normal serum digoxin level.","B":"Incorrect. A sodium of 138 mEq/L is within normal limits and does not alter digoxin safety.","C":"Incorrect. A haemoglobin of 12.6 g/dL is within normal limits and is not the priority report here.","D":"Incorrect. A magnesium of 2.0 mEq/L is normal; it is a low magnesium that would add to the risk."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential', 'Pharmacology', 'Cardiovascular',
 'Digoxin', 'Hypokalaemia and toxicity risk', 'Easy', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_540004', 'MCQ',
 'A client admitted with a seizure disorder has a serum phenytoin level of 26 mcg/mL. On assessment the nurse finds horizontal nystagmus, an unsteady gait and slurred speech. Which action is the PRIORITY?',
 'The therapeutic range for phenytoin is 10 to 20 mcg/mL. Above 20 mcg/mL the earliest sign is horizontal nystagmus, followed by ataxia and slurred speech; above 30 mcg/mL confusion and decreased level of consciousness appear. These are dose-related toxic effects, so the priority is to stop further drug entering the body and to have the level and the regimen reviewed, rather than to treat the symptoms or write them off as side effects.',
 '{"options":[{"id":"A","text":"Withhold the next phenytoin dose and notify the prescriber"},{"id":"B","text":"Encourage the client to walk in the corridor to improve balance"},{"id":"C","text":"Document the findings as expected side effects of phenytoin"},{"id":"D","text":"Give the dose with a full glass of milk to reduce gastric irritation"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. A level of 26 mcg/mL with nystagmus, ataxia and slurred speech is toxicity, so the dose is held and the prescriber informed.","B":"Incorrect. Walking an ataxic client without support risks a fall and does not address the raised level.","C":"Incorrect. Nystagmus and ataxia are toxic effects, not expected side effects to be simply recorded.","D":"Incorrect. Managing gastric irritation is irrelevant when the level is already above the therapeutic range."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential', 'Pharmacology', 'Neurological',
 'Phenytoin', 'Serum level interpretation', 'Medium', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_540005', 'MCQ',
 'A client receiving a continuous intravenous aminophylline infusion for a severe asthma exacerbation becomes restless and nauseated, and the heart rate rises from 88 to 132 beats per minute. The serum theophylline level is 26 mcg/mL. Which action should the nurse take FIRST?',
 'The therapeutic range for theophylline and aminophylline is 10 to 20 mcg/mL, a narrow window that sits close to the toxic threshold. Above 20 mcg/mL clients develop nausea, restlessness and tachycardia; above 30 mcg/mL ventricular dysrhythmias and seizures can occur. When the toxic agent is running into a vein, the first action is to stop the source, because every further minute of infusion raises the level; notifying the prescriber follows immediately afterwards.',
 '{"options":[{"id":"A","text":"Stop the aminophylline infusion"},{"id":"B","text":"Notify the prescriber and await instructions"},{"id":"C","text":"Administer the prescribed antiemetic for the nausea"},{"id":"D","text":"Halve the infusion rate and continue the infusion"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Stopping the infusion halts further drug entering the circulation and is the first action before escalating.","B":"Incorrect. Notification is essential but comes second; the infusion continues to raise the level while the nurse waits.","C":"Incorrect. Treating the nausea masks a sign of toxicity and leaves the cause running.","D":"Incorrect. A reduced rate still delivers drug to a client whose level is already above the therapeutic range."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Pharmacology', 'Respiratory',
 'Theophylline and aminophylline', 'Toxicity and immediate action', 'Hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_540006', 'MCQ',
 'A client is receiving intravenous vancomycin every 12 hours. The prescriber has requested a trough level. When should the nurse arrange for the blood sample to be taken?',
 'A trough is the lowest concentration in a dosing interval and is drawn immediately before the next scheduled dose, usually within 30 minutes of it. It shows whether the drug is clearing safely between doses, which matters for a narrow therapeutic index agent where too high a trough predicts kidney injury. A peak, by contrast, is timed after administration and its timing depends on the route, so the two samples answer different questions and cannot be substituted for one another.',
 '{"options":[{"id":"A","text":"Immediately before the next scheduled dose"},{"id":"B","text":"Thirty minutes after the infusion has finished"},{"id":"C","text":"Midway between two doses"},{"id":"D","text":"At any convenient time during the shift"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. The trough is the lowest level in the interval and is drawn immediately before the next dose is due.","B":"Incorrect. That timing describes a peak level, not a trough.","C":"Incorrect. A mid-interval sample is neither a peak nor a trough and cannot be interpreted against the reference range.","D":"Incorrect. Untimed samples make the result meaningless, which defeats the purpose of monitoring a narrow therapeutic index drug."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Pharmacology', 'Immune',
 'Peak and trough sampling', 'Trough timing', 'Very easy', 'CURATOR_LABEL', 'Understand', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_540007', 'MCQ',
 'Fifteen minutes into an intravenous vancomycin infusion running over 30 minutes, a client develops flushing and erythema of the face, neck and upper chest with mild itching. Blood pressure is 112/68 mmHg, there is no wheeze and no facial or airway swelling. Which action should the nurse take?',
 'Rapid vancomycin infusion causes direct, non-immune histamine release from mast cells, producing the flushing of the face and trunk sometimes called vancomycin flushing syndrome. It is rate-related, not IgE-mediated, so it settles when the infusion is paused and does not recur if the drug is given more slowly, typically over at least 60 minutes. Recording it as an allergy is a real harm: it removes an antibiotic the client may need for resistant infection later.',
 '{"options":[{"id":"A","text":"Continue at the same rate, since the reaction is harmless"},{"id":"B","text":"Stop the infusion and, once the symptoms settle, resume it over at least 60 minutes as prescribed"},{"id":"C","text":"Record a vancomycin allergy in the notes and withhold all future doses"},{"id":"D","text":"Administer intramuscular adrenaline immediately"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. Continuing at the same rate prolongs the histamine release and can lead to hypotension.","B":"Correct. The reaction is rate-related histamine release, so pausing and then infusing more slowly resolves it without losing the antibiotic.","C":"Incorrect. Labelling a rate-related reaction as an allergy wrongly removes a needed antibiotic from future options.","D":"Incorrect. Adrenaline is reserved for anaphylaxis, which involves airway swelling, wheeze or hypotension; none are present here."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Pharmacology', 'Immune',
 'Vancomycin', 'Infusion reaction versus allergy', 'Hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_540008', 'MCQ',
 'A client has received intravenous gentamicin for five days. The serum creatinine has risen from 0.8 mg/dL on admission to 2.2 mg/dL, and the urine output over the last 12 hours is 180 mL. Which action should the nurse take?',
 'Aminoglycosides accumulate in the proximal renal tubular cells, and nephrotoxicity typically declares itself after several days of therapy as a rising creatinine with a falling urine output. Because the drug is cleared by the kidney, a failing kidney raises the drug level, which in turn worsens the kidney injury — a loop that only breaks if dosing stops. The nurse therefore withholds the dose and escalates so that levels, creatinine clearance and the regimen can be reviewed.',
 '{"options":[{"id":"A","text":"Withhold the next dose and notify the prescriber"},{"id":"B","text":"Give the dose and encourage an increased oral fluid intake"},{"id":"C","text":"Request a trough level after the next three doses have been given"},{"id":"D","text":"Document the results as an expected response to gentamicin"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. A creatinine rise with oliguria signals aminoglycoside nephrotoxicity, so the dose is held and the prescriber informed.","B":"Incorrect. Fluids alone do not clear an accumulating nephrotoxic drug and the dose would deepen the injury.","C":"Incorrect. Waiting for three more doses exposes the client to further harm before anyone acts.","D":"Incorrect. Nephrotoxicity is an adverse toxic effect, not an expected response to be recorded and ignored."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential', 'Pharmacology', 'Genitourinary',
 'Aminoglycosides', 'Nephrotoxicity monitoring', 'Medium', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_540009', 'MCQ',
 'A client with hepatic encephalopathy is prescribed oral neomycin. A student nurse asks why an aminoglycoside is being given by mouth when this class is normally reserved for serious resistant infection given intravenously. Which response by the nurse is correct?',
 'Aminoglycosides are almost entirely unabsorbed from the gastrointestinal tract, which is exactly why they must be given parenterally to treat a systemic infection. That same poor absorption is turned into an advantage when the target is inside the bowel: oral neomycin stays in the gut lumen and suppresses the urease-producing bacteria that generate ammonia, and it is used on the same principle for preoperative bowel decontamination. Because so little reaches the bloodstream, the usual systemic ototoxic and nephrotoxic risks are much reduced, although they are not abolished in prolonged use or renal failure.',
 '{"options":[{"id":"A","text":"Oral neomycin is poorly absorbed from the gut, so it acts locally to reduce the ammonia-producing bacteria in the bowel"},{"id":"B","text":"Oral neomycin is absorbed better than the intravenous form and reaches the liver more quickly"},{"id":"C","text":"Oral neomycin is given to treat an infection of the liver tissue itself"},{"id":"D","text":"Oral neomycin protects the kidneys from the effects of a raised ammonia level"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Poor gastrointestinal absorption keeps the drug in the bowel lumen, where it suppresses the ammonia-producing flora.","B":"Incorrect. Aminoglycosides are very poorly absorbed orally, which is why systemic infection requires the parenteral route.","C":"Incorrect. Hepatic encephalopathy is not a liver infection; the target is the gut flora that generate ammonia.","D":"Incorrect. Neomycin is itself nephrotoxic when absorbed; it does not protect the kidney."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Pharmacology', 'Gastrointestinal',
 'Aminoglycosides', 'Oral route for a local gut effect', 'Very hard', 'CURATOR_LABEL', 'Understand', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_540010', 'MCQ',
 'A heparin infusion is prepared as 25,000 units in 500 mL of 0.9% sodium chloride. The prescription is for 1,100 units per hour. At how many mL per hour should the nurse set the infusion pump?',
 'Work out the concentration first, then the volume needed. 25,000 units divided by 500 mL gives 50 units in every mL. The prescribed 1,100 units per hour divided by 50 units per mL gives 22 mL per hour. Because heparin is a high-alert medication, this calculation is one of the values a second nurse independently repeats before the pump is started.',
 '{"options":[{"id":"A","text":"11 mL per hour"},{"id":"B","text":"22 mL per hour"},{"id":"C","text":"44 mL per hour"},{"id":"D","text":"55 mL per hour"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. 11 mL per hour would deliver only 550 units per hour, half the prescribed dose.","B":"Correct. The bag contains 50 units per mL, and 1,100 divided by 50 gives 22 mL per hour.","C":"Incorrect. 44 mL per hour would deliver 2,200 units per hour, double the prescription.","D":"Incorrect. 55 mL per hour would deliver 2,750 units per hour, a dangerous overdose."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Pharmacology', 'Hematologic',
 'Heparin', 'Infusion rate calculation', 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728');

INSERT INTO nclex_bank_items (
  item_id, question_type, stem, rationale, content, correct,
  client_needs_category, client_needs_subcategory, nursing_subject, body_system,
  topic, subtopic, difficulty, difficulty_source, bloom_level, tags,
  marks, is_published, is_builder_visible, is_free_sample, cat_pool, batch_id
) VALUES
('NCLEX_MCQ_540011', 'MCQ',
 'A client weighing 80 kg is prescribed an intravenous heparin bolus of 60 units/kg before a heparin infusion is started. The vial available contains 1,000 units/mL. How many mL should the nurse draw up? Round to one decimal place.',
 'Weight-based heparin dosing is a two-step calculation: dose first, then volume. 60 units multiplied by 80 kg gives a total of 4,800 units. Dividing 4,800 units by the 1,000 units contained in each mL gives 4.8 mL. A misplaced decimal in heparin dosing is one of the classic high-alert medication errors, which is why the dose, the concentration and the final volume are all verified by an independent second check.',
 '{"options":[{"id":"A","text":"0.48 mL"},{"id":"B","text":"4.8 mL"},{"id":"C","text":"8.4 mL"},{"id":"D","text":"48 mL"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. 0.48 mL is one tenth of the dose and reflects a misplaced decimal point.","B":"Correct. 60 units multiplied by 80 kg is 4,800 units, and 4,800 divided by 1,000 units per mL is 4.8 mL.","C":"Incorrect. 8.4 mL reverses the digits of the correct answer and would deliver 8,400 units.","D":"Incorrect. 48 mL is ten times the required dose and would deliver 48,000 units."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Pharmacology', 'Hematologic',
 'Heparin', 'Weight-based bolus calculation', 'Hard', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_540012', 'MCQ',
 'A client who takes warfarin for atrial fibrillation attends the anticoagulation clinic. The INR is 6.8. There is no bruising, no bleeding and the vital signs are normal. Which action should the nurse take?',
 'For atrial fibrillation the usual INR target is 2.0 to 3.0, rising to 2.5 to 3.5 for a mechanical heart valve. The response to a rising INR is graded: a mildly raised result may only need a dose adjustment, above about 5.0 with no bleeding the drug is withheld and the INR rechecked, and very high results attract oral vitamin K. Major bleeding needs intravenous vitamin K with prothrombin complex concentrate. Protamine sulfate has no role here because it reverses heparin, not warfarin.',
 '{"options":[{"id":"A","text":"Withhold the warfarin and notify the prescriber"},{"id":"B","text":"Give the usual dose, since there is no bleeding"},{"id":"C","text":"Administer protamine sulfate"},{"id":"D","text":"Advise the client to eat extra green leafy vegetables to bring the INR down today"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. An INR of 6.8 is far above target, so the dose is withheld and the prescriber informed for a decision on vitamin K and rechecking.","B":"Incorrect. The absence of bleeding does not make the result safe; the client is at high risk of a bleed.","C":"Incorrect. Protamine sulfate reverses heparin; warfarin is reversed with vitamin K.","D":"Incorrect. Dietary vitamin K is kept steady rather than used as an emergency correction, and it will not act quickly enough."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential', 'Pharmacology', 'Hematologic',
 'Warfarin', 'INR interpretation', 'Medium', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_540013', 'MCQ',
 'A child on the paediatric ward is prescribed digoxin 0.125 mg orally. The elixir supplied contains 0.05 mg/mL. How many mL should the nurse draw up?',
 'Divide the prescribed dose by the strength on hand: 0.125 mg divided by 0.05 mg/mL gives 2.5 mL. Paediatric digoxin is measured in an oral syringe rather than a spoon because the therapeutic window is narrow and small volume errors matter. Two nurses independently verify paediatric digoxin doses in most organisations for the same reason.',
 '{"options":[{"id":"A","text":"1.5 mL"},{"id":"B","text":"2.5 mL"},{"id":"C","text":"3.5 mL"},{"id":"D","text":"0.25 mL"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. 1.5 mL would deliver 0.075 mg, less than prescribed.","B":"Correct. 0.125 mg divided by 0.05 mg/mL equals 2.5 mL.","C":"Incorrect. 3.5 mL would deliver 0.175 mg, more than prescribed.","D":"Incorrect. 0.25 mL reflects a misplaced decimal and would deliver only 0.0125 mg."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Pharmacology', 'Cardiovascular',
 'Digoxin', 'Oral dose calculation', 'Very easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_540014', 'MCQ',
 'A client receives NPH (isophane) insulin subcutaneously at 0730. NPH has an onset of 1 to 2 hours, a peak of 6 to 12 hours and a duration of 14 to 24 hours. During which period should the nurse be most alert for hypoglycaemia?',
 'Hypoglycaemia is most likely at the peak of insulin action, so the nursing question is always arithmetic: administration time plus the peak window. Adding 6 to 12 hours to 0730 gives 1330 to 1930, which spans the late afternoon and early evening. Knowing this window tells the nurse when to check the capillary glucose, when a snack matters most and why a missed evening meal after morning NPH is a genuine hazard.',
 '{"options":[{"id":"A","text":"0830 to 0930"},{"id":"B","text":"1030 to 1230"},{"id":"C","text":"1330 to 1930"},{"id":"D","text":"2130 to 0730 the following morning"}]}'::jsonb,
 '{"answer":"C","feedback":{"A":"Incorrect. That period is around the onset of action, when the glucose-lowering effect is only beginning.","B":"Incorrect. That window fits a regular insulin peak of 2 to 4 hours, not NPH.","C":"Correct. Adding the 6 to 12 hour peak to a 0730 dose gives 1330 to 1930.","D":"Incorrect. That period falls in the tail of the duration, where the effect is waning rather than peaking."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Pharmacology', 'Endocrine',
 'Insulin', 'Peak action and hypoglycaemia timing', 'Very hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_540015', 'MCQ',
 'A newly qualified nurse reads a written prescription that states: potassium chloride 20 mEq intravenous push. Which action should the nurse take?',
 'Concentrated potassium chloride is never given by intravenous push under any circumstance, because a rapid rise in serum potassium stops the heart in asystole. It must always be diluted and infused through a rate-controlled pump. A nurse who recognises an unsafe prescription is accountable for not carrying it out: the prescription is withheld and the prescriber contacted for clarification, and the concern is documented.',
 '{"options":[{"id":"A","text":"Administer it slowly over five minutes while watching the monitor"},{"id":"B","text":"Withhold the drug and contact the prescriber to clarify the prescription"},{"id":"C","text":"Ask a second nurse to give it so that the check is shared"},{"id":"D","text":"Dilute it in 10 mL of sodium chloride and give it over 10 minutes"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. Slowing a push does not make it safe; potassium chloride is never pushed intravenously.","B":"Correct. The nurse withholds an unsafe prescription and contacts the prescriber for clarification.","C":"Incorrect. Sharing an unsafe act does not make it safe, and both nurses would be accountable.","D":"Incorrect. Bolus dilution is still a push; potassium requires a large diluent volume through a rate-controlled pump."}}'::jsonb,
 'Safe and Effective Care Environment', 'Management of Care', 'Pharmacology', 'Cardiovascular',
 'Potassium chloride', 'Verifying a questionable prescription', 'Very easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_540016', 'MCQ',
 'A client is prescribed potassium chloride 40 mEq in 250 mL of 0.9% sodium chloride to infuse over 4 hours through a peripheral cannula. At how many mL per hour should the pump be set, and does the delivery stay within the usual peripheral maximum of 10 mEq per hour?',
 'Two calculations are needed. The volume rate is 250 mL divided by 4 hours, which is 62.5 mL per hour. The potassium delivery is 40 mEq divided by 4 hours, which is 10 mEq per hour — exactly at the usual peripheral ceiling. Nurses check both numbers, because a pump set correctly for volume can still deliver potassium faster than the heart tolerates if the bag concentration is high.',
 '{"options":[{"id":"A","text":"62.5 mL per hour, delivering 10 mEq per hour, which is at the usual maximum"},{"id":"B","text":"62.5 mL per hour, delivering 20 mEq per hour, which exceeds the usual maximum"},{"id":"C","text":"125 mL per hour, delivering 10 mEq per hour, which is within the usual maximum"},{"id":"D","text":"41.7 mL per hour, delivering 6.7 mEq per hour, which is within the usual maximum"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. 250 divided by 4 is 62.5 mL per hour, and 40 mEq divided by 4 hours is 10 mEq per hour, at the usual peripheral ceiling.","B":"Incorrect. The volume rate is right but 40 mEq over 4 hours is 10 mEq per hour, not 20.","C":"Incorrect. 125 mL per hour would empty the bag in 2 hours and deliver 20 mEq per hour.","D":"Incorrect. 41.7 mL per hour corresponds to a 6-hour infusion, not the 4 hours prescribed."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Pharmacology', 'Cardiovascular',
 'Potassium chloride', 'Infusion rate calculation', 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_540017', 'MCQ',
 'A client with acute kidney injury has a serum potassium of 7.2 mEq/L. The cardiac monitor shows tall peaked T waves and a widening QRS complex. Intravenous calcium gluconate, intravenous insulin with dextrose, nebulised salbutamol and oral sodium polystyrene sulfonate are all prescribed. Which should the nurse administer FIRST?',
 'Severe hyperkalaemia is managed in three stages: stabilise the myocardium, shift potassium into the cells, then remove it from the body. Calcium gluconate does not lower the potassium at all, but it raises the threshold for cardiac cell depolarisation within minutes and so protects against ventricular fibrillation while the other measures take effect. Insulin with dextrose and nebulised salbutamol shift potassium intracellularly over 15 to 30 minutes, and a binding resin or dialysis removes it over hours.',
 '{"options":[{"id":"A","text":"Intravenous calcium gluconate"},{"id":"B","text":"Intravenous insulin with dextrose"},{"id":"C","text":"Oral sodium polystyrene sulfonate"},{"id":"D","text":"Nebulised salbutamol"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Calcium gluconate stabilises the myocardium within minutes and protects against a lethal dysrhythmia while the potassium is shifted and removed.","B":"Incorrect. Insulin with dextrose is essential but takes 15 to 30 minutes to shift potassium and does not protect the heart immediately.","C":"Incorrect. A binding resin removes potassium through the gut over hours and is the slowest of the options.","D":"Incorrect. Nebulised salbutamol shifts potassium intracellularly but is an adjunct, not the immediate cardiac protection."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Pharmacology', 'Cardiovascular',
 'Hyperkalaemia', 'Emergency treatment sequence', 'Very hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_540018', 'MCQ',
 'A client admitted after taking an excess of digoxin tablets has a serum digoxin level of 4.6 ng/mL, a serum potassium of 6.1 mEq/L and third-degree heart block on the cardiac monitor. Which prescription should the nurse anticipate?',
 'The therapeutic range for digoxin is 0.5 to 2 ng/mL. A level above 2 ng/mL accompanied by a life-threatening dysrhythmia or by hyperkalaemia is the recognised indication for digoxin immune Fab, an antibody fragment that binds digoxin and removes it from the tissue receptors. Hyperkalaemia in digoxin poisoning reflects a poisoned sodium-potassium pump and marks a poor prognosis, so it is treated by giving the antidote rather than by giving calcium, which can worsen the dysrhythmia.',
 '{"options":[{"id":"A","text":"Digoxin immune Fab"},{"id":"B","text":"A further loading dose of digoxin"},{"id":"C","text":"Protamine sulfate"},{"id":"D","text":"Flumazenil"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Digoxin immune Fab binds digoxin and is indicated for a toxic level with a life-threatening dysrhythmia or hyperkalaemia.","B":"Incorrect. More digoxin would deepen the block and the hyperkalaemia.","C":"Incorrect. Protamine sulfate reverses heparin and has no effect on digoxin.","D":"Incorrect. Flumazenil reverses benzodiazepines and has no effect on digoxin."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Pharmacology', 'Cardiovascular',
 'Digoxin immune Fab', 'Indication for the antidote', 'Medium', 'CURATOR_LABEL', 'Understand', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_540019', 'MCQ',
 'A client weighing 68 kg is prescribed gentamicin 5 mg/kg intravenously once daily. The vial contains 40 mg/mL. How many mL should the nurse withdraw? Round to one decimal place.',
 'Calculate the dose, then the volume. 5 mg multiplied by 68 kg gives 340 mg, and 340 mg divided by 40 mg/mL gives 8.5 mL. Once-daily aminoglycoside dosing relies on a high peak to kill the organism and a long low trough to let the kidney and inner ear recover, so both the dose and the sampling times have to be exact.',
 '{"options":[{"id":"A","text":"3.4 mL"},{"id":"B","text":"8.5 mL"},{"id":"C","text":"13.6 mL"},{"id":"D","text":"17 mL"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. 3.4 mL delivers 136 mg, well under the prescribed dose.","B":"Correct. 5 mg/kg for 68 kg is 340 mg, and 340 divided by 40 mg/mL is 8.5 mL.","C":"Incorrect. 13.6 mL delivers 544 mg and reflects dividing by the wrong strength.","D":"Incorrect. 17 mL delivers 680 mg, double the prescribed dose."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Pharmacology', 'Immune',
 'Aminoglycosides', 'Weight-based dose calculation', 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_540020', 'SATA',
 'A client attends a community clinic for a routine lithium review. Which findings should the nurse report as early indicators of lithium toxicity? Select all that apply.',
 'Distinguishing a side effect from a toxic effect changes the nursing response entirely. A fine tremor, mild polyuria and thirst are common side effects that are taught about and monitored while the drug continues. A coarse tremor, slurred speech, ataxia and persistent vomiting or diarrhoea signal a level above the therapeutic 0.6 to 1.2 mEq/L range and require the dose to be withheld and the prescriber informed. Gastrointestinal losses are doubly important because they also cause the level to climb.',
 '{"options":[{"id":"A","text":"A new coarse hand tremor"},{"id":"B","text":"Persistent vomiting and diarrhoea"},{"id":"C","text":"A fine hand tremor present since the drug was first started"},{"id":"D","text":"Slurred speech"},{"id":"E","text":"Increased thirst and urination present for several months"},{"id":"F","text":"A new unsteady gait"},{"id":"G","text":"A metallic taste noticed during the first week of treatment"}]}'::jsonb,
 '{"answers":["A","B","D","F"],"feedback":{"A":"Correct. A coarse tremor is a hallmark of a rising lithium level, unlike the fine tremor of ordinary therapy.","B":"Correct. Vomiting and diarrhoea are both toxic effects and a cause of further sodium and water loss that raises the level.","C":"Incorrect. A long-standing fine tremor is a recognised side effect that is monitored rather than escalated.","D":"Correct. Slurred speech is a neurological toxic effect requiring the dose to be withheld.","E":"Incorrect. Polyuria and thirst are common side effects of lithium and, when stable, do not indicate toxicity.","F":"Correct. New ataxia indicates central nervous system toxicity and needs urgent review.","G":"Incorrect. A transient metallic taste early in treatment is a benign side effect."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential', 'Pharmacology', 'Psychiatric/Mental Health',
 'Lithium', 'Side effect versus toxic effect', 'Medium', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728');

INSERT INTO nclex_bank_items (
  item_id, question_type, stem, rationale, content, correct,
  client_needs_category, client_needs_subcategory, nursing_subject, body_system,
  topic, subtopic, difficulty, difficulty_source, bloom_level, tags,
  marks, is_published, is_builder_visible, is_free_sample, cat_pool, batch_id
) VALUES
('NCLEX_SATA_540021', 'SATA',
 'A healthcare assistant reports several observations about an older adult who takes digoxin. Which findings should the nurse recognise as early manifestations of digoxin toxicity? Select all that apply.',
 'Digoxin toxicity announces itself through the gut, the eyes and the brain long before the rhythm collapses. Anorexia and nausea are usually the earliest complaints, visual disturbance such as blurring or yellow-green halos around lights is highly characteristic, and new confusion is a common presentation in older adults. Recognising this cluster prompts the nurse to withhold the dose, check the serum digoxin level and the potassium, and inform the prescriber.',
 '{"options":[{"id":"A","text":"Anorexia and nausea"},{"id":"B","text":"Yellow-green halos around lights"},{"id":"C","text":"An increase in urine output"},{"id":"D","text":"New onset confusion"},{"id":"E","text":"A blood pressure of 128/78 mmHg"},{"id":"F","text":"Blurred vision"}]}'::jsonb,
 '{"answers":["A","B","D","F"],"feedback":{"A":"Correct. Loss of appetite and nausea are typically the earliest features of digoxin toxicity.","B":"Correct. Yellow-green halos are a classic visual disturbance of digoxin excess.","C":"Incorrect. A rise in urine output reflects an improving cardiac output, which is a therapeutic response.","D":"Correct. New confusion is a frequent presentation of digoxin toxicity in older adults.","E":"Incorrect. That blood pressure is within normal limits and is not a toxicity sign.","F":"Correct. Blurred vision is part of the visual disturbance seen with a raised digoxin level."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential', 'Pharmacology', 'Cardiovascular',
 'Digoxin', 'Early toxicity manifestations', 'Easy', 'CURATOR_LABEL', 'Understand', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_540022', 'SATA',
 'A client is receiving intravenous amikacin for a resistant Gram-negative infection. Which findings should the nurse report to the prescriber without delay? Select all that apply.',
 'Aminoglycosides are reserved for serious or resistant infection precisely because their two dose-related toxicities are so damaging. Ototoxicity affects both the cochlear branch, producing tinnitus and high-frequency hearing loss, and the vestibular branch, producing dizziness and unsteadiness, and the hearing loss can be permanent. Nephrotoxicity shows as a rising creatinine, a falling creatinine clearance and reducing urine output. Both are monitored alongside peak and trough levels throughout the course.',
 '{"options":[{"id":"A","text":"Ringing in the ears"},{"id":"B","text":"New unsteadiness when standing with the eyes closed"},{"id":"C","text":"A urine output of 15 mL per hour"},{"id":"D","text":"A serum creatinine that has risen from 0.9 to 1.9 mg/dL"},{"id":"E","text":"A temperature that has fallen from 39.1 to 37.2 degrees C"},{"id":"F","text":"Two loose stools on the first day of therapy"}]}'::jsonb,
 '{"answers":["A","B","C","D"],"feedback":{"A":"Correct. Tinnitus is an early warning of cochlear damage, which may become permanent if the drug continues.","B":"Correct. Vestibular toxicity produces unsteadiness and dizziness and is reported promptly.","C":"Correct. Oliguria of 15 mL per hour suggests developing nephrotoxicity.","D":"Correct. A doubling of the creatinine indicates falling clearance and drug accumulation.","E":"Incorrect. A settling temperature is evidence that the antibiotic is working.","F":"Incorrect. Transient loose stools are a minor side effect rather than a dose-limiting toxicity."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential', 'Pharmacology', 'Sensory',
 'Aminoglycosides', 'Ototoxicity monitoring', 'Hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_540023', 'SATA',
 'The nurse is preparing an intravenous heparin infusion, which the organisation classifies as a high-alert medication. Which actions should the nurse take? Select all that apply.',
 'High-alert medications are not more likely to be given in error; they are the ones where an error causes serious harm. The defences are systematic: an independent double check in which the second nurse calculates the dose separately rather than confirming the first calculation, the drug library and dose limits on the smart pump, and the rights of administration verified against two client identifiers. Look-alike and sound-alike products are separated in storage rather than shelved together.',
 '{"options":[{"id":"A","text":"Have a second nurse independently verify the drug, the concentration, the pump rate and the client identity"},{"id":"B","text":"Program the infusion using the drug library and dose-limit settings on the smart pump"},{"id":"C","text":"Accept the calculation already worked out by the second nurse rather than repeating it independently"},{"id":"D","text":"Check the prescription against the client identity band using two identifiers"},{"id":"E","text":"Override a smart pump dose-limit alert to save time when the ward is busy"},{"id":"F","text":"Store the heparin vials beside the insulin vials so that both are easy to find"}]}'::jsonb,
 '{"answers":["A","B","D"],"feedback":{"A":"Correct. An independent double check of drug, concentration, rate and client is the core defence for high-alert infusions.","B":"Correct. The drug library and soft or hard dose limits catch programming errors before they reach the client.","C":"Incorrect. Confirming another calculation rather than repeating it independently defeats the purpose of the check.","D":"Correct. Two identifiers verify the right client, one of the rights of administration.","E":"Incorrect. A dose-limit alert is investigated, not overridden for convenience.","F":"Incorrect. Heparin and insulin are a classic look-alike pairing and are deliberately stored apart."}}'::jsonb,
 'Safe and Effective Care Environment', 'Management of Care', 'Pharmacology', 'Not applicable',
 'High-alert medications', 'Independent double checks', 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_540024', 'SATA',
 'Which actions are correct when the nurse administers intravenous potassium chloride on a general ward? Select all that apply.',
 'Potassium is a high-alert drug because the margin between a therapeutic infusion and cardiac arrest is a matter of rate and concentration. It is always diluted and given through a rate-controlled pump, never pushed. Peripheral concentrations are kept at or below about 40 mEq per litre to limit vein irritation, the site is watched for phlebitis and extravasation, and urine output and cardiac rhythm are monitored throughout. Potassium is never added to a bag already hanging, because the drug settles at the bottom and the client receives a concentrated bolus.',
 '{"options":[{"id":"A","text":"Always dilute the potassium and give it by infusion pump, never by intravenous push"},{"id":"B","text":"Keep the peripheral concentration at or below 40 mEq per litre where possible"},{"id":"C","text":"Assess the infusion site for pain, redness and swelling during the infusion"},{"id":"D","text":"Give a rapid bolus if the serum potassium is below 2.5 mEq/L"},{"id":"E","text":"Add the potassium to a bag that is already hanging and invert it afterwards"},{"id":"F","text":"Monitor the urine output and the cardiac rhythm during the infusion"}]}'::jsonb,
 '{"answers":["A","B","C","F"],"feedback":{"A":"Correct. Undiluted or pushed potassium causes fatal asystole, so a pump-controlled dilute infusion is mandatory.","B":"Correct. Higher peripheral concentrations cause severe vein pain and phlebitis and need central access.","C":"Correct. Potassium is a vesicant and extravasation causes tissue damage.","D":"Incorrect. A severe deficit is corrected by a controlled infusion, never by a bolus.","E":"Incorrect. Additives placed in a hanging bag layer at the bottom and are delivered as a concentrated bolus.","F":"Correct. Urine output reflects the ability to excrete potassium and the rhythm reveals early cardiac effects."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Pharmacology', 'Cardiovascular',
 'Potassium chloride', 'Intravenous administration safety', 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_540025', 'SATA',
 'A student nurse on placement is revising insulin before a medicines assessment. Which statements made by the student are correct? Select all that apply.',
 'Insulin safety rests on matching the profile of the preparation to what the body needs at that moment. Rapid-acting analogues are given 5 to 15 minutes before eating so their peak lands on the meal. Regular soluble insulin is the only preparation that may be given intravenously, which makes it the insulin of diabetic ketoacidosis. Long-acting analogues such as glargine have no pronounced peak, which is exactly why they are the safer bedtime basal option, and they are never mixed in a syringe with another insulin.',
 '{"options":[{"id":"A","text":"Regular soluble insulin is the only insulin that may be given intravenously"},{"id":"B","text":"Insulin glargine has no pronounced peak, which makes it a safer bedtime option"},{"id":"C","text":"Rapid-acting insulin aspart is given 5 to 15 minutes before a meal"},{"id":"D","text":"NPH insulin has no peak and gives a flat effect for 24 hours"},{"id":"E","text":"Insulin glargine may be drawn into the same syringe as regular insulin"},{"id":"F","text":"A long-acting insulin is used to cover the glucose rise after a meal"}]}'::jsonb,
 '{"answers":["A","B","C"],"feedback":{"A":"Correct. Only regular soluble insulin is licensed for intravenous use, which is why it is used in diabetic ketoacidosis.","B":"Correct. A peakless profile reduces the risk of nocturnal hypoglycaemia compared with a bedtime NPH dose.","C":"Correct. The rapid onset means it is timed immediately before eating.","D":"Incorrect. NPH peaks at 6 to 12 hours and lasts 14 to 24 hours; it is not peakless.","E":"Incorrect. Glargine is never mixed with another insulin in the same syringe.","F":"Incorrect. Mealtime coverage is the role of a rapid-acting or regular insulin, not a basal preparation."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Pharmacology', 'Endocrine',
 'Insulin', 'Onset, peak and duration', 'Easy', 'CURATOR_LABEL', 'Understand', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_540026', 'SATA',
 'A client is discharged on apixaban after a pulmonary embolism. Which statements by the client indicate correct understanding of the medicine? Select all that apply.',
 'Direct oral anticoagulants act on a single clotting factor, either thrombin or factor Xa, and give a predictable response, so routine INR monitoring is not required. That convenience creates its own risks: the client may assume no monitoring means no danger, may stop the drug abruptly and lose protection within a day, and may not realise that non-steroidal anti-inflammatory drugs sharply increase bleeding. Vitamin K does not reverse a direct oral anticoagulant; specific agents such as andexanet alfa or idarucizumab are used instead.',
 '{"options":[{"id":"A","text":"I do not need routine INR blood tests while I take this medicine"},{"id":"B","text":"I should tell any dentist or surgeon that I take an anticoagulant"},{"id":"C","text":"I should not stop this medicine suddenly without speaking to my prescriber"},{"id":"D","text":"I can take ibuprofen freely for my knee pain"},{"id":"E","text":"Vitamin K will reverse this medicine if I have a bleed"},{"id":"F","text":"If I miss a dose I should take two doses at the next scheduled time"}]}'::jsonb,
 '{"answers":["A","B","C"],"feedback":{"A":"Correct. Direct oral anticoagulants have a predictable effect and do not require routine INR monitoring.","B":"Correct. Any procedure carrying a bleeding risk needs the anticoagulant to be known and planned around.","C":"Correct. Protection is lost rapidly after stopping, so the drug is never discontinued without advice.","D":"Incorrect. Non-steroidal anti-inflammatory drugs add an antiplatelet effect and gastric irritation, raising bleeding risk substantially.","E":"Incorrect. Vitamin K reverses warfarin; direct oral anticoagulants have their own specific reversal agents.","F":"Incorrect. Doubling up doubles the bleeding risk; missed-dose advice depends on how close the next dose is."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Pharmacology', 'Hematologic',
 'Direct oral anticoagulants', 'Client teaching', 'Hard', 'CURATOR_LABEL', 'Evaluate', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_540027', 'SATA',
 'The nurse is giving subcutaneous enoxaparin to a client on a surgical ward. Which actions are correct? Select all that apply.',
 'Low molecular weight heparins have a predictable dose response, so routine aPTT monitoring is not required and dosing is by weight and renal function instead. The administration technique matters: the prefilled syringe contains a deliberate air bubble that clears the last of the dose from the needle, aspirating risks vessel puncture and haematoma, and rubbing or massaging the site increases bruising. Platelet counts are still checked because heparin-induced thrombocytopenia can occur.',
 '{"options":[{"id":"A","text":"Give the injection into the fatty tissue of the abdomen, at least 5 cm away from the umbilicus"},{"id":"B","text":"Do not expel the air bubble from the prefilled syringe"},{"id":"C","text":"Do not rub the site after the injection"},{"id":"D","text":"Aspirate before injecting to check for a blood return"},{"id":"E","text":"Arrange a daily aPTT to titrate the dose"},{"id":"F","text":"Massage the site afterwards to aid absorption"}]}'::jsonb,
 '{"answers":["A","B","C"],"feedback":{"A":"Correct. The abdominal fat pad away from the umbilicus gives reliable absorption and fewer complications.","B":"Correct. The bubble is intentional and ensures the full dose is delivered.","C":"Correct. Rubbing increases local bruising and haematoma formation.","D":"Incorrect. Aspiration is not performed for subcutaneous heparin and increases the risk of a haematoma.","E":"Incorrect. Low molecular weight heparin has a predictable response and does not need routine aPTT titration.","F":"Incorrect. Massaging is the opposite of correct technique and worsens bruising."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Pharmacology', 'Hematologic',
 'Low molecular weight heparin', 'Administration technique', 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SELN_540028', 'SELECT_N',
 'A client with a deep vein thrombosis is started on an intravenous heparin infusion and on oral warfarin on the same day. A relative asks why two blood thinners are needed at once. Which 3 statements explain this practice correctly?',
 'Warfarin blocks the synthesis of new vitamin K dependent clotting factors but does nothing to the factors already circulating, so full antithrombotic effect takes three to five days and the INR can rise before real protection exists. Heparin acts within minutes and covers that gap. The overlap continues until the INR has been in the target range for about 24 to 48 hours, at which point the heparin is stopped. Understanding this prevents the dangerous error of stopping heparin as soon as the INR first enters range.',
 '{"options":[{"id":"A","text":"Warfarin takes several days to lower the clotting factors already circulating, so it gives no immediate protection"},{"id":"B","text":"Heparin acts within minutes and covers the client until warfarin becomes effective"},{"id":"C","text":"The heparin is usually stopped once the INR has stayed in the target range for about 24 to 48 hours"},{"id":"D","text":"Warfarin works immediately and the heparin is given only to prevent bleeding"},{"id":"E","text":"The two are combined because heparin raises the INR permanently"},{"id":"F","text":"The overlap is needed because warfarin cannot be absorbed unless heparin is present"}],"select_count":3}'::jsonb,
 '{"answers":["A","B","C"],"feedback":{"A":"Correct. Existing clotting factors must decay before warfarin protects, which takes three to five days.","B":"Correct. Heparin gives the immediate anticoagulation that warfarin cannot.","C":"Correct. A sustained therapeutic INR is the signal that heparin can safely be withdrawn.","D":"Incorrect. Warfarin is slow in onset, and heparin is an anticoagulant, not a bleeding preventive.","E":"Incorrect. Heparin can transiently affect the INR but does not raise it permanently, and that is not the reason for the overlap.","F":"Incorrect. Warfarin absorption is independent of heparin."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Pharmacology', 'Hematologic',
 'Anticoagulant overlap', 'Heparin to warfarin transition', 'Very hard', 'CURATOR_LABEL', 'Understand', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SELN_540029', 'SELECT_N',
 'A nurse is teaching a group of student nurses about therapeutic drug monitoring. Which 3 medications require routine serum level measurement because they have a narrow therapeutic index?',
 'A narrow therapeutic index means the concentration that treats and the concentration that harms are close together, so the dose cannot be judged from the clinical picture alone. Lithium, digoxin, phenytoin, theophylline, vancomycin and the aminoglycosides all fall into this group and are dosed against measured serum levels. Most other medicines have a wide margin and are titrated against effect, so routine levels add nothing.',
 '{"options":[{"id":"A","text":"Lithium"},{"id":"B","text":"Digoxin"},{"id":"C","text":"Vancomycin"},{"id":"D","text":"Paracetamol taken at the prescribed dose"},{"id":"E","text":"Omeprazole"},{"id":"F","text":"Senna"}],"select_count":3}'::jsonb,
 '{"answers":["A","B","C"],"feedback":{"A":"Correct. Lithium is therapeutic at 0.6 to 1.2 mEq/L and toxic above 2.0 mEq/L, a very narrow margin.","B":"Correct. Digoxin is therapeutic at 0.5 to 2 ng/mL with toxicity just above.","C":"Correct. Vancomycin trough levels guide dosing and predict kidney injury.","D":"Incorrect. Paracetamol levels are measured after overdose, not routinely during normal dosing.","E":"Incorrect. Omeprazole has a wide margin of safety and is not level-monitored.","F":"Incorrect. Senna is titrated against bowel response, not serum concentration."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Pharmacology', 'Multisystem',
 'Therapeutic drug monitoring', 'Narrow therapeutic index', 'Very easy', 'CURATOR_LABEL', 'Remember', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SELN_540030', 'SELECT_N',
 'A verbal prescription is received by telephone for hydralazine 25 mg orally for a client who was described earlier on the ward round as anxious. The nurse suspects that hydroxyzine may have been intended. Which 3 actions should the nurse take?',
 'Hydralazine and hydroxyzine are a recognised look-alike and sound-alike pairing with completely different effects: one lowers blood pressure, the other sedates. Verbal and telephone prescriptions are the highest-risk route, which is why the read-back is mandatory and the drug name is spelled out. Where the indication and the drug do not fit together, the nurse withholds the medicine until the prescription is confirmed in writing rather than choosing between the two.',
 '{"options":[{"id":"A","text":"Contact the prescriber and ask for the prescription to be confirmed and written in full"},{"id":"B","text":"Read back the drug name, dose, route and frequency and ask the prescriber to spell the drug name"},{"id":"C","text":"Withhold the medicine until the prescription has been clarified"},{"id":"D","text":"Give hydroxyzine, because the indication fits that drug better"},{"id":"E","text":"Ask a colleague which of the two is usually prescribed on this ward and follow that"},{"id":"F","text":"Give hydralazine exactly as spoken and monitor the blood pressure closely"}],"select_count":3}'::jsonb,
 '{"answers":["A","B","C"],"feedback":{"A":"Correct. A written, confirmed prescription resolves the ambiguity and creates an accountable record.","B":"Correct. Read-back with spelling is the standard safeguard against look-alike and sound-alike errors.","C":"Correct. A medicine that may be the wrong drug is not given until the doubt is settled.","D":"Incorrect. Substituting a drug on the basis of a guess is prescribing, which is outside the nursing role here.","E":"Incorrect. Ward custom is not a substitute for a clarified prescription.","F":"Incorrect. Giving an antihypertensive to a client who may need an anxiolytic risks serious hypotension."}}'::jsonb,
 'Safe and Effective Care Environment', 'Management of Care', 'Pharmacology', 'Not applicable',
 'Look-alike and sound-alike medicines', 'Verifying a questionable prescription', 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728');

INSERT INTO nclex_bank_items (
  item_id, question_type, stem, rationale, content, correct,
  client_needs_category, client_needs_subcategory, nursing_subject, body_system,
  topic, subtopic, difficulty, difficulty_source, bloom_level, tags,
  marks, is_published, is_builder_visible, is_free_sample, cat_pool, batch_id
) VALUES
('NCLEX_MAT_540031', 'MATRIX',
 'For each finding below, indicate whether it is a side effect that the nurse monitors and teaches about while the medicine continues, or a toxic effect for which the nurse withholds the drug and notifies the prescriber.',
 'The distinction between a side effect and a toxic effect drives two completely different nursing responses. A side effect is an unwanted but expected consequence of a normal dose; it is explained to the client, monitored and often managed, and the drug continues. A toxic effect indicates that the drug concentration has exceeded the safe range or is damaging an organ; the dose is withheld and the prescriber informed. Confusing the two either alarms a client unnecessarily or allows a dangerous level to keep climbing.',
 '{"rows":[{"id":"r1","text":"Gingival hyperplasia in a client who has taken phenytoin for two years"},{"id":"r2","text":"Horizontal nystagmus and an unsteady gait in a client taking phenytoin"},{"id":"r3","text":"Increased thirst and urine output in a client on stable lithium therapy"},{"id":"r4","text":"Vomiting with a new coarse tremor in a client taking lithium"},{"id":"r5","text":"Nausea with yellow-green halos around lights in a client taking digoxin"},{"id":"r6","text":"A small bruise at the site of a subcutaneous enoxaparin injection"}],"columns":[{"id":"c1","text":"Side effect - monitor and teach, continue the drug"},{"id":"c2","text":"Toxic effect - withhold the drug and notify the prescriber"}],"row_label":"Finding"}'::jsonb,
 '{"cells":{"r1":"c1","r2":"c2","r3":"c1","r4":"c2","r5":"c2","r6":"c1"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Pharmacology', 'Multisystem',
 'Side effect versus toxic effect', 'Nursing response', 'Hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MAT_540032', 'MATRIX',
 'Match each insulin preparation to the time at which its glucose-lowering effect reaches its greatest intensity.',
 'Knowing when an insulin peaks tells the nurse when hypoglycaemia is most likely and therefore when to check the capillary glucose and when a meal or snack matters. Rapid-acting analogues peak in 1 to 3 hours, regular soluble insulin in 2 to 4 hours, NPH in 6 to 12 hours, and long-acting analogues such as glargine have no pronounced peak at all. The peakless profile is exactly why a long-acting analogue is the safer choice for a bedtime basal dose.',
 '{"rows":[{"id":"r1","text":"Insulin aspart (rapid-acting)"},{"id":"r2","text":"Regular (soluble) insulin"},{"id":"r3","text":"NPH (isophane) insulin"},{"id":"r4","text":"Insulin glargine (long-acting)"}],"columns":[{"id":"c1","text":"Peaks 1 to 3 hours after the dose"},{"id":"c2","text":"Peaks 2 to 4 hours after the dose"},{"id":"c3","text":"Peaks 6 to 12 hours after the dose"},{"id":"c4","text":"No pronounced peak"}],"row_label":"Insulin"}'::jsonb,
 '{"cells":{"r1":"c1","r2":"c2","r3":"c3","r4":"c4"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Pharmacology', 'Endocrine',
 'Insulin', 'Peak action times', 'Easy', 'CURATOR_LABEL', 'Understand', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MAT_540033', 'MATRIX',
 'The nurse reviews the morning laboratory results on a medical ward. For each serum level, indicate whether it falls within the therapeutic range or above it.',
 'Four ranges cover most narrow therapeutic index drugs a ward nurse meets: lithium 0.6 to 1.2 mEq/L, digoxin 0.5 to 2 ng/mL, phenytoin 10 to 20 mcg/mL, and theophylline 10 to 20 mcg/mL. A level above the range does not automatically mean the client is unwell, but it does mean the nurse assesses for the specific toxic features of that drug and escalates before the next dose. Reading the number without knowing the range is the commonest reason a rising level is missed.',
 '{"rows":[{"id":"r1","text":"Lithium 1.8 mEq/L"},{"id":"r2","text":"Digoxin 1.4 ng/mL"},{"id":"r3","text":"Phenytoin 24 mcg/mL"},{"id":"r4","text":"Theophylline 14 mcg/mL"},{"id":"r5","text":"Lithium 0.9 mEq/L"},{"id":"r6","text":"Digoxin 3.2 ng/mL"}],"columns":[{"id":"c1","text":"Within the therapeutic range"},{"id":"c2","text":"Above the therapeutic range"}],"row_label":"Serum level"}'::jsonb,
 '{"cells":{"r1":"c2","r2":"c1","r3":"c2","r4":"c1","r5":"c1","r6":"c2"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential', 'Pharmacology', 'Multisystem',
 'Therapeutic ranges', 'Serum level interpretation', 'Medium', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MAT_540034', 'MATRIX',
 'A nurse is taking a medicines history in an outpatient clinic. For each report, indicate whether it describes a true allergic reaction or an intolerance or expected drug effect.',
 'A true allergy is an immune-mediated reaction, typically appearing within minutes and involving urticaria, wheeze, angio-oedema, stridor or hypotension. An intolerance is an unpleasant but non-immune response, most often gastrointestinal, and an expected effect is simply the pharmacology of the drug at work. The distinction is not academic: recording an intolerance as an allergy removes whole antibiotic classes from a client for life, while dismissing a genuine allergy risks a fatal re-exposure.',
 '{"rows":[{"id":"r1","text":"Urticaria, wheeze and lip swelling within minutes of intravenous co-amoxiclav"},{"id":"r2","text":"Nausea and stomach discomfort after oral erythromycin"},{"id":"r3","text":"Drowsiness after the first dose of chlorphenamine"},{"id":"r4","text":"Sudden hypotension and stridor after an intravenous contrast injection"},{"id":"r5","text":"Loose stools during a course of oral amoxicillin"}],"columns":[{"id":"c1","text":"True allergic reaction"},{"id":"c2","text":"Intolerance or expected effect"}],"row_label":"Client report"}'::jsonb,
 '{"cells":{"r1":"c1","r2":"c2","r3":"c2","r4":"c1","r5":"c2"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Pharmacology', 'Immune',
 'Adverse drug reactions', 'Allergy versus intolerance', 'Medium', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MMR_540035', 'MATRIX_MR',
 'For each medication, select every monitoring parameter the nurse should expect to be checked during therapy. Each medication has at least one.',
 'Monitoring follows the way a drug is handled and the harm it can cause. Aminoglycosides need serum levels because the index is narrow, and renal function because they damage the proximal tubule and because a failing kidney raises the level further. Lithium likewise needs both, since it is renally cleared and causes long-term renal effects. Warfarin is followed by the INR and unfractionated heparin by the aPTT, but neither has a routinely measured serum drug concentration.',
 '{"rows":[{"id":"r1","text":"Intravenous gentamicin"},{"id":"r2","text":"Oral warfarin"},{"id":"r3","text":"Unfractionated heparin infusion"},{"id":"r4","text":"Oral lithium carbonate"}],"columns":[{"id":"c1","text":"Serum drug level"},{"id":"c2","text":"Renal function (serum creatinine)"},{"id":"c3","text":"Coagulation test (INR or aPTT)"}],"row_label":"Medication"}'::jsonb,
 '{"cells":{"r1":["c1","c2"],"r2":["c3"],"r3":["c3"],"r4":["c1","c2"]},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential', 'Pharmacology', 'Multisystem',
 'Therapeutic drug monitoring', 'Monitoring parameters', 'Very hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MMR_540036', 'MATRIX_MR',
 'It is the morning medicine round. For each situation, select every action the nurse should take. Each situation has at least one.',
 'Three responses are possible when a dose falls due: give it, hold it, or hold it and escalate. Holding alone is appropriate only when the drug can safely wait; where the finding signals toxicity or a new adverse reaction, the prescriber must also be informed so the regimen can be changed. A result that sits inside the therapeutic range with no worrying assessment findings is simply given, and hesitating over a safe dose delays treatment.',
 '{"rows":[{"id":"r1","text":"Digoxin is due; the apical pulse is 48 beats per minute"},{"id":"r2","text":"Warfarin is due; the INR is 2.4 and there is no bleeding"},{"id":"r3","text":"Lithium is due; the level is 2.1 mEq/L and the client has vomited twice"},{"id":"r4","text":"Enoxaparin is due; the platelet count has fallen from 240 to 70 x 10^9/L"},{"id":"r5","text":"Vancomycin is due; the trough level is 12 mcg/mL and renal function is stable"}],"columns":[{"id":"c1","text":"Withhold the dose"},{"id":"c2","text":"Notify the prescriber"},{"id":"c3","text":"Administer as prescribed"}],"row_label":"Situation"}'::jsonb,
 '{"cells":{"r1":["c1","c2"],"r2":["c3"],"r3":["c1","c2"],"r4":["c1","c2"],"r5":["c3"]},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Pharmacology', 'Multisystem',
 'High-alert medication decisions', 'Withhold, escalate or administer', 'Very hard', 'CURATOR_LABEL', 'Evaluate', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_CLZ_540037', 'CLOZE',
 'A nurse is preparing a teaching board on reversal agents for the emergency department. Complete each statement. The reversal agent for unfractionated heparin is {1}. Respiratory depression caused by an opioid is reversed with {2}. Paracetamol overdose is treated with {3}. Excessive sedation from a benzodiazepine may be reversed with {4}. Severe bradycardia caused by a beta-blocker overdose is treated with {5}.',
 'Antidotes are only useful if the pairing is instant knowledge at the bedside. Protamine sulfate neutralises heparin by binding it directly, naloxone competitively displaces opioids from their receptors, acetylcysteine replenishes glutathione so the toxic paracetamol metabolite can be conjugated, flumazenil blocks the benzodiazepine receptor, and high-dose glucagon bypasses the blocked beta receptor to restore cardiac contractility and rate. Each agent needs its own cautions, notably that naloxone often wears off before the opioid does.',
 '{"blanks":[{"id":"b1","choices":[{"id":"c1","text":"protamine sulfate"},{"id":"c2","text":"vitamin K"},{"id":"c3","text":"calcium gluconate"}]},{"id":"b2","choices":[{"id":"c1","text":"flumazenil"},{"id":"c2","text":"naloxone"},{"id":"c3","text":"acetylcysteine"}]},{"id":"b3","choices":[{"id":"c1","text":"acetylcysteine"},{"id":"c2","text":"naloxone"},{"id":"c3","text":"digoxin immune Fab"}]},{"id":"b4","choices":[{"id":"c1","text":"glucagon"},{"id":"c2","text":"flumazenil"},{"id":"c3","text":"protamine sulfate"}]},{"id":"b5","choices":[{"id":"c1","text":"glucagon"},{"id":"c2","text":"vitamin K"},{"id":"c3","text":"flumazenil"}]}]}'::jsonb,
 '{"answers":{"b1":"c1","b2":"c2","b3":"c1","b4":"c2","b5":"c1"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Pharmacology', 'Multisystem',
 'Antidotes and reversal agents', 'Drug and antidote pairings', 'Easy', 'CURATOR_LABEL', 'Remember', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_CLZ_540038', 'CLOZE',
 'A client takes warfarin for atrial fibrillation with a target INR of 2.0 to 3.0. Complete the graded response. If the INR is 2.6 with no bleeding, the nurse should {1}. If the INR is 5.5 with no bleeding, the expected management is to {2}. If the INR is 9.0 with no bleeding, the prescriber is likely to withhold the warfarin and give {3}. If the INR is raised and the client has major bleeding, intravenous vitamin K is given together with {4}.',
 'The response to a raised INR is graded against both the number and the presence of bleeding, not the number alone. Within range the dose is simply given. Moderately above range with no bleeding, doses are withheld and the INR rechecked. Markedly above range attracts oral vitamin K, which acts over several hours. Major bleeding cannot wait for factor synthesis, so intravenous vitamin K is combined with prothrombin complex concentrate, which replaces the missing factors immediately.',
 '{"blanks":[{"id":"b1","choices":[{"id":"c1","text":"withhold the dose"},{"id":"c2","text":"administer the dose as prescribed"},{"id":"c3","text":"give oral vitamin K"}]},{"id":"b2","choices":[{"id":"c1","text":"continue the same dose"},{"id":"c2","text":"withhold one or more doses and recheck the INR"},{"id":"c3","text":"give protamine sulfate"}]},{"id":"b3","choices":[{"id":"c1","text":"intravenous protamine sulfate"},{"id":"c2","text":"oral vitamin K"},{"id":"c3","text":"a double dose of warfarin"}]},{"id":"b4","choices":[{"id":"c1","text":"prothrombin complex concentrate"},{"id":"c2","text":"oral iron"},{"id":"c3","text":"a further dose of warfarin"}]}]}'::jsonb,
 '{"answers":{"b1":"c2","b2":"c2","b3":"c2","b4":"c1"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential', 'Pharmacology', 'Hematologic',
 'Warfarin', 'Graded response to a rising INR', 'Hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_DO_540039', 'DRAG_ORDER',
 'The nurse is drawing regular (soluble) insulin and NPH (isophane) insulin into a single syringe for a morning dose. Place the four required steps in the correct order.',
 'Air is injected into the cloudy NPH vial first, without letting the needle touch the solution, so that no NPH is carried into the clear vial. Air is then injected into the regular insulin vial and the clear regular insulin is drawn up. The cloudy NPH is drawn last, because a trace of clear insulin entering the cloudy vial matters far less than long-acting suspension contaminating the short-acting vial. The phrase clear before cloudy captures the drawing-up order. Vials are gently rolled, never shaken, as shaking creates froth and makes the dose inaccurate.',
 '{"slots":[{"id":"s1","target_text":"1st"},{"id":"s2","target_text":"2nd"},{"id":"s3","target_text":"3rd"},{"id":"s4","target_text":"4th"}],"tokens":[{"id":"t1","text":"Inject air equal to the NPH dose into the NPH vial without touching the solution"},{"id":"t2","text":"Inject air equal to the regular insulin dose into the regular insulin vial"},{"id":"t3","text":"Withdraw the prescribed dose of regular (clear) insulin"},{"id":"t4","text":"Withdraw the prescribed dose of NPH (cloudy) insulin"},{"id":"t5","text":"Shake both vials vigorously until fully mixed"}]}'::jsonb,
 '{"slots":{"s1":"t1","s2":"t2","s3":"t3","s4":"t4"}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Pharmacology', 'Endocrine',
 'Insulin', 'Mixing two insulins in one syringe', 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_TF_540040', 'TF',
 'Two minutes into an intravenous antibiotic infusion, a client develops wheeze, swelling of the lips and face, and a fall in blood pressure from 124/76 to 82/48 mmHg. The nurse should stop the infusion immediately while calling for help. Is this statement true or false?',
 'Anaphylaxis is recognised by the speed of onset and the combination of airway, breathing or circulation involvement with skin changes. The first action is always to remove the trigger by stopping the infusion, while summoning help, because every further millilitre worsens the reaction. Intramuscular adrenaline into the anterolateral thigh follows immediately, with the airway supported, the legs raised if there is hypotension, high-flow oxygen and intravenous fluids. Antihistamines and corticosteroids are secondary and never replace adrenaline.',
 '{"options":[{"id":"A","text":"True"},{"id":"B","text":"False"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Stopping the infusion removes the trigger and is the immediate first action, alongside calling for help and preparing intramuscular adrenaline.","B":"Incorrect. Leaving the infusion running while other treatment is arranged allows more allergen to enter the circulation and deepens the reaction."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Pharmacology', 'Immune',
 'Anaphylaxis', 'Immediate management', 'Very easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728');
