-- MyNclex bank gap-fill, 2026-07-28
-- Batch: gapfill-20260728
-- Topic: the newborn and the postpartum client (Maternity)
-- Item id block: 512001-512050 (50 items)
-- Physiological Adaptation used only for the named zero-coverage topics:
--   normal newborn skin variations, caput vs cephalohaematoma,
--   kernicterus/opisthotonos, boggy fundus midline vs displaced.

INSERT INTO nclex_bank_items (
  item_id, question_type, stem, rationale, content, correct,
  client_needs_category, client_needs_subcategory, nursing_subject, body_system,
  topic, subtopic, difficulty, difficulty_source, bloom_level, tags,
  marks, is_published, is_builder_visible, is_free_sample, cat_pool, batch_id
) VALUES
('NCLEX_MCQ_512001', 'MCQ',
 'A mother points to tiny white pinpoint papules across the nose and chin of her 2-day-old newborn and says she plans to squeeze them out at home. Which response by the nurse is most appropriate?',
 'Milia are retained sebum and keratin in immature sebaceous glands. They are a normal variation in about half of all term newborns and resolve without treatment within the first few weeks as the glands mature. Squeezing or picking breaks the skin barrier and introduces organisms, so the teaching point is to leave the skin alone and wash the face with plain water only.',
 '{"options":[{"id":"A","text":"These are milia, blocked oil glands. Leave them alone and they will disappear on their own within a few weeks."},{"id":"B","text":"Squeeze them gently once a day so the skin clears faster."},{"id":"C","text":"Apply a thin layer of antibiotic ointment to each spot twice a day."},{"id":"D","text":"Wash the face with a medicated soap at every nappy change."}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Milia are a benign, self-limiting variation that needs no treatment beyond routine washing with plain water.","B":"Incorrect. Squeezing breaks the skin and risks introducing infection and scarring.","C":"Incorrect. There is no infection to treat, and ointment blocks the glands further.","D":"Incorrect. Medicated soap dries and irritates newborn skin without affecting milia."}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance', 'Maternity', 'Integumentary',
 'Newborn skin variations', 'Milia',
 'Very easy', 'CURATOR_LABEL', 'Understand', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_512002', 'MCQ',
 'During the first examination of a term newborn, the nurse observes two small, firm, white cysts along the midline of the hard palate. The newborn is latching and feeding well. How should the nurse interpret this finding?',
 'Epstein pearls are epithelial inclusion cysts found on the hard palate or at the gum margins in most newborns. They are firm, fixed and painless, do not interfere with feeding, and disappear within weeks without any intervention. Recognising them prevents an unnecessary antifungal prescription and needless parental worry.',
 '{"options":[{"id":"A","text":"They are Epstein pearls, benign inclusion cysts that disappear without treatment."},{"id":"B","text":"They are oral thrush and an antifungal suspension is needed."},{"id":"C","text":"They indicate an underlying cleft of the soft palate."},{"id":"D","text":"They are milk curds that should be wiped away with a gauze swab."}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Epstein pearls are a normal variation that resolves spontaneously in the first weeks of life.","B":"Incorrect. Thrush appears as white plaques on the tongue and buccal mucosa that leave a raw base when scraped, not as firm midline cysts.","C":"Incorrect. Epstein pearls sit on an intact palate and are unrelated to clefting, which is found on inspection and palpation of the palate.","D":"Incorrect. Milk curds wipe away easily; Epstein pearls are firm and fixed."}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance', 'Maternity', 'Integumentary',
 'Newborn skin variations', 'Epstein pearls',
 'Easy', 'CURATOR_LABEL', 'Understand', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_512003', 'SATA',
 'A nurse admitting a newborn to the postnatal ward finds large bluish-grey macular areas over the buttocks and lower back. The parents are at the cot side and the newborn is otherwise well. Which actions should the nurse take? Select all that apply.',
 'Congenital dermal melanocytosis, still widely called a Mongolian spot, is a collection of melanocytes trapped in the dermis and is common in newborns with darker skin. Because the areas look like bruising, careful description of the site, size and colour in the record at birth is what later protects the family from a false allegation of non-accidental injury. The finding needs no treatment and usually fades during early childhood.',
 '{"options":[{"id":"A","text":"Document the exact site, size and colour of each area in the admission skin assessment."},{"id":"B","text":"Explain to the parents that the areas are congenital dermal melanocytosis and usually fade during early childhood."},{"id":"C","text":"Refer the newborn to the child protection team as suspected non-accidental injury."},{"id":"D","text":"Describe the areas in the handover to the community midwife so later carers are not misled."},{"id":"E","text":"Apply a warm compress to help the discolouration resolve."},{"id":"F","text":"Include the finding in the discharge summary so it is available to health professionals who see the child later."}]}'::jsonb,
 '{"answers":["A","B","D","F"],"feedback":{"A":"Correct. A precise baseline description at birth is the record that distinguishes this from later bruising.","B":"Correct. Parents need to know the marks are benign and will fade, so they are not alarmed.","C":"Incorrect. The finding is a normal pigmentary variation, not an injury, and referring it wrongly distresses the family.","D":"Correct. Handover to the community team carries the baseline description forward.","E":"Incorrect. There is no treatment; the pigment lies deep in the dermis and heat does nothing.","F":"Correct. Documenting it in the discharge summary protects the family from a later false safeguarding allegation."}}'::jsonb,
 'Physiological Integrity', 'Physiological Adaptation', 'Maternity', 'Integumentary',
 'Newborn skin variations', 'Congenital dermal melanocytosis',
 'Hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_512004', 'MCQ',
 'On the second day of life a newborn develops blotchy erythematous macules with small yellow-white papules at the centre, scattered over the trunk. The newborn is afebrile and feeding well. The father asks whether a cream is needed. Which response by the nurse is correct?',
 'Erythema toxicum neonatorum appears in the first 3 days in up to half of term newborns and lasts about a week. The lesions come and go on different parts of the body over hours, spare the palms and soles, and the newborn remains well. Because it is benign and self-limiting, no cream, isolation or investigation is required.',
 '{"options":[{"id":"A","text":"This is erythema toxicum neonatorum. It needs no treatment and clears within about a week."},{"id":"B","text":"This is a staphylococcal skin infection and the newborn will need to be isolated."},{"id":"C","text":"This is a heat rash from over-wrapping and needs a cooling bath."},{"id":"D","text":"This is an allergic reaction to the detergent used on the cot linen."}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Erythema toxicum is a benign, self-limiting newborn rash in a well, afebrile newborn.","B":"Incorrect. Staphylococcal lesions are pustular and the newborn would show signs of sepsis such as fever, poor feeding or lethargy.","C":"Incorrect. Miliaria appears in skin folds and covered areas as tiny clear or red vesicles, not as macules with central papules.","D":"Incorrect. Newborns are rarely sensitised to detergent this early, and the pattern described is typical of erythema toxicum."}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance', 'Maternity', 'Integumentary',
 'Newborn skin variations', 'Erythema toxicum neonatorum',
 'Easy', 'CURATOR_LABEL', 'Understand', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_512005', 'MCQ',
 'One newborn on the ward has a flat pink patch at the nape of the neck that whitens when the nurse presses it. Another newborn has a flat deep purple patch over one cheek that does not change colour with pressure. Which statement by the nurse correctly distinguishes the two findings?',
 'A telangiectatic nevus, or stork bite, is a cluster of dilated capillaries that blanches under pressure and fades over the first years of life. A port-wine stain is a malformation of dermal capillaries that does not blanch, darkens and thickens with age and is permanent. Blanching and the natural history are the two features that separate them at the cot side.',
 '{"options":[{"id":"A","text":"The blanching patch is a telangiectatic nevus that fades in early childhood; the non-blanching purple patch is a port-wine stain that is permanent."},{"id":"B","text":"Both are telangiectatic nevi and both fade by the second birthday."},{"id":"C","text":"The blanching patch is a port-wine stain and the purple patch is bruising from the birth."},{"id":"D","text":"Both will fade once the newborn bilirubin level falls."}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Blanching plus fading identifies a stork bite; non-blanching and permanent identifies a port-wine stain.","B":"Incorrect. A port-wine stain does not fade and persists without treatment.","C":"Incorrect. This reverses the two lesions, and bruising resolves through green and yellow colour change within days.","D":"Incorrect. Neither lesion has any relationship to the bilirubin level."}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance', 'Maternity', 'Integumentary',
 'Newborn skin variations', 'Telangiectatic nevus and port-wine stain',
 'Very easy', 'CURATOR_LABEL', 'Understand', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_512006', 'SATA',
 'The parents of a newborn with a port-wine stain across the forehead and upper eyelid ask the nurse what to expect. Which statements should the nurse include? Select all that apply.',
 'A port-wine stain is a capillary malformation present from birth that does not blanch and does not resolve. When it follows the ophthalmic division of the trigeminal nerve, there is an association with Sturge-Weber syndrome, so the newborn needs ophthalmic and neurological review. Parents commonly believe something they did in pregnancy caused the mark, and correcting that belief is part of the teaching.',
 '{"options":[{"id":"A","text":"The mark is permanent and will not fade with time."},{"id":"B","text":"The mark does not turn white when it is pressed."},{"id":"C","text":"Because the mark involves the forehead and eyelid, your baby will be reviewed for associated eye and neurological problems."},{"id":"D","text":"Nothing either of you did during the pregnancy caused this mark."},{"id":"E","text":"The mark will disappear once your baby starts to crawl."},{"id":"F","text":"Rubbing the area with oil twice a day will lighten it."}]}'::jsonb,
 '{"answers":["A","B","C","D"],"feedback":{"A":"Correct. A port-wine stain persists for life and tends to darken and thicken with age.","B":"Correct. Failure to blanch is what distinguishes it from a telangiectatic nevus.","C":"Correct. Involvement of the ophthalmic trigeminal distribution warrants review for glaucoma and for Sturge-Weber syndrome.","D":"Correct. It is a capillary malformation of unknown cause and no maternal behaviour produces it.","E":"Incorrect. Fading over the first years describes a telangiectatic nevus, not a port-wine stain.","F":"Incorrect. No topical measure alters the lesion; pulsed dye laser therapy is the treatment offered later."}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance', 'Maternity', 'Integumentary',
 'Newborn skin variations', 'Port-wine stain',
 'Hard', 'CURATOR_LABEL', 'Understand', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_512007', 'SATA',
 'A nurse is preparing to give a term newborn the first bath at 8 hours of age. Which actions should the nurse take? Select all that apply.',
 'The first bath is delayed until the temperature has been stable, because bathing causes evaporative heat loss in a newborn with a large surface area and little insulating fat. Vernix caseosa is a protective barrier that hydrates the skin and has antimicrobial properties, so remaining vernix is left to absorb rather than scrubbed away. Lanugo, the fine hair over the shoulders and back, is a normal finding that rubs off over the following weeks.',
 '{"options":[{"id":"A","text":"Check that the axillary temperature is stable at 36.5 °C or above before starting."},{"id":"B","text":"Leave the remaining vernix caseosa on the skin to absorb rather than scrubbing it off."},{"id":"C","text":"Bath the newborn under a radiant warmer and dry the newborn immediately afterwards."},{"id":"D","text":"Rub the fine soft hair over the shoulders and back until it is removed."},{"id":"E","text":"Use a firm brush on the scalp to lift any remaining vernix."},{"id":"F","text":"Explain to the mother that the fine hair over the shoulders is lanugo and will rub away over the coming weeks."}]}'::jsonb,
 '{"answers":["A","B","C","F"],"feedback":{"A":"Correct. Bathing before the temperature is stable risks cold stress.","B":"Correct. Vernix protects and hydrates the skin and is absorbed without help.","C":"Correct. A warm environment and prompt drying limit evaporative heat loss.","D":"Incorrect. Lanugo is a normal finding and rubbing it damages the skin barrier.","E":"Incorrect. Brushing the scalp abrades fragile skin and offers no benefit.","F":"Correct. Naming lanugo and explaining its natural history reassures the mother."}}'::jsonb,
 'Physiological Integrity', 'Basic Care and Comfort', 'Maternity', 'Integumentary',
 'Newborn skin care', 'Vernix caseosa and lanugo',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MAT_512008', 'MATRIX',
 'A nurse examines the skin of several newborns on the postnatal ward. For each finding, indicate whether it is an expected newborn variation or whether it requires further evaluation.',
 'Most newborn skin findings are transient variations produced by immature sebaceous glands, sluggish peripheral circulation or trapped pigment, and they need only explanation. The findings that matter are those that reflect oxygenation, bilirubin or clotting: central cyanosis of the lips and tongue, jaundice within the first 24 hours, and non-blanching purpura. Sorting the benign from the significant is what prevents both over-investigation and missed pathology.',
 '{"rows":[{"id":"r1","text":"Pinpoint white papules across the nose"},{"id":"r2","text":"Blue-tinged hands and feet at 2 hours of age with a pink trunk"},{"id":"r3","text":"Blotchy erythema with central white papules on the trunk at 48 hours"},{"id":"r4","text":"Blue-tinged lips and tongue"},{"id":"r5","text":"Yellow tinge to the face and sclerae at 14 hours of age"},{"id":"r6","text":"Generalised pinpoint purple spots that do not blanch"}],"columns":[{"id":"c1","text":"Expected variation"},{"id":"c2","text":"Requires further evaluation"}],"row_label":"Finding"}'::jsonb,
 '{"cells":{"r1":"c1","r2":"c1","r3":"c1","r4":"c2","r5":"c2","r6":"c2"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Physiological Adaptation', 'Maternity', 'Integumentary',
 'Newborn skin variations', 'Expected versus significant findings',
 'Medium', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MAT_512009', 'MATRIX',
 'A nurse is teaching a student about scalp swellings in the newborn. For each feature, indicate whether it describes caput succedaneum or cephalohaematoma.',
 'Caput succedaneum is oedema of the scalp above the periosteum, so it crosses suture lines, is present at birth because it is produced by pressure during labour, pits on pressure and settles within a few days. A cephalohaematoma is bleeding under the periosteum of a single cranial bone, so it is bounded by the suture lines, appears hours after birth as the bleed accumulates, feels firm and takes weeks to resorb. The distinction matters because the collected blood in a cephalohaematoma is later broken down and adds to the bilirubin load.',
 '{"rows":[{"id":"r1","text":"The swelling crosses the suture lines"},{"id":"r2","text":"The swelling is limited to the surface of one cranial bone"},{"id":"r3","text":"The swelling is present at birth and begins to settle within 2 to 3 days"},{"id":"r4","text":"The swelling appears several hours after birth and enlarges over the first day"},{"id":"r5","text":"The swelling feels soft and pits on pressure"},{"id":"r6","text":"The swelling takes several weeks to resorb"}],"columns":[{"id":"c1","text":"Caput succedaneum"},{"id":"c2","text":"Cephalohaematoma"}],"row_label":"Feature"}'::jsonb,
 '{"cells":{"r1":"c1","r2":"c2","r3":"c1","r4":"c2","r5":"c1","r6":"c2"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Physiological Adaptation', 'Maternity', 'Multisystem',
 'Newborn head assessment', 'Caput succedaneum versus cephalohaematoma',
 'Hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_512010', 'MCQ',
 'A 36-hour-old newborn has a firm swelling over the right parietal bone that does not cross the suture lines. Which assessment is the PRIORITY for the nurse over the next 3 days?',
 'A cephalohaematoma is a collection of blood under the periosteum. As those red cells break down they release an extra bilirubin load at exactly the time the immature liver is least able to conjugate it, so these newborns are at raised risk of significant hyperbilirubinaemia. Serial bilirubin measurement plotted against the hour-specific treatment threshold is therefore the assessment that changes management.',
 '{"options":[{"id":"A","text":"Serial total serum bilirubin levels plotted against the hour-specific threshold"},{"id":"B","text":"Daily head circumference to monitor brain growth"},{"id":"C","text":"Blood pressure in all four limbs"},{"id":"D","text":"Urine specific gravity at every nappy change"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Resorption of the trapped blood raises the bilirubin load, so serial levels guide phototherapy decisions.","B":"Incorrect. Head circumference is recorded, but a localised subperiosteal bleed does not reflect brain growth over 3 days.","C":"Incorrect. Four-limb blood pressure screens for coarctation, which is unrelated to a scalp swelling.","D":"Incorrect. Hydration is monitored through weight and nappy counts, and specific gravity is not the priority here."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential', 'Maternity', 'Hematologic',
 'Newborn head assessment', 'Cephalohaematoma and jaundice risk',
 'Medium', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728');

INSERT INTO nclex_bank_items (
  item_id, question_type, stem, rationale, content, correct,
  client_needs_category, client_needs_subcategory, nursing_subject, body_system,
  topic, subtopic, difficulty, difficulty_source, bloom_level, tags,
  marks, is_published, is_builder_visible, is_free_sample, cat_pool, batch_id
) VALUES
('NCLEX_CLZ_512011', 'CLOZE',
 'At 1 minute of age a newborn has a heart rate of 130 beats per minute, a slow weak cry with irregular respirations, some flexion of the limbs, a grimace in response to suction, and a pink body with blue hands and feet. Complete the sentences. The total Apgar score is {1}, and the nurse should {2}.',
 'The Apgar score allocates 0, 1 or 2 to heart rate, respiratory effort, muscle tone, reflex irritability and colour, and is assigned at 1 and 5 minutes. Here heart rate above 100 scores 2, while weak irregular respirations, some flexion, a grimace and acrocyanosis each score 1, giving a total of 6. A score of 4 to 6 signals moderate difficulty and calls for stimulation and oxygen support with a repeat score at 5 minutes; it is not by itself an indication for chest compressions, which follow a heart rate below 60 despite effective ventilation.',
 '{"blanks":[{"id":"b1","choices":[{"id":"c1","text":"4"},{"id":"c2","text":"6"},{"id":"c3","text":"8"},{"id":"c4","text":"10"}]},{"id":"b2","choices":[{"id":"c1","text":"provide stimulation and supplemental oxygen as indicated and repeat the score at 5 minutes"},{"id":"c2","text":"begin chest compressions immediately"},{"id":"c3","text":"record the score and take no further action until the newborn examination"}]}]}'::jsonb,
 '{"answers":{"b1":"c2","b2":"c1"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential', 'Maternity', 'Multisystem',
 'Apgar scoring', 'Scoring and required response',
 'Medium', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MAT_512012', 'MATRIX',
 'A nurse assesses a term newborn who is 6 hours old and quietly awake. For each finding, indicate whether it is expected or unexpected.',
 'Term newborn ranges differ from adult ranges: heart rate 110 to 160 beats per minute while awake, respiratory rate 30 to 60 breaths per minute and unlaboured, and axillary temperature 36.5 to 37.5 °C. A sustained respiratory rate above 60, a waking heart rate below 100, or a temperature below 36.5 °C all point to a problem such as sepsis, respiratory disease or cold stress. Knowing the ranges is what lets the nurse separate normal transition from deterioration.',
 '{"rows":[{"id":"r1","text":"Axillary temperature 36.8 °C"},{"id":"r2","text":"Apical heart rate 142 beats per minute while awake"},{"id":"r3","text":"Respiratory rate 46 breaths per minute, unlaboured"},{"id":"r4","text":"Sustained respiratory rate of 74 breaths per minute"},{"id":"r5","text":"Apical heart rate 88 beats per minute while awake"},{"id":"r6","text":"Axillary temperature 36.1 °C"}],"columns":[{"id":"c1","text":"Expected"},{"id":"c2","text":"Unexpected"}],"row_label":"Finding"}'::jsonb,
 '{"cells":{"r1":"c1","r2":"c1","r3":"c1","r4":"c2","r5":"c2","r6":"c2"},"feedback":{}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance', 'Maternity', 'Multisystem',
 'Newborn vital signs', 'Expected ranges',
 'Medium', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_512013', 'MCQ',
 'Three hours after birth a term newborn has an axillary temperature of 36.0 °C. The newborn is lying in an open cot in a damp vest after a nappy change. Which action should the nurse take FIRST?',
 'The first step in cold stress is to stop the heat loss that is causing it. Damp clothing against a large body surface area produces rapid evaporative and conductive loss, so removing the wet vest, drying the skin and using skin-to-skin contact under a warm cover addresses the mechanism directly. Investigations and escalation follow once rewarming has been started.',
 '{"options":[{"id":"A","text":"Remove the damp clothing, dry the newborn and place the newborn skin-to-skin with the mother under a warm cover"},{"id":"B","text":"Obtain a capillary blood glucose measurement"},{"id":"C","text":"Notify the paediatric team"},{"id":"D","text":"Raise the room temperature and re-check the newborn in 1 hour"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Removing the source of evaporative heat loss and starting skin-to-skin rewarming is the immediate action.","B":"Incorrect. Glucose is checked, but measuring it does nothing to stop the ongoing heat loss.","C":"Incorrect. The nurse can correct simple environmental cold stress independently before escalating.","D":"Incorrect. Waiting an hour with the newborn still in damp clothing allows the temperature to fall further."}}'::jsonb,
 'Physiological Integrity', 'Basic Care and Comfort', 'Maternity', 'Multisystem',
 'Newborn thermoregulation', 'Cold stress first action',
 'Very easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_512014', 'MCQ',
 'A newborn has been cold-stressed after a prolonged period in a damp cot, and the temperature has now been restored under a radiant warmer. Which laboratory value is the PRIORITY for the nurse to obtain?',
 'A cold newborn generates heat by metabolising brown fat, a process that consumes oxygen and glucose at a high rate. Glycogen stores are small, so hypoglycaemia develops quickly and, unlike the other values, can cause seizures and permanent neurological injury within hours. Anaerobic metabolism during the same episode also produces acidosis, but glucose is the value that is checked first and acted on fastest.',
 '{"options":[{"id":"A","text":"Blood glucose"},{"id":"B","text":"Serum sodium"},{"id":"C","text":"Total white cell count"},{"id":"D","text":"Serum calcium"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Brown fat metabolism rapidly depletes limited glycogen stores, so hypoglycaemia is the immediate threat.","B":"Incorrect. Sodium is not appreciably altered by a short period of cold stress.","C":"Incorrect. A white cell count is relevant if sepsis is suspected, but it does not guide immediate management of cold stress.","D":"Incorrect. Calcium can fall in a stressed newborn, but it is not the first or the most dangerous derangement here."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential', 'Maternity', 'Multisystem',
 'Newborn thermoregulation', 'Consequences of cold stress',
 'Hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_512015', 'MCQ',
 'A large-for-gestational-age newborn of a mother with type 1 diabetes is jittery at 90 minutes of age. The capillary blood glucose is 1.9 mmol/L (34 mg/dL). The newborn has a strong suck and no respiratory distress. Which action should the nurse take first?',
 'Newborns of mothers with diabetes have been exposed to high maternal glucose and respond with high insulin production, which continues after the cord is cut and drops the glucose sharply in the first hours. A newborn who is alert with a strong suck and no respiratory distress can be corrected enterally, so an early feed of breast milk or formula followed by a repeat glucose is the protocol response. Intravenous dextrose is reserved for the newborn who cannot feed, is symptomatic with seizures, or fails to respond to feeding.',
 '{"options":[{"id":"A","text":"Feed the newborn breast milk or formula and repeat the glucose within 30 minutes according to protocol"},{"id":"B","text":"Withhold feeds and prepare an intravenous dextrose infusion"},{"id":"C","text":"Swaddle the newborn firmly and re-check the glucose in 2 hours"},{"id":"D","text":"Give oral glucose gel and stop glucose monitoring once the newborn settles"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. A newborn with a strong suck is corrected by feeding, with a repeat level to confirm the response.","B":"Incorrect. Intravenous dextrose is used when the newborn cannot feed or does not respond, not as the first measure here.","C":"Incorrect. Swaddling treats jitteriness from over-stimulation, not documented hypoglycaemia, and a 2-hour delay is unsafe.","D":"Incorrect. Monitoring must continue until levels are stable, because rebound hypoglycaemia is common in these newborns."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential', 'Maternity', 'Multisystem',
 'Newborn hypoglycaemia', 'Infant of a diabetic mother',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MMR_512016', 'MATRIX_MR',
 'A nurse is assessing several newborns in the transitional care nursery. For each finding, select every condition the finding should make the nurse suspect. Each finding has at least one condition.',
 'Newborn presentations overlap heavily: the same non-specific signs appear in hypoglycaemia, cold stress and respiratory distress, which is why any one of them prompts a glucose check, a temperature and a respiratory assessment together. Jitteriness with a normal temperature points at glucose; mottled cool skin with a low temperature points at heat loss; grunting, flaring and retractions point at the lungs. Poor feeding and lethargy are the shared late signs that belong to all three and must never be dismissed.',
 '{"rows":[{"id":"r1","text":"Jitteriness and fine tremors with a normal temperature"},{"id":"r2","text":"Axillary temperature 35.9 °C with cool mottled skin"},{"id":"r3","text":"Nasal flaring and intercostal retractions"},{"id":"r4","text":"Poor feeding and lethargy"},{"id":"r5","text":"Expiratory grunting with a rising oxygen requirement"},{"id":"r6","text":"Blood glucose 1.7 mmol/L (31 mg/dL) after an hour in a cold cot"}],"columns":[{"id":"c1","text":"Hypoglycaemia"},{"id":"c2","text":"Cold stress"},{"id":"c3","text":"Respiratory distress"}],"row_label":"Finding"}'::jsonb,
 '{"cells":{"r1":["c1"],"r2":["c2"],"r3":["c3"],"r4":["c1","c2","c3"],"r5":["c3"],"r6":["c1","c2"]},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential', 'Maternity', 'Multisystem',
 'Newborn transition', 'Overlapping signs of instability',
 'Very hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_512017', 'MCQ',
 'A newborn is visibly jaundiced to the level of the chest at 18 hours of age. Which conclusion should the nurse draw?',
 'Physiological jaundice does not become visible before 24 hours of age, because it depends on the normal breakdown of surplus red cells and a liver that is only gradually conjugating bilirubin. Jaundice appearing within the first 24 hours is pathological until proved otherwise and usually reflects haemolysis, most often from blood group incompatibility. It always requires a measured bilirubin level and medical review rather than observation.',
 '{"options":[{"id":"A","text":"The jaundice is pathological, so the nurse should obtain a serum bilirubin level and notify the provider"},{"id":"B","text":"The jaundice is physiological because it has appeared within the first 3 days of life"},{"id":"C","text":"The jaundice is breast milk jaundice, so feeds should be stopped for 24 hours"},{"id":"D","text":"The jaundice is expected after a vaginal birth and can be re-checked at discharge"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Jaundice within the first 24 hours is pathological until proved otherwise and needs a measured level.","B":"Incorrect. Physiological jaundice appears after 24 hours, typically peaking on days 3 to 5.","C":"Incorrect. Breast milk jaundice appears later, and stopping breastfeeding is not the response to early jaundice.","D":"Incorrect. Deferring assessment risks a rapidly rising bilirubin from haemolysis going undetected."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential', 'Maternity', 'Hematologic',
 'Newborn jaundice', 'Physiological versus pathological',
 'Medium', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_512018', 'SATA',
 'A newborn is receiving intensive phototherapy for hyperbilirubinaemia. Which nursing actions are appropriate? Select all that apply.',
 'Phototherapy converts unconjugated bilirubin in the skin into water-soluble isomers that can be excreted without conjugation, so the effect depends on the area of skin exposed. Eye shields protect the retina from the intense light, and the radiant energy plus increased stool water loss threaten both temperature stability and hydration. Lotions and oils absorb the light and can cause burns, so the skin is left bare.',
 '{"options":[{"id":"A","text":"Apply protective eye shields whenever the lights are on"},{"id":"B","text":"Undress the newborn to a nappy to expose the maximum skin surface"},{"id":"C","text":"Monitor the axillary temperature at least every 4 hours"},{"id":"D","text":"Apply an emollient lotion to the exposed skin to prevent drying"},{"id":"E","text":"Encourage frequent feeds and record the number of wet nappies and stools"},{"id":"F","text":"Keep the newborn in one position for the whole treatment to protect the eyes"}]}'::jsonb,
 '{"answers":["A","B","C","E"],"feedback":{"A":"Correct. Eye shields protect the retina from the intensity of the light.","B":"Correct. The response to phototherapy depends on the area of skin exposed.","C":"Correct. Radiant heat and increased insensible loss make both hyperthermia and instability possible.","D":"Incorrect. Lotions and oils absorb the light energy and can cause skin burns.","E":"Correct. Frequent feeds replace increased stool and insensible water loss and speed bilirubin excretion.","F":"Incorrect. The newborn is repositioned regularly so all skin surfaces receive the light."}}'::jsonb,
 'Physiological Integrity', 'Basic Care and Comfort', 'Maternity', 'Hematologic',
 'Newborn jaundice', 'Phototherapy care',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_512019', 'MCQ',
 'A 4-day-old readmitted from home has a total serum bilirubin of 460 micromol/L (27 mg/dL). The newborn has a high-pitched cry, refuses feeds and now lies with the neck and back arched backwards. Which action is the PRIORITY?',
 'The hyperextended, arched posture is opisthotonos, a sign that unconjugated bilirubin has crossed the blood-brain barrier and is staining the basal ganglia. This is acute bilirubin encephalopathy, and without immediate reduction of the circulating bilirubin it progresses to kernicterus, with permanent choreoathetoid cerebral palsy, hearing loss and gaze abnormalities. Intensive phototherapy is continued while urgent exchange transfusion is arranged, because at this level phototherapy alone cannot lower the bilirubin fast enough.',
 '{"options":[{"id":"A","text":"Notify the provider immediately and prepare for urgent exchange transfusion while continuing intensive phototherapy"},{"id":"B","text":"Place the newborn prone under the phototherapy lights and reassess in 1 hour"},{"id":"C","text":"Offer a formula feed to encourage bilirubin excretion in the stool"},{"id":"D","text":"Position the newborn with the neck flexed onto a pillow to relieve the arching"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Opisthotonos with a bilirubin at this level is acute bilirubin encephalopathy and demands immediate exchange transfusion.","B":"Incorrect. Waiting an hour allows further bilirubin staining of the brain, and prone positioning is unsafe.","C":"Incorrect. Feeding helps mild jaundice but cannot lower a bilirubin of this magnitude, and the newborn is refusing feeds.","D":"Incorrect. A pillow is an airway and suffocation hazard, and repositioning does not treat the underlying cause."}}'::jsonb,
 'Physiological Integrity', 'Physiological Adaptation', 'Maternity', 'Hematologic',
 'Kernicterus', 'Acute bilirubin encephalopathy',
 'Very hard', 'CURATOR_LABEL', 'Evaluate', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SELN_512020', 'SELECT_N',
 'A newborn with severe hyperbilirubinaemia is being monitored for acute bilirubin encephalopathy. Which 3 findings should the nurse report immediately?',
 'Acute bilirubin encephalopathy begins with lethargy, hypotonia and a poor suck, then progresses to a shrill high-pitched cry, hypertonia and retrocollis with opisthotonos as bilirubin stains the basal ganglia. These neurological signs, not the appearance of the skin, are what mark the transition from a treatable bilirubin level to permanent injury. Yellow seedy stools and fading jaundice are signs that treatment is working.',
 '{"options":[{"id":"A","text":"High-pitched shrill cry"},{"id":"B","text":"Backward arching of the neck and trunk"},{"id":"C","text":"Yellow seedy stools four times a day"},{"id":"D","text":"Extreme lethargy with a poor suck"},{"id":"E","text":"Jaundice of the face that is fading"},{"id":"F","text":"Moro reflex that is symmetrical and brisk"}],"select_count":3}'::jsonb,
 '{"answers":["A","B","D"],"feedback":{"A":"Correct. A shrill high-pitched cry is a classic early sign of bilirubin encephalopathy.","B":"Correct. Opisthotonos indicates bilirubin staining of the basal ganglia and is an emergency.","C":"Incorrect. Frequent yellow seedy stools show that bilirubin is being excreted, which is desirable.","D":"Correct. Lethargy with a poor suck is an early neurological sign that is easily dismissed as sleepiness.","E":"Incorrect. Fading jaundice suggests the bilirubin level is falling.","F":"Incorrect. A symmetrical brisk Moro is a normal neurological finding."}}'::jsonb,
 'Physiological Integrity', 'Physiological Adaptation', 'Maternity', 'Hematologic',
 'Kernicterus', 'Recognition of neurological signs',
 'Very hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728');

INSERT INTO nclex_bank_items (
  item_id, question_type, stem, rationale, content, correct,
  client_needs_category, client_needs_subcategory, nursing_subject, body_system,
  topic, subtopic, difficulty, difficulty_source, bloom_level, tags,
  marks, is_published, is_builder_visible, is_free_sample, cat_pool, batch_id
) VALUES
('NCLEX_MMR_512021', 'MATRIX_MR',
 'A nurse is teaching student nurses about newborn reflexes. For each reflex, select every statement that applies. Each reflex has at least one statement.',
 'Primitive reflexes are brainstem-mediated responses present at birth that disappear as the cortex matures, and their timely disappearance is as important a sign of normal development as their presence. Moro, rooting and stepping all fade by about 4 to 6 months, whereas the plantar (Babinski) response with fanning of the toes normally persists beyond the first birthday until myelination is complete. The parachute reflex is the opposite pattern: it is absent at birth, emerges at around 8 months as a protective response, and persists for life.',
 '{"rows":[{"id":"r1","text":"Moro"},{"id":"r2","text":"Rooting"},{"id":"r3","text":"Plantar (Babinski) response with fanning of the toes"},{"id":"r4","text":"Stepping"},{"id":"r5","text":"Parachute"}],"columns":[{"id":"c1","text":"Present at birth in a healthy term newborn"},{"id":"c2","text":"Expected to disappear by 6 months of age"},{"id":"c3","text":"Normally still present after 12 months of age"}],"row_label":"Reflex"}'::jsonb,
 '{"cells":{"r1":["c1","c2"],"r2":["c1","c2"],"r3":["c1","c3"],"r4":["c1","c2"],"r5":["c3"]},"feedback":{}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance', 'Maternity', 'Multisystem',
 'Newborn reflexes', 'Presence and expected disappearance',
 'Very hard', 'CURATOR_LABEL', 'Understand', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_512022', 'SATA',
 'A nurse is teaching a first-time mother how to care for the newborn umbilical cord at home. Which instructions should the nurse include? Select all that apply.',
 'The cord stump separates by dry gangrene, so the single most useful measure is to keep it clean, dry and exposed to air rather than covered or moistened. Folding the nappy below the stump prevents urine soaking it, and sponge bathing until separation avoids submerging it. Parents also need the specific signs of omphalitis to report, because infection can spread rapidly into the abdominal wall and bloodstream in a newborn.',
 '{"options":[{"id":"A","text":"Keep the stump clean and dry and leave it exposed to the air"},{"id":"B","text":"Fold the top of the nappy down below the stump"},{"id":"C","text":"Report redness spreading onto the abdomen, a foul odour or any discharge"},{"id":"D","text":"Pull gently on the stump each day so that it separates sooner"},{"id":"E","text":"Give sponge baths until the stump separates, usually within 7 to 14 days"},{"id":"F","text":"Cover the stump with a plaster so that it stays protected"}]}'::jsonb,
 '{"answers":["A","B","C","E"],"feedback":{"A":"Correct. Air exposure and dryness speed separation and reduce infection risk.","B":"Correct. Folding the nappy down keeps urine off the stump.","C":"Correct. These are the signs of omphalitis, which needs urgent treatment in a newborn.","D":"Incorrect. Pulling on the stump causes bleeding and pain; it separates on its own.","E":"Correct. Sponge baths avoid submerging and softening the stump before it separates.","F":"Incorrect. Covering the stump keeps it moist and delays separation."}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance', 'Maternity', 'Integumentary',
 'Newborn cord care', 'Parent teaching',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_512023', 'SATA',
 'A newborn returns to the postnatal ward after a circumcision performed with a clamp technique. Which actions should the nurse take or teach the parents? Select all that apply.',
 'After a clamp circumcision the raw glans is protected with petroleum jelly at each nappy change until healing, unless a plastic ring device was used, in which case nothing is applied. A yellow-white film over the glans from about the second day is granulation tissue and a normal part of healing, not exudate to be removed, and wiping it away causes bleeding and pain. The two findings that must be reported are failure to pass urine, which suggests obstruction or oedema, and bleeding heavier than a few spots.',
 '{"options":[{"id":"A","text":"Apply petroleum jelly to the glans at each nappy change unless a plastic ring device was used"},{"id":"B","text":"Report if the newborn has not passed urine within 6 to 8 hours of the procedure"},{"id":"C","text":"Leave the yellow-white film that forms over the glans after 24 hours undisturbed"},{"id":"D","text":"Wipe the yellow-white film away at each nappy change to prevent infection"},{"id":"E","text":"Report bleeding heavier than a few spots on the nappy"},{"id":"F","text":"Bath the newborn in a bath tub within the first 24 hours to keep the area clean"}]}'::jsonb,
 '{"answers":["A","B","C","E"],"feedback":{"A":"Correct. Petroleum jelly stops the healing glans from adhering to the nappy, but it is omitted with a plastic ring device.","B":"Correct. Failure to void may indicate oedema or obstruction of the urethral meatus.","C":"Correct. The yellow-white film is granulation tissue and part of normal healing.","D":"Incorrect. Removing granulation tissue causes bleeding and delays healing.","E":"Correct. More than a few spots of blood needs pressure and medical review.","F":"Incorrect. Tub bathing is avoided until the site has healed; the area is cleaned by squeezing warm water over it."}}'::jsonb,
 'Physiological Integrity', 'Basic Care and Comfort', 'Maternity', 'Reproductive',
 'Newborn circumcision', 'Postprocedure care',
 'Hard', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_512024', 'MCQ',
 'The nurse is preparing to give vitamin K to a term newborn within the first hour of life. Which action is correct?',
 'Newborns are born with low vitamin K because it crosses the placenta poorly and the gut is not yet colonised with the bacteria that produce it, leaving the clotting factors II, VII, IX and X underproduced. A single 1 mg intramuscular dose prevents vitamin K deficiency bleeding, including the late intracranial form. The vastus lateralis is used because it is the largest and best developed muscle in a newborn and is free of major nerves and vessels.',
 '{"options":[{"id":"A","text":"Give 1 mg intramuscularly into the vastus lateralis to prevent vitamin K deficiency bleeding"},{"id":"B","text":"Give 1 mg intramuscularly into the dorsogluteal muscle"},{"id":"C","text":"Give 1 mg subcutaneously into the abdomen to reduce pain"},{"id":"D","text":"Withhold the dose until the newborn has fed, because vitamin K is absorbed with milk"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. A single 1 mg intramuscular dose into the vastus lateralis is the standard prophylaxis.","B":"Incorrect. The dorsogluteal site is not used in newborns because the gluteal muscle is undeveloped and the sciatic nerve is close.","C":"Incorrect. The intramuscular route is required for reliable absorption and sustained protection.","D":"Incorrect. Feeding is unrelated; the dose is given within the first hours regardless of feeding."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Maternity', 'Hematologic',
 'Newborn prophylaxis', 'Vitamin K administration',
 'Very easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_512025', 'MCQ',
 'A mother asks the nurse to delay the erythromycin eye ointment so that she can hold her newborn skin-to-skin and make eye contact first. Which response by the nurse is appropriate?',
 'Erythromycin eye ointment prevents gonococcal and chlamydial ophthalmia neonatorum acquired during passage through the birth canal, and it remains effective when given within the first hours after birth. Because the ointment blurs vision briefly and can cause mild chemical irritation, a short delay of up to an hour to support bonding and eye contact is accepted practice. The ointment is not wiped off or flushed away, as contact time is what makes it work.',
 '{"options":[{"id":"A","text":"The ointment can be delayed for up to an hour so you can hold your baby, as long as it is given within the first hours after birth"},{"id":"B","text":"The ointment must be given in the delivery room before you hold your baby"},{"id":"C","text":"I will give the ointment now and then flush the eyes with sterile water so your baby can see you clearly"},{"id":"D","text":"The ointment is optional and can be left out if you would prefer to hold your baby"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. A delay of up to an hour supports bonding without losing the protective effect.","B":"Incorrect. Immediate administration is not required and needlessly interrupts the first skin-to-skin period.","C":"Incorrect. Flushing removes the ointment before it has had contact time and defeats the prophylaxis.","D":"Incorrect. Prophylaxis is a legal or policy requirement in most settings and prevents blinding infection."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Maternity', 'Multisystem',
 'Newborn prophylaxis', 'Eye ointment administration',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SELN_512026', 'SELECT_N',
 'A nurse is collecting the newborn blood spot screening sample. Which 3 actions should the nurse take?',
 'The screen detects metabolic and endocrine disorders such as phenylketonuria and congenital hypothyroidism, several of which are only detectable once the newborn has been taking milk feeds long enough to load the affected pathway, so the sample is taken after at least 24 hours of feeding. Warming the heel increases blood flow and lets a free-flowing drop form without squeezing, which would haemolyse the sample. The lateral aspect of the heel is used because the calcaneus lies close to the surface centrally and puncture there risks osteomyelitis.',
 '{"options":[{"id":"A","text":"Collect the sample after the newborn has been taking milk feeds for at least 24 hours"},{"id":"B","text":"Warm the heel before the puncture"},{"id":"C","text":"Puncture the lateral aspect of the heel"},{"id":"D","text":"Puncture the centre of the heel to obtain a larger sample"},{"id":"E","text":"Layer several drops onto the same circle until the card is soaked through"},{"id":"F","text":"Collect the sample within the first 2 hours of birth so that it is not forgotten"}],"select_count":3}'::jsonb,
 '{"answers":["A","B","C"],"feedback":{"A":"Correct. Several conditions are only detectable once feeding has loaded the metabolic pathway.","B":"Correct. Warming increases blood flow so a free-flowing drop forms without squeezing.","C":"Correct. The lateral heel avoids the calcaneus and the risk of osteomyelitis.","D":"Incorrect. The central heel overlies the calcaneus and must be avoided.","E":"Incorrect. Layering drops gives an invalid sample; each circle is filled with a single drop that soaks through.","F":"Incorrect. A sample this early gives false negative results for several of the conditions screened."}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance', 'Maternity', 'Multisystem',
 'Newborn screening', 'Blood spot collection',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_512027', 'SATA',
 'A community nurse visits a mother and her exclusively breastfed newborn on day 5. Which findings indicate that breastfeeding is going well? Select all that apply.',
 'Because the volume taken at the breast cannot be measured, adequacy is judged from what comes out and from what happens during the feed. By day 5 the nurse expects at least six wet nappies and three or more soft yellow seedy stools in 24 hours, 8 to 12 feeds in 24 hours, and audible swallowing showing that milk is being transferred. Nipple pain throughout a feed and a latch onto the nipple tip alone signal a shallow attachment that will damage the nipple and limit transfer.',
 '{"options":[{"id":"A","text":"Six or more wet nappies in 24 hours"},{"id":"B","text":"Three or four soft yellow seedy stools in 24 hours"},{"id":"C","text":"Audible swallowing during the feed"},{"id":"D","text":"The newborn latches onto the tip of the nipple only"},{"id":"E","text":"The mother reports sharp nipple pain throughout every feed"},{"id":"F","text":"The newborn feeds 8 to 12 times in 24 hours"}]}'::jsonb,
 '{"answers":["A","B","C","F"],"feedback":{"A":"Correct. Six or more wet nappies by day 5 shows adequate intake.","B":"Correct. Yellow seedy stools show that the newborn is receiving milk beyond the initial colostrum.","C":"Correct. Audible swallowing is direct evidence of milk transfer.","D":"Incorrect. A nipple-tip latch is shallow, damages the nipple and transfers little milk.","E":"Incorrect. Pain throughout the feed indicates poor attachment and needs the latch to be corrected.","F":"Correct. Frequent feeding at this stage both meets need and drives milk supply."}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance', 'Maternity', 'Multisystem',
 'Newborn feeding', 'Breastfeeding adequacy',
 'Medium', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SELN_512028', 'SELECT_N',
 'A nurse is observing a mother prepare formula for her 2-week-old. Which 3 statements by the mother indicate correct technique?',
 'Formula is not sterile and newborn immunity is immature, so hand hygiene, sterilised equipment and discarding milk left after a feed prevent gastroenteritis. Over-dilution to make a tin last longer is a common and dangerous economy: it under-feeds the newborn and can cause water intoxication with hyponatraemic seizures. Microwaving is avoided because it heats unevenly and produces hot spots that scald the mouth even when the bottle feels cool.',
 '{"options":[{"id":"A","text":"I wash my hands and sterilise the bottles and teats before I start"},{"id":"B","text":"I use the scoop that came in the tin and level it off without packing it down"},{"id":"C","text":"I throw away any formula left in the bottle at the end of a feed"},{"id":"D","text":"I add extra water to each bottle so that the tin lasts longer"},{"id":"E","text":"I warm the bottle in the microwave for 30 seconds"},{"id":"F","text":"I leave a made-up bottle standing at room temperature for up to 8 hours"}],"select_count":3}'::jsonb,
 '{"answers":["A","B","C"],"feedback":{"A":"Correct. Formula is not sterile, so clean hands and sterilised equipment are essential.","B":"Correct. Using the correct scoop levelled off gives the intended concentration.","C":"Correct. Milk left after a feed is contaminated with saliva and must be discarded.","D":"Incorrect. Over-dilution under-feeds the newborn and risks water intoxication and hyponatraemic seizures.","E":"Incorrect. Microwaving heats unevenly and creates hot spots that scald the mouth.","F":"Incorrect. Made-up formula standing at room temperature allows rapid bacterial growth."}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance', 'Maternity', 'Multisystem',
 'Newborn feeding', 'Formula preparation',
 'Easy', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_512029', 'MCQ',
 'At 2 hours of age a newborn has expiratory grunting, nasal flaring and intercostal retractions, with a respiratory rate of 78 breaths per minute. Which action should the nurse take FIRST?',
 'Grunting, flaring and retractions are the newborn signs of increased work of breathing and mean the lungs are failing to establish or maintain functional residual capacity. The first action supports oxygenation and gathers objective data at the same time: open the airway in a neutral position, apply saturation monitoring and summon help without leaving the newborn. Feeding a newborn who is working this hard to breathe risks aspiration, and investigations must not delay respiratory support.',
 '{"options":[{"id":"A","text":"Position the airway in a neutral position, apply oxygen saturation monitoring and stay with the newborn while calling for help"},{"id":"B","text":"Wrap the newborn warmly and take the newborn to the mother for a feed"},{"id":"C","text":"Obtain the full set of blood cultures before contacting the neonatal team"},{"id":"D","text":"Pass a nasogastric tube and aspirate the stomach contents"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Airway and oxygenation come first, and the newborn is not left alone while help is summoned.","B":"Incorrect. Feeding a newborn with this work of breathing risks aspiration and delays treatment.","C":"Incorrect. Cultures are likely to be needed, but they must not delay respiratory support.","D":"Incorrect. Gastric aspiration does not relieve the respiratory distress and delays definitive care."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential', 'Maternity', 'Multisystem',
 'Newborn respiratory distress', 'Immediate management',
 'Hard', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_512030', 'MCQ',
 'A nurse receives handover on four newborns on the postnatal ward. Which newborn should the nurse assess FIRST?',
 'Prioritisation depends on separating findings that reflect a failing physiological system from findings that are normal variations. Grunting with a respiratory rate of 76 breaths per minute is increased work of breathing and the only finding here that threatens oxygenation. The bluish-grey sacral macules, the blotchy rash with central papules and the firm swelling bounded by suture lines are congenital dermal melanocytosis, erythema toxicum and a cephalohaematoma, all of which are assessed but none of which is urgent.',
 '{"options":[{"id":"A","text":"A 3-hour-old with expiratory grunting and a respiratory rate of 76 breaths per minute"},{"id":"B","text":"A 12-hour-old with bluish-grey macular areas over the sacrum"},{"id":"C","text":"A 2-day-old with a blotchy rash with central white papules over the trunk"},{"id":"D","text":"A 36-hour-old with a firm swelling over one parietal bone that does not cross the suture lines"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Grunting with tachypnoea is increased work of breathing and is the only finding that threatens oxygenation.","B":"Incorrect. These are congenital dermal melanocytosis, a normal pigmentary variation that needs documentation, not urgent review.","C":"Incorrect. This describes erythema toxicum, a benign self-limiting newborn rash.","D":"Incorrect. This is a cephalohaematoma, which needs bilirubin monitoring over days rather than immediate assessment."}}'::jsonb,
 'Safe and Effective Care Environment', 'Management of Care', 'Maternity', 'Multisystem',
 'Newborn prioritisation', 'Assessing which newborn first',
 'Very hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728');

INSERT INTO nclex_bank_items (
  item_id, question_type, stem, rationale, content, correct,
  client_needs_category, client_needs_subcategory, nursing_subject, body_system,
  topic, subtopic, difficulty, difficulty_source, bloom_level, tags,
  marks, is_published, is_builder_visible, is_free_sample, cat_pool, batch_id
) VALUES
('NCLEX_DO_512031', 'DRAG_ORDER',
 'A nurse is carrying out a systematic postpartum assessment on a client 8 hours after a vaginal birth. Place the assessments in the order in which the nurse should perform them. One option will not be used.',
 'A postpartum assessment follows the BUBBLE-HE sequence: breasts, uterus, bladder, bowel, lochia, episiotomy or perineum, then Homans or lower limbs and emotional state. Working head to toe in a fixed order means nothing is missed and findings are recorded in the same sequence at every shift, so a change is obvious. Deep tendon reflexes and clonus belong to the assessment of a client with pre-eclampsia or receiving magnesium sulfate, not to routine postpartum care.',
 '{"slots":[{"id":"s1","target_text":"1st"},{"id":"s2","target_text":"2nd"},{"id":"s3","target_text":"3rd"},{"id":"s4","target_text":"4th"},{"id":"s5","target_text":"5th"},{"id":"s6","target_text":"6th"}],"tokens":[{"id":"t1","text":"Breasts and nipples"},{"id":"t2","text":"Uterine fundus"},{"id":"t3","text":"Bladder"},{"id":"t4","text":"Bowel sounds and passage of flatus"},{"id":"t5","text":"Lochia"},{"id":"t6","text":"Perineum, including any episiotomy or laceration"},{"id":"t7","text":"Deep tendon reflexes and clonus"}]}'::jsonb,
 '{"slots":{"s1":"t1","s2":"t2","s3":"t3","s4":"t4","s5":"t5","s6":"t6"}}'::jsonb,
 'Physiological Integrity', 'Basic Care and Comfort', 'Maternity', 'Reproductive',
 'Postpartum assessment', 'BUBBLE-HE sequence',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_512032', 'MCQ',
 'A nurse is about to palpate the fundus of a client 6 hours after a vaginal birth. Which action should the nurse take FIRST?',
 'A full bladder lifts and displaces the uterus and prevents it from contracting down, so a fundus palpated over a full bladder gives a false reading of both height and tone. Asking the client to void first means the assessment reflects the uterus itself, and it also removes the commonest reversible cause of a boggy, displaced fundus. Positioning and analgesia matter but come after the bladder has been emptied.',
 '{"options":[{"id":"A","text":"Ask the client to empty her bladder"},{"id":"B","text":"Administer the prescribed analgesia"},{"id":"C","text":"Place the client in a left lateral position"},{"id":"D","text":"Position the client supine with the knees flexed"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. A full bladder displaces the uterus and makes both the height and the tone unreliable.","B":"Incorrect. Analgesia may be appropriate but it does not affect the accuracy of the assessment.","C":"Incorrect. The fundus is palpated with the client supine, not in a lateral position.","D":"Incorrect. This is the correct position for the assessment, but the bladder is emptied before positioning."}}'::jsonb,
 'Physiological Integrity', 'Basic Care and Comfort', 'Maternity', 'Reproductive',
 'Postpartum assessment', 'Fundal palpation technique',
 'Very easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SELN_512033', 'SELECT_N',
 'A nurse assesses a client 12 hours after an uncomplicated vaginal birth. Which 3 findings should the nurse document as expected?',
 'In the first 12 hours the fundus is firm, midline and at or just above the umbilicus, and the lochia is rubra, moderate in amount and may contain a few small clots. A temperature up to 38 °C in the first 24 hours is attributed to the dehydration and muscular effort of labour and is not treated as infection unless it persists. A boggy displaced fundus, saturation of a pad in 20 minutes and a unilateral swollen calf are each abnormal and each point to a different complication.',
 '{"options":[{"id":"A","text":"Fundus firm, midline and 1 cm above the umbilicus"},{"id":"B","text":"Moderate lochia rubra containing a few small clots"},{"id":"C","text":"Oral temperature 37.8 °C"},{"id":"D","text":"Fundus boggy and displaced to the right"},{"id":"E","text":"A perineal pad saturated in 20 minutes"},{"id":"F","text":"One calf 4 cm larger in circumference than the other"}],"select_count":3}'::jsonb,
 '{"answers":["A","B","C"],"feedback":{"A":"Correct. The fundus is expected at or just above the umbilicus, firm and midline, in the first 12 hours.","B":"Correct. Moderate lochia rubra with a few small clots is expected on day 1.","C":"Correct. A temperature up to 38 °C in the first 24 hours reflects dehydration and the effort of labour.","D":"Incorrect. A boggy displaced fundus suggests a full bladder with uterine atony and requires action.","E":"Incorrect. Saturating a pad within 20 minutes is excessive bleeding and must be escalated.","F":"Incorrect. Unilateral calf enlargement suggests deep vein thrombosis."}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance', 'Maternity', 'Reproductive',
 'Postpartum assessment', 'Expected findings on day 1',
 'Easy', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_CLZ_512034', 'CLOZE',
 'A nurse is teaching a student about normal involution. Complete the sentences. On the fourth postpartum day the nurse expects to palpate the fundus {1} and to find the lochia {2}.',
 'After birth the fundus is at the umbilicus and then descends by about one fingerbreadth, roughly 1 cm, each day, so by day 4 it is about 4 cm below the umbilicus and by day 10 it is no longer palpable abdominally. Lochia follows its own timetable: rubra for about 3 days, then serosa, which is pink to brown, from about days 4 to 10, then alba, creamy white, until about week 6. A fundus that stays high or lochia that returns to bright red suggests subinvolution or retained products.',
 '{"blanks":[{"id":"b1","choices":[{"id":"c1","text":"at the level of the umbilicus"},{"id":"c2","text":"about 4 cm below the umbilicus"},{"id":"c3","text":"at the symphysis pubis"}]},{"id":"b2","choices":[{"id":"c1","text":"bright red and heavy"},{"id":"c2","text":"pink to brown and moderate to scant"},{"id":"c3","text":"creamy white"}]}]}'::jsonb,
 '{"answers":{"b1":"c2","b2":"c2"},"feedback":{}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance', 'Maternity', 'Reproductive',
 'Uterine involution', 'Fundal descent and lochia progression',
 'Medium', 'CURATOR_LABEL', 'Understand', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_512035', 'MCQ',
 'One hour after a vaginal birth the nurse finds the fundus soft and boggy, at the level of the umbilicus and in the midline. The lochia is heavy. Which action should the nurse take FIRST?',
 'A boggy fundus in the midline means the uterine muscle is not contracting, and an uncontracted uterus cannot compress the open sinuses at the placental site, which is why the bleeding is heavy. Massage stimulates the muscle to contract immediately and is the one action a nurse can take without a prescription, so it comes before drugs or escalation. The lower uterine segment is supported with the other hand during massage to prevent uterine inversion.',
 '{"options":[{"id":"A","text":"Massage the fundus until it is firm while supporting the lower uterine segment"},{"id":"B","text":"Insert an indwelling urinary catheter"},{"id":"C","text":"Start the prescribed oxytocin infusion"},{"id":"D","text":"Notify the obstetric team"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. A boggy midline fundus is atony, and massage restores tone immediately without waiting for a prescription.","B":"Incorrect. Catheterisation is the action for a fundus displaced by a full bladder; this fundus is midline.","C":"Incorrect. Oxytocin is likely to follow, but massage is the immediate independent nursing action.","D":"Incorrect. The team is notified if the fundus does not firm with massage, but massage is not delayed for the call."}}'::jsonb,
 'Physiological Integrity', 'Physiological Adaptation', 'Maternity', 'Reproductive',
 'Postpartum fundal assessment', 'Boggy fundus in the midline',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_512036', 'MCQ',
 'Four hours after a vaginal birth the nurse finds the fundus boggy, 2 cm above the umbilicus and displaced to the right. The client has not passed urine since the birth and a bladder scan shows 620 mL. Which action should the nurse take?',
 'A fundus that is high and pushed to one side, almost always the right, is the classic picture of a distended bladder lifting the uterus out of position. While the bladder is full the uterus cannot contract down, so massage alone gives only a temporary response and the bleeding continues. Emptying the bladder, by assisting the client to void and catheterising if she cannot, removes the cause and allows the uterus to contract.',
 '{"options":[{"id":"A","text":"Assist the client to void, and catheterise her if she is unable to do so"},{"id":"B","text":"Massage the fundus every 15 minutes and continue to observe"},{"id":"C","text":"Encourage the client to increase oral fluids and reassess in 2 hours"},{"id":"D","text":"Place the client in a Trendelenburg position"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. A displaced fundus with a distended bladder is corrected by emptying the bladder so the uterus can contract.","B":"Incorrect. Massage gives only a temporary response while the bladder continues to displace the uterus.","C":"Incorrect. More fluid worsens the distension, and a 2-hour delay allows continued blood loss.","D":"Incorrect. Trendelenburg positioning does not empty the bladder and is not indicated for a stable client."}}'::jsonb,
 'Physiological Integrity', 'Physiological Adaptation', 'Maternity', 'Reproductive',
 'Postpartum fundal assessment', 'Boggy fundus displaced by a full bladder',
 'Hard', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_TF_512037', 'TF',
 'A client telephones the postnatal line on the sixth day after a vaginal birth to report that her vaginal loss is now pinkish-brown rather than red. The nurse determines that this is an expected finding. Is the determination correct?',
 'Lochia progresses in a predictable sequence: rubra, dark red, for about 3 days; serosa, pink to brown, from about days 4 to 10; and alba, creamy white, from about day 10 until the sixth week. A change to pink-brown on day 6 is lochia serosa and is exactly what is expected. It is a return to bright red, a foul odour or a sudden increase in volume that would need review.',
 '{"options":[{"id":"A","text":"True"},{"id":"B","text":"False"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Pink to brown loss on day 6 is lochia serosa and follows the expected progression.","B":"Incorrect. Lochia serosa is expected from about day 4 to day 10, so no follow-up is required for this change alone."}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance', 'Maternity', 'Reproductive',
 'Lochia', 'Expected progression',
 'Very easy', 'CURATOR_LABEL', 'Understand', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_512038', 'MCQ',
 'Two hours after a forceps birth a client saturates a perineal pad in 15 minutes. The fundus is firm, midline and 1 cm below the umbilicus, and the blood is bright red and continuous. Which action is the PRIORITY?',
 'Saturating a pad within an hour is excessive bleeding, and saturating one in 15 minutes is heavy loss that needs immediate action. Because the fundus is firm the uterus is contracting normally, so atony is not the source, and a steady bright red trickle with a firm fundus points to trauma of the genital tract, which is more likely after an instrumental birth. Only direct visualisation and repair will stop it, so the obstetric team is contacted rather than continuing nursing measures.',
 '{"options":[{"id":"A","text":"Notify the obstetric team immediately, as a genital tract laceration is the likely source"},{"id":"B","text":"Massage the fundus vigorously for 2 minutes"},{"id":"C","text":"Encourage the client to void and reassess in 30 minutes"},{"id":"D","text":"Apply a cold pack to the perineum and continue to observe"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Heavy bright red bleeding with a firm fundus indicates trauma that needs visualisation and repair.","B":"Incorrect. Massaging an already firm uterus achieves nothing and causes unnecessary pain.","C":"Incorrect. The fundus is firm and correctly positioned, so bladder distension is not the cause, and a 30-minute delay is unsafe.","D":"Incorrect. A cold pack reduces oedema and pain but does not control bleeding from a laceration."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential', 'Maternity', 'Reproductive',
 'Postpartum haemorrhage', 'Bleeding with a firm fundus',
 'Hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_512039', 'SATA',
 'A nurse reviews the labour records of the clients admitted to the postnatal ward. Which factors increase the risk of postpartum haemorrhage? Select all that apply.',
 'Most postpartum haemorrhage is caused by uterine atony, so the risk factors are the ones that leave the uterine muscle over-stretched or exhausted: a prolonged or augmented labour, a large baby, and high parity. Retained placental fragments are the other major cause, because the uterus cannot contract down evenly around retained tissue and bleeding continues despite a partly firm fundus. Early breastfeeding is protective, since suckling releases endogenous oxytocin.',
 '{"options":[{"id":"A","text":"Labour augmented with an oxytocin infusion for 16 hours"},{"id":"B","text":"Birth of a newborn weighing 4.6 kg"},{"id":"C","text":"Grand multiparity"},{"id":"D","text":"Retained placental fragments"},{"id":"E","text":"A birth weight of 3.1 kg at 39 weeks gestation"},{"id":"F","text":"Exclusive breastfeeding started in the first hour after birth"}]}'::jsonb,
 '{"answers":["A","B","C","D"],"feedback":{"A":"Correct. A long augmented labour leaves the myometrium exhausted and prone to atony.","B":"Correct. A macrosomic newborn over-distends the uterus, impairing contraction after birth.","C":"Correct. Repeated pregnancies reduce the contractile efficiency of the uterine muscle.","D":"Correct. The uterus cannot contract down evenly around retained tissue, so bleeding continues.","E":"Incorrect. An average birth weight at term does not over-distend the uterus.","F":"Incorrect. Suckling releases endogenous oxytocin, which promotes contraction and reduces bleeding."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential', 'Maternity', 'Reproductive',
 'Postpartum haemorrhage', 'Risk factor recognition',
 'Medium', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SELN_512040', 'SELECT_N',
 'A client with continuing postpartum bleeding is being monitored for hypovolaemic shock. Which 3 findings indicate that shock is developing?',
 'Pregnancy increases circulating volume by around 40 per cent, so a postpartum client can lose a great deal of blood before the blood pressure falls, which makes a falling blood pressure a late and unreliable sign. The early signs come from compensation and from reduced perfusion: a rising pulse, cool clammy pale skin as blood is shunted centrally, and restlessness or anxiety from cerebral hypoperfusion. Urine output above 30 mL an hour indicates that renal perfusion is still adequate.',
 '{"options":[{"id":"A","text":"Pulse rising from 78 to 122 beats per minute"},{"id":"B","text":"Cool, clammy, pale skin"},{"id":"C","text":"Restlessness and anxiety"},{"id":"D","text":"Urine output of 60 mL in the past hour"},{"id":"E","text":"Blood pressure rising from 110/70 to 128/78 mmHg"},{"id":"F","text":"Warm flushed cheeks with a slow bounding pulse"}],"select_count":3}'::jsonb,
 '{"answers":["A","B","C"],"feedback":{"A":"Correct. Tachycardia is the earliest compensatory response to falling circulating volume.","B":"Correct. Peripheral vasoconstriction shunts blood centrally and produces cool, clammy, pale skin.","C":"Correct. Restlessness reflects reduced cerebral perfusion and often precedes any fall in blood pressure.","D":"Incorrect. An output above 30 mL an hour indicates that renal perfusion is still adequate.","E":"Incorrect. Blood pressure falls, not rises, in hypovolaemia, and any fall is a late sign.","F":"Incorrect. Warm flushed skin with a bounding pulse is the opposite of the hypovolaemic picture."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential', 'Maternity', 'Multisystem',
 'Postpartum haemorrhage', 'Recognising hypovolaemic shock',
 'Very hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728');

INSERT INTO nclex_bank_items (
  item_id, question_type, stem, rationale, content, correct,
  client_needs_category, client_needs_subcategory, nursing_subject, body_system,
  topic, subtopic, difficulty, difficulty_source, bloom_level, tags,
  marks, is_published, is_builder_visible, is_free_sample, cat_pool, batch_id
) VALUES
('NCLEX_MCQ_512041', 'MCQ',
 'A nurse is assessing a client on the third postpartum day for deep vein thrombosis. Which assessment gives the most reliable information?',
 'Pregnancy and the puerperium are hypercoagulable states, so deep vein thrombosis is a real risk and the assessment must be objective. Measuring both calves at the same marked point, conventionally 10 cm below the tibial tuberosity, and comparing them detects the unilateral swelling that is the most consistent physical sign, and the mark allows the same point to be remeasured each day. Homans sign is unreliable, being negative in most clients with a confirmed thrombosis and positive in many conditions that are not thrombosis, and forced dorsiflexion is no longer recommended.',
 '{"options":[{"id":"A","text":"Measuring and comparing the circumference of both calves at the same marked distance below the tibial tuberosity"},{"id":"B","text":"Dorsiflexing the foot and asking the client about calf pain, the Homans sign"},{"id":"C","text":"Palpating both pedal pulses and comparing them"},{"id":"D","text":"Asking the client to walk the length of the corridor and report any pain"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Serial bilateral measurement from a fixed marked point objectively detects unilateral swelling and can be repeated identically each day.","B":"Incorrect. Homans sign is insensitive and non-specific, and forced dorsiflexion is no longer recommended.","C":"Incorrect. Pedal pulses assess arterial flow and remain present in venous thrombosis.","D":"Incorrect. Exertion is not a diagnostic test and provokes pain in many other conditions."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential', 'Maternity', 'Multisystem',
 'Postpartum thrombophlebitis', 'Calf circumference assessment',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_512042', 'MCQ',
 'A student nurse is caring for a client on the fourth postpartum day whose left calf is warm, reddened, oedematous and tender. The student begins to massage the calf to relieve the discomfort. Which action should the nurse take?',
 'A warm, red, swollen, tender calf in the puerperium is treated as a deep vein thrombosis until imaging says otherwise. Massaging or vigorously exercising the limb can dislodge the clot and send it to the pulmonary circulation, so the nurse must intervene at once rather than modify the technique. Supervising nurses are accountable for stopping unsafe practice by a student and for explaining the reasoning so the learning is carried forward.',
 '{"options":[{"id":"A","text":"Stop the student immediately, explain the risk of dislodging a thrombus, and report the findings to the provider"},{"id":"B","text":"Allow the massage to continue but ask the student to use lighter pressure"},{"id":"C","text":"Ask the student to apply a cold pack once the massage is finished"},{"id":"D","text":"Instruct the student to have the client walk after the massage to improve circulation"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Massage risks embolising the clot, so the nurse stops it at once, teaches the reason and escalates the findings.","B":"Incorrect. Any pressure over a suspected thrombus can dislodge it; lighter pressure is not safer.","C":"Incorrect. Applying a cold pack afterwards does not undo the risk taken during the massage.","D":"Incorrect. Mobilising the limb after manipulation compounds the risk of pulmonary embolism."}}'::jsonb,
 'Safe and Effective Care Environment', 'Management of Care', 'Maternity', 'Multisystem',
 'Postpartum thrombophlebitis', 'Supervising unsafe practice',
 'Hard', 'CURATOR_LABEL', 'Evaluate', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_512043', 'SATA',
 'On the third postpartum day a client has a temperature of 38.6 °C, uterine tenderness and foul-smelling lochia. Which actions should the nurse take? Select all that apply.',
 'Fever after the first 24 hours with uterine tenderness and offensive lochia is endometritis, an ascending infection of the uterine lining. Specimens are taken before the first antibiotic dose so the organism can still be grown, and an upright or semi-Fowler position uses gravity to promote drainage of infected lochia rather than allowing it to pool in the uterus. Fever and infection raise fluid requirements, and scrupulous hand hygiene limits spread to the newborn and to other clients.',
 '{"options":[{"id":"A","text":"Obtain the prescribed cultures before the first antibiotic dose is given"},{"id":"B","text":"Position the client in a semi-Fowler position to promote drainage of lochia"},{"id":"C","text":"Encourage an oral fluid intake of at least 3 litres a day unless contraindicated"},{"id":"D","text":"Keep the client on bed rest lying flat"},{"id":"E","text":"Reinforce hand hygiene before and after perineal care and nappy changes"},{"id":"F","text":"Stop breastfeeding until the antibiotic course is complete"}]}'::jsonb,
 '{"answers":["A","B","C","E"],"feedback":{"A":"Correct. Cultures taken before antibiotics still identify the organism and guide treatment.","B":"Correct. An upright position lets gravity drain infected lochia instead of allowing it to pool.","C":"Correct. Fever and infection increase fluid requirements and support the response to treatment.","D":"Incorrect. Lying flat encourages pooling of lochia, and early mobilisation reduces thrombosis risk.","E":"Correct. Hand hygiene limits transmission to the newborn and to other clients.","F":"Incorrect. Breastfeeding usually continues, and antibiotics are chosen to be compatible with it."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential', 'Maternity', 'Reproductive',
 'Postpartum infection', 'Endometritis management',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_512044', 'SATA',
 'A breastfeeding client is diagnosed with mastitis of the left breast on the tenth postpartum day. Which instructions should the nurse give? Select all that apply.',
 'Mastitis is inflammation of breast tissue that usually begins with milk stasis, so the treatment that matters most is keeping the affected breast well drained by continuing to feed or express. The milk is safe for the newborn, and stopping feeding worsens the stasis and can lead to an abscess. Warmth before a feed encourages let-down, and the antibiotic course is completed in full because partial treatment leads to relapse and abscess formation.',
 '{"options":[{"id":"A","text":"Continue to breastfeed or express from the affected breast so that it is emptied fully"},{"id":"B","text":"Apply a warm compress to the breast just before a feed"},{"id":"C","text":"Complete the whole course of the prescribed antibiotic"},{"id":"D","text":"Stop feeding from the affected breast until the infection has cleared"},{"id":"E","text":"Rest, increase fluid intake and take the prescribed analgesia"},{"id":"F","text":"Bind both breasts tightly to reduce milk production"}]}'::jsonb,
 '{"answers":["A","B","C","E"],"feedback":{"A":"Correct. Emptying the breast relieves the milk stasis that underlies mastitis, and the milk is safe for the newborn.","B":"Correct. Warmth before a feed encourages let-down and helps the breast drain.","C":"Correct. Stopping the antibiotic early leads to relapse and abscess formation.","D":"Incorrect. Stopping feeds worsens stasis and increases the risk of an abscess.","E":"Correct. Rest, extra fluids and analgesia support recovery from a systemic infection.","F":"Incorrect. Tight binding increases stasis and pain in a breastfeeding client."}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance', 'Maternity', 'Reproductive',
 'Mastitis', 'Client teaching',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_512045', 'SATA',
 'A client who has chosen not to breastfeed has firm, painful, engorged breasts on the third postpartum day. Which measures should the nurse suggest? Select all that apply.',
 'In a client who is not breastfeeding the aim is to suppress lactation, so every measure works by avoiding stimulation and reducing blood flow to the breast. Firm support, cold applications and analgesia relieve the discomfort while the milk is reabsorbed over a few days. Warmth, expressing and even letting water run over the nipples in the shower all trigger let-down and prolong the engorgement.',
 '{"options":[{"id":"A","text":"Wear a well-fitting supportive bra day and night"},{"id":"B","text":"Apply cold packs to the breasts"},{"id":"C","text":"Take the prescribed simple analgesia"},{"id":"D","text":"Express a small amount of milk each time the breasts feel full"},{"id":"E","text":"Let warm water run over the breasts in the shower"},{"id":"F","text":"Avoid any stimulation of the nipples, including running water directly over them"}]}'::jsonb,
 '{"answers":["A","B","C","F"],"feedback":{"A":"Correct. Firm support reduces movement, discomfort and stimulation.","B":"Correct. Cold reduces blood flow and swelling and eases the pain.","C":"Correct. Engorgement is genuinely painful and analgesia is appropriate.","D":"Incorrect. Expressing signals the breast to make more milk and prolongs the engorgement.","E":"Incorrect. Warm water triggers let-down and increases milk production.","F":"Correct. Avoiding all nipple stimulation allows lactation to suppress."}}'::jsonb,
 'Physiological Integrity', 'Basic Care and Comfort', 'Maternity', 'Reproductive',
 'Breast engorgement', 'Lactation suppression',
 'Very easy', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MAT_512046', 'MATRIX',
 'A nurse is reviewing postpartum mood disorders with a group of new staff. For each presentation, indicate the condition it best describes.',
 'Postpartum blues affects up to 80 per cent of mothers, begins around day 3 as hormone levels fall, is mild and self-limiting and resolves by about day 10 without treatment. Postpartum depression develops over weeks, persists beyond a fortnight and impairs function, with hopelessness, anhedonia and disturbed sleep, and needs assessment and treatment. Postpartum psychosis is rare but is a psychiatric emergency: delusions and hallucinations about the baby carry a real risk of infanticide and suicide and demand immediate protection of both mother and baby.',
 '{"rows":[{"id":"r1","text":"Tearfulness and mood swings beginning on day 3 and resolving by day 10 without treatment"},{"id":"r2","text":"Persistent hopelessness, loss of interest in the baby and disturbed sleep continuing at 8 weeks"},{"id":"r3","text":"Reports hearing a voice telling her that the baby is evil and must be saved"},{"id":"r4","text":"Feeling overwhelmed and crying easily but still able to care for herself and the baby"},{"id":"r5","text":"Belief that the baby has been swapped for another infant"},{"id":"r6","text":"Intrusive thoughts of being a failure as a mother, with appetite loss, at 6 weeks"}],"columns":[{"id":"c1","text":"Postpartum blues"},{"id":"c2","text":"Postpartum depression"},{"id":"c3","text":"Postpartum psychosis"}],"row_label":"Presentation"}'::jsonb,
 '{"cells":{"r1":"c1","r2":"c2","r3":"c3","r4":"c1","r5":"c3","r6":"c2"},"feedback":{}}'::jsonb,
 'Psychosocial Integrity', 'Psychosocial Integrity', 'Maternity', 'Multisystem',
 'Postpartum mood disorders', 'Blues, depression and psychosis',
 'Hard', 'CURATOR_LABEL', 'Analyze', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_512047', 'MCQ',
 'On the eighth postpartum day a client tells the nurse that her baby is possessed and that she has been told she must protect him from the evil inside him. Which action is the PRIORITY?',
 'Delusional beliefs about the baby occurring in the first weeks after birth indicate postpartum psychosis, which is a psychiatric emergency rather than an exaggerated form of the blues. The immediate risk is to the infant and to the mother, and command beliefs of this kind are associated with infanticide and suicide. Safety therefore comes first: the mother is not left unsupervised with the baby and urgent psychiatric assessment is arranged.',
 '{"options":[{"id":"A","text":"Ensure the client is not left alone with the baby and arrange urgent psychiatric review"},{"id":"B","text":"Reassure the client that these thoughts are a normal part of postpartum blues"},{"id":"C","text":"Encourage the client to sleep and reassess her thinking in the morning"},{"id":"D","text":"Ask the partner to take the client home so that she can rest in familiar surroundings"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Delusional beliefs about the baby are a psychiatric emergency, and protecting the infant while arranging urgent review is the priority.","B":"Incorrect. Delusions are never part of postpartum blues, and false reassurance delays lifesaving treatment.","C":"Incorrect. Sleep may be needed but leaving the situation until morning leaves the baby at risk.","D":"Incorrect. Discharging a client with active delusions about her baby removes supervision at the point of greatest danger."}}'::jsonb,
 'Psychosocial Integrity', 'Psychosocial Integrity', 'Maternity', 'Multisystem',
 'Postpartum psychosis', 'Immediate safety response',
 'Very hard', 'CURATOR_LABEL', 'Evaluate', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_512048', 'MCQ',
 'A client who is Rh-negative gives birth to an Rh-positive newborn. The maternal indirect Coombs test is negative and the newborn direct Coombs test is negative. Which action should the nurse expect?',
 'Rh sensitisation happens when fetal Rh-positive red cells enter the maternal circulation, most commonly at birth, and prompt the mother to make anti-D antibodies that would attack the red cells of a future Rh-positive fetus. Rho(D) immune globulin destroys those fetal cells before the maternal immune system can recognise them, so it must be given to the mother within 72 hours of the birth. A negative indirect Coombs test is what confirms she has not already been sensitised and that the dose will still work.',
 '{"options":[{"id":"A","text":"Give Rho(D) immune globulin to the mother within 72 hours of the birth"},{"id":"B","text":"Give Rho(D) immune globulin to the newborn within 72 hours of the birth"},{"id":"C","text":"Withhold Rho(D) immune globulin because the indirect Coombs test is negative"},{"id":"D","text":"Give Rho(D) immune globulin only if the client plans a further pregnancy"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. The mother receives the dose within 72 hours to prevent sensitisation against a future Rh-positive fetus.","B":"Incorrect. The preparation is given to the mother; giving it to the newborn would destroy the newborn own red cells.","C":"Incorrect. A negative indirect Coombs test means she is not yet sensitised, which is precisely why the dose will work.","D":"Incorrect. Future intentions can change, and sensitisation once established is permanent."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Maternity', 'Hematologic',
 'Rh incompatibility', 'Postpartum Rho(D) immune globulin',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_512049', 'MCQ',
 'A client who is exclusively breastfeeding her 3-week-old asks the nurse about starting the combined oral contraceptive pill. Which response by the nurse is most appropriate?',
 'Oestrogen in the combined pill can reduce milk volume, so while breastfeeding is being established a progestogen-only method, which does not affect supply, is preferred and can be started in the early weeks. Contraception is genuinely needed because ovulation can return before the first period, so a client who waits for menstruation may already have conceived. Lactational amenorrhoea only offers reliable protection under strict conditions, and few clients meet all of them.',
 '{"options":[{"id":"A","text":"A progestogen-only method is usually recommended while breastfeeding is being established, because the oestrogen in the combined pill can reduce your milk supply"},{"id":"B","text":"You can start the combined pill today, as it has no effect on breast milk"},{"id":"C","text":"You do not need any contraception while you are fully breastfeeding"},{"id":"D","text":"You should wait until your periods return before using any contraception"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Progestogen-only methods do not reduce milk supply and are preferred while lactation is being established.","B":"Incorrect. Oestrogen can reduce milk volume, particularly in the early weeks.","C":"Incorrect. Lactational amenorrhoea is only reliable under strict conditions that few clients meet.","D":"Incorrect. Ovulation can occur before the first period returns, so waiting risks an unplanned pregnancy."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies', 'Maternity', 'Reproductive',
 'Postpartum contraception', 'Method choice while breastfeeding',
 'Hard', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_512050', 'SATA',
 'A nurse is giving discharge teaching to a client after a vaginal birth. Which findings should the nurse tell the client to report? Select all that apply.',
 'Discharge teaching works only if the client can tell the difference between the expected course of the puerperium and the signs of the complications that kill: infection, haemorrhage, thromboembolism and severe mental illness. Fever, heavy bleeding or large clots, unilateral calf pain and thoughts of harming herself or the baby each map onto one of those four. Tiredness and the change from red to pink-brown loss are part of normal recovery and should be named as such so the client is not alarmed by them.',
 '{"options":[{"id":"A","text":"A temperature above 38 °C"},{"id":"B","text":"Soaking a pad within an hour or passing a clot larger than a golf ball"},{"id":"C","text":"Pain, redness or swelling in one calf"},{"id":"D","text":"Thoughts of harming herself or the baby"},{"id":"E","text":"Vaginal loss that changes from red to pink-brown by the end of the first week"},{"id":"F","text":"Feeling tired in the afternoons during the first fortnight"}]}'::jsonb,
 '{"answers":["A","B","C","D"],"feedback":{"A":"Correct. Fever after the first 24 hours suggests puerperal infection and needs review.","B":"Correct. This defines excessive bleeding and may indicate late postpartum haemorrhage.","C":"Correct. Unilateral calf pain or swelling suggests deep vein thrombosis in a hypercoagulable client.","D":"Correct. Thoughts of self-harm or of harming the baby require urgent mental health assessment.","E":"Incorrect. This is lochia serosa and is the expected progression.","F":"Incorrect. Tiredness in the early weeks is expected and does not need to be reported."}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance', 'Maternity', 'Reproductive',
 'Postpartum discharge teaching', 'Warning signs to report',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728');
