-- =========================================================
-- MyNclex — gap-fill batch 05: Paediatric clinical conditions
-- Generated 2026-07-28. batch_id = 'gapfill-20260728'
-- item_id block: 521001-521050 (50 items)
--
-- Coverage: congenital heart defects (cyanotic vs acyanotic,
-- tetralogy of Fallot, transposition of the great arteries,
-- truncus arteriosus, tricuspid atresia, TAPVR, VSD, PDA,
-- coarctation), respiratory, gastrointestinal, neurological,
-- musculoskeletal, genitourinary, haematology/oncology,
-- endocrine and communicable childhood illness.
--
-- To remove:
--   DELETE FROM nclex_bank_items WHERE item_id BETWEEN
--   'NCLEX_A' AND 'NCLEX_Z' AND batch_id = 'gapfill-20260728';
-- =========================================================

-- ── Block 1 (521001-521010) — congenital heart defects ──────────────
INSERT INTO nclex_bank_items (
  item_id, question_type, stem, rationale, content, correct,
  client_needs_category, client_needs_subcategory, nursing_subject, body_system,
  topic, subtopic, difficulty, difficulty_source, bloom_level, tags,
  instruction, marks, is_published, is_builder_visible, is_free_sample, cat_pool, batch_id
) VALUES

('NCLEX_SELN_521001', 'SELECT_N',
 'A nurse is teaching a group of student nurses about tetralogy of Fallot. Which 4 structural defects make up this condition?',
 'Tetralogy of Fallot is defined by four anatomical features that always occur together: pulmonary stenosis, a ventricular septal defect, an aorta that overrides the septum, and right ventricular hypertrophy. The obstruction at the pulmonary valve raises right ventricular pressure above left ventricular pressure, so deoxygenated blood is pushed across the septal defect into the systemic circulation. That right-to-left shunt is why the child is cyanotic rather than simply breathless.',
 '{"options":[{"id":"A","text":"Pulmonary stenosis"},{"id":"B","text":"Ventricular septal defect"},{"id":"C","text":"Overriding aorta"},{"id":"D","text":"Right ventricular hypertrophy"},{"id":"E","text":"Patent ductus arteriosus"},{"id":"F","text":"Coarctation of the aorta"}],"select_count":4}'::jsonb,
 '{"answers":["A","B","C","D"],"feedback":{"A":"Correct. Obstruction to right ventricular outflow is the defect that drives the right-to-left shunt.","B":"Correct. The septal defect provides the route for deoxygenated blood to enter the systemic circulation.","C":"Correct. The aorta sits over the septal defect and receives blood from both ventricles.","D":"Correct. The right ventricle hypertrophies because it pumps against the pulmonary obstruction.","E":"Incorrect. A patent ductus arteriosus is a separate defect, although it may coexist and temporarily improve pulmonary blood flow.","F":"Incorrect. Coarctation is a narrowing of the aortic arch and is not part of this tetrad."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Pediatrics', 'Cardiovascular', 'Tetralogy of Fallot', 'Structural components',
 'Very easy', 'CURATOR_LABEL', 'Remember', '{}', 'Select 4.', 4, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_521002', 'MCQ',
 'A 5-month-old infant with tetralogy of Fallot becomes deeply cyanotic, inconsolable and hyperpnoeic while crying during a nappy change on the paediatric ward. Which action should the nurse take FIRST?',
 'A hypercyanotic or tet spell is an acute worsening of the right-to-left shunt, usually triggered by crying, feeding or straining. Placing the infant in a knee-chest position kinks the femoral arteries and raises systemic vascular resistance, which pushes blood back across the ventricular septal defect towards the lungs. It is a physical manoeuvre the nurse can start immediately, before oxygen, morphine or fluids are prepared.',
 '{"options":[{"id":"A","text":"Administer the prescribed paracetamol"},{"id":"B","text":"Place the infant in a knee-chest position"},{"id":"C","text":"Obtain a 12-lead electrocardiogram"},{"id":"D","text":"Offer the infant a bottle of formula"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. The spell is a shunting event, not a febrile one, and paracetamol does nothing for the hypoxaemia.","B":"Correct. Knee-chest positioning increases systemic vascular resistance and reduces the right-to-left shunt within seconds.","C":"Incorrect. Diagnostics delay treatment of an evolving hypoxic episode.","D":"Incorrect. Feeding increases oxygen demand and commonly triggers or prolongs a spell."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Pediatrics', 'Cardiovascular', 'Tetralogy of Fallot', 'Hypercyanotic spell',
 'Hard', 'CURATOR_LABEL', 'Apply', '{}', NULL, 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_521003', 'MCQ',
 'A term newborn has central cyanosis with an oxygen saturation of 68 per cent that does not rise when 100 per cent oxygen is delivered. Echocardiography confirms transposition of the great arteries. Which prescription should the nurse anticipate?',
 'In transposition the aorta arises from the right ventricle and the pulmonary artery from the left, so the systemic and pulmonary circulations run in parallel rather than in series. Oxygen cannot correct the saturation because oxygenated blood keeps returning to the lungs instead of reaching the body. Survival depends on mixing, so a prostaglandin E1 infusion is started to keep the ductus arteriosus open until a balloon atrial septostomy or an arterial switch operation can be performed.',
 '{"options":[{"id":"A","text":"Intravenous prostaglandin E1 infusion"},{"id":"B","text":"Intravenous indomethacin"},{"id":"C","text":"Oral propranolol"},{"id":"D","text":"Intravenous furosemide"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Prostaglandin E1 keeps the ductus arteriosus patent so the two parallel circulations can mix.","B":"Incorrect. Indomethacin closes the ductus, which would be fatal in this defect.","C":"Incorrect. Propranolol is used to reduce infundibular spasm in tetralogy of Fallot, not to create mixing.","D":"Incorrect. A diuretic treats fluid overload and does nothing for a mixing problem."}}'::jsonb,
 'Physiological Integrity', 'Physiological Adaptation',
 'Pediatrics', 'Cardiovascular', 'Transposition of the great arteries', 'Maintaining ductal patency',
 'Very hard', 'CURATOR_LABEL', 'Analyze', '{}', NULL, 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_TF_521004', 'TF',
 'In transposition of the great arteries the aorta arises from the right ventricle and the pulmonary artery arises from the left ventricle, creating two parallel circulations, so the newborn survives only while a connection such as the ductus arteriosus or an atrial septal defect allows the two circulations to mix. Is this statement true or false?',
 'Normally the circulations run in series: body to right heart to lungs to left heart to body. In transposition the vessels are swapped, so deoxygenated blood circles endlessly around the body and oxygenated blood circles endlessly around the lungs. Without a shunt the newborn has no route for oxygenated blood to reach the tissues, which is why cyanosis appears within hours of birth and worsens as the ductus closes.',
 '{"options":[{"id":"A","text":"True"},{"id":"B","text":"False"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. The two circuits are parallel, so a mixing point is what keeps the newborn alive until surgery.","B":"Incorrect. The description is accurate; parallel circulations with no mixing are incompatible with life."}}'::jsonb,
 'Physiological Integrity', 'Physiological Adaptation',
 'Pediatrics', 'Cardiovascular', 'Transposition of the great arteries', 'Parallel circulations',
 'Easy', 'CURATOR_LABEL', 'Understand', '{}', NULL, 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_521005', 'SATA',
 'A 4-week-old infant with truncus arteriosus is admitted before surgical repair. Which findings should the nurse expect? Select all that apply.',
 'In truncus arteriosus a single great vessel arises above a ventricular septal defect and supplies the systemic, pulmonary and coronary circulations. As pulmonary vascular resistance falls over the first weeks of life, an increasing share of the cardiac output floods the lungs, producing pulmonary overcirculation and congestive heart failure. The picture is therefore tachypnoea, a loud murmur, sweating and exhaustion with feeds, poor weight gain and hepatomegaly rather than a well, thriving baby.',
 '{"options":[{"id":"A","text":"Tachypnoea with a respiratory rate of 72 breaths per minute at rest"},{"id":"B","text":"A loud systolic murmur heard across the praecordium"},{"id":"C","text":"Diaphoresis and fatigue after only a few minutes of feeding"},{"id":"D","text":"Weight gain that has moved the infant up two centile lines"},{"id":"E","text":"Hepatomegaly on abdominal palpation"},{"id":"F","text":"Oxygen saturation consistently above 98 per cent in air"}]}'::jsonb,
 '{"answers":["A","B","C","E"],"feedback":{"A":"Correct. Pulmonary overcirculation produces persistent tachypnoea and increased work of breathing.","B":"Correct. Turbulent flow through the septal defect and the single valve generates a loud murmur.","C":"Correct. Feeding is the hardest work an infant does, so heart failure shows first as sweating and early exhaustion.","D":"Incorrect. Failure to thrive with weight faltering, not accelerated gain, is the expected pattern.","E":"Correct. Systemic venous congestion enlarges the liver, an early sign of right-sided failure in infants.","F":"Incorrect. Mixing of systemic and pulmonary blood in a single trunk produces mild desaturation, not high-normal saturations."}}'::jsonb,
 'Physiological Integrity', 'Physiological Adaptation',
 'Pediatrics', 'Cardiovascular', 'Truncus arteriosus', 'Pulmonary overcirculation',
 'Hard', 'CURATOR_LABEL', 'Analyze', '{}', 'Select all that apply.', 4, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_521006', 'MCQ',
 'The parent of an infant with truncus arteriosus asks why the baby becomes breathless and sweaty after only a few minutes of feeding. Which response by the nurse is BEST?',
 'Explaining the mechanism in plain language helps parents accept the feeding plan that follows, which usually means shorter, more frequent, higher-energy feeds. Because one vessel supplies both the body and the lungs, too much blood flows to the lungs once pulmonary resistance falls, so the heart is already working hard at rest. Feeding adds the metabolic demand of sucking and swallowing, which is why the effort shows up there first.',
 '{"options":[{"id":"A","text":"Too much blood is flowing to the lungs, so the heart is already working hard and the effort of feeding tires the baby quickly"},{"id":"B","text":"The lungs are underdeveloped, so the baby cannot take in enough oxygen while sucking"},{"id":"C","text":"There is a narrowing in the main artery leaving the heart that blocks blood from reaching the body"},{"id":"D","text":"Feeding difficulty at this age is usually reflux, and the heart defect is unlikely to be the cause"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Excess pulmonary blood flow means the heart has little reserve, so the work of feeding causes tachypnoea and diaphoresis.","B":"Incorrect. The lungs are structurally normal; the problem is the volume of blood being delivered to them.","C":"Incorrect. That describes coarctation or aortic stenosis, not a single common arterial trunk.","D":"Incorrect. Dismissing the feeding difficulty misses the earliest and most reliable sign of heart failure in infants."}}'::jsonb,
 'Physiological Integrity', 'Physiological Adaptation',
 'Pediatrics', 'Cardiovascular', 'Truncus arteriosus', 'Parent explanation',
 'Medium', 'CURATOR_LABEL', 'Understand', '{}', NULL, 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MAT_521007', 'MATRIX',
 'A nurse is revising congenital heart defects. For each defect, indicate whether it typically presents as a cyanotic (right-to-left shunt or abnormal mixing) or an acyanotic (left-to-right shunt or obstructive) lesion.',
 'The simplest way to sort congenital defects is to ask which way blood is shunted. Left-to-right shunts and obstructive lesions send fully oxygenated blood around the body, so the child is pink but overloads the lungs and develops heart failure. Right-to-left shunts and mixing lesions deliver deoxygenated blood into the systemic circulation, so the child is blue and the saturation does not correct with oxygen.',
 '{"rows":[{"id":"r1","text":"Tetralogy of Fallot"},{"id":"r2","text":"Ventricular septal defect"},{"id":"r3","text":"Transposition of the great arteries"},{"id":"r4","text":"Coarctation of the aorta"},{"id":"r5","text":"Tricuspid atresia"},{"id":"r6","text":"Total anomalous pulmonary venous return"},{"id":"r7","text":"Patent ductus arteriosus"},{"id":"r8","text":"Atrial septal defect"}],"columns":[{"id":"c1","text":"Cyanotic"},{"id":"c2","text":"Acyanotic"}],"row_label":"Defect"}'::jsonb,
 '{"cells":{"r1":"c1","r2":"c2","r3":"c1","r4":"c2","r5":"c1","r6":"c1","r7":"c2","r8":"c2"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Pediatrics', 'Cardiovascular', 'Congenital heart defects', 'Cyanotic versus acyanotic',
 'Medium', 'CURATOR_LABEL', 'Understand', '{}', 'Select one column for each row.', 8, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_521008', 'MCQ',
 'A 3-week-old infant is being investigated at the paediatric outpatient clinic after a murmur was heard. Which assessment finding would most strongly support a diagnosis of coarctation of the aorta?',
 'Coarctation is a narrowing of the aorta, usually just beyond the left subclavian artery, so perfusion above the narrowing is preserved while perfusion below it is reduced. This produces higher blood pressure and strong pulses in the arms with lower pressure and weak or delayed femoral pulses in the legs. Comparing upper and lower limb pressures and palpating the femoral pulses is therefore the single most useful bedside assessment.',
 '{"options":[{"id":"A","text":"Blood pressure 96/60 mmHg in the arms and 62/38 mmHg in the legs, with weak femoral pulses"},{"id":"B","text":"Equally bounding pulses in all four limbs"},{"id":"C","text":"Oxygen saturation of 70 per cent that does not rise with supplemental oxygen"},{"id":"D","text":"A continuous machinery murmur below the left clavicle"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. An arm-to-leg pressure gradient with weak femoral pulses is the classic sign of aortic narrowing.","B":"Incorrect. Equal bounding pulses argue against an obstruction between the arms and the legs.","C":"Incorrect. Fixed severe desaturation points to a cyanotic mixing lesion such as transposition.","D":"Incorrect. A continuous machinery murmur is characteristic of a patent ductus arteriosus."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Pediatrics', 'Cardiovascular', 'Coarctation of the aorta', 'Four-limb blood pressure',
 'Medium', 'CURATOR_LABEL', 'Analyze', '{}', NULL, 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_521009', 'MCQ',
 'A preterm neonate with a patent ductus arteriosus is prescribed intravenous ibuprofen to close the duct. Which assessment is most important for the nurse to monitor during therapy?',
 'Ibuprofen and indomethacin close the ductus by inhibiting prostaglandin synthesis, but prostaglandins also maintain renal perfusion. Reduced renal blood flow is the most common serious adverse effect, so urine output and serum creatinine are monitored closely, and the drug is withheld if output falls below about 1 mL/kg/hour. These agents also inhibit platelet function, so the nurse watches for bleeding as well.',
 '{"options":[{"id":"A","text":"Urine output and serum creatinine"},{"id":"B","text":"Serum calcium"},{"id":"C","text":"Deep tendon reflexes"},{"id":"D","text":"Pupillary response to light"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Prostaglandin inhibition reduces renal perfusion, so oliguria and a rising creatinine are the key warning signs.","B":"Incorrect. Calcium disturbance is not a recognised effect of ibuprofen therapy for a patent ductus.","C":"Incorrect. Reflex depression is monitored during magnesium sulfate therapy, not prostaglandin inhibitors.","D":"Incorrect. Pupillary changes relate to neurological injury and are not a marker of this drug effect."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pediatrics', 'Cardiovascular', 'Patent ductus arteriosus', 'Ibuprofen for ductal closure',
 'Hard', 'CURATOR_LABEL', 'Apply', '{}', NULL, 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_521010', 'SATA',
 'A 3-month-old infant with a large ventricular septal defect attends the child health clinic. Which findings should the nurse recognise as evidence that the defect is causing heart failure? Select all that apply.',
 'Feeding is the infant equivalent of an exercise test, so heart failure in a baby is usually discovered as a feeding and growth problem rather than as breathlessness on exertion. Prolonged, exhausting feeds with forehead sweating, tachypnoea at rest and weight faltering across centile lines together indicate that the left-to-right shunt is overloading the pulmonary circulation. Recognising this pattern at a routine clinic visit is what triggers earlier referral and surgical planning.',
 '{"options":[{"id":"A","text":"Takes 40 minutes to finish a feed and falls asleep exhausted before completing it"},{"id":"B","text":"Sweating over the forehead and scalp during feeds"},{"id":"C","text":"Weight has crossed downwards through two centile lines since birth"},{"id":"D","text":"Respiratory rate of 68 breaths per minute while asleep"},{"id":"E","text":"Sleeps for one 5-hour stretch overnight"},{"id":"F","text":"Passes six wet nappies in 24 hours"}]}'::jsonb,
 '{"answers":["A","B","C","D"],"feedback":{"A":"Correct. Prolonged feeds ending in exhaustion are a cardinal sign of limited cardiac reserve.","B":"Correct. Sweating during feeds reflects the sympathetic response to the increased work of the heart.","C":"Correct. Weight faltering across centiles is failure to thrive and is often the presenting sign of a significant defect.","D":"Correct. A resting respiratory rate of 68 in a 3-month-old is tachypnoea caused by pulmonary overcirculation.","E":"Incorrect. A settled 5-hour sleep is a normal finding at 3 months and is reassuring.","F":"Incorrect. Six wet nappies a day indicates adequate hydration and renal perfusion."}}'::jsonb,
 'Physiological Integrity', 'Basic Care and Comfort',
 'Pediatrics', 'Cardiovascular', 'Ventricular septal defect', 'Feeding difficulty and failure to thrive',
 'Medium', 'CURATOR_LABEL', 'Analyze', '{}', 'Select all that apply.', 4, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728');

-- ── Block 2 (521011-521020) — heart, then respiratory ───────────────
INSERT INTO nclex_bank_items (
  item_id, question_type, stem, rationale, content, correct,
  client_needs_category, client_needs_subcategory, nursing_subject, body_system,
  topic, subtopic, difficulty, difficulty_source, bloom_level, tags,
  instruction, marks, is_published, is_builder_visible, is_free_sample, cat_pool, batch_id
) VALUES

('NCLEX_MCQ_521011', 'MCQ',
 'At a community clinic a parent asks why an echocardiogram has been arranged after a murmur was heard in an otherwise well 2-month-old. Which response by the nurse is most accurate?',
 'A murmur is simply the sound of turbulent blood flow, and turbulence is exactly what a hole, a narrowing or an abnormal connection produces. Because auscultation alone cannot distinguish an innocent murmur from a structural defect, echocardiography is the standard next step: it images the chambers, valves and great vessels and shows the direction of flow. Explaining this honestly reduces anxiety without promising that nothing is wrong.',
 '{"options":[{"id":"A","text":"The scan uses sound waves to show the structure of the heart and the direction of blood flow, which shows whether the murmur comes from a defect"},{"id":"B","text":"The scan records the electrical activity of the heart to check whether the rhythm is abnormal"},{"id":"C","text":"The scan is arranged only because the doctor must rule out an infection of the heart valves"},{"id":"D","text":"The scan will show today whether the baby needs an operation this week"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Echocardiography images structure and flow, which is what a murmur requires the team to check.","B":"Incorrect. That describes an electrocardiogram, which assesses rhythm rather than anatomy.","C":"Incorrect. Endocarditis is rare in a well 2-month-old; the concern is a structural defect.","D":"Incorrect. Overstating the immediacy raises alarm and may not reflect the findings."}}'::jsonb,
 'Safe and Effective Care Environment', 'Management of Care',
 'Pediatrics', 'Cardiovascular', 'Heart murmur in infancy', 'Purpose of echocardiography',
 'Very easy', 'CURATOR_LABEL', 'Understand', '{}', NULL, 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_CLZ_521012', 'CLOZE',
 'An infant with heart failure is prescribed digoxin. Before each dose the nurse counts the apical rate for {1} and withholds the dose if the rate is below {2} beats per minute.',
 'Digoxin slows conduction through the atrioventricular node, so bradycardia is the first sign that the level is becoming toxic. In infants the apical rate is counted for a full minute because the rhythm is irregular and a shorter count is unreliable, and the dose is withheld and reported if the rate falls below about 90 beats per minute. The threshold rises with age, to roughly 70 in older children and 60 in adults.',
 '{"blanks":[{"id":"b1","choices":[{"id":"c1","text":"15 seconds"},{"id":"c2","text":"30 seconds"},{"id":"c3","text":"1 full minute"}]},{"id":"b2","choices":[{"id":"c1","text":"60"},{"id":"c2","text":"90"},{"id":"c3","text":"120"}]}]}'::jsonb,
 '{"answers":{"b1":"c3","b2":"c2"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pediatrics', 'Cardiovascular', 'Digoxin in infants', 'Apical rate before dosing',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 'Complete the sentence by choosing from each drop-down.', 2, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_521013', 'MCQ',
 'A 7-month-old infant is admitted to the childrens ward with bronchiolitis caused by respiratory syncytial virus. Which infection control measure should the nurse implement?',
 'Respiratory syncytial virus spreads mainly by large droplets and by contact with contaminated hands, cot rails and toys, where it survives for several hours. Contact precautions with a single room, or cohorting with other virus-positive infants, plus rigorous hand hygiene, are what interrupt transmission on a paediatric ward. The virus does not require a negative pressure room because it is not transmitted over long distances on air currents.',
 '{"options":[{"id":"A","text":"Contact precautions in a single room, or cohorting with other infants known to have the same virus"},{"id":"B","text":"Airborne precautions in a negative pressure room"},{"id":"C","text":"Standard precautions only, because the virus does not spread within hospital"},{"id":"D","text":"Protective isolation in a positive pressure room"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Contact precautions with single-room care or cohorting interrupt the hand and surface route that spreads this virus.","B":"Incorrect. Negative pressure rooms are reserved for airborne pathogens such as tuberculosis, measles and varicella.","C":"Incorrect. Nosocomial spread of this virus is well documented and can be severe in other infants.","D":"Incorrect. Protective isolation shields an immunocompromised child from others; here the aim is the reverse."}}'::jsonb,
 'Safe and Effective Care Environment', 'Safety and Infection Control',
 'Pediatrics', 'Respiratory', 'Bronchiolitis', 'Transmission-based precautions',
 'Very easy', 'CURATOR_LABEL', 'Apply', '{}', NULL, 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_521014', 'SATA',
 'A nurse is caring for a 5-month-old infant admitted with bronchiolitis. Which interventions should the nurse include in the plan of care? Select all that apply.',
 'Bronchiolitis is a viral illness, so care is supportive and aimed at the two problems that actually threaten the infant: blocked nasal passages and exhaustion during feeding. Clearing the nose before feeds, offering smaller more frequent feeds and nursing the infant with the head of the cot raised address both. Antibiotics and routine chest physiotherapy do not shorten the illness and fluid restriction risks dehydration in a tachypnoeic baby.',
 '{"options":[{"id":"A","text":"Suction the nares with a bulb syringe before feeds"},{"id":"B","text":"Offer smaller feeds more frequently"},{"id":"C","text":"Nurse the infant with the head of the cot elevated"},{"id":"D","text":"Administer a course of oral antibiotics"},{"id":"E","text":"Perform chest physiotherapy every 4 hours"},{"id":"F","text":"Encourage the parents to stay and provide comfort"},{"id":"G","text":"Restrict fluids to half maintenance to prevent pulmonary oedema"}]}'::jsonb,
 '{"answers":["A","B","C","F"],"feedback":{"A":"Correct. Infants breathe mainly through the nose, so clearing secretions before a feed makes feeding possible.","B":"Correct. Smaller frequent feeds reduce the work of feeding in a tachypnoeic infant.","C":"Correct. Elevating the head improves diaphragmatic excursion and eases the work of breathing.","D":"Incorrect. Bronchiolitis is viral, so antibiotics add risk without benefit unless a bacterial infection is proven.","E":"Incorrect. Routine chest physiotherapy is not recommended and can distress an already tiring infant.","F":"Correct. Parental presence reduces crying, which lowers oxygen demand and helps the infant settle.","G":"Incorrect. Tachypnoea increases insensible losses, so the risk is dehydration rather than fluid overload."}}'::jsonb,
 'Physiological Integrity', 'Basic Care and Comfort',
 'Pediatrics', 'Respiratory', 'Bronchiolitis', 'Supportive nursing care',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 'Select all that apply.', 4, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MAT_521015', 'MATRIX',
 'Two children present to the emergency department with stridor. For each finding, indicate whether it is more characteristic of croup (laryngotracheobronchitis) or of epiglottitis.',
 'Croup is a viral illness of the subglottic airway that builds over a day or two after a coryzal prodrome and produces a barking cough with stridor that eases in cool humidified air. Epiglottitis is a bacterial infection of the supraglottic structures that develops over hours, with high fever, drooling, refusal to swallow, a muffled voice and a child who sits forward to keep the airway open. Distinguishing them matters because epiglottitis is an airway emergency and the throat must not be examined.',
 '{"rows":[{"id":"r1","text":"Barking, seal-like cough"},{"id":"r2","text":"Drooling with refusal to swallow"},{"id":"r3","text":"Gradual onset over one to two days after a coryzal illness"},{"id":"r4","text":"Muffled voice with the child sitting forward in a tripod position"},{"id":"r5","text":"Temperature of 39.5 degrees Celsius with onset over a few hours"},{"id":"r6","text":"Inspiratory stridor that eases in cool humidified air"}],"columns":[{"id":"c1","text":"Croup"},{"id":"c2","text":"Epiglottitis"}],"row_label":"Finding"}'::jsonb,
 '{"cells":{"r1":"c1","r2":"c2","r3":"c1","r4":"c2","r5":"c2","r6":"c1"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Pediatrics', 'Respiratory', 'Stridor in children', 'Croup versus epiglottitis',
 'Hard', 'CURATOR_LABEL', 'Analyze', '{}', 'Select one column for each row.', 6, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_521016', 'MCQ',
 'A 4-year-old arrives at the emergency department sitting forward, drooling, with a muffled voice and a temperature of 39.6 degrees Celsius. Epiglottitis is suspected. Which prescription should the nurse question?',
 'In suspected epiglottitis the swollen supraglottic tissue sits on a knife edge, and anything that provokes crying, gagging or laryngospasm can convert partial obstruction into complete obstruction. Inspecting the throat with a tongue depressor or taking a throat swab is therefore contraindicated until the airway is secured by an anaesthetist in theatre. The nurse keeps the child calm on the lap of the parent, has intubation and tracheostomy equipment ready, and does not lay the child flat.',
 '{"options":[{"id":"A","text":"Obtain a throat swab using a tongue depressor"},{"id":"B","text":"Allow the child to remain in the position of comfort on the lap of the parent"},{"id":"C","text":"Prepare intubation and tracheostomy equipment at the bedside"},{"id":"D","text":"Administer intravenous antibiotics after blood cultures are taken"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Instrumenting the throat can trigger laryngospasm and complete airway obstruction, so this must be questioned.","B":"Incorrect. Keeping the child calm and upright maintains the airway and should not be questioned.","C":"Incorrect. Having airway equipment immediately available is essential preparation.","D":"Incorrect. Intravenous antibiotics after cultures are the definitive treatment once the airway is safe."}}'::jsonb,
 'Safe and Effective Care Environment', 'Management of Care',
 'Pediatrics', 'Respiratory', 'Epiglottitis', 'Prescription to question',
 'Very hard', 'CURATOR_LABEL', 'Analyze', '{}', NULL, 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_521017', 'MCQ',
 'An 8-year-old with asthma is prescribed inhaled salbutamol and inhaled beclometasone, both by metered dose inhaler with a spacer. Which instruction should the nurse give the child and the parent?',
 'The bronchodilator is given first because it opens the airways, allowing the corticosteroid that follows to reach the smaller distal airways where inflammation sits. Rinsing and spitting after the corticosteroid removes drug deposited in the mouth and prevents oral candidiasis and hoarseness. A spacer is used at this age because it improves lung deposition and removes the need for perfect breath-actuation timing.',
 '{"options":[{"id":"A","text":"Take the salbutamol first, wait a few minutes, then take the beclometasone and rinse the mouth afterwards"},{"id":"B","text":"Take the beclometasone first because it acts fastest on the airways"},{"id":"C","text":"Use both inhalers only when wheezing is present"},{"id":"D","text":"Rinse the mouth after the salbutamol to prevent oral thrush"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Bronchodilator first opens the airways for the steroid, and rinsing after the steroid prevents oral thrush.","B":"Incorrect. The corticosteroid is preventive and has no immediate bronchodilator effect.","C":"Incorrect. The preventer must be taken regularly even when the child is symptom free.","D":"Incorrect. Thrush is a corticosteroid effect, so it is the beclometasone that requires mouth rinsing."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pediatrics', 'Respiratory', 'Paediatric asthma', 'Inhaler sequence and technique',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', NULL, 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_521018', 'SATA',
 'A nurse is preparing home care teaching for the parents of a 4-year-old with cystic fibrosis. Which instructions should be included? Select all that apply.',
 'Cystic fibrosis produces thick secretions that obstruct the airways and block the pancreatic ducts, so home care targets both. Pancreatic enzyme replacement with every meal and snack allows fat and protein to be absorbed, and a high energy, high protein diet compensates for the increased work of breathing and malabsorption. Airway clearance is done before meals to avoid vomiting, and extra salt is needed because sweat sodium losses are high, particularly in hot climates.',
 '{"options":[{"id":"A","text":"Give pancreatic enzyme replacement with every meal and snack"},{"id":"B","text":"Provide a diet high in energy and protein"},{"id":"C","text":"Carry out airway clearance before meals rather than immediately after"},{"id":"D","text":"Restrict salt intake, particularly in hot weather"},{"id":"E","text":"Restrict fluids in order to reduce secretions"},{"id":"F","text":"Report any change to bulky, greasy, foul-smelling stools"}]}'::jsonb,
 '{"answers":["A","B","C","F"],"feedback":{"A":"Correct. Enzymes must accompany food to allow fat and protein absorption.","B":"Correct. Energy requirements are high because of malabsorption and increased work of breathing.","C":"Correct. Clearance before meals prevents vomiting of a recently eaten meal.","D":"Incorrect. Sweat sodium losses are high, so extra salt is needed rather than restriction.","E":"Incorrect. Adequate fluid keeps secretions less viscous; restriction makes clearance harder.","F":"Correct. Steatorrhoea indicates that the enzyme dose is inadequate and needs review."}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance',
 'Pediatrics', 'Respiratory', 'Cystic fibrosis', 'Home care teaching',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 'Select all that apply.', 4, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_DO_521019', 'DRAG_ORDER',
 'A 6-month-old infant suddenly stops making any sound while eating, cannot cry and has an ineffective cough. Place the actions in the order the nurse should perform them.',
 'A silent, ineffective cough means the airway obstruction is complete and the infant cannot clear it alone. Help is summoned first, then the infant is supported head-down along the forearm for five back blows, turned over for five chest thrusts, and the mouth is checked so that only a visible object is removed. Abdominal thrusts are never used in infants because the liver is large and poorly protected by the rib cage.',
 '{"slots":[{"id":"s1","target_text":"1st"},{"id":"s2","target_text":"2nd"},{"id":"s3","target_text":"3rd"},{"id":"s4","target_text":"4th"}],"tokens":[{"id":"t1","text":"Shout for help and position the infant face down along the forearm with the head lower than the chest"},{"id":"t2","text":"Deliver five back blows between the shoulder blades with the heel of the hand"},{"id":"t3","text":"Turn the infant face up and deliver five chest thrusts"},{"id":"t4","text":"Look in the mouth and remove an object only if it is visible"},{"id":"t5","text":"Deliver five abdominal thrusts below the ribcage"}]}'::jsonb,
 '{"slots":{"s1":"t1","s2":"t2","s3":"t3","s4":"t4"}}'::jsonb,
 'Safe and Effective Care Environment', 'Safety and Infection Control',
 'Pediatrics', 'Respiratory', 'Foreign body aspiration', 'Choking infant sequence',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 'Place the options in the correct order.', 4, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SELN_521020', 'SELECT_N',
 'A 6-year-old is being observed 4 hours after a tonsillectomy. Which 3 findings suggest haemorrhage and require immediate action?',
 'The tonsillar bed bleeds into the pharynx, so blood is swallowed rather than seen, and the earliest sign is repeated swallowing while the child is otherwise quiet or asleep. Restlessness with a rising pulse reflects early hypovolaemia, and vomiting of bright red blood confirms active bleeding. Old dark blood-tinged mucus and throat pain are expected in the first hours and do not by themselves indicate haemorrhage.',
 '{"options":[{"id":"A","text":"Frequent swallowing while lying quietly"},{"id":"B","text":"Restlessness with a pulse rising to 138 beats per minute"},{"id":"C","text":"Vomiting of bright red blood"},{"id":"D","text":"Complaint of a sore throat when swallowing fluids"},{"id":"E","text":"A small amount of dark brown blood-tinged mucus"},{"id":"F","text":"Refusal of red-coloured juice offered by a parent"}],"select_count":3}'::jsonb,
 '{"answers":["A","B","C"],"feedback":{"A":"Correct. Repeated swallowing is the classic covert sign that blood is trickling down the pharynx.","B":"Correct. Restlessness with tachycardia signals early hypovolaemia before blood pressure falls.","C":"Correct. Bright red vomit indicates fresh active bleeding and demands immediate action.","D":"Incorrect. Throat pain is expected after tonsillectomy and is managed with regular analgesia.","E":"Incorrect. Small amounts of old dark blood-tinged mucus are an expected postoperative finding.","F":"Incorrect. Red fluids are avoided anyway because they mask blood; refusal is not a bleeding sign."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Pediatrics', 'Respiratory', 'Tonsillectomy', 'Postoperative haemorrhage',
 'Medium', 'CURATOR_LABEL', 'Analyze', '{}', 'Select 3.', 3, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728');

-- ── Block 3 (521021-521030) — gastrointestinal, then neurological ───
INSERT INTO nclex_bank_items (
  item_id, question_type, stem, rationale, content, correct,
  client_needs_category, client_needs_subcategory, nursing_subject, body_system,
  topic, subtopic, difficulty, difficulty_source, bloom_level, tags,
  instruction, marks, is_published, is_builder_visible, is_free_sample, cat_pool, batch_id
) VALUES

('NCLEX_SATA_521021', 'SATA',
 'A 4-week-old infant is being assessed for suspected hypertrophic pyloric stenosis. Which findings support this diagnosis? Select all that apply.',
 'The thickened pyloric muscle obstructs the gastric outlet, so the stomach empties forcefully backwards and the vomit is projectile and never bile-stained, because the obstruction lies above the ampulla of Vater. The infant loses hydrochloric acid with each vomit and becomes hypochloraemic and alkalotic, yet remains hungry and feeds eagerly straight afterwards. Bile-stained vomiting or redcurrant-jelly stool points to a different, more distal problem.',
 '{"options":[{"id":"A","text":"Forceful projectile vomiting that contains no bile"},{"id":"B","text":"A firm olive-shaped mass palpable in the right upper quadrant"},{"id":"C","text":"The infant appears hungry and feeds eagerly immediately after vomiting"},{"id":"D","text":"Bile-stained vomit with marked abdominal distension"},{"id":"E","text":"Stool containing blood and mucus resembling redcurrant jelly"}]}'::jsonb,
 '{"answers":["A","B","C"],"feedback":{"A":"Correct. The obstruction lies proximal to the bile duct opening, so the vomit is milk only.","B":"Correct. The hypertrophied pylorus is palpable as an olive-shaped mass, best felt after a feed.","C":"Correct. The infant is genuinely hungry because no feed is being absorbed.","D":"Incorrect. Bile-stained vomit indicates obstruction below the ampulla, such as malrotation or atresia.","E":"Incorrect. Redcurrant-jelly stool is characteristic of intussusception."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Pediatrics', 'Gastrointestinal', 'Pyloric stenosis', 'Presenting findings',
 'Very hard', 'CURATOR_LABEL', 'Analyze', '{}', 'Select all that apply.', 3, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_521022', 'MCQ',
 'A 9-month-old is being prepared for an air enema to treat intussusception. While waiting, the infant passes a normal soft brown stool. Which action should the nurse take?',
 'Passage of a normal brown stool in a child with intussusception often means the telescoped bowel has reduced spontaneously, which changes the entire plan of care. The provider must be told before the enema proceeds, because the procedure and its risks may no longer be necessary. Documenting alone, or simply continuing with the preparation, would allow an avoidable invasive procedure to go ahead.',
 '{"options":[{"id":"A","text":"Notify the provider, as this may indicate that the intussusception has reduced"},{"id":"B","text":"Document the stool and continue to prepare the infant for the enema"},{"id":"C","text":"Offer a full feed now that bowel function has returned"},{"id":"D","text":"Insert a rectal tube to decompress the bowel further"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. A normal stool suggests spontaneous reduction and must be reported before the procedure goes ahead.","B":"Incorrect. Documenting without reporting allows an invasive procedure that may no longer be indicated.","C":"Incorrect. The infant remains nil by mouth until the provider confirms the situation.","D":"Incorrect. A rectal tube is not indicated and risks perforating already compromised bowel."}}'::jsonb,
 'Safe and Effective Care Environment', 'Management of Care',
 'Pediatrics', 'Gastrointestinal', 'Intussusception', 'Evaluating spontaneous reduction',
 'Very hard', 'CURATOR_LABEL', 'Analyze', '{}', NULL, 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_521023', 'MCQ',
 'A 10-year-old admitted with right lower quadrant pain suddenly reports that the pain has completely gone and looks relieved. The temperature is 38.9 degrees Celsius, the pulse is 132 beats per minute and the abdomen is rigid. Which action is the PRIORITY?',
 'Sudden relief of appendicitis pain is not improvement: it means the distended appendix has perforated and the pressure has been released. Peritonitis follows within hours, signalled by rigidity, fever and tachycardia, and the child needs urgent surgical review, intravenous fluids and antibiotics. Analgesia, heat and mobilisation all delay recognition, and heat in particular accelerates perforation and spread.',
 '{"options":[{"id":"A","text":"Notify the surgical team immediately, as perforation is likely"},{"id":"B","text":"Administer the prescribed oral analgesia and reassess in 30 minutes"},{"id":"C","text":"Apply a warm compress to the abdomen for comfort"},{"id":"D","text":"Encourage the child to walk around the ward to relieve trapped wind"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Sudden pain relief with rigidity, fever and tachycardia indicates perforation and peritonitis.","B":"Incorrect. Oral intake and delay are unsafe when emergency surgery is likely.","C":"Incorrect. Heat increases blood flow and inflammation and can worsen perforation.","D":"Incorrect. This misreads peritonitis as wind and wastes critical time."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Pediatrics', 'Gastrointestinal', 'Appendicitis', 'Recognising perforation',
 'Hard', 'CURATOR_LABEL', 'Analyze', '{}', NULL, 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SELN_521024', 'SELECT_N',
 'A 2-year-old has had diarrhoea and vomiting for 3 days and is brought to a rural health centre. Which 3 findings indicate severe dehydration?',
 'Severity of dehydration is judged on perfusion and tissue turgor rather than on how unwell the child looks. Sunken eyes with absent tears, a skin pinch that recedes very slowly and prolonged capillary refill with cool mottled limbs together indicate a fluid deficit of roughly 10 per cent or more and the need for intravenous rehydration. Moist membranes, stable weight and a good urine output are all reassuring and point away from severe loss.',
 '{"options":[{"id":"A","text":"Sunken eyes with absent tears when crying"},{"id":"B","text":"A skin pinch over the abdomen that recedes very slowly"},{"id":"C","text":"Capillary refill of 4 seconds with cool mottled limbs"},{"id":"D","text":"Moist oral mucous membranes"},{"id":"E","text":"Weight unchanged over the 3 days of illness"},{"id":"F","text":"Urine output of 2 mL per kilogram per hour"}],"select_count":3}'::jsonb,
 '{"answers":["A","B","C"],"feedback":{"A":"Correct. Loss of periorbital fluid and absent tears reflect a substantial deficit.","B":"Correct. Very slow skin recoil indicates markedly reduced interstitial fluid.","C":"Correct. Prolonged refill with cool mottled skin shows that perfusion is now compromised.","D":"Incorrect. Moist membranes suggest that hydration is at worst mild.","E":"Incorrect. Acute weight loss is the most sensitive measure; unchanged weight argues against severe dehydration.","F":"Incorrect. Two mL per kilogram per hour is a normal output and indicates adequate renal perfusion."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Pediatrics', 'Gastrointestinal', 'Dehydration in children', 'Severity assessment',
 'Medium', 'CURATOR_LABEL', 'Analyze', '{}', 'Select 3.', 3, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MAT_521025', 'MATRIX',
 'A nurse is teaching the parents of a child newly diagnosed with coeliac disease. For each food, indicate whether it is suitable or should be avoided.',
 'Coeliac disease is an immune reaction to gluten, the protein found in wheat, barley and rye, which flattens the intestinal villi and causes malabsorption. The diet is lifelong and works only if every source of these three grains is removed, including many processed foods. Rice, maize, plantain, fresh fruit, plain dairy, meat and fish are naturally gluten free and form the basis of the diet.',
 '{"rows":[{"id":"r1","text":"Porridge made from barley"},{"id":"r2","text":"Rice with grilled chicken"},{"id":"r3","text":"Wheat-based breakfast cereal"},{"id":"r4","text":"Boiled maize and fried plantain"},{"id":"r5","text":"Rye crackers"},{"id":"r6","text":"Fresh fruit with plain yoghurt"}],"columns":[{"id":"c1","text":"Suitable"},{"id":"c2","text":"Should be avoided"}],"row_label":"Food"}'::jsonb,
 '{"cells":{"r1":"c2","r2":"c1","r3":"c2","r4":"c1","r5":"c2","r6":"c1"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Basic Care and Comfort',
 'Pediatrics', 'Gastrointestinal', 'Coeliac disease', 'Gluten-free diet',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 'Select one column for each row.', 6, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_521026', 'MCQ',
 'A newborn on the postnatal ward is 30 hours old and has not passed meconium. The abdomen is distended and the baby has vomited bile-stained fluid. Which action should the nurse take?',
 'Almost all healthy term newborns pass meconium within 24 to 48 hours, and failure to do so with abdominal distension and bile-stained vomiting suggests a distal obstruction such as Hirschsprung disease, in which an aganglionic segment of colon cannot propel stool. This requires medical review, contrast studies and eventually a rectal biopsy, so the finding is reported rather than treated on the ward. Suppositories, stimulation or increasing feeds risk perforating an obstructed bowel.',
 '{"options":[{"id":"A","text":"Report the findings to the provider, as Hirschsprung disease must be excluded"},{"id":"B","text":"Give a glycerine suppository and reassess in 6 hours"},{"id":"C","text":"Reassure the parents that meconium may take up to 5 days to appear"},{"id":"D","text":"Increase the volume of each formula feed to stimulate the bowel"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Delayed meconium with distension and bilious vomiting is a classic presentation that must be investigated.","B":"Incorrect. Stimulating an obstructed bowel risks perforation and delays diagnosis.","C":"Incorrect. Failure to pass meconium beyond 24 to 48 hours is abnormal and not reassured away.","D":"Incorrect. Increasing feeds adds to distension in an obstructed newborn."}}'::jsonb,
 'Safe and Effective Care Environment', 'Management of Care',
 'Pediatrics', 'Gastrointestinal', 'Hirschsprung disease', 'Delayed passage of meconium',
 'Medium', 'CURATOR_LABEL', 'Analyze', '{}', NULL, 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_521027', 'SATA',
 'A nurse is teaching parents how to feed a newborn who has a cleft lip and palate. Which instructions should be included? Select all that apply.',
 'A cleft palate prevents the newborn from generating suction, so milk must be delivered rather than drawn, using a wide-based or squeezable bottle with a specialised teat. Holding the baby upright uses gravity to reduce nasal regurgitation and the risk of aspiration, and frequent burping clears the large volume of air swallowed during feeds. Feeding slowly with rest breaks prevents exhaustion and lets the baby take an adequate volume.',
 '{"options":[{"id":"A","text":"Hold the infant upright during the feed"},{"id":"B","text":"Use a wide-based or squeezable bottle with a specialised teat"},{"id":"C","text":"Burp the infant frequently during the feed"},{"id":"D","text":"Lay the infant flat immediately after the feed"},{"id":"E","text":"Thicken every feed with cereal to slow the flow of milk"}]}'::jsonb,
 '{"answers":["A","B","C"],"feedback":{"A":"Correct. An upright position uses gravity to reduce nasal regurgitation and aspiration.","B":"Correct. The infant cannot create suction, so milk must be delivered by a squeezable bottle or specialised teat.","C":"Correct. Large volumes of air are swallowed, so frequent burping prevents distension and vomiting.","D":"Incorrect. Lying flat after a feed increases the risk of regurgitation and aspiration.","E":"Incorrect. Thickening is used for reflux and would make an already difficult feed harder."}}'::jsonb,
 'Physiological Integrity', 'Basic Care and Comfort',
 'Pediatrics', 'Gastrointestinal', 'Cleft lip and palate', 'Feeding technique',
 'Very easy', 'CURATOR_LABEL', 'Apply', '{}', 'Select all that apply.', 3, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_521028', 'SATA',
 'A 2-year-old had a generalised tonic-clonic convulsion at home during a febrile illness. Which actions should the nurse teach the parents to take if this happens again? Select all that apply.',
 'Febrile convulsions are common between 6 months and 5 years and are usually brief and self-limiting, so the aim of first aid is to protect the child rather than to stop the seizure. Placing the child on the side on a safe flat surface protects the airway, loosening tight clothing eases breathing, and timing the event determines whether emergency help is needed. Nothing is ever placed in the mouth and the limbs are not restrained, because both cause injury without shortening the convulsion.',
 '{"options":[{"id":"A","text":"Place the child on the side on a flat, safe surface"},{"id":"B","text":"Note the time the convulsion starts and how long it lasts"},{"id":"C","text":"Place a spoon between the teeth to protect the tongue"},{"id":"D","text":"Loosen tight clothing around the neck"},{"id":"E","text":"Hold the arms and legs still to stop the shaking"},{"id":"F","text":"Call emergency services if the convulsion lasts longer than 5 minutes"}]}'::jsonb,
 '{"answers":["A","B","D","F"],"feedback":{"A":"Correct. Side-lying allows secretions to drain and protects the airway.","B":"Correct. Duration determines whether the seizure is simple or requires emergency treatment.","C":"Incorrect. Placing anything in the mouth risks broken teeth, injury and obstruction.","D":"Correct. Loosening clothing around the neck eases breathing during the event.","E":"Incorrect. Restraining the limbs can cause fractures and does not shorten the convulsion.","F":"Correct. A convulsion beyond 5 minutes may progress to status epilepticus and needs emergency care."}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance',
 'Pediatrics', 'Neurological', 'Febrile convulsion', 'Parental first aid and seizure care',
 'Very easy', 'CURATOR_LABEL', 'Apply', '{}', 'Select all that apply.', 4, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_521029', 'MCQ',
 'A 9-year-old is admitted at midnight with suspected bacterial meningitis. Which action should the nurse take on admission?',
 'Meningococcal and haemophilus meningitis spread by respiratory droplets from the nasopharynx, so droplet precautions with a single room are started on suspicion rather than on confirmation. They are maintained until 24 hours of effective antibiotic therapy have been given, after which the child is no longer infectious. Waiting for culture results before isolating exposes staff, family and other children unnecessarily.',
 '{"options":[{"id":"A","text":"Place the child on droplet precautions and maintain them until 24 hours of effective antibiotic therapy are complete"},{"id":"B","text":"Place the child in a negative pressure room on airborne precautions for 7 days"},{"id":"C","text":"Use standard precautions only, because meningitis is not transmissible"},{"id":"D","text":"Place the child on contact precautions until any rash has resolved"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Droplet precautions start on suspicion and continue for the first 24 hours of effective antibiotics.","B":"Incorrect. Bacterial meningitis spreads by droplets, not on air currents, so a negative pressure room is not required.","C":"Incorrect. Standard precautions alone leave staff and contacts exposed to droplet spread.","D":"Incorrect. Contact precautions address surface and hand spread and do not match this route of transmission."}}'::jsonb,
 'Safe and Effective Care Environment', 'Safety and Infection Control',
 'Pediatrics', 'Neurological', 'Bacterial meningitis', 'Transmission-based precautions',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', NULL, 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SELN_521030', 'SELECT_N',
 'A 6-week-old is being assessed for possible meningitis. Which 3 findings are most consistent with meningitis in an infant of this age?',
 'The classical signs of meningeal irritation depend on a mature nervous system and on the child being able to describe symptoms, so they are unreliable in early infancy. Instead, a young infant shows a tense or bulging fontanelle from raised intracranial pressure, a high-pitched shrill cry, and non-specific illness such as poor feeding with temperature instability. Expecting nuchal rigidity or a described headache in a 6-week-old is the commonest reason the diagnosis is missed.',
 '{"options":[{"id":"A","text":"A tense, bulging anterior fontanelle"},{"id":"B","text":"A high-pitched shrill cry"},{"id":"C","text":"Poor feeding with temperature instability"},{"id":"D","text":"A positive Kernig sign"},{"id":"E","text":"Marked nuchal rigidity on neck flexion"},{"id":"F","text":"Complaint of photophobia"}],"select_count":3}'::jsonb,
 '{"answers":["A","B","C"],"feedback":{"A":"Correct. The open fontanelle bulges as intracranial pressure rises, making it a key infant sign.","B":"Correct. A high-pitched shrill cry is a recognised sign of cerebral irritation in infants.","C":"Correct. Non-specific poor feeding and unstable temperature are often the only early features.","D":"Incorrect. Kernig and Brudzinski signs are unreliable in infants and usually absent.","E":"Incorrect. Neck stiffness typically appears only in older children and adults.","F":"Incorrect. A 6-week-old cannot report photophobia, so it cannot be a presenting complaint."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Pediatrics', 'Neurological', 'Meningitis in infancy', 'Age-specific presentation',
 'Very hard', 'CURATOR_LABEL', 'Analyze', '{}', 'Select 3.', 3, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728');

-- ── Block 4 (521031-521040) — neuro, musculoskeletal, genitourinary ─
INSERT INTO nclex_bank_items (
  item_id, question_type, stem, rationale, content, correct,
  client_needs_category, client_needs_subcategory, nursing_subject, body_system,
  topic, subtopic, difficulty, difficulty_source, bloom_level, tags,
  instruction, marks, is_published, is_builder_visible, is_free_sample, cat_pool, batch_id
) VALUES

('NCLEX_MCQ_521031', 'MCQ',
 'A 3-year-old with a ventriculoperitoneal shunt is brought to the paediatric clinic by a grandparent. Which finding should the nurse act on FIRST?',
 'A shunt that stops draining allows cerebrospinal fluid to accumulate, so the signs of malfunction are the signs of raised intracranial pressure. In a toddler these are early morning vomiting, increasing drowsiness, irritability and, later, sunsetting eyes and a rising head circumference. Vomiting with a falling level of consciousness is the combination that indicates pressure is rising now and needs urgent imaging.',
 '{"options":[{"id":"A","text":"Repeated early morning vomiting with increasing drowsiness"},{"id":"B","text":"A temperature of 37.4 degrees Celsius"},{"id":"C","text":"Crying when the immunisation is mentioned"},{"id":"D","text":"Head circumference unchanged since the last clinic visit"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Vomiting with a declining conscious level indicates rising intracranial pressure from shunt malfunction.","B":"Incorrect. This temperature is within normal limits and needs monitoring only.","C":"Incorrect. Anticipatory distress about needles is age-appropriate behaviour.","D":"Incorrect. A stable head circumference is a reassuring finding in a shunted child."}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Pediatrics', 'Neurological', 'Hydrocephalus', 'Shunt malfunction',
 'Hard', 'CURATOR_LABEL', 'Analyze', '{}', NULL, 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_521032', 'SATA',
 'A newborn with a myelomeningocele is admitted to the neonatal unit before surgical closure. Which nursing actions should be included in the plan of care? Select all that apply.',
 'The exposed neural sac is the priority: it must stay intact, moist and uncontaminated until closure, because rupture or infection causes meningitis and further neurological damage. The newborn is nursed prone with the sac covered by a sterile dressing moistened with warm sterile saline, and pressure from nappies or supine positioning is avoided. Latex-free equipment is used from birth because repeated exposure gives these children a very high rate of latex allergy, and daily head circumference detects the hydrocephalus that frequently follows.',
 '{"options":[{"id":"A","text":"Position the newborn prone"},{"id":"B","text":"Cover the sac with a sterile dressing moistened with warm sterile saline"},{"id":"C","text":"Use latex-free gloves and equipment"},{"id":"D","text":"Measure the head circumference daily"},{"id":"E","text":"Apply a nappy snugly over the sac to keep it clean"},{"id":"F","text":"Place the newborn supine in a car seat for feeds"}]}'::jsonb,
 '{"answers":["A","B","C","D"],"feedback":{"A":"Correct. Prone positioning keeps pressure off the sac and reduces the risk of rupture.","B":"Correct. A moist sterile dressing prevents the sac drying, cracking and becoming infected.","C":"Correct. Early and consistent latex avoidance prevents the sensitisation these children are prone to.","D":"Correct. Hydrocephalus commonly develops, and daily measurement detects it early.","E":"Incorrect. A nappy over the sac applies pressure and risks faecal contamination.","F":"Incorrect. Supine positioning places direct pressure on the sac and must be avoided before closure."}}'::jsonb,
 'Safe and Effective Care Environment', 'Safety and Infection Control',
 'Pediatrics', 'Neurological', 'Spina bifida', 'Preoperative care of the sac',
 'Very hard', 'CURATOR_LABEL', 'Apply', '{}', 'Select all that apply.', 4, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_521033', 'SATA',
 'A 7-year-old is being discharged from the emergency department after a minor head injury sustained falling from a bicycle. Which findings should the nurse teach the parents to return to hospital for immediately? Select all that apply.',
 'Most minor head injuries settle, but a small number develop delayed intracranial bleeding, so discharge advice must name the specific changes that mean pressure is rising. A falling level of consciousness, repeated vomiting, a convulsion and clear fluid draining from the nose or ear all indicate a complication needing urgent reassessment. Written advice that lists these is more reliable than telling parents to watch for anything unusual.',
 '{"options":[{"id":"A","text":"Becoming difficult to rouse or unusually drowsy"},{"id":"B","text":"Vomiting more than once after returning home"},{"id":"C","text":"Any convulsion or twitching of the limbs"},{"id":"D","text":"A bruise on the forehead that is slowly fading"},{"id":"E","text":"A mild headache that is relieved by paracetamol"},{"id":"F","text":"Clear fluid draining from the nose or ear"}]}'::jsonb,
 '{"answers":["A","B","C","F"],"feedback":{"A":"Correct. A falling level of consciousness is the most important sign of rising intracranial pressure.","B":"Correct. Repeated vomiting after a head injury suggests an intracranial complication.","C":"Correct. A post-traumatic seizure requires immediate reassessment.","D":"Incorrect. A resolving bruise is an expected part of recovery.","E":"Incorrect. A mild headache that responds to simple analgesia is common after a minor head injury.","F":"Correct. Clear drainage may be cerebrospinal fluid, indicating a base of skull fracture."}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance',
 'Pediatrics', 'Neurological', 'Head injury in children', 'Discharge advice',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 'Select all that apply.', 4, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_521034', 'MCQ',
 'A nurse is caring for a 6-year-old with spastic cerebral palsy who has a swallowing difficulty and a prescribed thickened diet. Which task may the nurse delegate to the healthcare assistant?',
 'Delegation rules turn on whether the task requires assessment, teaching or clinical judgement, all of which remain with the registered nurse. Assisting an already assessed child into an upright position and giving a prescribed diet slowly is a routine, predictable task within the assistant scope of practice. Assessing the swallow, changing the diet consistency and teaching parents to recognise aspiration all require nursing judgement and cannot be delegated.',
 '{"options":[{"id":"A","text":"Assisting the child to sit upright and giving the prepared thickened diet slowly"},{"id":"B","text":"Assessing the swallow before the first oral intake of the day"},{"id":"C","text":"Deciding whether the consistency of the diet should be changed"},{"id":"D","text":"Teaching the parents how to recognise signs of aspiration"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Positioning and feeding a stable child a prescribed diet is a routine delegable task.","B":"Incorrect. Assessment of swallowing requires nursing judgement and cannot be delegated.","C":"Incorrect. Changing the plan of care is a nursing and dietetic decision.","D":"Incorrect. Client and family teaching is a registered nurse responsibility."}}'::jsonb,
 'Safe and Effective Care Environment', 'Management of Care',
 'Pediatrics', 'Neurological', 'Cerebral palsy', 'Delegation to assistive personnel',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', NULL, 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_521035', 'MCQ',
 'The parents of a 6-week-old fitted with a Pavlik harness for developmental dysplasia of the hip ask how to care for it at home. Which instruction is correct?',
 'The harness holds the hips flexed and abducted so that the femoral head sits deep in the acetabulum and the socket can develop normally, which only works if the position is maintained continuously as prescribed. Parents check the skin under the straps daily and dress the baby in a light vest to protect it, but they do not adjust the straps, because a change in position defeats the treatment and can cause avascular necrosis. Lotions and powders soften and macerate the skin under the straps.',
 '{"options":[{"id":"A","text":"Keep the harness on as prescribed, check the skin under the straps daily, and dress the baby in a light vest beneath the straps"},{"id":"B","text":"Remove the harness for a few hours each day so the hips can move freely"},{"id":"C","text":"Apply lotion generously under the straps to prevent rubbing"},{"id":"D","text":"Adjust the straps yourselves whenever the baby seems uncomfortable"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Continuous prescribed wear, daily skin checks and a vest under the straps are the core of harness care.","B":"Incorrect. Removing the harness interrupts the sustained positioning that allows the acetabulum to develop.","C":"Incorrect. Lotions macerate the skin and increase the risk of breakdown under the straps.","D":"Incorrect. Only the clinician adjusts the straps; incorrect positioning can cause avascular necrosis of the femoral head."}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance',
 'Pediatrics', 'Musculoskeletal', 'Developmental dysplasia of the hip', 'Pavlik harness care',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', NULL, 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MAT_521036', 'MATRIX',
 'A 9-year-old has a long leg plaster cast applied after a tibial fracture. For each finding, indicate whether it is expected or requires immediate reporting.',
 'A cast is a rigid container, so any swelling inside it raises compartment pressure and compromises perfusion and nerve function. Neurovascular observation looks for the five warning features: pain out of proportion and worse on passive stretch, pallor, paraesthesia, paralysis and pulselessness. Warm pink toes with brisk refill, mild itching and slight swelling that settles with elevation are expected in the first 24 hours.',
 '{"rows":[{"id":"r1","text":"Toes warm and pink with capillary refill of 2 seconds"},{"id":"r2","text":"Pain not relieved by prescribed analgesia and worse on passive stretching of the toes"},{"id":"r3","text":"Mild itching felt under the cast"},{"id":"r4","text":"Inability to wiggle the toes with numbness of the foot"},{"id":"r5","text":"Slight swelling of the toes that settles when the limb is elevated"},{"id":"r6","text":"Cool pale toes with an absent pedal pulse"}],"columns":[{"id":"c1","text":"Expected"},{"id":"c2","text":"Requires immediate reporting"}],"row_label":"Finding"}'::jsonb,
 '{"cells":{"r1":"c1","r2":"c2","r3":"c1","r4":"c2","r5":"c1","r6":"c2"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Pediatrics', 'Musculoskeletal', 'Cast care', 'Neurovascular observation',
 'Hard', 'CURATOR_LABEL', 'Analyze', '{}', 'Select one column for each row.', 6, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_521037', 'MCQ',
 'A nurse enters the room of a school-age child in Buck skin traction and finds that the child has slipped down the bed and the weights are resting on the floor. Which action is BEST?',
 'Traction works only when the weights hang freely, because the pull is generated by gravity acting on the line of the limb. Weights resting on the floor remove that pull, so the fracture loses alignment and muscle spasm returns. Moving the child back up the bed restores the line of pull, after which alignment, the ropes and pulleys and the neurovascular status of the limb are checked; weights are never removed or lifted by the nurse.',
 '{"options":[{"id":"A","text":"Lift the weights and hold them until help arrives"},{"id":"B","text":"Move the child up in the bed so that the weights hang freely, then check alignment and neurovascular status"},{"id":"C","text":"Remove the traction until the provider reviews the child"},{"id":"D","text":"Place a pillow under the affected limb to raise it off the bed"}]}'::jsonb,
 '{"answer":"B","feedback":{"A":"Incorrect. Holding the weights is a temporary measure that does not restore the line of pull.","B":"Correct. Repositioning the child restores free-hanging weights, and the limb is then reassessed.","C":"Incorrect. Traction is not removed by the nurse, as this loses alignment and causes pain and spasm.","D":"Incorrect. A pillow under the limb alters the line of pull and defeats the traction."}}'::jsonb,
 'Physiological Integrity', 'Basic Care and Comfort',
 'Pediatrics', 'Musculoskeletal', 'Traction', 'Maintaining the line of pull',
 'Very easy', 'CURATOR_LABEL', 'Apply', '{}', NULL, 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_521038', 'SATA',
 'A 13-year-old has been prescribed a thoracolumbosacral brace for idiopathic scoliosis. Which teaching points should the nurse include? Select all that apply.',
 'Bracing does not straighten an existing curve; it aims to stop the curve progressing while the spine is still growing, and it only works if worn for the prescribed number of hours each day. A smooth cotton vest under the brace protects the skin, and inspecting bony prominences twice daily catches redness before it breaks down. Setting an honest expectation about what the brace can achieve improves adherence in an age group for whom appearance matters greatly.',
 '{"options":[{"id":"A","text":"Wear the brace for the prescribed number of hours each day, which is usually most of the day and night"},{"id":"B","text":"Wear a smooth cotton vest under the brace"},{"id":"C","text":"Inspect the skin over bony prominences twice daily for redness"},{"id":"D","text":"Remove the brace at school whenever it feels uncomfortable"},{"id":"E","text":"Expect the brace to correct the existing curve completely"}]}'::jsonb,
 '{"answers":["A","B","C"],"feedback":{"A":"Correct. The effect depends almost entirely on hours of wear during the growth period.","B":"Correct. A cotton layer reduces friction and absorbs perspiration under the brace.","C":"Correct. Twice-daily inspection detects pressure damage before skin breakdown occurs.","D":"Incorrect. Intermittent removal reduces wear time below the level at which bracing works.","E":"Incorrect. Bracing halts progression of the curve rather than correcting it."}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance',
 'Pediatrics', 'Musculoskeletal', 'Idiopathic scoliosis', 'Brace teaching',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 'Select all that apply.', 3, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_521039', 'MCQ',
 'A 3-year-old is admitted for investigation of a suspected Wilms tumour after a parent felt a firm mass in the abdomen while bathing the child. Which action is the PRIORITY for the nurse?',
 'A Wilms tumour is encapsulated, and palpating it can rupture the capsule and seed malignant cells throughout the abdomen, converting a localised tumour into disseminated disease. The single most important nursing action is therefore to prevent all abdominal palpation by placing a clear sign at the cot and alerting everyone involved in care. Handling and bathing are also carried out carefully for the same reason.',
 '{"options":[{"id":"A","text":"Place a sign at the cot stating that the abdomen must not be palpated"},{"id":"B","text":"Measure abdominal girth every 2 hours using deep palpation"},{"id":"C","text":"Ask the parent to demonstrate exactly where the mass was felt"},{"id":"D","text":"Position the child prone to relieve pressure on the mass"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Preventing palpation protects the tumour capsule and prevents seeding of malignant cells.","B":"Incorrect. Deep palpation is exactly what must be avoided; girth is measured without pressing.","C":"Incorrect. Asking the parent to palpate again repeats the very risk being avoided.","D":"Incorrect. Prone positioning presses the abdomen against the mattress and adds pressure to the tumour."}}'::jsonb,
 'Safe and Effective Care Environment', 'Safety and Infection Control',
 'Pediatrics', 'Genitourinary', 'Wilms tumour', 'Do not palpate the abdomen',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', NULL, 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MMR_521040', 'MATRIX_MR',
 'A nurse is comparing two renal conditions seen in school-age children. For each finding, select all the conditions in which it is typically seen. Each finding applies to at least one condition.',
 'Nephrotic syndrome is a problem of glomerular permeability: protein pours into the urine, serum albumin falls and fluid shifts into the tissues, producing massive proteinuria, a very low albumin and marked oedema with normal or low blood pressure. Acute glomerulonephritis is a problem of glomerular inflammation, usually one to three weeks after a group A streptococcal infection, producing haematuria, oliguria and hypertension with only mild proteinuria. Oedema is the one prominent feature the two share, which is why the urine and the blood pressure separate them.',
 '{"rows":[{"id":"r1","text":"Massive proteinuria of 3+ to 4+"},{"id":"r2","text":"Periorbital and generalised oedema"},{"id":"r3","text":"Tea-coloured or smoky urine"},{"id":"r4","text":"Hypertension requiring treatment"},{"id":"r5","text":"Serum albumin of 18 g/L"},{"id":"r6","text":"Group A streptococcal throat infection one to three weeks earlier"}],"columns":[{"id":"c1","text":"Nephrotic syndrome"},{"id":"c2","text":"Acute glomerulonephritis"}],"row_label":"Finding"}'::jsonb,
 '{"cells":{"r1":["c1"],"r2":["c1","c2"],"r3":["c2"],"r4":["c2"],"r5":["c1"],"r6":["c2"]},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Reduction of Risk Potential',
 'Pediatrics', 'Genitourinary', 'Paediatric renal disease', 'Nephrotic syndrome versus glomerulonephritis',
 'Very hard', 'CURATOR_LABEL', 'Analyze', '{}', 'Select all that apply for each row.', 7, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728');

-- ── Block 5 (521041-521050) — renal, haematology, endocrine, infection
INSERT INTO nclex_bank_items (
  item_id, question_type, stem, rationale, content, correct,
  client_needs_category, client_needs_subcategory, nursing_subject, body_system,
  topic, subtopic, difficulty, difficulty_source, bloom_level, tags,
  instruction, marks, is_published, is_builder_visible, is_free_sample, cat_pool, batch_id
) VALUES

('NCLEX_SATA_521041', 'SATA',
 'A 7-year-old is admitted with acute post-streptococcal glomerulonephritis. Which interventions should the nurse include in the plan of care? Select all that apply.',
 'During the acute phase the inflamed glomeruli retain sodium and water, so the child is at risk of hypertension, circulatory overload and encephalopathy. Daily weight on the same scales at the same time is the most sensitive measure of fluid retention, and regular blood pressure with accurate fluid balance detects deterioration early. Sodium is restricted while oedema and hypertension persist, and fluids are limited rather than encouraged.',
 '{"options":[{"id":"A","text":"Weigh the child daily on the same scales at the same time"},{"id":"B","text":"Record blood pressure every 4 hours"},{"id":"C","text":"Measure urine output and record the colour of each specimen"},{"id":"D","text":"Encourage a fluid intake of at least 3 litres per day"},{"id":"E","text":"Provide a diet with no added salt"},{"id":"F","text":"Encourage foods high in potassium such as bananas and orange juice"}]}'::jsonb,
 '{"answers":["A","B","C","E"],"feedback":{"A":"Correct. Daily weight is the most sensitive indicator of fluid retention or loss.","B":"Correct. Hypertension is the complication that can progress to encephalopathy and must be tracked.","C":"Correct. Volume and colour together show whether the glomerular inflammation is settling.","D":"Incorrect. Fluids are restricted, not encouraged, while output is reduced.","E":"Correct. Restricting sodium limits further water retention and helps control blood pressure.","F":"Incorrect. Potassium may rise when output falls, so high-potassium foods are avoided."}}'::jsonb,
 'Physiological Integrity', 'Basic Care and Comfort',
 'Pediatrics', 'Genitourinary', 'Acute glomerulonephritis', 'Acute phase monitoring',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 'Select all that apply.', 4, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_521042', 'MCQ',
 'A newborn is found to have hypospadias at the routine newborn examination. Which information should the nurse give the parents?',
 'In hypospadias the urethral opening lies on the underside of the penis rather than at the tip, and surgical repair is usually carried out between 6 and 12 months of age. The foreskin is frequently used as graft tissue during that repair, so circumcision is deferred until the surgeon has decided the plan. Explaining this early prevents a well-meaning but irreversible procedure being requested before discharge.',
 '{"options":[{"id":"A","text":"Circumcision will be deferred because the foreskin may be needed for the surgical repair"},{"id":"B","text":"Circumcision should be carried out before discharge to reduce the risk of infection"},{"id":"C","text":"Repair is performed only after the second birthday and only if symptoms develop"},{"id":"D","text":"Urine will need to be drained by catheter until the repair is carried out"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. The foreskin is often used as graft tissue, so circumcision is deferred until after surgical planning.","B":"Incorrect. Circumcision may remove tissue the surgeon needs and is therefore avoided.","C":"Incorrect. Repair is usually undertaken between 6 and 12 months, before body image and toilet training are affected.","D":"Incorrect. The newborn voids normally through the misplaced opening and does not need a catheter."}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance',
 'Pediatrics', 'Genitourinary', 'Hypospadias', 'Deferring circumcision',
 'Very easy', 'CURATOR_LABEL', 'Understand', '{}', NULL, 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_521043', 'MCQ',
 'A 9-year-old with sickle cell disease is admitted with severe pain in both legs and the lower back. The temperature is 37.8 degrees Celsius and oxygen saturation is 96 per cent in air. Which nursing action is the PRIORITY?',
 'In a vaso-occlusive crisis, sickled cells block small vessels and cause ischaemic tissue pain, and the two interventions that shorten the crisis are rehydration to reduce blood viscosity and effective analgesia, usually with opioids on a regular schedule. Fear of dependence leads to persistent undertreatment of pain in this group, and untreated pain itself worsens sickling through stress and hypoxia. Cold causes vasoconstriction and increases sickling, so warmth rather than cold is applied.',
 '{"options":[{"id":"A","text":"Start the prescribed intravenous fluids and give the prescribed opioid analgesia"},{"id":"B","text":"Apply cold packs to the painful limbs"},{"id":"C","text":"Encourage vigorous active exercise of both legs"},{"id":"D","text":"Restrict oral fluids until the pain has settled"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Hydration reduces blood viscosity and opioid analgesia treats genuinely severe ischaemic pain.","B":"Incorrect. Cold causes vasoconstriction, which increases sickling and worsens the crisis.","C":"Incorrect. Vigorous exercise raises oxygen demand and aggravates the crisis; gentle movement is allowed as pain permits.","D":"Incorrect. Restricting fluids concentrates the blood and promotes further sickling."}}'::jsonb,
 'Physiological Integrity', 'Basic Care and Comfort',
 'Pediatrics', 'Hematologic', 'Sickle cell disease', 'Vaso-occlusive crisis management',
 'Hard', 'CURATOR_LABEL', 'Apply', '{}', NULL, 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SATA_521044', 'SATA',
 'A nurse is teaching the parents of a 4-year-old newly diagnosed with haemophilia A. Which instructions should be included? Select all that apply.',
 'Haemophilia is a deficiency of clotting factor, so home management aims to avoid trauma and to avoid anything that further impairs haemostasis. Aspirin and non-steroidal anti-inflammatory drugs inhibit platelet function and are replaced by paracetamol, and a soft toothbrush prevents gum bleeding. Non-contact activity is encouraged rather than inactivity, and first aid for a bleed is pressure, cold and elevation, followed by factor replacement.',
 '{"options":[{"id":"A","text":"Give paracetamol rather than aspirin or ibuprofen for pain"},{"id":"B","text":"Use a soft toothbrush and supervise daily dental care"},{"id":"C","text":"Encourage swimming and cycling with a helmet rather than contact sports"},{"id":"D","text":"Apply firm pressure and a cold pack to a bleeding site and elevate the limb"},{"id":"E","text":"Ask that all immunisations be given by the intramuscular route"},{"id":"F","text":"Massage a swollen joint vigorously to disperse the blood"}]}'::jsonb,
 '{"answers":["A","B","C","D"],"feedback":{"A":"Correct. Aspirin and ibuprofen impair platelet function and add to the bleeding risk.","B":"Correct. A soft brush prevents gum trauma, which is a common source of prolonged bleeding.","C":"Correct. Activity is encouraged for joint and muscle health, but contact sports are avoided.","D":"Correct. Pressure, cold and elevation limit bleeding until factor replacement is given.","E":"Incorrect. Subcutaneous administration with pressure afterwards is preferred to reduce deep muscle bleeding.","F":"Incorrect. Massage of a bleeding joint increases bleeding and pain; the joint is rested and elevated."}}'::jsonb,
 'Health Promotion and Maintenance', 'Health Promotion and Maintenance',
 'Pediatrics', 'Hematologic', 'Haemophilia', 'Home safety teaching',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', 'Select all that apply.', 4, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_521045', 'MCQ',
 'A nurse is teaching the parent of a 15-month-old who has been prescribed liquid ferrous sulfate for iron deficiency anaemia. Which statement by the parent indicates correct understanding?',
 'Iron is absorbed best in an acid environment on a relatively empty stomach, and vitamin C enhances absorption, whereas milk, tea and antacids bind iron and reduce it substantially. Liquid iron stains developing teeth, so it is given through a straw or placed towards the back of the mouth with a dropper, and the mouth is rinsed afterwards. Black tarry stools are an expected and harmless effect, not a reason to stop.',
 '{"options":[{"id":"A","text":"I will give it between meals with orange juice, using a dropper towards the back of the mouth"},{"id":"B","text":"I will mix it into a full bottle of milk so it goes down more easily"},{"id":"C","text":"I will stop the medicine if the stools turn black"},{"id":"D","text":"I will give it with a cup of tea to settle the stomach"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Between meals with vitamin C maximises absorption, and a dropper protects the teeth from staining.","B":"Incorrect. Milk binds iron and markedly reduces absorption.","C":"Incorrect. Black stools are an expected effect of oral iron and are not a reason to stop treatment.","D":"Incorrect. Tannins in tea bind iron and reduce absorption considerably."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pediatrics', 'Hematologic', 'Iron deficiency anaemia', 'Oral iron administration',
 'Easy', 'CURATOR_LABEL', 'Apply', '{}', NULL, 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_SELN_521046', 'SELECT_N',
 'A 6-year-old receiving chemotherapy for acute lymphoblastic leukaemia has a neutrophil count of 0.4 x 10^9/L. Which 3 actions should the nurse take?',
 'Severe neutropenia removes the ability to mount an inflammatory response, so infection may present only as fever and can progress within hours. Protective measures reduce exposure: a single room, exclusion of visitors with infection, removal of fresh flowers, plants and unpeeled raw foods that carry bacteria and fungal spores. Rectal thermometers, suppositories and live vaccines are avoided because they either breach the mucosa or introduce live organisms.',
 '{"options":[{"id":"A","text":"Nurse the child in a single room and exclude visitors with any infection"},{"id":"B","text":"Measure the temperature by the axillary route rather than the rectal route"},{"id":"C","text":"Remove fresh flowers and uncooked salad from the room"},{"id":"D","text":"Encourage the child to join group play sessions in the ward playroom"},{"id":"E","text":"Administer the scheduled live varicella vaccine"},{"id":"F","text":"Bathe the child daily using scented bubble bath"}],"select_count":3}'::jsonb,
 '{"answers":["A","B","C"],"feedback":{"A":"Correct. Reducing exposure to other people is the core of protective isolation.","B":"Correct. Rectal measurement can breach fragile mucosa and introduce bacteraemia.","C":"Correct. Flowers, plants and raw produce carry bacteria and fungal spores.","D":"Incorrect. Group play exposes a severely neutropenic child to other children and their infections.","E":"Incorrect. Live vaccines are contraindicated during immunosuppression.","F":"Incorrect. Scented products irritate and dry the skin, which is an important barrier to infection."}}'::jsonb,
 'Safe and Effective Care Environment', 'Safety and Infection Control',
 'Pediatrics', 'Hematologic', 'Neutropenia in childhood leukaemia', 'Protective measures',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 'Select 3.', 3, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_CLZ_521047', 'CLOZE',
 'A 14-year-old with type 1 diabetes becomes shaky, pale and sweaty during a physical education lesson, and the school nurse records a blood glucose of 3.1 mmol/L. The nurse should first give {1} and then recheck the blood glucose after {2}.',
 'Hypoglycaemia in a conscious adolescent is treated with about 15 g of a rapidly absorbed carbohydrate, such as glucose tablets or fruit juice, because fat and protein slow gastric emptying and delay the rise. The glucose is rechecked after 15 minutes and the dose repeated if it remains low, which is the rule of 15. Once the glucose is above 4 mmol/L, a longer-acting carbohydrate such as bread or a sandwich prevents a second fall.',
 '{"blanks":[{"id":"b1","choices":[{"id":"c1","text":"15 g of a fast-acting carbohydrate such as glucose tablets or fruit juice"},{"id":"c2","text":"the usual dose of rapid-acting insulin"},{"id":"c3","text":"a slice of wholemeal bread with peanut butter"}]},{"id":"b2","choices":[{"id":"c1","text":"5 minutes"},{"id":"c2","text":"15 minutes"},{"id":"c3","text":"60 minutes"}]}]}'::jsonb,
 '{"answers":{"b1":"c1","b2":"c2"},"feedback":{}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pediatrics', 'Endocrine', 'Type 1 diabetes in adolescence', 'Treating hypoglycaemia',
 'Medium', 'CURATOR_LABEL', 'Apply', '{}', 'Complete the sentence by choosing from each drop-down.', 2, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_521048', 'MCQ',
 'A nurse is teaching the parents of a newborn diagnosed with congenital hypothyroidism through newborn screening, who has been prescribed levothyroxine. Which statement indicates that teaching has been effective?',
 'Thyroid hormone is essential for brain development in the first years of life, so treatment must start within the first weeks and continue without interruption to prevent irreversible intellectual disability. The tablet is crushed and mixed with a small amount of water or breast milk and given at the same time each day, and it is not given with soya formula, iron or calcium, which bind the drug and reduce absorption. A missed dose is given as soon as it is remembered; doses are never doubled.',
 '{"options":[{"id":"A","text":"I will crush the tablet, mix it with a small amount of water or breast milk, give it at the same time each morning, and continue it for life"},{"id":"B","text":"I will mix the tablet into a full bottle of soya formula"},{"id":"C","text":"We can stop the medicine once the baby is growing well"},{"id":"D","text":"I will give a double dose if a dose was missed the day before"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Consistent daily dosing in a small volume of liquid, continued lifelong, is what protects brain development.","B":"Incorrect. Soya binds levothyroxine and significantly reduces absorption, and a full bottle may not be finished.","C":"Incorrect. Normal growth reflects successful treatment; stopping causes hypothyroidism to return.","D":"Incorrect. Doubling a dose risks thyrotoxic effects such as tachycardia and irritability."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pediatrics', 'Endocrine', 'Congenital hypothyroidism', 'Levothyroxine administration',
 'Hard', 'CURATOR_LABEL', 'Apply', '{}', NULL, 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MMR_521049', 'MATRIX_MR',
 'A nurse is admitting several children with communicable illnesses to a paediatric ward. For each illness, select all the transmission-based precautions required in addition to standard precautions.',
 'Transmission-based precautions follow the route the organism actually travels. Varicella needs both airborne and contact precautions because the virus is carried on air currents and is also present in the vesicle fluid, whereas measles is airborne only. Pertussis, mumps and group A streptococcal illness such as scarlet fever spread on large respiratory droplets that fall within a short distance, so droplet precautions apply until the child has had effective antibiotics or the infectious period has passed.',
 '{"rows":[{"id":"r1","text":"Chickenpox (varicella)"},{"id":"r2","text":"Measles"},{"id":"r3","text":"Pertussis (whooping cough)"},{"id":"r4","text":"Mumps"},{"id":"r5","text":"Scarlet fever (group A streptococcus)"}],"columns":[{"id":"c1","text":"Airborne"},{"id":"c2","text":"Droplet"},{"id":"c3","text":"Contact"}],"row_label":"Illness"}'::jsonb,
 '{"cells":{"r1":["c1","c3"],"r2":["c1"],"r3":["c2"],"r4":["c2"],"r5":["c2"]},"feedback":{}}'::jsonb,
 'Safe and Effective Care Environment', 'Safety and Infection Control',
 'Pediatrics', 'Immune', 'Communicable childhood illness', 'Transmission-based precautions',
 'Very hard', 'CURATOR_LABEL', 'Analyze', '{}', 'Select all that apply for each row.', 6, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728'),

('NCLEX_MCQ_521050', 'MCQ',
 'A 3-year-old is being discharged after treatment for Kawasaki disease with intravenous immunoglobulin and is continuing low-dose aspirin at home. Which instruction is most important for the nurse to give the parents?',
 'Kawasaki disease is one of the few paediatric indications for aspirin, given first in high dose for inflammation and then in low dose for its antiplatelet effect while the coronary arteries are at risk of aneurysm. Aspirin taken during a varicella or influenza infection is strongly associated with Reye syndrome, an acute encephalopathy with fatty liver, so exposure must be reported and the therapy reviewed. Parents are also told that live vaccines are deferred for about 11 months after immunoglobulin, because passive antibody blunts the response.',
 '{"options":[{"id":"A","text":"Contact the clinic if the child is exposed to chickenpox or influenza, because the aspirin must be reviewed to reduce the risk of Reye syndrome"},{"id":"B","text":"Give the aspirin only on days when the child has a fever"},{"id":"C","text":"Attend for the scheduled live vaccines during the next month as usual"},{"id":"D","text":"Stop the aspirin as soon as the rash and the peeling of the fingers have resolved"}]}'::jsonb,
 '{"answer":"A","feedback":{"A":"Correct. Aspirin during varicella or influenza is linked with Reye syndrome, so exposure must prompt urgent review.","B":"Incorrect. Low-dose aspirin is continued daily for its antiplatelet effect, not used as an antipyretic.","C":"Incorrect. Live vaccines are deferred for about 11 months after immunoglobulin because passive antibody blocks the response.","D":"Incorrect. Aspirin continues until coronary artery imaging confirms that no aneurysm has formed."}}'::jsonb,
 'Physiological Integrity', 'Pharmacological and Parenteral Therapies',
 'Pediatrics', 'Cardiovascular', 'Kawasaki disease', 'Aspirin therapy and Reye syndrome',
 'Hard', 'CURATOR_LABEL', 'Apply', '{}', NULL, 1, TRUE, TRUE, FALSE, FALSE,
 'gapfill-20260728');
