// mynclex/lib/authoring/actions/save-question.ts
//
// Server action for the new authoring tree. Branches on question_type
// and dispatches to the matching parser (lib/authoring/parsers/<type>.ts)
// to build content + correct JSONB. Currently supports MCQ (slice 2),
// TF (slice 3), SATA (slice 4), SELECT_N (slice 5), MATRIX (slice 6),
// and BOWTIE (slice 7); the remaining 3 types land slice-by-slice (8-10).
//
// Surface-aware: reads the `surface` hidden input on the form and
// branches between admin (nclex_bank_items, NCLEX_<TYPE>_NNNNN) and
// tutor (nclex_tutor_questions, NCLEX_TUT_<TYPE>_NNNNN, with
// tutor_id = auth.uid()).
//
// Returns a structured SaveResult instead of redirecting — the modal
// host (sandbox client / bank-list client) closes and re-renders the
// list via revalidatePath. Old `app/(app)/admin/bank/actions.ts` uses
// redirect() because it lives inside a focus-mode page; the new path
// is modal-based, so it owns its own UX flow.

'use server';

import { revalidatePath } from 'next/cache';
import { requireBankCurator, type ServerSupabaseClient } from '@/lib/access';
import {
  CLIENT_NEEDS_CATEGORIES,
  DIFFICULTY_LEVELS,
  ITEM_ID_PREFIX,
  TUTOR_ITEM_ID_PREFIX,
  type QuestionType,
} from '@/lib/authoring/classifications';
import type {
  BankItemContent,
  BankItemCorrect,
} from '@/lib/authoring/types';
import { parseMcq } from '@/lib/authoring/parsers/mcq';
import { parseTf } from '@/lib/authoring/parsers/tf';
import { parseSata } from '@/lib/authoring/parsers/sata';
import { parseSelectN } from '@/lib/authoring/parsers/select-n';
import { parseMatrix } from '@/lib/authoring/parsers/matrix';
import {
  parseBowtie,
  type BowtieWingInput,
} from '@/lib/authoring/parsers/bowtie';
import {
  parseCloze,
  type ClozeBlankInput,
} from '@/lib/authoring/parsers/cloze';
import {
  parseHighlight,
  type HighlightChunkInput,
} from '@/lib/authoring/parsers/highlight';

const VALID_CATEGORIES = new Set<string>(CLIENT_NEEDS_CATEGORIES);
const VALID_DIFFICULTIES = new Set<string>(DIFFICULTY_LEVELS);

type Surface = 'admin' | 'tutor';

export type SaveResult =
  | { ok: true; item_id: string; created: boolean }
  | { ok: false; error: string };

// ─────────────────────────────────────────────────────────────
// Surface plumbing.
// ─────────────────────────────────────────────────────────────

function surfaceConfig(surface: Surface) {
  if (surface === 'tutor') {
    return {
      table: 'nclex_tutor_questions' as const,
      prefix: TUTOR_ITEM_ID_PREFIX,
      revalidate: '/tutor/bank/all-v2',
    };
  }
  return {
    table: 'nclex_bank_items' as const,
    prefix: ITEM_ID_PREFIX,
    revalidate: '/admin/bank/all-v2',
  };
}

function readSurface(formData: FormData): Surface {
  const raw = String(formData.get('surface') ?? '');
  return raw === 'tutor' ? 'tutor' : 'admin';
}

// ─────────────────────────────────────────────────────────────
// Auto-numbering — same scheme as the legacy action so the IDs
// generated by both surfaces stay aligned during the transition.
// Lexical sort works because the suffix is fixed-width zero-padded.
// ─────────────────────────────────────────────────────────────

async function nextItemId(
  supabase: ServerSupabaseClient,
  surface: Surface,
  type: QuestionType,
): Promise<string> {
  const cfg = surfaceConfig(surface);
  const prefix = cfg.prefix[type];
  const { data, error } = await supabase
    .from(cfg.table)
    .select('item_id')
    .like('item_id', `${prefix}%`)
    .order('item_id', { ascending: false })
    .limit(1);

  if (error) throw error;

  let next = 1;
  if (data && data.length > 0) {
    const last = data[0].item_id as string;
    const suffix = last.slice(prefix.length);
    const n = parseInt(suffix, 10);
    if (Number.isFinite(n)) next = n + 1;
  }

  return `${prefix}${String(next).padStart(5, '0')}`;
}

// ─────────────────────────────────────────────────────────────
// Form parsing — branches per supported question type. Adds one
// case per slice (3-10) until every editor is wired in.
// ─────────────────────────────────────────────────────────────

const SUPPORTED_TYPES = new Set<QuestionType>([
  'MCQ',
  'TF',
  'SATA',
  'SELECT_N',
  'MATRIX',
  'BOWTIE',
  'CLOZE',
  'HIGHLIGHT',
]);

interface ParsedQuestion {
  question_type: QuestionType;
  instruction: string | null;
  stem: string;
  rationale: string | null;
  rationale_img: string | null;
  content: BankItemContent;
  correct: BankItemCorrect;
  client_needs_category: string;
  client_needs_subcategory: string | null;
  nursing_subject: string | null;
  body_system: string | null;
  topic: string | null;
  subtopic: string | null;
  difficulty: string | null;
  bloom_level: string | null;
  tags: string[];
  is_published: boolean;
  is_free_sample: boolean;
  is_builder_visible: boolean;
  marks: number;
  shuffle_options: boolean;
  question_ref: string | null;
  batch_id: string | null;
}

function parseQuestionFormData(formData: FormData): ParsedQuestion | { error: string } {
  const question_type = String(formData.get('question_type') ?? '') as QuestionType;
  if (!SUPPORTED_TYPES.has(question_type)) {
    return {
      error: `Unsupported question type "${question_type}" — current support: ${[...SUPPORTED_TYPES].join(', ')}.`,
    };
  }

  const stem = String(formData.get('stem') ?? '').trim();
  if (!stem) return { error: 'Stem is required.' };

  const instructionRaw = String(formData.get('instruction') ?? '').trim();
  const instruction = instructionRaw || null;

  const client_needs_category = String(formData.get('client_needs_category') ?? '').trim();
  if (!VALID_CATEGORIES.has(client_needs_category)) {
    return { error: 'Client Needs category is required.' };
  }

  const optionIds = formData.getAll('option_id').map(String);
  const optionTexts = formData.getAll('option_text').map(String);
  const optionFeedbacks = formData.getAll('option_feedback').map(String);
  const correctIds = formData
    .getAll('correct_id')
    .map((v) => String(v).trim())
    .filter(Boolean);

  // Per-type content/correct construction. Each branch returns the
  // matching parser's { content, correct } pair (or an error).
  // MATRIX uses a different form-data contract (rows × columns +
  // dynamic per-row correct radios) so it builds its own input
  // payload instead of consuming the option arrays.
  const parsed = (() => {
    switch (question_type) {
      case 'TF':
        return parseTf(optionIds, optionTexts, optionFeedbacks, correctIds);
      case 'SATA':
        return parseSata(optionIds, optionTexts, optionFeedbacks, correctIds);
      case 'SELECT_N': {
        const selectCount = parseInt(String(formData.get('select_count') ?? ''), 10);
        return parseSelectN(
          optionIds,
          optionTexts,
          optionFeedbacks,
          correctIds,
          selectCount,
        );
      }
      case 'MATRIX': {
        const rowIds = formData.getAll('matrix_row_id').map(String);
        const rowTexts = formData.getAll('matrix_row_text').map(String);
        const rowFeedbacks = formData.getAll('matrix_row_feedback').map(String);
        const colIds = formData.getAll('matrix_col_id').map(String);
        const colTexts = formData.getAll('matrix_col_text').map(String);
        const correctByRow: Record<string, string> = {};
        for (const rid of rowIds) {
          const picked = String(formData.get(`matrix_correct_${rid}`) ?? '').trim();
          if (picked) correctByRow[rid] = picked;
        }
        return parseMatrix({
          row_label: String(formData.get('matrix_row_label') ?? ''),
          rowIds,
          rowTexts,
          rowFeedbacks,
          colIds,
          colTexts,
          correctByRow,
        });
      }
      case 'BOWTIE': {
        const readWing = (
          wing: 'left' | 'centre' | 'right',
        ): BowtieWingInput => ({
          label: String(formData.get(`bowtie_${wing}_label`) ?? ''),
          tokenIds:       formData.getAll(`bowtie_${wing}_token_id`).map(String),
          tokenTexts:     formData.getAll(`bowtie_${wing}_token_text`).map(String),
          tokenFeedbacks: formData.getAll(`bowtie_${wing}_token_feedback`).map(String),
          // Centre uses a single radio value; left/right post repeated checkbox values.
          correctIds:
            wing === 'centre'
              ? [String(formData.get('bowtie_centre_correct') ?? '')]
              : formData.getAll(`bowtie_${wing}_correct`).map(String),
        });
        return parseBowtie({
          left:   readWing('left'),
          centre: readWing('centre'),
          right:  readWing('right'),
        });
      }
      case 'CLOZE': {
        // Read the parallel arrays of blank cards (every card the
        // editor holds, including orphans). For each one, read its
        // per-blank choice arrays via dynamic field names keyed on
        // the blank ID. Filter out orphans (in_stem !== 'true')
        // before handing to the parser.
        const blankIds = formData.getAll('cloze_blank_id').map(String);
        const inStemFlags = formData.getAll('cloze_blank_in_stem').map(String);
        const blanks: ClozeBlankInput[] = [];
        for (let i = 0; i < blankIds.length; i++) {
          const bid = blankIds[i];
          if (inStemFlags[i] !== 'true') continue;
          const choiceIds  = formData.getAll(`cloze_choice_id_${bid}`).map(String);
          const choiceTexts = formData.getAll(`cloze_choice_text_${bid}`).map(String);
          const choiceFbs   = formData.getAll(`cloze_choice_feedback_${bid}`).map(String);
          const choices = choiceIds.map((cid, j) => ({
            id: cid,
            text: choiceTexts[j] ?? '',
            feedback: choiceFbs[j] ?? '',
          }));
          blanks.push({
            id: bid,
            choices,
            correct_id: String(formData.get(`cloze_correct_${bid}`) ?? ''),
          });
        }
        return parseCloze({ stem, blanks });
      }
      case 'HIGHLIGHT': {
        // Five parallel arrays per chunk card. Orphans (in_passage !==
        // 'true') get passed through to the parser, which filters them.
        const chunkIds        = formData.getAll('hl_chunk_id').map(String);
        const chunkTexts      = formData.getAll('hl_chunk_text').map(String);
        const chunkDecisions  = formData.getAll('hl_chunk_decision').map(String);
        const chunkFeedbacks  = formData.getAll('hl_chunk_feedback').map(String);
        const chunkInPassages = formData.getAll('hl_chunk_in_passage').map(String);
        const hlChunks: HighlightChunkInput[] = chunkIds.map((id, i) => ({
          id,
          text: chunkTexts[i] ?? '',
          decision:
            chunkDecisions[i] === 'correct'
              ? 'correct'
              : chunkDecisions[i] === 'wrong'
                ? 'wrong'
                : 'undecided',
          feedback: chunkFeedbacks[i] ?? '',
          in_passage: chunkInPassages[i] === 'true',
        }));
        return parseHighlight({ stem, chunks: hlChunks });
      }
      default:
        return parseMcq(optionIds, optionTexts, optionFeedbacks, correctIds);
    }
  })();
  if (!parsed.ok) return { error: parsed.error };

  const subcategory = String(formData.get('client_needs_subcategory') ?? '').trim();
  const difficultyRaw = String(formData.get('difficulty') ?? '').trim();
  const difficulty =
    difficultyRaw && VALID_DIFFICULTIES.has(difficultyRaw) ? difficultyRaw : null;

  const tagsRaw = String(formData.get('tags') ?? '');
  const tags = tagsRaw.split(',').map((t) => t.trim()).filter(Boolean);

  const marksRaw = parseFloat(String(formData.get('marks') ?? '1'));
  const marks = Number.isFinite(marksRaw) && marksRaw > 0 ? marksRaw : 1;

  // CLOZE rewrites the stem on save (gap-closing renumber). Other
  // parsers don't touch it, so we fall back to the curator-typed stem.
  const finalStem = 'stem' in parsed ? parsed.stem : stem;

  return {
    question_type,
    instruction,
    stem: finalStem,
    rationale: String(formData.get('rationale') ?? '').trim() || null,
    rationale_img: String(formData.get('rationale_img') ?? '').trim() || null,
    content: parsed.content,
    correct: parsed.correct,
    client_needs_category,
    client_needs_subcategory: subcategory || null,
    nursing_subject: String(formData.get('nursing_subject') ?? '').trim() || null,
    body_system: String(formData.get('body_system') ?? '').trim() || null,
    topic: String(formData.get('topic') ?? '').trim() || null,
    subtopic: String(formData.get('subtopic') ?? '').trim() || null,
    difficulty,
    bloom_level: String(formData.get('bloom_level') ?? '').trim() || null,
    tags,
    is_published: formData.get('is_published') === 'on',
    is_free_sample: formData.get('is_free_sample') === 'on',
    // Default true: when the checkbox is rendered, the form posts 'on'
    // when ticked and nothing when unticked. We treat "absent" as
    // "default true" only in standalone mode (which is the only mode
    // slice 2 ships).
    is_builder_visible: formData.get('is_builder_visible') !== null,
    marks,
    shuffle_options: formData.get('shuffle_options') === 'on',
    question_ref: String(formData.get('question_ref') ?? '').trim() || null,
    batch_id: String(formData.get('batch_id') ?? '').trim() || null,
  };
}

// ─────────────────────────────────────────────────────────────
// Save action — create OR update based on presence of item_id in
// the form. Returns SaveResult for the modal host to consume.
// ─────────────────────────────────────────────────────────────

export async function saveQuestionAction(formData: FormData): Promise<SaveResult> {
  const surface = readSurface(formData);
  const { supabase, user } = await requireBankCurator(surface);

  const parsed = parseQuestionFormData(formData);
  if ('error' in parsed) return { ok: false, error: parsed.error };

  const cfg = surfaceConfig(surface);
  const existingItemId = String(formData.get('item_id') ?? '').trim();

  // ── UPDATE ─────────────────────────────────────────────────
  if (existingItemId) {
    const { data: existing, error: fetchErr } = await supabase
      .from(cfg.table)
      .select('question_type')
      .eq('item_id', existingItemId)
      .maybeSingle();

    if (fetchErr || !existing) {
      return { ok: false, error: 'Question not found.' };
    }
    if (existing.question_type !== parsed.question_type) {
      return { ok: false, error: 'Question type cannot be changed after creation.' };
    }

    const { error } = await supabase
      .from(cfg.table)
      .update({
        ...parsed,
        updated_at: new Date().toISOString(),
      })
      .eq('item_id', existingItemId);

    if (error) return { ok: false, error: `Update failed: ${error.message}` };

    revalidatePath(cfg.revalidate);
    return { ok: true, item_id: existingItemId, created: false };
  }

  // ── CREATE ─────────────────────────────────────────────────
  const item_id = await nextItemId(supabase, surface, parsed.question_type);

  const row: Record<string, unknown> = { item_id, ...parsed };
  if (surface === 'tutor') {
    row.tutor_id = user.id;
  }

  const { error } = await supabase.from(cfg.table).insert(row);
  if (error) return { ok: false, error: `Insert failed: ${error.message}` };

  revalidatePath(cfg.revalidate);
  return { ok: true, item_id, created: true };
}
