-- db/seed/pitch/09-weekly-year.sql
-- GENERATED by db/seed/pitch/build_weekly_year.py — edit the generator.
--
-- The Free Weekly NCLEX Q&A becomes a full year: 52 weeks, each with a
-- taught NCLEX topic (~25 min) followed by the open floor (~30 min).
--
-- Weeks 1-51 carry one Client Needs subcategory each; week 52 is the
-- finale. Across the 51 teaching weeks every subcategory lands inside
-- its published NCSBN range:
--
--   Management of Care                          8 weeks  15.7%  (15-21%)
--   Safety and Infection Control                7 weeks  13.7%  (10-16%)
--   Health Promotion and Maintenance            5 weeks   9.8%  (6-12%)
--   Psychosocial Integrity                      5 weeks   9.8%  (6-12%)
--   Basic Care and Comfort                      5 weeks   9.8%  (6-12%)
--   Pharmacological and Parenteral Therapies    8 weeks  15.7%  (13-19%)
--   Reduction of Risk Potential                 6 weeks  11.8%  (9-15%)
--   Physiological Adaptation                    7 weeks  13.7%  (11-17%)
--
-- Four terms of 13, each touching all eight areas in proportion, so
-- joining cold in any term still gives representative coverage.
--
-- Weeks 6, 17, 22, 29, 34, 40 point at the paid maternity
-- programmes from 08-maternity.sql (the activity `note` field).
--
-- Live sessions are dated for TERM 1 ONLY (weeks 1-13).
-- Terms 2-4 are published with their topic and no date, because 52
-- dated sessions is a year-long promise a tutor should make a term at
-- a time.
--
-- Requires 08-maternity.sql (the programme row and the six notes it
-- cross-sells). Idempotent throughout.

BEGIN;

-- ====================================================================
-- 1. The programme — 4 weeks becomes 52
-- ====================================================================
-- Upsert rather than UPDATE so the file stands alone if the programme
-- was never seeded. Either path fires a unit trigger (seed_units on
-- INSERT, reconcile_units on the length_units change), both of which
-- create blank units with random ids — section 2 clears them.

INSERT INTO nclex_programmes (
  programme_id, tutor_id, title, tagline, description,
  delivery_mode, unit_label, length_units,
  price_currency, show_price_publicly, payment_collection_mode,
  access_window_days, payment_gates_access, status, published_at
) VALUES (
  '80000000-0000-4000-8000-000000000004', '4ed777d7-e4f7-403b-88f4-63ce5432d65e',
  'Free Weekly NCLEX Q&A',
  'A free taught session every Tuesday, all year — weighted to the real test plan. Recordings the same evening.',
  'Every Tuesday evening I teach one NCLEX topic for about twenty-five minutes, and then the floor is open for as long as you have questions. It is free, and it always will be.

The year is not a random list of topics. All eight NCLEX Client Needs areas appear across the 52 weeks in the same proportions the real exam uses, so a candidate who attends for a year has been taught the test plan — not somebody''s favourite subjects. The year runs in four terms of thirteen weeks, and every term touches all eight areas, so it does not matter which week you start.

Sessions are recorded and posted here the same evening, so a shift does not cost you the week. Join the cohort and you get the joining link, the full 52-week plan and every recording so far.

Who comes: candidates at every stage, including people who have not decided whether they want a paid programme at all. That is fine. Come and see how I teach before you spend anything.',
  'TUTOR_LED', 'WEEK', 52,
  'GHS', TRUE, 'ON_PLATFORM',
  NULL, FALSE, 'PUBLISHED', NOW()
)
ON CONFLICT (programme_id) DO UPDATE SET
  title = EXCLUDED.title, tagline = EXCLUDED.tagline,
  description = EXCLUDED.description, delivery_mode = EXCLUDED.delivery_mode,
  unit_label = EXCLUDED.unit_label, length_units = EXCLUDED.length_units,
  access_window_days = EXCLUDED.access_window_days,
  show_price_publicly = EXCLUDED.show_price_publicly,
  payment_gates_access = EXCLUDED.payment_gates_access,
  status = 'PUBLISHED', updated_at = NOW();

-- ====================================================================
-- 2. Clear the trigger's blank units
-- ====================================================================
-- Must run AFTER section 1 and BEFORE section 3: the trigger's rows
-- carry random ids and collide with ours on (programme_id, unit_index).

DELETE FROM nclex_programme_units
WHERE  programme_id = '80000000-0000-4000-8000-000000000004'
  AND  unit_id::text NOT LIKE '81000000-0000-4000-8000-004%';

-- ====================================================================
-- 3. Fifty-two weeks
-- ====================================================================
-- The unit description carries the term and the NCLEX area, so both
-- are visible everywhere a unit is listed.

INSERT INTO nclex_programme_units
  (unit_id, programme_id, unit_index, title, description, is_published)
VALUES
  ('81000000-0000-4000-8000-004001000000', '80000000-0000-4000-8000-000000000004', 1,
   'Prioritisation: who do you see first?',
   'Term 1 · Foundations — Management of Care. Maslow, ABC, acute before chronic, unstable before stable — and the order to apply them in.', TRUE),
  ('81000000-0000-4000-8000-004002000000', '80000000-0000-4000-8000-000000000004', 2,
   'The five rights of delegation',
   'Term 1 · Foundations — Safety and Infection Control. What an RN may delegate to an LPN and to a UAP, and the tasks that can never leave the RN.', TRUE),
  ('81000000-0000-4000-8000-004003000000', '80000000-0000-4000-8000-000000000004', 3,
   'The six rights of medication administration',
   'Term 1 · Foundations — Pharmacological and Parenteral Therapies. The six rights, the three checks, and the high-alert drugs that need a second nurse.', TRUE),
  ('81000000-0000-4000-8000-004004000000', '80000000-0000-4000-8000-000000000004', 4,
   'Fluids and electrolytes I: sodium and potassium',
   'Term 1 · Foundations — Physiological Adaptation. Hyper- and hyponatraemia, hyper- and hypokalaemia: the signs, and what you never push IV.', TRUE),
  ('81000000-0000-4000-8000-004005000000', '80000000-0000-4000-8000-000000000004', 5,
   'The ten lab values that actually turn up',
   'Term 1 · Foundations — Reduction of Risk Potential. The values worth memorising, the ones you can reason out, and how the exam disguises them.', TRUE),
  ('81000000-0000-4000-8000-004006000000', '80000000-0000-4000-8000-000000000004', 6,
   'Dating a pregnancy',
   'Term 1 · Foundations — Health Promotion and Maintenance. Naegele''s rule, the weeks-minus-nine weight shortcut, fundal height and the visit schedule.', TRUE),
  ('81000000-0000-4000-8000-004007000000', '80000000-0000-4000-8000-000000000004', 7,
   'Consent, advance directives, and who can sign',
   'Term 1 · Foundations — Management of Care. Informed consent and whose job it is, advance directives, power of attorney, and the minor exceptions.', TRUE),
  ('81000000-0000-4000-8000-004008000000', '80000000-0000-4000-8000-000000000004', 8,
   'Therapeutic communication',
   'Term 1 · Foundations — Psychosocial Integrity. Open questions, reflection and silence — and the reassurance, advice and ''why'' questions that lose marks.', TRUE),
  ('81000000-0000-4000-8000-004009000000', '80000000-0000-4000-8000-000000000004', 9,
   'Infection control: the four precaution types',
   'Term 1 · Foundations — Safety and Infection Control. Standard, contact, droplet and airborne — which disease sits where, and the PPE that goes with each.', TRUE),
  ('81000000-0000-4000-8000-004010000000', '80000000-0000-4000-8000-000000000004', 10,
   'Insulin: types, peaks, and the sliding scale',
   'Term 1 · Foundations — Pharmacological and Parenteral Therapies. Onset and peak by insulin type, when hypoglycaemia is due, mixing order, and the sliding-scale question.', TRUE),
  ('81000000-0000-4000-8000-004011000000', '80000000-0000-4000-8000-000000000004', 11,
   'Acid-base, made mechanical',
   'Term 1 · Foundations — Physiological Adaptation. The tic-tac-toe method: read the pH, read the CO2 and the bicarb, name it, and decide if it is compensated.', TRUE),
  ('81000000-0000-4000-8000-004012000000', '80000000-0000-4000-8000-000000000004', 12,
   'Positioning: the ones the exam asks about',
   'Term 1 · Foundations — Basic Care and Comfort. Post-op, post-procedure and emergency positions — and the reason behind each, so you can derive it.', TRUE),
  ('81000000-0000-4000-8000-004013000000', '80000000-0000-4000-8000-000000000004', 13,
   'Pre- and post-operative care',
   'Term 1 · Foundations — Reduction of Risk Potential. The pre-op checklist, what stops a case going ahead, and the post-op complications by day.', TRUE),
  ('81000000-0000-4000-8000-004014000000', '80000000-0000-4000-8000-000000000004', 14,
   'Heart failure: left versus right',
   'Term 2 · The body under stress — Physiological Adaptation. Pulmonary signs versus systemic signs, and the assessment findings that separate them at the bedside.', TRUE),
  ('81000000-0000-4000-8000-004015000000', '80000000-0000-4000-8000-000000000004', 15,
   'Cardiac drugs and their toxicity signs',
   'Term 2 · The body under stress — Pharmacological and Parenteral Therapies. Digoxin, beta blockers and ACE inhibitors: what you hold them for, and the first sign of toxicity.', TRUE),
  ('81000000-0000-4000-8000-004016000000', '80000000-0000-4000-8000-000000000004', 16,
   'Triage and disaster',
   'Term 2 · The body under stress — Management of Care. Who gets treated first in a mass-casualty event, and why the usual priority rules invert.', TRUE),
  ('81000000-0000-4000-8000-004017000000', '80000000-0000-4000-8000-000000000004', 17,
   'Positive, probable, presumptive',
   'Term 2 · The body under stress — Health Promotion and Maintenance. The four signs that PROVE a pregnancy, why a positive test is not one, and the three-word range trick.', TRUE),
  ('81000000-0000-4000-8000-004018000000', '80000000-0000-4000-8000-000000000004', 18,
   'Falls, restraints and the rules that govern them',
   'Term 2 · The body under stress — Safety and Infection Control. Risk assessment, the least-restrictive rule, the order requirements, and what must be documented.', TRUE),
  ('81000000-0000-4000-8000-004019000000', '80000000-0000-4000-8000-000000000004', 19,
   'ECG basics: the four rhythms you must recognise',
   'Term 2 · The body under stress — Reduction of Risk Potential. Normal sinus, atrial fibrillation, ventricular tachycardia and ventricular fibrillation — and the response to each.', TRUE),
  ('81000000-0000-4000-8000-004020000000', '80000000-0000-4000-8000-000000000004', 20,
   'COPD versus asthma, and the oxygen trap',
   'Term 2 · The body under stress — Physiological Adaptation. How the two differ in presentation and treatment, and why high-flow oxygen is the wrong answer in COPD.', TRUE),
  ('81000000-0000-4000-8000-004021000000', '80000000-0000-4000-8000-000000000004', 21,
   'Anticoagulants: heparin versus warfarin',
   'Term 2 · The body under stress — Pharmacological and Parenteral Therapies. Which lab monitors which, the therapeutic ranges, the antidotes, and the teaching points.', TRUE),
  ('81000000-0000-4000-8000-004022000000', '80000000-0000-4000-8000-000000000004', 22,
   'The stages of labour, and the prolapsed cord',
   'Term 2 · The body under stress — Health Promotion and Maintenance. The four stages, the three phases of the first, how to time contractions, and the emergency you act on before calling.', TRUE),
  ('81000000-0000-4000-8000-004023000000', '80000000-0000-4000-8000-000000000004', 23,
   'Anxiety versus panic',
   'Term 2 · The body under stress — Psychosocial Integrity. The four levels of anxiety, what a client can still learn at each, and the level at which you stop teaching and stay.', TRUE),
  ('81000000-0000-4000-8000-004024000000', '80000000-0000-4000-8000-000000000004', 24,
   'Medication errors: reporting and prevention',
   'Term 2 · The body under stress — Safety and Infection Control. What you do first for the client, incident reporting, and the just-culture reasoning behind it.', TRUE),
  ('81000000-0000-4000-8000-004025000000', '80000000-0000-4000-8000-000000000004', 25,
   'Case management, referrals and continuity',
   'Term 2 · The body under stress — Management of Care. Discharge planning, which discipline to refer to, and the handover that does not lose information.', TRUE),
  ('81000000-0000-4000-8000-004026000000', '80000000-0000-4000-8000-000000000004', 26,
   'Therapeutic diets: who gets which',
   'Term 2 · The body under stress — Basic Care and Comfort. Renal, cardiac, diabetic, low-residue and dysphagia diets — and the food the exam plants as a distractor.', TRUE),
  ('81000000-0000-4000-8000-004027000000', '80000000-0000-4000-8000-000000000004', 27,
   'Prioritisation II: the four-patient question',
   'Term 3 · Complex care — Management of Care. The format where four clients are described and one needs you now. A method, worked live on real stems.', TRUE),
  ('81000000-0000-4000-8000-004028000000', '80000000-0000-4000-8000-000000000004', 28,
   'DKA versus HHS, Addison versus Cushing',
   'Term 3 · Complex care — Physiological Adaptation. Two pairs the exam confuses on purpose: what separates them, and the treatment that differs.', TRUE),
  ('81000000-0000-4000-8000-004029000000', '80000000-0000-4000-8000-000000000004', 29,
   'Reading a fetal monitor strip',
   'Term 3 · Complex care — Reduction of Risk Potential. VEAL CHOP: naming the pattern from its timing, and the five actions for a late deceleration.', TRUE),
  ('81000000-0000-4000-8000-004030000000', '80000000-0000-4000-8000-000000000004', 30,
   'Pain management and the opioid rules',
   'Term 3 · Complex care — Pharmacological and Parenteral Therapies. The analgesic ladder, equianalgesia, the respiratory-rate threshold, and naloxone.', TRUE),
  ('81000000-0000-4000-8000-004031000000', '80000000-0000-4000-8000-000000000004', 31,
   'Delegation II: the assignments you cannot make',
   'Term 3 · Complex care — Management of Care. Room assignments, infection risk, the new graduate, and the float nurse outside their competence.', TRUE),
  ('81000000-0000-4000-8000-004032000000', '80000000-0000-4000-8000-000000000004', 32,
   'Stroke, raised ICP, and the signs you never ignore',
   'Term 3 · Complex care — Physiological Adaptation. Ischaemic versus haemorrhagic, the tPA window, Cushing''s triad, and the positioning that differs.', TRUE),
  ('81000000-0000-4000-8000-004033000000', '80000000-0000-4000-8000-000000000004', 33,
   'Emergencies: the order of actions',
   'Term 3 · Complex care — Safety and Infection Control. When several things are happening at once — what you do, what you delegate, and what waits.', TRUE),
  ('81000000-0000-4000-8000-004034000000', '80000000-0000-4000-8000-000000000004', 34,
   'Postpartum assessment',
   'Term 3 · Complex care — Health Promotion and Maintenance. Fundus (tone, height, position), lochia, temperature — and why a deviated fundus changes your first action.', TRUE),
  ('81000000-0000-4000-8000-004035000000', '80000000-0000-4000-8000-000000000004', 35,
   'Antibiotics: families, toxicities, peak and trough',
   'Term 3 · Complex care — Pharmacological and Parenteral Therapies. Aminoglycosides, vancomycin and the rest: what each damages, and when the levels are drawn.', TRUE),
  ('81000000-0000-4000-8000-004036000000', '80000000-0000-4000-8000-000000000004', 36,
   'Diagnostic tests: prep, aftercare, consent',
   'Term 3 · Complex care — Reduction of Risk Potential. NPO rules, contrast and the kidney, which tests need written consent, and the post-procedure checks.', TRUE),
  ('81000000-0000-4000-8000-004037000000', '80000000-0000-4000-8000-000000000004', 37,
   'Incident reports, QI, and what belongs in a chart',
   'Term 3 · Complex care — Management of Care. The difference between the chart and the incident report, and the documentation that survives scrutiny.', TRUE),
  ('81000000-0000-4000-8000-004038000000', '80000000-0000-4000-8000-000000000004', 38,
   'Depression and suicide risk',
   'Term 3 · Complex care — Psychosocial Integrity. Assessing risk directly, the danger period as mood lifts, and what a safety plan contains.', TRUE),
  ('81000000-0000-4000-8000-004039000000', '80000000-0000-4000-8000-000000000004', 39,
   'Mobility, skin integrity and pressure injuries',
   'Term 3 · Complex care — Basic Care and Comfort. The four stages plus unstageable, the sites that break down first, and prevention that is actually done.', TRUE),
  ('81000000-0000-4000-8000-004040000000', '80000000-0000-4000-8000-000000000004', 40,
   'The normal newborn — and what is not',
   'Term 4 · Finishing — Physiological Adaptation. Skin findings that need only reassurance, the 24-hour jaundice rule, and APGAR bands and actions.', TRUE),
  ('81000000-0000-4000-8000-004041000000', '80000000-0000-4000-8000-000000000004', 41,
   'Substance use: withdrawal, and what you treat first',
   'Term 4 · Finishing — Psychosocial Integrity. Alcohol withdrawal timelines and why it is the lethal one, opioid withdrawal, and the CIWA response.', TRUE),
  ('81000000-0000-4000-8000-004042000000', '80000000-0000-4000-8000-000000000004', 42,
   'Lithium, SSRIs, antipsychotics — and their crises',
   'Term 4 · Finishing — Pharmacological and Parenteral Therapies. Lithium levels and toxicity, serotonin syndrome, neuroleptic malignant syndrome, and extrapyramidal signs.', TRUE),
  ('81000000-0000-4000-8000-004043000000', '80000000-0000-4000-8000-000000000004', 43,
   'Immunisation across the lifespan',
   'Term 4 · Finishing — Health Promotion and Maintenance. The childhood schedule, live-vaccine contraindications, and the adult and pregnancy exceptions.', TRUE),
  ('81000000-0000-4000-8000-004044000000', '80000000-0000-4000-8000-000000000004', 44,
   'Paediatric safety and developmental milestones',
   'Term 4 · Finishing — Safety and Infection Control. The hazard that matches each age, car-seat and sleep rules, and the milestones worth memorising.', TRUE),
  ('81000000-0000-4000-8000-004045000000', '80000000-0000-4000-8000-000000000004', 45,
   'Elimination: catheters, ostomies, bowel programmes',
   'Term 4 · Finishing — Basic Care and Comfort. Catheter care and CAUTI prevention, stoma assessment and output by type, and bowel training.', TRUE),
  ('81000000-0000-4000-8000-004046000000', '80000000-0000-4000-8000-000000000004', 46,
   'Paediatric vital signs that change everything',
   'Term 4 · Finishing — Reduction of Risk Potential. Normal ranges by age, the first sign of paediatric deterioration, and why the blood pressure falls last.', TRUE),
  ('81000000-0000-4000-8000-004047000000', '80000000-0000-4000-8000-000000000004', 47,
   'Grief, loss and end-of-life care',
   'Term 4 · Finishing — Psychosocial Integrity. The stages and why they are not a sequence, cultural practice around death, and comfort-focused care.', TRUE),
  ('81000000-0000-4000-8000-004048000000', '80000000-0000-4000-8000-000000000004', 48,
   'Home and community safety for the older adult',
   'Term 4 · Finishing — Safety and Infection Control. Fall-proofing a home, polypharmacy, driving and heat, and recognising elder abuse.', TRUE),
  ('81000000-0000-4000-8000-004049000000', '80000000-0000-4000-8000-000000000004', 49,
   'Dosage calculation, worked slowly',
   'Term 4 · Finishing — Pharmacological and Parenteral Therapies. The four question types — tablets, liquids, IV rates, weight-based — one method each, done step by step.', TRUE),
  ('81000000-0000-4000-8000-004050000000', '80000000-0000-4000-8000-000000000004', 50,
   'Putting it together: a full prioritisation set',
   'Term 4 · Finishing — Management of Care. A live set of prioritisation and delegation stems, answered out loud, with the reasoning shown each time.', TRUE),
  ('81000000-0000-4000-8000-004051000000', '80000000-0000-4000-8000-000000000004', 51,
   'Comfort, sleep and complementary therapies',
   'Term 4 · Finishing — Basic Care and Comfort. Non-pharmacological pain relief, sleep hygiene on shift work, and the therapies the exam recognises.', TRUE),
  ('81000000-0000-4000-8000-004052000000', '80000000-0000-4000-8000-000000000004', 52,
   'Exam day, and how CAT actually works',
   'Term 4 · Finishing — The finale. What computer-adaptive testing really does, the 85-150 item range, the last two weeks, and the day itself.', TRUE)
ON CONFLICT (unit_id) DO UPDATE SET
  title = EXCLUDED.title, description = EXCLUDED.description,
  is_published = TRUE, updated_at = NOW();

-- ====================================================================
-- 4. One block per week
-- ====================================================================

INSERT INTO nclex_programme_blocks
  (block_id, unit_id, cohort_id, ordinal, title, description, is_published)
VALUES
  ('82000000-0000-4000-8000-004001001000', '81000000-0000-4000-8000-004001000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004002001000', '81000000-0000-4000-8000-004002000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004003001000', '81000000-0000-4000-8000-004003000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004004001000', '81000000-0000-4000-8000-004004000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004005001000', '81000000-0000-4000-8000-004005000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004006001000', '81000000-0000-4000-8000-004006000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004007001000', '81000000-0000-4000-8000-004007000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004008001000', '81000000-0000-4000-8000-004008000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004009001000', '81000000-0000-4000-8000-004009000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004010001000', '81000000-0000-4000-8000-004010000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004011001000', '81000000-0000-4000-8000-004011000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004012001000', '81000000-0000-4000-8000-004012000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004013001000', '81000000-0000-4000-8000-004013000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004014001000', '81000000-0000-4000-8000-004014000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004015001000', '81000000-0000-4000-8000-004015000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004016001000', '81000000-0000-4000-8000-004016000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004017001000', '81000000-0000-4000-8000-004017000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004018001000', '81000000-0000-4000-8000-004018000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004019001000', '81000000-0000-4000-8000-004019000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004020001000', '81000000-0000-4000-8000-004020000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004021001000', '81000000-0000-4000-8000-004021000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004022001000', '81000000-0000-4000-8000-004022000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004023001000', '81000000-0000-4000-8000-004023000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004024001000', '81000000-0000-4000-8000-004024000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004025001000', '81000000-0000-4000-8000-004025000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004026001000', '81000000-0000-4000-8000-004026000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004027001000', '81000000-0000-4000-8000-004027000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004028001000', '81000000-0000-4000-8000-004028000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004029001000', '81000000-0000-4000-8000-004029000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004030001000', '81000000-0000-4000-8000-004030000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004031001000', '81000000-0000-4000-8000-004031000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004032001000', '81000000-0000-4000-8000-004032000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004033001000', '81000000-0000-4000-8000-004033000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004034001000', '81000000-0000-4000-8000-004034000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004035001000', '81000000-0000-4000-8000-004035000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004036001000', '81000000-0000-4000-8000-004036000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004037001000', '81000000-0000-4000-8000-004037000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004038001000', '81000000-0000-4000-8000-004038000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004039001000', '81000000-0000-4000-8000-004039000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004040001000', '81000000-0000-4000-8000-004040000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004041001000', '81000000-0000-4000-8000-004041000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004042001000', '81000000-0000-4000-8000-004042000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004043001000', '81000000-0000-4000-8000-004043000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004044001000', '81000000-0000-4000-8000-004044000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004045001000', '81000000-0000-4000-8000-004045000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004046001000', '81000000-0000-4000-8000-004046000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004047001000', '81000000-0000-4000-8000-004047000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004048001000', '81000000-0000-4000-8000-004048000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004049001000', '81000000-0000-4000-8000-004049000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004050001000', '81000000-0000-4000-8000-004050000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004051001000', '81000000-0000-4000-8000-004051000000', NULL, 1, 'This week', NULL, TRUE),
  ('82000000-0000-4000-8000-004052001000', '81000000-0000-4000-8000-004052000000', NULL, 1, 'This week', NULL, TRUE)
ON CONFLICT (block_id) DO UPDATE SET
  title = EXCLUDED.title, is_published = TRUE, updated_at = NOW();

-- ====================================================================
-- 5. The live session for each week
-- ====================================================================
-- ONLINE_LIVE_SESSION is a MARKER: identity and typical duration only.
-- Dates, joining details and recordings are per-cohort and live in
-- nclex_cohort_live_sessions (section 8).
--
-- `note` renders as "Note: ..." in online-live-session-viewer.tsx,
-- which is where the six cross-sell weeks put their pointer.

INSERT INTO nclex_programme_activities
  (activity_id, unit_id, block_id, cohort_id, ordinal,
   type, title, description, note, payload, is_published)
VALUES
  ('83000000-0000-4000-8000-004001001001',
   '81000000-0000-4000-8000-004001000000',
   '82000000-0000-4000-8000-004001001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Prioritisation: who do you see first?',
   'About 25 minutes on Management of Care, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004002001001',
   '81000000-0000-4000-8000-004002000000',
   '82000000-0000-4000-8000-004002001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'The five rights of delegation',
   'About 25 minutes on Safety and Infection Control, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004003001001',
   '81000000-0000-4000-8000-004003000000',
   '82000000-0000-4000-8000-004003001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'The six rights of medication administration',
   'About 25 minutes on Pharmacological and Parenteral Therapies, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004004001001',
   '81000000-0000-4000-8000-004004000000',
   '82000000-0000-4000-8000-004004001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Fluids and electrolytes I: sodium and potassium',
   'About 25 minutes on Physiological Adaptation, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004005001001',
   '81000000-0000-4000-8000-004005000000',
   '82000000-0000-4000-8000-004005001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'The ten lab values that actually turn up',
   'About 25 minutes on Reduction of Risk Potential, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004006001001',
   '81000000-0000-4000-8000-004006000000',
   '82000000-0000-4000-8000-004006001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Dating a pregnancy',
   'About 25 minutes on Health Promotion and Maintenance, then the floor is open — bring anything, including questions on other topics.',
   'Going deeper: this week''s topic is one of the six notes in Maternity & Newborn — Revision Notes (GHS 150), and the same six with practice built into every note in Maternity & Newborn — Learn by Doing (GHS 600).',
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004007001001',
   '81000000-0000-4000-8000-004007000000',
   '82000000-0000-4000-8000-004007001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Consent, advance directives, and who can sign',
   'About 25 minutes on Management of Care, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004008001001',
   '81000000-0000-4000-8000-004008000000',
   '82000000-0000-4000-8000-004008001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Therapeutic communication',
   'About 25 minutes on Psychosocial Integrity, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004009001001',
   '81000000-0000-4000-8000-004009000000',
   '82000000-0000-4000-8000-004009001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Infection control: the four precaution types',
   'About 25 minutes on Safety and Infection Control, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004010001001',
   '81000000-0000-4000-8000-004010000000',
   '82000000-0000-4000-8000-004010001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Insulin: types, peaks, and the sliding scale',
   'About 25 minutes on Pharmacological and Parenteral Therapies, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004011001001',
   '81000000-0000-4000-8000-004011000000',
   '82000000-0000-4000-8000-004011001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Acid-base, made mechanical',
   'About 25 minutes on Physiological Adaptation, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004012001001',
   '81000000-0000-4000-8000-004012000000',
   '82000000-0000-4000-8000-004012001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Positioning: the ones the exam asks about',
   'About 25 minutes on Basic Care and Comfort, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004013001001',
   '81000000-0000-4000-8000-004013000000',
   '82000000-0000-4000-8000-004013001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Pre- and post-operative care',
   'About 25 minutes on Reduction of Risk Potential, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004014001001',
   '81000000-0000-4000-8000-004014000000',
   '82000000-0000-4000-8000-004014001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Heart failure: left versus right',
   'About 25 minutes on Physiological Adaptation, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004015001001',
   '81000000-0000-4000-8000-004015000000',
   '82000000-0000-4000-8000-004015001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Cardiac drugs and their toxicity signs',
   'About 25 minutes on Pharmacological and Parenteral Therapies, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004016001001',
   '81000000-0000-4000-8000-004016000000',
   '82000000-0000-4000-8000-004016001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Triage and disaster',
   'About 25 minutes on Management of Care, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004017001001',
   '81000000-0000-4000-8000-004017000000',
   '82000000-0000-4000-8000-004017001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Positive, probable, presumptive',
   'About 25 minutes on Health Promotion and Maintenance, then the floor is open — bring anything, including questions on other topics.',
   'Going deeper: this week''s topic is one of the six notes in Maternity & Newborn — Revision Notes (GHS 150), and the same six with practice built into every note in Maternity & Newborn — Learn by Doing (GHS 600).',
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004018001001',
   '81000000-0000-4000-8000-004018000000',
   '82000000-0000-4000-8000-004018001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Falls, restraints and the rules that govern them',
   'About 25 minutes on Safety and Infection Control, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004019001001',
   '81000000-0000-4000-8000-004019000000',
   '82000000-0000-4000-8000-004019001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'ECG basics: the four rhythms you must recognise',
   'About 25 minutes on Reduction of Risk Potential, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004020001001',
   '81000000-0000-4000-8000-004020000000',
   '82000000-0000-4000-8000-004020001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'COPD versus asthma, and the oxygen trap',
   'About 25 minutes on Physiological Adaptation, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004021001001',
   '81000000-0000-4000-8000-004021000000',
   '82000000-0000-4000-8000-004021001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Anticoagulants: heparin versus warfarin',
   'About 25 minutes on Pharmacological and Parenteral Therapies, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004022001001',
   '81000000-0000-4000-8000-004022000000',
   '82000000-0000-4000-8000-004022001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'The stages of labour, and the prolapsed cord',
   'About 25 minutes on Health Promotion and Maintenance, then the floor is open — bring anything, including questions on other topics.',
   'Going deeper: this week''s topic is one of the six notes in Maternity & Newborn — Revision Notes (GHS 150), and the same six with practice built into every note in Maternity & Newborn — Learn by Doing (GHS 600).',
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004023001001',
   '81000000-0000-4000-8000-004023000000',
   '82000000-0000-4000-8000-004023001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Anxiety versus panic',
   'About 25 minutes on Psychosocial Integrity, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004024001001',
   '81000000-0000-4000-8000-004024000000',
   '82000000-0000-4000-8000-004024001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Medication errors: reporting and prevention',
   'About 25 minutes on Safety and Infection Control, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004025001001',
   '81000000-0000-4000-8000-004025000000',
   '82000000-0000-4000-8000-004025001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Case management, referrals and continuity',
   'About 25 minutes on Management of Care, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004026001001',
   '81000000-0000-4000-8000-004026000000',
   '82000000-0000-4000-8000-004026001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Therapeutic diets: who gets which',
   'About 25 minutes on Basic Care and Comfort, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004027001001',
   '81000000-0000-4000-8000-004027000000',
   '82000000-0000-4000-8000-004027001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Prioritisation II: the four-patient question',
   'About 25 minutes on Management of Care, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004028001001',
   '81000000-0000-4000-8000-004028000000',
   '82000000-0000-4000-8000-004028001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'DKA versus HHS, Addison versus Cushing',
   'About 25 minutes on Physiological Adaptation, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004029001001',
   '81000000-0000-4000-8000-004029000000',
   '82000000-0000-4000-8000-004029001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Reading a fetal monitor strip',
   'About 25 minutes on Reduction of Risk Potential, then the floor is open — bring anything, including questions on other topics.',
   'Going deeper: this week''s topic is covered in Maternity & Newborn — Revision Notes (GHS 150) and Maternity & Newborn — Learn by Doing (GHS 600), and it is examined in Maternity & Newborn — Mock Exam (GHS 100).',
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004030001001',
   '81000000-0000-4000-8000-004030000000',
   '82000000-0000-4000-8000-004030001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Pain management and the opioid rules',
   'About 25 minutes on Pharmacological and Parenteral Therapies, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004031001001',
   '81000000-0000-4000-8000-004031000000',
   '82000000-0000-4000-8000-004031001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Delegation II: the assignments you cannot make',
   'About 25 minutes on Management of Care, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004032001001',
   '81000000-0000-4000-8000-004032000000',
   '82000000-0000-4000-8000-004032001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Stroke, raised ICP, and the signs you never ignore',
   'About 25 minutes on Physiological Adaptation, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004033001001',
   '81000000-0000-4000-8000-004033000000',
   '82000000-0000-4000-8000-004033001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Emergencies: the order of actions',
   'About 25 minutes on Safety and Infection Control, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004034001001',
   '81000000-0000-4000-8000-004034000000',
   '82000000-0000-4000-8000-004034001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Postpartum assessment',
   'About 25 minutes on Health Promotion and Maintenance, then the floor is open — bring anything, including questions on other topics.',
   'Going deeper: this week''s topic is one of the six notes in Maternity & Newborn — Revision Notes (GHS 150), and the same six with practice built into every note in Maternity & Newborn — Learn by Doing (GHS 600).',
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004035001001',
   '81000000-0000-4000-8000-004035000000',
   '82000000-0000-4000-8000-004035001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Antibiotics: families, toxicities, peak and trough',
   'About 25 minutes on Pharmacological and Parenteral Therapies, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004036001001',
   '81000000-0000-4000-8000-004036000000',
   '82000000-0000-4000-8000-004036001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Diagnostic tests: prep, aftercare, consent',
   'About 25 minutes on Reduction of Risk Potential, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004037001001',
   '81000000-0000-4000-8000-004037000000',
   '82000000-0000-4000-8000-004037001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Incident reports, QI, and what belongs in a chart',
   'About 25 minutes on Management of Care, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004038001001',
   '81000000-0000-4000-8000-004038000000',
   '82000000-0000-4000-8000-004038001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Depression and suicide risk',
   'About 25 minutes on Psychosocial Integrity, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004039001001',
   '81000000-0000-4000-8000-004039000000',
   '82000000-0000-4000-8000-004039001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Mobility, skin integrity and pressure injuries',
   'About 25 minutes on Basic Care and Comfort, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004040001001',
   '81000000-0000-4000-8000-004040000000',
   '82000000-0000-4000-8000-004040001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'The normal newborn — and what is not',
   'About 25 minutes on Physiological Adaptation, then the floor is open — bring anything, including questions on other topics.',
   'Going deeper: this week''s topic is one of the six notes in Maternity & Newborn — Revision Notes (GHS 150), and the same six with practice built into every note in Maternity & Newborn — Learn by Doing (GHS 600).',
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004041001001',
   '81000000-0000-4000-8000-004041000000',
   '82000000-0000-4000-8000-004041001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Substance use: withdrawal, and what you treat first',
   'About 25 minutes on Psychosocial Integrity, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004042001001',
   '81000000-0000-4000-8000-004042000000',
   '82000000-0000-4000-8000-004042001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Lithium, SSRIs, antipsychotics — and their crises',
   'About 25 minutes on Pharmacological and Parenteral Therapies, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004043001001',
   '81000000-0000-4000-8000-004043000000',
   '82000000-0000-4000-8000-004043001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Immunisation across the lifespan',
   'About 25 minutes on Health Promotion and Maintenance, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004044001001',
   '81000000-0000-4000-8000-004044000000',
   '82000000-0000-4000-8000-004044001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Paediatric safety and developmental milestones',
   'About 25 minutes on Safety and Infection Control, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004045001001',
   '81000000-0000-4000-8000-004045000000',
   '82000000-0000-4000-8000-004045001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Elimination: catheters, ostomies, bowel programmes',
   'About 25 minutes on Basic Care and Comfort, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004046001001',
   '81000000-0000-4000-8000-004046000000',
   '82000000-0000-4000-8000-004046001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Paediatric vital signs that change everything',
   'About 25 minutes on Reduction of Risk Potential, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004047001001',
   '81000000-0000-4000-8000-004047000000',
   '82000000-0000-4000-8000-004047001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Grief, loss and end-of-life care',
   'About 25 minutes on Psychosocial Integrity, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004048001001',
   '81000000-0000-4000-8000-004048000000',
   '82000000-0000-4000-8000-004048001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Home and community safety for the older adult',
   'About 25 minutes on Safety and Infection Control, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004049001001',
   '81000000-0000-4000-8000-004049000000',
   '82000000-0000-4000-8000-004049001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Dosage calculation, worked slowly',
   'About 25 minutes on Pharmacological and Parenteral Therapies, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004050001001',
   '81000000-0000-4000-8000-004050000000',
   '82000000-0000-4000-8000-004050001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Putting it together: a full prioritisation set',
   'About 25 minutes on Management of Care, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004051001001',
   '81000000-0000-4000-8000-004051000000',
   '82000000-0000-4000-8000-004051001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Comfort, sleep and complementary therapies',
   'About 25 minutes on Basic Care and Comfort, then the floor is open — bring anything, including questions on other topics.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE),
  ('83000000-0000-4000-8000-004052001001',
   '81000000-0000-4000-8000-004052000000',
   '82000000-0000-4000-8000-004052001000', NULL, 1,
   'ONLINE_LIVE_SESSION', 'Exam day, and how CAT actually works',
   'The last session of the year: exam-day logistics, how the adaptive test decides, and a recap of the twelve months. Open floor after, as always.',
   NULL,
   $j${"typical_duration_minutes": 60}$j$::jsonb, TRUE)
ON CONFLICT (activity_id) DO UPDATE SET
  ordinal = EXCLUDED.ordinal, type = EXCLUDED.type, title = EXCLUDED.title,
  description = EXCLUDED.description, note = EXCLUDED.note,
  payload = EXCLUDED.payload, is_published = TRUE, updated_at = NOW();

-- ====================================================================
-- 6. The cohort — one cycle, running now
-- ====================================================================
-- The programme's own description promises a cohort ('join the cohort
-- and you get the joining link'), and until now there was not one.
--
-- start_date is the Tuesday on or before CURRENT_DATE - 56, so eight
-- weeks have already aired and carry recordings. That is deliberate:
-- the back catalogue is the reason joining late is attractive rather
-- than a problem. Anchored to the weekday rather than a raw offset,
-- because the cohort is named 'Tuesdays' and the first thing anyone
-- reads is the date beside that name.
--
-- allow_late_join is TRUE — a rolling free year that you could not
-- join in week 30 would be a strange thing to publish. No size cap.

INSERT INTO nclex_cohorts (
  cohort_id, programme_id, name, start_date, end_date,
  cohort_size, allow_late_join
)
SELECT
  '86000000-0000-4000-8000-000000000004'::uuid, '80000000-0000-4000-8000-000000000004',
  'Tuesdays 19:00 GMT — the 2026 cycle',
  v.start_date, v.start_date + 363, NULL, TRUE
FROM (
  SELECT (CURRENT_DATE - 56)
    - ((EXTRACT(DOW FROM CURRENT_DATE - 56)::int - 2 + 7) % 7) AS start_date
) AS v
ON CONFLICT (cohort_id) DO UPDATE SET
  name = EXCLUDED.name,
  start_date = EXCLUDED.start_date, end_date = EXCLUDED.end_date,
  cohort_size = EXCLUDED.cohort_size,
  allow_late_join = EXCLUDED.allow_late_join,
  cancelled_at = NULL, updated_at = NOW();

-- ====================================================================
-- 7. Cohort checklist — all 52 weeks
-- ====================================================================
-- For a TUTOR_LED programme the student sees the curriculum THROUGH
-- these rows: no checklist row, no activity. All 52 are written, not
-- just the scheduled term — the complete year is the thing worth
-- joining for, and an undated week still shows its topic.
--
-- release_date follows the app's own week pacing
-- (lib/curriculum/cohort-attach.ts): start_date + (unit_index - 1) x 7.

INSERT INTO nclex_cohort_checklist_items (
  cohort_id, template_activity_id, is_included,
  release_date, due_date, close_date, source
)
SELECT
  c.cohort_id, a.activity_id, TRUE,
  c.start_date + ((u.unit_index - 1) * 7),
  NULL, NULL, 'TEMPLATE'
FROM   nclex_cohorts c
JOIN   nclex_programme_units u      ON u.programme_id = c.programme_id
JOIN   nclex_programme_activities a ON a.unit_id = u.unit_id
WHERE  c.cohort_id = '86000000-0000-4000-8000-000000000004'
  AND  a.cohort_id IS NULL
ON CONFLICT (cohort_id, template_activity_id) DO UPDATE SET
  is_included = TRUE,
  release_date = EXCLUDED.release_date,
  updated_at = NOW();

-- ====================================================================
-- 8. Live-session planner — TERM 1 ONLY (weeks 1-13)
-- ====================================================================
-- Terms 2-4 deliberately have no rows: published topic, no date. The
-- tutor schedules the next term when they are ready to commit to it.
--
-- The date is derived from the cohort row rather than recomputing the
-- CURRENT_DATE arithmetic of section 6 — two copies of that sum would
-- eventually disagree, and this is what students turn up on.
--
-- Anything already past carries a recording, which is what makes the
-- back catalogue visible in the pitch.

INSERT INTO nclex_cohort_live_sessions (
  session_id, cohort_id, marker_activity_id,
  scheduled_at, duration_minutes, platform,
  join_url, meeting_id, passcode, joining_instructions, recording_url
)
SELECT
  ('87000000-0000-4000-8000-004' || lpad(w::text,3,'0') || '000000')::uuid,
  c.cohort_id,
  ('83000000-0000-4000-8000-004' || lpad(w::text,3,'0') || '001001')::uuid,
  c.start_date::timestamptz + INTERVAL '19 hours'
    + ((w - 1) * INTERVAL '7 days'),
  60, 'ZOOM',
  'https://us06web.zoom.us/j/97700112233', '977 0011 2233', 'NCLEX',
  'Free and open — no registration beyond joining the cohort. Come for the taught part, stay for the questions, or just lurk. Recording goes up the same evening.',
  CASE WHEN c.start_date::timestamptz + INTERVAL '19 hours'
            + ((w - 1) * INTERVAL '7 days') < NOW()
       THEN 'https://example.com/mynclex/recordings/weekly/week-' || w
       ELSE NULL END
FROM generate_series(1,13) w
CROSS JOIN nclex_cohorts c
WHERE c.cohort_id = '86000000-0000-4000-8000-000000000004'
ON CONFLICT (cohort_id, marker_activity_id) DO UPDATE SET
  scheduled_at = EXCLUDED.scheduled_at,
  duration_minutes = EXCLUDED.duration_minutes,
  platform = EXCLUDED.platform,
  join_url = EXCLUDED.join_url,
  meeting_id = EXCLUDED.meeting_id,
  passcode = EXCLUDED.passcode,
  joining_instructions = EXCLUDED.joining_instructions,
  recording_url = EXCLUDED.recording_url,
  updated_at = NOW();

COMMIT;
